### ISSUE TITLE
Prevent generation of certain sequences

### ISSUE THREAD

**Issue by jlsarry** [OpenNMT/CTranslate2#1001]
I was wondering if it would be feasible to use the `LogitsProcessor` class introduced recently in C++ to expose an option in Python, like `surpress_tokens` that would disable the generation of some tokens.

A possible use case would be to prevent generative language models to generate rude/inadequate/obscene tokens, words or sentences. 

Thank you very much for all the recent improvements and the additional features introduced lately.

**Comment by guillaumekln** [comment]
> words or sentences.

Ok so we should not disable single tokens but a sequence of tokens. In that case we should implement something like the [`NoBadWordsLogitsProcessor`](https://github.com/huggingface/transformers/blob/v4.25.1/src/transformers/generation/logits_process.py#L389-L514) from Transformers.

**Comment by jlsarry** [comment]
You are right, good point. Yes, indeed, this is the option I use on HF for
this purpose.
