### ISSUE TITLE
Support encoder-only models like BERT

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/CTranslate2#1008]
We should look into supporting encoder-only models like BERT via a new high-level class `ctranslate2.Encoder`.

BERT models are usually followed by various prediction heads depending on the task. We can't support all these tasks so the scope of the development should be restricted to the Transformer model itself. The module should return the last hidden state and/or the pooled output and the predictions heads should be run separately with the initial framework (e.g. PyTorch).

**Comment by panosk** [comment]
Hi @guillaumekln , I would love to use such models too, but my use case requires C++ without a PyTorch dependency. May I hope for a future implementation? :)

**Comment by guillaumekln** [comment]
In any case, there will be ways to create layers directly from C++. It's just that it will require some work to save/load the weights, run the layer, etc.

**Comment by aamir-s18** [comment]
@guillaumekln Any updates on this? It would be amazing to add support for [SentenceTransformers](https://www.sbert.net/).

**Comment by guillaumekln** [comment]
The latest version (3.15.0) adds initial support for encoder-only models like BERT. To get started I added an example using a BERT model for sequence classification:

https://opennmt.net/CTranslate2/guides/transformers.html#bert

At this time I only registered a converter for Hugging Face models using a BertConfig. More converters should come in the future (help needed!).

### About sentence-transformers

I'm sharing here a Gist demonstrating how one could wrap the class `SentenceTransformer` to use the CTranslate2 model instead of the PyTorch model:

https://gist.github.com/guillaumekln/fb125fc3eb108d1a304b7432486e712f

Again this is a basic example that could break easily, but it's also a way to demonstrate the CTranslate2 <-> PyTorch interoperability.

### About C++ usage

The `Encoder` class can be easily executed like the `Translator` or `Generator` classes. However, as mentionned above, running additional layers after the model would require some work: loading the additional weights from somewhere, calling the operators, etc.

**Comment by aamir-s18** [comment]
Oh wow thank you! This works perfectly. For more layers we can use sentence_transformers `models`. For example we can use your code and extend it like this for [all-MiniLM-L6-v2 ](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2):

```python
from sentence_transformers import models

# CT2SentenceTransformer provided by Guillaume
encoder = CT2SentenceTransformer("sentence-transformers/multi-qa-MiniLM-L6-cos-v1")
mean_layer = models.Pooling(384)
normalize = models.Normalize()
model = SentenceTransformer(modules=[encoder, mean_layer, normalize])
```

I verfied it returns the same results as the normal SentenceTransformer code. However by just implementing the functions instead of this nested modules thing you can get great speed-up. Thank you again, this is really great. Now it shouldn't be that hard to also use the T5-Encoder right?

**Comment by guillaumekln** [comment]
Thanks for testing.

Regarding T5-Encoder, is it a specific model or just the encoder part of a T5 encoder-decoder model?

**Comment by jncraton** [comment]
I've also experimented with this, and it looks good to me. Thanks for your work on this!

If you it's useful to anyone else, the following worked for me to compute document embeddings without requiring the sentence_transformers package:

```python
import ctranslate2
import numpy as np
import transformers

docs = ["I love Python!"]

tokenizer = transformers.AutoTokenizer.from_pretrained(
    "sentence-transformers/all-MiniLM-L6-v2"
)
encoder = ctranslate2.Encoder("all-MiniLM-L6-v2-ct2")
tokens = tokenizer(docs).input_ids
output = encoder.forward_batch(tokens)

# Average all token embeddings from the last hidden state to compute document embedding
embeddings = np.mean(np.array(output.last_hidden_state), axis=1)

# Apply normalization to bring the length of the embedding vector to 1
embeddings = embeddings / np.linalg.norm(embeddings)

print(f"{embeddings[0]=}")
print(f"{embeddings[0].shape=}")
```

That worked for me for that particular model (the output matched `SentenceTransformer` aside from minor rounding errors), but not all models compute their embeddings in the same way, so confirm that this works properly for your use case.

It still requires `transformers`, but only for the tokenizer.

**Comment by aamir-s18** [comment]
@guillaumekln, I would be just interested in using the T5Encoder model, more precisely, I am interested in trying out [gtr](https://huggingface.co/sentence-transformers/gtr-t5-large) with CTranslate2.

Off-topic: Btw having the encoder now should also allow the implementation of muti-modal models. I was already working on this. When I have something ready, I will share it.

**Comment by R4ZZ3** [comment]
Does this work for when using cuda?

**Comment by robinp** [comment]
@R4ZZ3 it works with cuda, but you either need to `.to_device(ct.Device.cpu)` the `output.last_hidden_state` StorageView before converting to numpy, or create a torch tensor from it and perform the ops using torch.
