### ISSUE TITLE
Enable the Conv1D op in ARM Python wheels

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/CTranslate2#1009]
Trying to run the Whisper model on a ARM platforms currently raises this error:

> RuntimeError: Conv1D on CPU currently requires the oneDNN library (a.k.a. DNNL) which is not integrated in this build

We should either compile oneDNN with the Arm Compute Library backend, or provide an alternative implementation for ARM.

The issue with compiling oneDNN is that it will increase the binary sizes and the build times, especially for Linux ARM which is emulated in the GitHub runner. Since the Conv1D performance is not critical for this model, it may be easier to start with a custom implementation.

**Comment by BrightXiaoHan** [comment]
Thanks. By the way, can the model on macOS benefit from the MPS backend?
