### ISSUE TITLE
why the quantized model has no significant improvement in the speed and peak memory usage?

### ISSUE THREAD

**Issue by tricky61** [OpenNMT/CTranslate2#1017]
comparing with the model size reduction, seems the speed and peak memory usage has limited promotion, is that right?

**Comment by guillaumekln** [comment]
See the [benchmark](https://github.com/OpenNMT/CTranslate2#benchmarks) which shows improvements in both speed and memory usage when quantization is enabled.

There could be situations where you don't see such improvements depending on the usage and hardware configuration. For example quantization maybe [silently disabled](https://opennmt.net/CTranslate2/quantization.html#implicit-model-conversion-on-load) if your system does not support it.

If you want more help, please post more information about how you converted the model, how you run it, and what is your system configuration.
