### ISSUE TITLE
Score: How to get translation `score`

### ISSUE THREAD

**Issue by tahirahmad2030** [OpenNMT/CTranslate2#1024]
On `OpenNMT-py` model using `ctranslate2` version `1.19.0` we used to get score like:
```
[[{'tokens': ['▁Hallo'], 'score': -0.482818603515625}]]
```

Using `ctranslate2` version `3.2.0` we dont get a score but empty scores list in the prediction like 
```
[TranslationResult(hypotheses=[['▁Hallo']], scores=[], attention=[])]
```

Is there a way to get the `score`?

**Comment by guillaumekln** [comment]
Search for `return_scores` in the documentation.

https://opennmt.net/CTranslate2/python/ctranslate2.Translator.html#ctranslate2.Translator.translate_batch

**Comment by hnhoangdz** [comment]
what is the meaning of this score? it's negative number, so is better or not if it bigger?

**Comment by guillaumekln** [comment]
It is the log of a probability. The closer to zero, the better.
