### ISSUE TITLE
m2m100 model generates gibberish after converted by ctranslate2 with latest transformers library

### ISSUE THREAD

**Issue by bugzyz** [OpenNMT/CTranslate2#1039]
Hi team,

We found that the m2m100 model converted by ctranslate2 cannot generate correct result on transformers[torch]==4.24.0 
But it works on transformers[torch]==4.23.0

Could you help to check? Thanks!

### Reproduction:
1. install package + conversion
```
pip install transformers[torch]==4.24.0 ctranslate2==3.2.0
ct2-transformers-converter --model facebook/m2m100_418M --output_dir m2m100_418M_ctranslate2 --force
```

2. do some translation

```
import ctranslate2
import transformers

translator = ctranslate2.Translator("m2m100_418M_ctranslate2", device="cuda")
tokenizer = transformers.AutoTokenizer.from_pretrained("/models/m2m100_418M/")
 
tokenizer.src_lang = "es"
text = ["He revisado esta transacción y parece que eres nuevo en las ventas con PayPal.  A veces, los vendedores nuevos pueden acumular un número elevado de devoluciones, reclamaciones o devoluciones de cargo de los compradores.", "hello"]
encoded_src = [tokenizer.convert_ids_to_tokens(tokenizer.encode(one_text)) for one_text in text]
target_prefix = [[tokenizer.lang_code_to_token["en"]] for i in range(len(text))]
results = translator.translate_batch(encoded_src, target_prefix=target_prefix)
target = results[0].hypotheses[0][1:]
 
print(tokenizer.batch_decode([tokenizer.convert_tokens_to_ids(target.hypotheses[0]) for target in results], skip_special_tokens=True))
```

### Expectation:
For transformers[torch]==4.24.0, the translation code generates some gibberish like this:
`['He revisado esta transacción y parece que eres nuevo en las ventas conાયاری Po. A veces, los vendedores nuevosyor tetular un número elevado de наesterday наesterday наesterday наesterday наesterday наesterday', 'hariരാòcòcেলзин']
`
For transformers[torch]==4.23.0, the translation look good, like:
`['I have reviewed this transaction and it seems that you are new in sales with PayPal. Sometimes, new sellers can accumulate a high number of returns, claims or charges from buyers.', 'Hello']`

**Comment by guillaumekln** [comment]
Hi,

Thanks for all the info.

It looks there is an inconsistency in the vocabulary returned by the tokenizer. The `<unk>` token does not have the correct ID when using `get_vocab()`.

```python
>>> tokenizer = transformers.M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")
>>> tokenizer.convert_tokens_to_ids("<unk>")
3
>>> tokenizer.get_vocab()["<unk>"]
128111
```

This is causing an offset in the vocabulary of the converted model and the tokens don't get their correct embedding.

I will report this issue in the transformers repository.

**Comment by bugzyz** [comment]
Oh, so the unexpected result is because of the bug of transformers during calculation instead of the model conversion? Is my understanding right? @guillaumekln

**Comment by guillaumekln** [comment]
It's an issue during the model conversion because of a bug in transformers. The transformers tokenizer returns an incorrect vocabulary, so the vocabulary file inside the converted model is also incorrect.

I suggested a bug fix in the transformers library: https://github.com/huggingface/transformers/pull/20976

**Comment by guillaumekln** [comment]
Since the transformers maintainers are slow to respond, I'm also implementing a workaround in the converter itself.
