### ISSUE TITLE
[Issue] Ctranslate2 m2m100 translation result is cut off

### ISSUE THREAD

**Issue by bugzyz** [OpenNMT/CTranslate2#1040]
Hi team,

We noticed that for ctranslate2 m2m100, some of the translation results will be cut off. Could you please help us to understand the problem, thank you!

**Info**
ctranslate2        3.1.0
transformers       4.25.1

**Reproduction**
Run code
```
import ctranslate2
import transformers

translator = ctranslate2.Translator("/models/m2m100_418M_ctranslate2", compute_type="int8", device="cuda")
tokenizer = transformers.AutoTokenizer.from_pretrained("/models/m2m100_418M/")

tokenizer.src_lang = "es"
text = ["Por ejemplo, MM/AA. Vamos a encontrar el tema adecuado para ayudarte hoy mismo.   No he recibido el cheque La limitación se tendrá que resolver antes de poder añadir una tarjeta a tu cuenta PayPal. Selecciona el tipo de número de teléfono: "]
encoded_src = [tokenizer.convert_ids_to_tokens(tokenizer.encode(one_text)) for one_text in text]
target_prefix = [[tokenizer.lang_code_to_token["en"]] for i in range(len(text))]
results = translator.translate_batch(encoded_src, target_prefix=target_prefix,
                                     )
target = results[0].hypotheses[0][1:]

print(tokenizer.batch_decode([tokenizer.convert_tokens_to_ids(target.hypotheses[0]) for target in results], skip_special_tokens=True))

```

**Expectation**
We expect the result is 
```
For example, MM/AA. We will find the right topic to help you today. I have not received the check The limitation will be solved before you can add a card to your PayPal account. Select the type of phone number:
```
But we got cut-off result like this. **Not only for this case, the final sentence is cut-off in many cases.**
```
For example, MM/AA. We will find the right topic to help you today. I have not received the check The limitation will have to be resolved before you can add a card to your PayPal account.
```

**Comment by guillaumekln** [comment]
The M2M100 model expects sentences as inputs. So you should first segment the text into sentences.

See also https://forum.opennmt.net/t/m2m100-sentences-cut-off-during-translation/4865

**Comment by bugzyz** [comment]
Thanks! @guillaumekln Got your point. 

I can confirm that for the original m2m100 model not matter loaded with transformers or optimum library, we did see the cut off translation result but not too many. And for ctranslate2, the cut off become more and more frequent. Do you have any idea of the differences?

**Comment by bugzyz** [comment]
Yeah, I tried the setting you just share plus some default settings copied from [transformers.generate()](https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationMixin). 

Still cannot get good result on ctranslate2 compared to transformers framework. Did i miss any configuration? @guillaumekln 

**For transformers framework, I always can get this result** 
['For example, MM/AA. We will find the right topic to help you today. I have not received the check The limitation will be solved before you can add a card to your PayPal account. Select the type of phone number:']
**But for ctranslate2, we got different results after repeatedly run the code**
result 1: ['__en__Please read eJ, MM/AA. We’ll find the right topic to help you today just. I have not received the check Limitation you will need to solve before we can add a card to my PayPal account.']
result 2: ['__en__To get the right case for your service today, let’s see the topics to help you right now. I didn’t receive the search Quote limit will do not have to be resolved before you can add a card to your PayPal account.']
result 3: ['__en__A/M. Fishing the job to help you today just we will find the right subject for a lot of people. I have not received Cheque A limitation can have been solved before you are able to add a card to your PayPal account. Please select the type of phone number:']

**Reproduction**
transformers code
```
import transformers
from transformers import M2M100ForConditionalGeneration

translator = M2M100ForConditionalGeneration.from_pretrained("/models/m2m100_418M/", local_files_only=True).to('cuda:0')
tokenizer = transformers.AutoTokenizer.from_pretrained("/models/m2m100_418M/")

tokenizer.src_lang = "es"
text = ["Por ejemplo, MM/AA. Vamos a encontrar el tema adecuado para ayudarte hoy mismo.   No he recibido el cheque La limitación se tendrá que resolver antes de poder añadir una tarjeta a tu cuenta PayPal. Selecciona el tipo de número de teléfono: "]
encoded_src = tokenizer(text, return_tensors="pt").to('cuda:0')

generated_tokens = translator.generate(**encoded_src, forced_bos_token_id=tokenizer.get_lang_id("en"),
                                       num_beams=1,
                                       no_repeat_ngram_size=5,
                                       repetition_penalty=1.2
                                       )
translated_texts = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

print(translated_texts)

```

ctranslate2 code
```
import ctranslate2
import transformers

translator = ctranslate2.Translator("/models/m2m100_418M_ctranslate2", device="cuda")
tokenizer = transformers.AutoTokenizer.from_pretrained("/models/m2m100_418M/")

tokenizer.src_lang = "es"
text = ["Por ejemplo, MM/AA. Vamos a encontrar el tema adecuado para ayudarte hoy mismo.   No he recibido el cheque La limitación se tendrá que resolver antes de poder añadir una tarjeta a tu cuenta PayPal. Selecciona el tipo de número de teléfono: "]
encoded_src = [tokenizer.convert_ids_to_tokens(tokenizer.encode(one_text)) for one_text in text]
target_prefix = [[tokenizer.lang_code_to_token["en"]] for i in range(len(text))]
results = translator.translate_batch(encoded_src, target_prefix=target_prefix,
                                     beam_size=1,
                                     length_penalty=1.0,
                                     repetition_penalty=1.2,
                                     no_repeat_ngram_size=5,
                                     sampling_topk=50,
                                     sampling_temperature=1.0,
                                     )
target = results[0].hypotheses[0][1:]

print(tokenizer.batch_decode([tokenizer.convert_tokens_to_ids(target.hypotheses[0]) for target in results]))

```

**Comment by guillaumekln** [comment]
> But for ctranslate2, we got different results after repeatedly run the code

You used some parameters for random sampling (`sampling_topk`), so that is expected. What do you get if you remove the two `sampling_` parameters?

**Comment by bugzyz** [comment]
Then I always got this result which is a cut off one and not frequently happen by using transformers framework:
['__en__For example, MM/AA. We will find the right topic to help you today. I have not received the check The limitation will be solved before you can add a card to your PayPal account.']

BTW, I choose sampling_topk=50, sampling_temperature=1.0 because of the default value of the top_k and temperature from https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationMixin

**Comment by guillaumekln** [comment]
> BTW, I choose sampling_topk=50, sampling_temperature=1.0 because of the default value of the top_k and temperature from https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationMixin

In the Transformers library, these parameters are only used when setting `do_sample=True`. So you can ignore them for this example.

---

I have an explanation now. There is a difference in how the repetition penalty is implemented in both frameworks. In Transformers, they penalize the decoder start token which happens to be the end of sentence token `</s>` in this model. So this token is slightly less likely to be generated and the prediction tend to be longer. If you disable repetition penalty in both frameworks, you get the same cut off output.

Even though that seems beneficial in your case, I believe this is an incorrect implementation of the repetition penalty. The paper says:

> This penalized sampling works by discounting the scores of **previously generated tokens**.

but the decoder start token was not generated by the model. So I don't think we will change our implementation.

Anyway, you should segment your text into multiple sentences before using this model. This step is really required, whether you are using Transformers or CTranslate2.
