### ISSUE TITLE
Can prefix biased decoding support beam_size=1(greedy search) 

### ISSUE THREAD

**Issue by Zenglinxiao** [OpenNMT/CTranslate2#1041]
Hi @guillaumekln,
I recently run into an error while trying to use prefix bias decoding with beam_size=1.

An error will be raised if I do so:
```bash
ValueError: Biased decoding is not compatible with greedy search
```
It seems the error is from parameter check: https://github.com/OpenNMT/CTranslate2/blob/94350b0963e7d2c8e7bac6de8b6aea74d673cc0b/src/decoding.cc#L897-L898

In theory, prefix bias decoding should be independent of beam search if I understood correctly. So **could we enable prefix bias decoding for beam_size=1 as well** by taking `BeamSearch` strategy instead when `prefix_bias_beta` is set according to this line?
https://github.com/OpenNMT/CTranslate2/blob/94350b0963e7d2c8e7bac6de8b6aea74d673cc0b/src/decoding.cc#L915-L923

Or is there any other reason I am not aware of that makes them incompatible?

**Comment by guillaumekln** [comment]
Hi,

I don't see a good reason to disallow using biased decoding with `beam_size=1`.

Do you want to contribute the change you suggested (taking the `BeamSearch` path if `prefix_bias_beta` is set)?

**Comment by Zenglinxiao** [comment]
> Hi,
> 
> I don't see a good reason to disallow using biased decoding with `beam_size=1`.
> 
> Do you want to contribute the change you suggested (taking the `BeamSearch` path if `prefix_bias_beta` is set)?

Great!
Having tested locally with the proposed change, it seems working fine. Will submit a PR in the next few days.
Thanks a lot for the confirmation.
