### ISSUE TITLE
Compile error with DNNL and MSVC

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#1047]
Hi @guillaumekln ,

I'm getting this error when compiling with DNNL.:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory:3416: error: C2661: 'dnnl::convolution_forward::primitive_desc::primitive_desc': no overloaded function takes 11 arguments
C:\Users\user\Development\Temp\Project\ext\CTranslate2\src\ops\conv1d_cpu.cc(60): note: see reference to function template instantiation 'std::unique_ptr<dnnl::convolution_forward::primitive_desc,std::default_delete<dnnl::convolution_forward::primitive_desc>> std::make_unique<dnnl::convolution_forward::primitive_desc,dnnl::engine&,dnnl::prop_kind,dnnl::algorithm,dnnl::memory::desc&,dnnl::memory::desc&,dnnl::memory::desc&,dnnl::memory::desc&,dnnl::memory::dims&,dnnl::memory::dims&,dnnl::memory::dims&,dnnl::memory::dims&,0>(dnnl::engine &,dnnl::prop_kind &&,dnnl::algorithm &&,dnnl::memory::desc &,dnnl::memory::desc &,dnnl::memory::desc &,dnnl::memory::desc &,dnnl::memory::dims &,dnnl::memory::dims &,dnnl::memory::dims &,dnnl::memory::dims &)' being compiled

Without DNNL I can compile fine.

Any ideas?

**Comment by guillaumekln** [comment]
Hi,

You should probably update to oneDNN >= 3.0.

See the version requirement in the documentation: https://opennmt.net/CTranslate2/installation.html#build-options

**Comment by panosk** [comment]
Hm, updated just yesterday all the related stuff (MKL, DNNL, etc) using the oneAPI installer, but didn't check versions. Will check and come back later.

Thanks!

**Comment by panosk** [comment]
That was it, thanks. It seems the installer didn't update to the latest version yesterday, so I reran it now and indeed it updated correctly.
