### ISSUE TITLE
Increasing max_batch_size lead to bad outputs

### ISSUE THREAD

**Issue by anthdr** [OpenNMT/CTranslate2#1050]
I trained a multilingual model using opennmt and converted it using ctranslate2 3.3.0.
When I load it and use the translate_file method, the greater the max_batch_size is, the greater the "hallucinations":
default: output is correct.
1024: few repetitions (of the same token(s)) and wrong language output.
3072: heavy repetitions and wrong language output throughout the file.

Here is the code:
```
import ctranslate2
translator = ctranslate2.Translator('mymodel_CT2-int8', 
device='cuda', 
device_index=[0])
translator.translate_file('text-src.uk.tok', 
'text-hyp.en.tok',
read_batch_size= 0,
max_batch_size= 1024)
```

Can't int8 handle larger batch size ? Should I use an other quantization to do large scale translation?

**Comment by guillaumekln** [comment]
By default, the batch size corresponds to the number of examples. Did you mean to use `batch_type="tokens"`?

We did not test with 1000+ examples in a single batch since it is not used in practice. It uses much more memory and is barely faster (or even slower).

However, we should still look to make your usage work, or at least raise an error indicating it is not supported.

**Comment by anthdr** [comment]
For the record, I just tried with `max_batch_size= 45000` and `batch_type='tokens'`, outputs are still wrong with way more repetitions than wrong language.

**Comment by guillaumekln** [comment]
45000 tokens is also a very big batch size so the issue is the same.

Why do you want to use such big values? Did you run a benchmark indicating these large batch sizes are faster?

**Comment by guillaumekln** [comment]
We limited some inputs to a total batch size of 65535 (batch*length) when calling some CUDA kernels. However, all GPUs that we support now accept a total batch size of up to 2^31-1. So raising the limit will fix the issue.
