### ISSUE TITLE
Splitting LLM layers across multiple GPUs

### ISSUE THREAD

**Issue by JOHW85** [OpenNMT/CTranslate2#1052]
As CTranslate2 now supports quantized 8-bit LLMs like OPT, are there any plans to include model parallelism to split a model layers across multiple GPUs or GPU+CPU to meet the memory requirements needed to load the model as described here:
https://huggingface.co/docs/transformers/v4.15.0/parallelism

**Comment by guillaumekln** [comment]
Yes, it would be great to implement tensor parallelism for large models.

Right now we support data parallelism on the GPU. We refer to it simply as "parallel execution" in the [documentation](https://opennmt.net/CTranslate2/parallel.html) but it's the same thing.

**Comment by japuiglaucia** [comment]
Splitting LLM layers across multiple GPUs #1052

**Comment by vince62s** [comment]
did you run 5 samples in batch_size = 1 sentence or did you run batch_size = 5 sentences ?

**Comment by minhthuc2502** [comment]
I updated the comment above for 2 cases: batch_size = 1 and batch_size = 5.

**Comment by minhthuc2502** [comment]
I'll close this issue as the feature is now supported. If you have any problems, feel free to open the new issue.
