### ISSUE TITLE
Use of Flan-t5 for answer generation

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [OpenNMT/CTranslate2#1064]
Hi,

I saw that there is a possibility to use Flan-t5 for translation. Is it possible to use the converted model for answer generation?

**Comment by guillaumekln** [comment]
Hi,

If the task can be implemented with the `ForConditionalGeneration` model in Transformers, then it can also be implemented here using the `Translator` object.

**Comment by Matthieu-Tinycoaching** [comment]
Nice to hear that!

Is it possible then to convert to 8-bits integers?

**Comment by guillaumekln** [comment]
Yes, all models can be converted and run in 8-bit integers.

**Comment by redthing1** [comment]
I tried it and I keep getting weird inputs. Do I need some special tokens?

**Comment by guillaumekln** [comment]
Did you check #1074 already?
