### ISSUE TITLE
Conv1D on GPU currently requires the cuDNN library which is not integrated in this build (Windows)

### ISSUE THREAD

**Issue by ItakeLs** [OpenNMT/CTranslate2#1076]
When using CTranslate2 on windows, the error, ```Conv1D on GPU currently requires the cuDNN library which is not integrated in this build``` occurs. The windows system has both Cuda 11.x and cuDNN 8.x.x installed.

**Comment by dkakaie** [comment]
I also faced the same problem. I managed to compile it from source with CUDA and cuDNN. It couldn't still run, complaining about failure to load ctranslate2.dll (or a dependency).

**Comment by KMC07** [comment]
From my understanding, you have to build CTranslate2 from source on windows with ```-DWITH_CUDA=ON``` and ```-DWITH_CUDNN=ON`` and have CUDA 11.x installed along with cuDNN 8.x.x, which leads back to [#1084](https://github.com/OpenNMT/CTranslate2/issues/1084)

**Comment by guillaumekln** [comment]
The linked PR is building Windows Python wheels with cuDNN. Can you help testing?

Go the the [build page](https://github.com/OpenNMT/CTranslate2/actions/runs/4185418997), download the "python-wheels" artifact, extract the archive, and finally install the appropriate wheel for your system.

**Comment by KMC07** [comment]
Yes, this is working for me, works as expected.
