### ISSUE TITLE
A lot of segments do not get detected compared with the original whisper

### ISSUE THREAD

**Issue by ItakeLs** [OpenNMT/CTranslate2#1078]
Hello, compared to this model a lot of segments are not detected compared with the original version of whisper using the same settings. I used [fast whisper] (https://github.com/guillaumekln/faster-whisper) which work wonderfully. The issue is not coming from that repo, as the results/segments without any post-processing (coming straight from ```generate()```), are not being detected.

**Comment by guillaumekln** [comment]
What do you mean by not detected?

Can you provide a way to reproduce the issue? Sharing an input audio file and specifying the model size would be helpful.

**Comment by ItakeLs** [comment]
Hello, here is a [notebook](https://colab.research.google.com/drive/11yP7gEIihq98ErBY89g736g9tRryMbJ0?usp=sharing) that showcases what I am talking about.

In case you don't want to use the notebook, here is the [youtube link](https://www.youtube.com/watch?v=D9G1VOjN_84) of the input mp4, and the model size is `medium` and `beam_size=5`

**Comment by guillaumekln** [comment]
Thanks for sharing the input file, this was helpful.

The linked PR will improve the output on your example. The first segment will be the same as the original Whisper implementation, but after that the fallback mode is trigerred so the outputs will be different.
