### ISSUE TITLE
Using the same data set, different batch_size prediction results are different

### ISSUE THREAD

**Issue by duanyongyao** [OpenNMT/CTranslate2#1079]
The same data set, a total of 5 samples, when the batch_size is 4 and batch_size is 5 input models, the prediction results are different, as shown in the figure  
![image](https://user-images.githubusercontent.com/24647121/218359602-698cbd73-81cf-4690-bae6-f8b190bf4c8d.png)

The calling code is as follows
```python
ct_translator = ct2.Translator(local_model_path, device="cuda", device_index=0, compute_type="float16")
results = ct_translator.translate_batch(input_list, max_batch_size=2048, batch_type="tokens", beam_size=10, return_scores=True, num_hypotheses=2)
```

Please help to see how to solve it, thank you very much

**Comment by guillaumekln** [comment]
From your example, it seems to me that only the score can be slightly different but the prediction is the same. Is that correct?

**Comment by duanyongyao** [comment]
> From your example, it seems to me that only the score can be slightly different but the prediction is the same. Is that correct?
That's true, the predicted results are consistent, but there is a difference in the score output to the third decimal place.

**Comment by guillaumekln** [comment]
This is generally expected for batch execution, especially when running in half precision (`compute_type="float16"`).

The score difference can be reduced to ~ 1e-7 by running the translation in full precision (`compute_type="float"`).
