### ISSUE TITLE
ImportError: DLL load failed while importing ctranslate2 as a python module (Windows)

### ISSUE THREAD

**Issue by KMC07** [OpenNMT/CTranslate2#1084]
I tried building on windows, and when I try to import the ctranslate2 I get the error
```FileNotFoundError: Could not find module 'D:\test\venv\lib\site-packages\ctranslate2\libiomp5md.dll' (or one of its dependencies). Try using the full path with constructor syntax.```

If I manually add the ```libiomp5md.dll`` to the corresponding directory the error stops and I instead get the error

```FileNotFoundError: Could not find module 'D:\test\venv\lib\site-packages\ctranslate2\ctranslate2.dll' (or one of its dependencies). Try using the full path with constructor syntax.```

I am not really good with building in c++, so I am not sure if there is something I am missing, the error comes from the ctranslate2 init file
```
    module_name = sys.modules[__name__].__name__
    package_dir = pkg_resources.resource_filename(module_name, "")

    add_dll_directory = getattr(os, "add_dll_directory", None)
    if add_dll_directory is not None:
        add_dll_directory(package_dir)

    for library in ("libiomp5md", "ctranslate2"):
        ctypes.CDLL(os.path.join(package_dir, "%s.dll" % library))
```

If I manually change the directory in the last line to ctranslate2 library installation directory, (the build argument, ```CMAKE_INSTALL_PREFIX```), the latter error still persists.  I have also tried setting the environment variable ```LD_LIBRARY_PATH``` to the installation directory. 
When I install ctranslate2 using ```pip install ctranslate2``` in the site-package folder both ```libiomp5md.dll``` and ```ctranslate2.dll``` are present, however when I build and install compile the python wrapper it is absence, is there some step I am missing to get this properly working.

This is the code I run in a jupyter notebook in windows to build the c++ and python wrapper
```
%cd CTranslate2
%cd build

!cmake .. -DWITH_MKL=ON -DWITH_CUDA=ON -DWITH_CUDNN=ON -DCMAKE_INSTALL_PREFIX="D:/CTranslate2" -G "Visual Studio 16" -DCMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD=ON
```
I then build and install the solution using VS 2019 then run the remaining part
```
%cd ../python

%env CTRANSLATE2_ROOT=D:/CTranslate2
%env LD_LIBRARY_PATH=$CTRANSLATE2_ROOT/lib #not sure what this does

!pip install -r install_requirements.txt
!python setup.py bdist_wheel

%cd dist

!pip install ctranslate2-3.5.0-cp310-cp310-win_amd64.whl
```

**Comment by dkakaie** [comment]
I have the same problem as mentioned in #1076 although I built it without MKL. I checked CUDA and cuDNN path settings in case problem related to it and it still fails.

**Comment by guillaumekln** [comment]
You can check [this script](https://github.com/OpenNMT/CTranslate2/blob/master/python/tools/prepare_build_environment_windows.sh) that is used to compile CTranslate2 before building the Python wheels.

In particular, it copies the DLLs in the `python/ctranslate2` directory before building the wheel with `bdist_wheel`. The DLLs are then registered as package data here: https://github.com/OpenNMT/CTranslate2/blob/v3.5.1/python/setup.py#L53

**Comment by KMC07** [comment]
Thank you, I followed the script and now both ```libiomp5md.dll``` and ```ctranslate2.dll``` are in the directory however, I am still getting the error which is strange because ```ctranslate2.dll``` is in the directory
```
FileNotFoundError: Could not find module 'D:\test\venv\lib\site-packages\ctranslate2\ctranslate2.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
The error does not give any more detail so I'm stuck on where to go from here.

**Comment by guillaumekln** [comment]
> or one of its dependencies

I think this is the important information. You should probably copy the required cuBLAS and cuDNN DLLs as well.

**Comment by KMC07** [comment]
I appreciate your help, Is there any way to know all the DLLs I might need to add, and how come the package form ```pip install ctranslate2``` doesn't require extra DLLs even though I am using the same build and install arguments as the ones in your script?

**Comment by guillaumekln** [comment]
> is there any way to know all the DLLs I might need to add

You can use this tool to know the DLL dependency tree: https://www.dependencywalker.com/

> how come the package from pip install ctranslate2 doesn't require extra DLLs even though I am using the same build and install arguments as the ones in your script?

1. For cuDNN, as you already know the published Windows wheel is not using it so this DLL is not needed
2. For cuBLAS, the CTranslate2 library is built with `-DCUDA_DYNAMIC_LOADING=ON` so that the DLL is not included in the package but loaded dynamically from the user system at runtime.

**Comment by KMC07** [comment]
Sorry for the back and forth, I have added both ```cudnn64_8.dll``` and ```cublas64_11.dll``` but the same error still appears, I tried using DLL dependency tree, and it showed ```kernel32.dll```, ```msvcp140.dll```, ```vcruntime140.dll```, ```vcruntime140_1.dll``` and I added them all to the site-package directory to no avail.

**Comment by guillaumekln** [comment]
I tried the procedure in a Windows 11 VM and was able to `import ctranslate2` without error (but I did not verify the execution).

Here's my full CMake command line (it's not very clean, I just wanted to get something working quickly):

> `cmake -DWITH_CUDA=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=COMP -DWITH_CUDNN=ON -DCUDA_DYNAMIC_LOADING=ON  -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7" -DCUDA_ARCH_LIST="6.1" -DCMAKE_PREFIX_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDNN" -DCUDNN_LIBRARIES="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDNN/lib/x64/cudnn.lib" -DCMAKE_INSTALL_PREFIX="Z:/CTranslate2/install" ..`

In particular I used:

* `-DOPENMP_RUNTIME=COMP` to not need to copy `libiomp5md.dll`
* `-DCUDA_DYNAMIC_LOADING=ON` to not need to copy `cublas64_11.dll`

So I only copied `cudnn64_8.dll` and `ctranslate2.dll` in `python/ctranslate2` and updated the DLL registration:

```diff
diff --git a/python/ctranslate2/__init__.py b/python/ctranslate2/__init__.py
index c1c0faa3..b40e4870 100644
--- a/python/ctranslate2/__init__.py
+++ b/python/ctranslate2/__init__.py
@@ -13,7 +13,7 @@ if sys.platform == "win32":
     if add_dll_directory is not None:
         add_dll_directory(package_dir)
 
-    for library in ("libiomp5md", "ctranslate2"):
+    for library in ("cudnn64_8", "ctranslate2"):
         ctypes.CDLL(os.path.join(package_dir, "%s.dll" % library))
 
 try:
```

**Comment by KMC07** [comment]
You are a genius and a life saver, thank you so much for your help. Your CMAKE command and changes to the DLL registration helped me get it working. Thanks for answering all my questions.
