### ISSUE TITLE
How to modify model structure and build own _ext.cpython-39-x86_64-linux-gnu.so?

### ISSUE THREAD

**Issue by tnlin** [OpenNMT/CTranslate2#1103]
Hi, I would like to add some customized modification on Whisper model.

I could successfully build libctranslate2.so, 

but how to I build the .so in the python's site-package? (_ext.cpython-39-x86_64-linux-gnu.so)

**Comment by guillaumekln** [comment]
Hi,

There is a section in the documentation that describes how to build the Python package: https://opennmt.net/CTranslate2/installation.html#compile-the-python-wrapper

Did you check it?
