### ISSUE TITLE
Does whisper decoding use GPU in CTranslate

### ISSUE THREAD

**Issue by ItakeLs** [OpenNMT/CTranslate2#1116]
Hello, I am just wondering if the beam search decoding uses GPU and if not if this might be a potential bottleneck worth me spending time to working on?

**Comment by guillaumekln** [comment]
Hi,

I'm not sure what you mean exactly here. If your question is "do all beam search operations run on the GPU" then the answer is no. Some of them are running on the CPU but they are not a bottleneck.

I don't have numbers for Whisper decoding specifically, but with a translation model the beam search ops take ~1% of the execution time.

**Comment by ItakeLs** [comment]
That answers everything, in the original whisper implementation beam search does not use GPU, and I saw some discussions about that being a potential bottleneck, as far as I'm aware I think the only bottleneck in the beam search is moving around the weights caused by ```return_attention = true``` (with no other changes made), but I need further testing to confirm.
