### ISSUE TITLE
In whisper SOT token should be in the same position for prompt

### ISSUE THREAD

**Issue by ItakeLs** [OpenNMT/CTranslate2#1118]
Hello, I was looking through the code base and came across this

```
        if (first) {
          sot_index = batch_sot_index;
          prompt_length = batch_prompt_length;
        } else if (batch_sot_index != sot_index) {
          throw std::invalid_argument("The generate method currently requires the "
                                      "<|startoftranscript|> token to be at the same position "
                                      "in all batches. To work around this limitation, "
                                      "simply adapt the number of previous text tokens in each "
                                      "batch.");
        } else if (batch_prompt_length != prompt_length) {
          throw std::invalid_argument("The generate method currently requires each batch to have "
                                      "the same number of task tokens after <|startoftranscript|>.");
        }
```

I am assuming this requires all prompts to be the same size and all have `<sot>` in the same index, assuming they are not the same size, you would have to take the highest number of tokens before and after each `<sot>` and pad the other prompts so they match. 

For example this
```
[a, b, c, d, <sot>, e, f]
[a, <sot>, b, c, d, e]
```

would become this (where  `_` is the token used for padding
```
[a, b, c, d, <sot>, e, f, _, _]
[_, _, _, a, <sot>, b, c, d, e]
```

My question is in that scenario what would you pad them with, is there a token that can pad the prompt and not also affect the transcription of the model?

**Comment by guillaumekln** [comment]
Hi,

For tokens before `<|startoftranscript|>`, you can control how much "previous text tokens" you include in the prompt (cf. https://github.com/openai/whisper#approach). For example with:

```
[<|startofprev|> a, b, c, d, <|startoftranscript|>]
[<|startofprev|>, a, b, <|startoftranscript|>]
```

You would need to send this:

```
[<|startofprev|>, c, d, <|startoftranscript|>]
[<|startofprev|>, a, b, <|startoftranscript|>]
```

This may change the transcription when the context is short but it is still a valid prompt.

For tokens after `<|startoftranscript|>`, we just require the same number of task tokens. So you can't mix prompts with and without the `<|notimestamps|>` token for example.

After the task tokens, the prefixes can have different lengths. For example this is a valid prompt:

```
[<|startofprev|>, c, d, <|startoftranscript|>, <|en|>, <|transcribe|>, <|notimestamps|>]
[<|startofprev|>, a, b, <|startoftranscript|>, <|en|>, <|transcribe|>, <|notimestamps|>, c, d]
```

**Comment by ItakeLs** [comment]
Thank you, just for further clarification, in the example you gave
>```
> [<|startofprev|> a, b, c, d, <|startoftranscript|>]
> [<|startofprev|>, a, b, <|startoftranscript|>]
>```

 would  ```c, d```  be moved to after ```<|notimestamps|>``` making it like this
 ```
[<|startofprev|>, a, b, <|startoftranscript|>, <|en|>, <|transcribe|>, <|notimestamps|>, c, d]
[<|startofprev|>, a, b, <|startoftranscript|>, <|en|>, <|transcribe|>, <|notimestamps|>]
 ```

or would one just cut it to make the the number of tokens between ```<|startofprev|>``` and ```<|startoftranscript|>``` the same
 ```
[<|startofprev|>, a, b, <|startoftranscript|>, <|en|>, <|transcribe|>, <|notimestamps|>]
[<|startofprev|>, a, b, <|startoftranscript|>, <|en|>, <|transcribe|>, <|notimestamps|>]
 ```
 
If I go the first route would this affect the transcription, because the latter would definitely affect the transcription since some context of the previous tokens is removed?

**Comment by guillaumekln** [comment]
The first solution is incorrect because c and d refer to the previous audio frame. It is not correct to use them as a prefix for the current frame.

**Comment by ItakeLs** [comment]
Okay, so the only solutions would be to set ```condition_on_previous_text=False``` as only using part of the previous tokens as context for the next segment might have unintended consequences on transcription quality. 
Or pad the shorter "previous token amounts" with a token that would not affect the transcription (assuming that token exists) so the distance between ```<|startofprev|>``` and ```<|startoftranscript|>``` is the same.

**Comment by guillaumekln** [comment]
Note that the sequence of previous text tokens is limited to 224 tokens anyway. So I think it’s fine to send a truncated context, even though it can slightly change the transcription.
