### ISSUE TITLE
Does batch inference introduce performance gains?

### ISSUE THREAD

**Issue by ItakeLs** [OpenNMT/CTranslate2#1119]
Hello, after this discussion [#1118](https://github.com/OpenNMT/CTranslate2/issues/1118), I was wondering if the way batch inference was implemented would increase throughput on GPUs vs running multiple audio files sequentially (assuming the model is already loaded).

I am assuming it would enable you to achieve substantial sub-linear throughput scaling on GPUs that would otherwise have additional headroom when performing serial transcription.

Edit:
Currently implementing batch processing/inference on whisper (which is a simple task, and shouldn't take too long) to see if there are performance gains, I am asking about batch inference speed up just to know what to expect.

**Comment by guillaumekln** [comment]
Sure, batch execution should increase the throughput.

**Comment by ItakeLs** [comment]
Sorry just to confirm, with batch execution on a single GPU, are the number of batches automatically detected, or must the ```inter_thread``` and ```intra_thread``` be set accordingly?

**Comment by guillaumekln** [comment]
There is no need to change these threading parameters. You just need to pass more inputs to the method `generate`.
