### ISSUE TITLE
Compilation error "‘CPU_FEATURES_VENDOR_GENUINE_INTEL’ was not declared in this scope"

### ISSUE THREAD

**Issue by Jeronymous** [OpenNMT/CTranslate2#1122]
When I try to install following the instructions of https://opennmt.net/CTranslate2/installation.html to "Compile the C++ library", I have this error when doing `make`:
```
/home/Jeronymous/src/CTranslate2/src/cpu/cpu_info.cc:19:35: error: ‘CPU_FEATURES_VENDOR_GENUINE_INTEL’ was not declared in this scope
   19 |       return strcmp(cpu_vendor(), CPU_FEATURES_VENDOR_GENUINE_INTEL) == 0;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by guillaumekln** [comment]
Hello,

This macro is defined in header `cpuinfo_x86.h` which is coming from the third party library `third_party/cpu_features`. Maybe this library is already installed on your system but with a different version?

However, as mentioned in https://github.com/guillaumekln/faster-whisper/issues/37, maybe you can avoid recompiling the library for your test.
