### ISSUE TITLE
Get the numpy equivalent of .min() / .max()

### ISSUE THREAD

**Issue by ItakeLs** [OpenNMT/CTranslate2#1124]
Hello, just wanted to confirm if there are functions that can get the equivalent of ```np.min()``` and ```np.max()``` for ```StorageView``` arrays, I know there is ```ops::min()``` but this compares arrays instead of getting the smallest/largest value.

**Comment by guillaumekln** [comment]
There is a `max` primitive which accepts data pointers:

https://github.com/OpenNMT/CTranslate2/blob/v3.8.0/include/ctranslate2/primitives.h#L39-L40

However, there is no `min` equivalent. (It was just not needed at this time.)

**Comment by ItakeLs** [comment]
Thank you, for the direction I managed to add them.
