### ISSUE TITLE
Returning whisper embeddings for each segment

### ISSUE THREAD

**Issue by ItakeLs** [OpenNMT/CTranslate2#1132]
Hello, wanted to ask how I would go about returning the embeddings for each segment and whether it be better to return the embeddings in the generate or align function.

I imagine it has something to do with these lines but I am not sure how to go about extracting the embeddings
```
layers::DecoderState state = _decoder->initial_state(); 
state.emplace("memory", encode(features));
```

**Comment by guillaumekln** [comment]
Hi,

Just to make sure: by embedding do you mean the encoder output? If yes, maybe you can define a new method that just runs the encoder?

**Comment by ItakeLs** [comment]
Yes, I'm referring to saving different encoder layers outputs

Just to confirm would the output just be of the encoder just be, or the ```state``` necessary to return them

```
embeddings = encode(features);
```

And then I can modify the encode function to return from the specified encoderp layers

**Comment by guillaumekln** [comment]
Currently only the output of the last layer is returned from the encoder. You would need to change `TransformerEncoder` to save the output of each layer.

**Comment by ItakeLs** [comment]
okay, thank you, that's perfect.
