### ISSUE TITLE
Is there an example how to do CTranslate2 Whisper inference in C++ ? 

### ISSUE THREAD

**Issue by sv2** [OpenNMT/CTranslate2#1138]
Thank you for the great work ! 
Is there an example how to do CTranslate2 Whisper inference in C++ ? 
I am currently using whisper.cpp. Would like to compare with CTranslate2 Whisper with the hope I can improve performance - 
my use case is real time streaming transcription. 
Thanks in advance!

**Comment by guillaumekln** [comment]
There is no example for a full transcription loop in C++. Basically you would need to reimplement the [faster-whisper](https://github.com/guillaumekln/faster-whisper/) demo in C++, which is quite some work.

Alternatively you can try calling the CTranslate2 model from whisper.cpp, but I don't know how feasible and easy this is.
