### ISSUE TITLE
Unable to convert fairseq model

### ISSUE THREAD

**Issue by bil-ash** [OpenNMT/CTranslate2#1151]
I am unable to convert the fairseq model which is available(compressed) at [https://ai4b-public-nlu-nlg.objectstore.e2enetworks.net/en2indic.zip](https://ai4b-public-nlu-nlg.objectstore.e2enetworks.net/en2indic.zip). Details about the model is available at [https://github.com/AI4Bharat/indicTrans](https://github.com/AI4Bharat/indicTrans). I get the following error while conversion - 
`Traceback (most recent call last):
  File "/usr/local/bin/ct2-fairseq-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/fairseq.py", line 341, in main
    converter.convert_from_args(args)
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/fairseq.py", line 166, in _load
    spec = _get_model_spec(args)
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/fairseq.py", line 32, in _get_model_spec
    model_name = fairseq.models.ARCH_MODEL_NAME_REGISTRY[args.arch]
KeyError: 'transformer_4x'`

Someone please provide a solution for the problem

**Comment by guillaumekln** [comment]
You should use the option `--user_dir indicTrans/model_configs` for Fairseq to register the custom model configurations:

```
ct2-fairseq-converter --model_path en-indic/model/checkpoint_best.pt --data_dir en-indic/final_bin/ \
                      --user_dir indicTrans/model_configs/ --output_dir en-indic-ct2
```

**Comment by bil-ash** [comment]
Thanks, the conversion worked. Now, how do I specify the language into which I want the text to be translated(since the model supports translation into 9 languages)? Would be very kind of you if you provide an example of translating into Hindi language.

**Comment by guillaumekln** [comment]
In [this script](https://github.com/AI4Bharat/indicTrans/blob/main/joint_translate.sh) you can find how they tokenize the input and add the language tags.

Once the input is tokenized with the language tags, you can refer to the existing translation examples. See for example the code snippet for M2M-100: https://opennmt.net/CTranslate2/guides/fairseq.html#m2m-100
