### ISSUE TITLE
Does Dockerfile docker pull ghcr.io/opennmt/ctranslate2:latest-ubuntu20.04-cuda11.2 include cuDNN?

### ISSUE THREAD

**Issue by mayeaux** [OpenNMT/CTranslate2#1152]
Based upon the documentation here:

https://opennmt.net/CTranslate2/installation.html#install-with-docker

It seems like cuDNN is not necessarily included

> The images include:
> 
> the C++ library installed in /opt/ctranslate2
> 
> the Python module installed in the Python system packages
> 
> the translator executable, which is the image entrypoint:

Yet, when I create a server using that Dockerfile, it *seems* to include cuDNN since I can run `faster-whisper` immediately, though I can't find it when I poke around the server.

If my assumption is right that it's included
1) Where can I find cuDNN installed on the server? 
2) Should it be added to the documentation that it is included? Specifically because `If you plan to run models with convolutional layers (e.g. for speech recognition), you should also install [cuDNN 8](https://developer.nvidia.com/cudnn).` is included right above the part about the Dockerfile I think it would be reassuring to people such as myself who were looking up how to install it not knowing it would be included in the Dockerfile installation.

Thanks a lot, I am loving `faster-whisper` !

**Comment by guillaumekln** [comment]
1. cuDNN is indeed [installed](https://github.com/OpenNMT/CTranslate2/blob/v3.10.3/docker/Dockerfile#L76) in the Docker image. You can use `ldconfig` to find where the libraries are located:

```
$ docker run --rm --entrypoint ldconfig ghcr.io/opennmt/ctranslate2:latest-ubuntu20.04-cuda11.2 -p | grep cudnn
	libcudnn_ops_train.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_ops_train.so.8
	libcudnn_ops_infer.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
	libcudnn_cnn_train.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8
	libcudnn_cnn_infer.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8
	libcudnn_adv_train.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_adv_train.so.8
	libcudnn_adv_infer.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8
	libcudnn.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn.so.8
```

2. The notice about cuDNN that you quoted is only valid when installing the package with pip. The notice in the Docker section simply states "The Docker image supports GPU execution", which implicitly means that all required NVIDIA libraries are installed in the image. Feel free to send a PR to clarify that the image already contains all the required NVIDIA libraries.
