### ISSUE TITLE
Run error with ruy on AArch64

### ISSUE THREAD

**Issue by MingyangW** [OpenNMT/CTranslate2#1154]
Hi, I compiled ctranslate2 with ruy, but encountered the following error when running the test cases for the int8 model. Does ctranslate support compilation solely with ruy?

`terminate called after throwing an instance of 'std::runtime_error'
  what():  No SGEMM backend on CPU
Aborted`

cmake command:
`cmake -DWITH_MKL=OFF -DBUILD_CLI=OFF -DOPENMP_RUNTIME=NONE `

Looking forward to your reply, thank you.

**Comment by guillaumekln** [comment]
Hi,

No, the Ruy backend alone is not sufficient to run a model. Ruy implements 8-bit matrix multiplication but some matrix multiplications are always running in float32 (e.g. the matmul in the dot product attention).

So you should enable another backend such as OpenBLAS to provide a GEMM implementation for float32 inputs.

**Comment by MingyangW** [comment]
Thank you!  Yes, when I compile ctranslate2 using ruy and OpenBLAS, the test case can run successfully. However, the memory usage when starting this case is unstable. At this point, the model has not yet been run. There is a fluctuation of over 20MB between the maximum and minimum memory usage. What could be the cause of this issue, and is there any way to stabilize the memory usage at a consistent value, preferably at the minimum level?

**Comment by guillaumekln** [comment]
What is the test case you are referring to?

**Comment by MingyangW** [comment]
As  C++ example in the tutorial, 
I set a sleep time before executing the translation, during which I checked the memory usage. Each time the program is executed, the memory usage is different, with a maximum of over 30M and a minimum of around 10M, 
I executed this example on the aarch64 architecture

<img width="616" alt="image" src="https://user-images.githubusercontent.com/26376213/229091085-3a148a6a-c1e7-44fd-acfe-e780b7bf9033.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/26376213/229091921-5c78f80d-2992-4e07-ba29-e7bbe95e0ce9.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/26376213/229091584-fd1c3e9b-9230-45c8-94f4-da05754a65a5.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/26376213/229091761-fad2edaa-5279-4848-b570-e57843a0d019.png">

**Comment by guillaumekln** [comment]
Try setting the environment variable `OMP_NUM_THREADS=1` when running your executable.

**Comment by MingyangW** [comment]
I'm sorry, it didn't work.

**Comment by MingyangW** [comment]
Thank you, 
I found where the problem was. It should be that there was a problem with my OpenBLAS library compilation. After recompiling it, the memory issue was resolved. 
Thanks again.

**Comment by guillaumekln** [comment]
Thank you for the update.
