### ISSUE TITLE
Positional Encoding RuntimeError 

### ISSUE THREAD

**Issue by VarunGumma** [OpenNMT/CTranslate2#1157]
I converted a `fairseq` transformer model checkpoint using `ctranslate2` to `int8` and used the converted checkpoint to evaluate `flores101`. I get the error `RuntimeError: No position encodings are defined for positions >= 210, but got position 210` while using the `translate_batch` method. I checked my pre-processing stage and confirmed that my input's sequence length was < 210 tokens. What could be the possible issue for it and anyone else facing this?

**Comment by guillaumekln** [comment]
You should probably limit the maximum decoding length:

```python
translator.translate_batch(..., max_decoding_length=210)
```
