### ISSUE TITLE
CTranslate2 missing dependency in Windows

### ISSUE THREAD

**Issue by jordimas** [OpenNMT/CTranslate2#1163]
Hello

In a new Windows 10 box after installing Python3 and ctranslate2 I get this error while importing the library:

<img width="970" alt="Captura de pantalla 2023-04-12 a les 11 12 44" src="https://user-images.githubusercontent.com/309265/231411732-9738a315-1bc3-415b-83b3-624bfbea19cb.png">

This happens because ctranslate2.dll has as dependency  MSVCP140.dll and VCRUNTIME140.dll libraries that are part of the Visual C++ runtime:

<img width="324" alt="Captura de pantalla 2023-04-12 a les 11 14 58" src="https://user-images.githubusercontent.com/309265/231412145-a1f97ea3-2207-4e61-b387-0a1c6a645477.png">

These libraries are not installed by default on Windows, however most of the users will have them because other applications installed them before.

Once I downloaded and installe [Visual C++ Redistributable for Visual Studio 2015 ](https://www.microsoft.com/en-US/download/details.aspx?id=48145) ctranslate2 worked as expected.

My suggestion is to add a small note in the [documentation](https://opennmt.net/CTranslate2/installation.html) explaining that in Windows you may need these dependencies, which are installed in most of the machines. I can do a PR for this in the docs.

**Comment by guillaumekln** [comment]
Sure, you can open a PR to add this note.
