### ISSUE TITLE
CUDA 12 Support

### ISSUE THREAD

**Issue by jzju** [OpenNMT/CTranslate2#1175]
The new RTX 4000 series GPUs seems to be made for driver version >= 525 and CUDA 12.

**Comment by guillaumekln** [comment]
You can still install and run CUDA 11 for the RTX 4000 series GPU.

I've seen multiple people using CTranslate2 on this GPU generation without issue.

**Comment by jzju** [comment]
I have a Intel cpu machine that works fine but my AMD cpu machine don't have any video output when using the old driver.

Or do you mean combining new driver with old cuda?

**Comment by guillaumekln** [comment]
Yes you can use CUDA 11 with a recent GPU driver.
