### ISSUE TITLE
Conversion breaks in some shared parameters setups.

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#118]
Hey @guillaumekln 

If we take a shared embeddings setup between encoder and decoder for instance, some aliases are made here:
https://github.com/OpenNMT/CTranslate2/blob/9379e2f3f8b83c0ff10ccccdfc6e7556a56716c1/python/ctranslate2/specs/model_spec.py#L83-L99

which is called when `.validate()` is called.

Here, we `.validate()` before getting the vocabulary sizes:
https://github.com/OpenNMT/CTranslate2/blob/9379e2f3f8b83c0ff10ccccdfc6e7556a56716c1/python/ctranslate2/converters/converter.py#L59-L61 

But, these `{source,target}_vocabulary_size` property/methods do not handle aliases:
https://github.com/OpenNMT/CTranslate2/blob/9379e2f3f8b83c0ff10ccccdfc6e7556a56716c1/python/ctranslate2/specs/transformer_spec.py#L34-L40

---> 
```
MODEL_SPEC AFTER VALIDATE {'weight': 'decoder/embeddings/weight', 'multiply_by_sqrt_depth': 'decoder/embeddings/multiply_by_sqrt_depth'}
Traceback (most recent call last):
  File "/home/moses/CTranslate2/env_onmt/bin/onmt_release_model", line 8, in <module>
    sys.exit(main())
  File "/home/moses/CTranslate2/env_onmt/lib/python3.6/site-packages/onmt/bin/release_model.py", line 52, in main
    converter.convert(opt.output, model_spec, force=True)
  File "/home/moses/CTranslate2/env_onmt/lib/python3.6/site-packages/ctranslate2/converters/converter.py", line 74, in convert
    self._check_vocabulary_size("source", src_vocab, model_spec.source_vocabulary_size)
  File "/home/moses/CTranslate2/env_onmt/lib/python3.6/site-packages/ctranslate2/specs/transformer_spec.py", line 32, in source_vocabulary_size
    return self.encoder.embeddings.weight.shape[0]
AttributeError: 'str' object has no attribute 'shape'
```

Am I missing something here?

**Comment by guillaumekln** [comment]
Thanks for reporting and locating the issue.

The regression was introduced in this commit https://github.com/OpenNMT/CTranslate2/commit/974635e8d777815aae2833dd71f721c683bf75cf which did not take aliases into account.

I will fix this and add a test case.
