### ISSUE TITLE
Llama 7B generator incorrectly creates sequence_ids from input tokens

### ISSUE THREAD

**Issue by vancoykendall** [OpenNMT/CTranslate2#1190]
When giving the following list of prompt tokens to a `Generator.generate_batch()` for a Llama 7B model
```
['<s>', '▁', '1', ',', '▁', '2', ',', '▁', '3', ',', '▁', '4', ',', '▁', '5', ',', '▁', '6', ',', '▁', '7', ',', '▁', '8', ',', '▁', '9']
```
the token ids in the `GenerationResult.sequences_ids` list corresponding to the prompt tokens are different from the token ids I get when I encode the tokens using`SentencePieceProcessor` from the python `sentencepiece` library. This causes the model to generate new lines in between the next numbers in the sequence.

**GenerationResult.sequences_ids**:  `[6756, 29896, 11167, 6756, 29906, 11167, 6756, 29941, 11167, 6756, 29946, 11167, 6756, 29945, 11167, 6756, 29953, 11167, 6756, 29955, 11167, 6756, 29947, 11167, 6756, 29929, 11167, 13, 29896, 29900, 11167, 13]`
**python sentencepiece**: `[1, 29871, 29896, 29892, 29871, 29906, 29892, 29871, 29941, 29892, 29871, 29946, 29892, 29871, 29945, 29892, 29871, 29953, 29892, 29871, 29955, 29892, 29871, 29947, 29892, 29871, 29929]`

These are the tokens from using `SentencePieceProcessor.id_to_piece()` to map the `GenerationResult.sequences_ids` to their token string: `['▁\r', '1', ',\r', '▁\r', '2', ',\r', '▁\r', '3', ',\r', '▁\r', '4', ',\r', '▁\r', '5', ',\r', '▁\r', '6', ',\r', '▁\r', '7', ',\r', '▁\r', '8', ',\r', '▁\r', '9', ',\r', '<0x0A>', '1', '0', ',\r', '<0x0A>']`

*<0x0A> corresponds to the `\n` character*

Here is the code I was using:
```python
import ctranslate2
import sentencepiece as spm

generator = ctranslate2.Generator(model_dir, device="cuda", compute_type="float16")
sp = spm.SentencePieceProcessor(os.path.join(model_dir, "tokenizer.model"))
prompt = "1, 2, 3, 4, 5, 6, 7, 8, 9"
prompt_tokens = sp.encode(prompt, out_type=str)
prompt_tokens.insert(0, sp.id_to_piece(sp.bos_id()))
result = generator.generate_batch([prompt_tokens], max_length=32)
print(result[0].sequences_ids)
print([sp.piece_to_id(t) for t in prompt_tokens])
```

```python
# Map GenerationResult.sequences_ids to token strings
pieces = []
for id in result[0].sequences_ids:
    pieces.append(sp.id_to_piece(id))
print(pieces)
```
This issue results in the model generating new lines in between

**Comment by guillaumekln** [comment]
Thank you for reporting this issue.

The vocabulary contains the tokens `▁\r` and `▁`, but \r is removed when the vocabulary is loaded in the C++ code. This explains the incorrect token ID.

The linked PR fixes the vocabulary loading by only removing \r if all all lines in the vocabulary end with this character.
