### ISSUE TITLE
CMake errors when using -DBUILD_SHARED_LIBS=OFF after #1178

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#1196]
Hi,

It seems sth went off after #1178 and now I'm getting these errors in my project:

```CMake
CMake Error: install(EXPORT "ctranslate2Targets" ...) includes target "ctranslate2" which requires target "spdlog_header_only" that is not in any export set.
CMake Error in ext/CTranslate2/CMakeLists.txt:
  export called with target "ctranslate2" which requires target
  "spdlog_header_only" that is not in any export set.


CMake Error in ext/CTranslate2/CMakeLists.txt:
  export called with target "ctranslate2" which requires target
  "cpu_features" that is not in any export set.
```

Building from command line seems OK, so do I have to change anything in my project's CMakeLists.txt?

**Comment by guillaumekln** [comment]
Hi,

@HennerM Do you have any idea? Note that the targets `spdlog_header_only` and `cpu_features` are "private".

**Comment by guillaumekln** [comment]
@panosk I'm not sure how to reproduce this error. Do you integrate CTranslate2 with `add_subdirectory` or something else?

**Comment by HennerM** [comment]
Can you use the CMake packaging stuff:
```
find_package(ctranslate2)

add_executable (main main.cpp)
target_link_libraries(main CTranslate2::ctranslate2)
```

**Comment by panosk** [comment]
> @panosk I'm not sure how to reproduce this error. Do you integrate CTranslate2 with `add_subdirectory` or something else?

Yes, I'm adding it with `add_subdirectory`.

**Comment by panosk** [comment]
> Can you use the CMake packaging stuff:
> 
> ```
> find_package(ctranslate2)
> 
> add_executable (main main.cpp)
> target_link_libraries(main CTranslate2::ctranslate2)
> ```

Thing is that I don't want to have to build and install the lib and then include it in my project, so it would be nice to still allow to integrate it with `add_subdirectory`.

**Comment by guillaumekln** [comment]
I don't reproduce this error after a fresh Git clone and this basic CMakeLists.txt:

```cmake
project(example)
cmake_minimum_required(VERSION 3.7)

add_subdirectory(CTranslate2)

add_library(example example.cc)
target_link_libraries(example ctranslate2)
```

**Comment by panosk** [comment]
> I don't reproduce this error after a fresh Git clone and this basic CMakeLists.txt:
> 
> ```cmake
> project(example)
> cmake_minimum_required(VERSION 3.7)
> 
> add_subdirectory(CTranslate2)
> 
> add_library(example example.cc)
> target_link_libraries(example ctranslate2)
> ```

Thanks for testing. Can you still include it without issues if you use `add_executable` instead of `add_library`?

**Comment by guillaumekln** [comment]
Yes it also works with `add_executable`.

**Comment by guillaumekln** [comment]
@HennerM Can you look to make the changes compatible with static compilation? Thanks.

**Comment by redthing1** [comment]
I get this too.

**Comment by guillaumekln** [comment]
Maybe the easiest fix is to not define these `export` command when using `-DBUILD_SHARED_LIBS=OFF`. Anyone wants to try and contribute a fix?

**Comment by panosk** [comment]
@guillaumekln , I could check later today.

**Comment by as-ascii** [comment]
I don't want to be a "party killer" but without exporting targets there is an incorrect include left in the config file and find_package will not work correctly in static builds of applications using CTranslate2. We just crashed on this trying to prepare static builds of https://github.com/docwire/docwire
