### ISSUE TITLE
Does CT2 support loading of two GPUs

### ISSUE THREAD

**Issue by lx0126z** [OpenNMT/CTranslate2#1199]
I want to try llama30b, when I converted it to 8bit by Ctranslate2,  the model still had 30GB, but my single graphics card had 24GB. How to make it work through two 24GB GPUs.

**Comment by guillaumekln** [comment]
Currently a single model cannot be loaded on multiple GPUs. See also #1052.

**Comment by guillaumekln** [comment]
Closing in favor of the other issue.
