### ISSUE TITLE
How to build the prebuild binaries?

### ISSUE THREAD

**Issue by JustFrederik** [OpenNMT/CTranslate2#1203]
I noticed that there is a list of supported devices for the prebuild binaries. What prompt did you use to compile these?

its compiled like this: `cmake -DWITH_OPENBLAS=ON -DWITH_CUDA=OFF .. && make -j4`, but which arguments where used in the prebuild binaries.

So the optimal backend will be selected and cuda will be used when supported.

[Supported Devices](https://opennmt.net/CTranslate2/hardware_support.html)

**Comment by guillaumekln** [comment]
See the `prepare_build_*` scripts here:

https://github.com/OpenNMT/CTranslate2/tree/master/python/tools

**Comment by JustFrederik** [comment]
Thanks!

So when i understood right i need to compile the project for every operating system and system architecture separately right?

**Comment by guillaumekln** [comment]
Yes.

**Comment by JustFrederik** [comment]
Is the precompiled  binary uploaded somewhere or do indeed to compile it for myself?

**Comment by guillaumekln** [comment]
The precompiled binaries currently refer to the Python packages and the Docker image. They are uploaded here:

* https://pypi.org/project/ctranslate2/#files
* https://github.com/OpenNMT/CTranslate2/pkgs/container/ctranslate2

**Comment by JustFrederik** [comment]
I’m looking for the precompiled lib not for python. So I can tell the program to download the file that is needed to compile for the project

**Comment by guillaumekln** [comment]
The links I shared are the only precompiled binaries available at this time.

For all other use cases, you should compile the library from the sources.
