### ISSUE TITLE
Optimize rotary embedding recreation

### ISSUE THREAD

**Issue by janekb04** [OpenNMT/CTranslate2#1204]
Opening this issue just in case, to keep track of it. Based on a comment from #1127. (Yes, the threshold was indeed 2048):

> > I noticed that after crossing some length threshold (of the entire conversation) the speed drops down to about 8 tokens per second. Is that to be expected as it is some kind of limitation of the model or CTranslate2?

> Does this length threshold happen to be 2048? That's default size of the rotary embeddings. Currently their size is increased by 1 for each step above 2048 which is not very efficient. We should increase the size by a larger value when the overflow happens (e.g. double the size).

_Originally posted by @guillaumekln in https://github.com/OpenNMT/CTranslate2/issues/1127#issuecomment-1516659861_

**Comment by guillaumekln** [comment]
This was changed in https://github.com/OpenNMT/CTranslate2/commit/ba784950f966e95385d0800c1c852fdeb949b1c5.

Are you still observing this behavior in the latest version?

**Comment by janekb04** [comment]
@guillaumekln Hi, I've been busy lately, but now, I've had the time to confirm that, indeed, there is no longer a drop in performance when the embeddings grow.
