### ISSUE TITLE
GPT-NeoX

### ISSUE THREAD

**Issue by palladium123** [OpenNMT/CTranslate2#1206]
Thank you for supporting GPT-NeoX in your latest release. 

I realised that memory usage has not really decreased much (compared to whisper -> faster-whisper for example) in this use case.  GPU memory on ctranslate2 using` int8-float16 `quantized model (during conversion), with the same compute type, is 22568MB. The original implementation used 24028MB (using `load_in_8bit = True)`. Loading time  on ctranslate2 was 71.1s compared to 113.5s on the original implementation, thanks to its smaller model size (19GB vs 38GB). Inference time was largely the same (9.05s @ ctranslate2 vs 8.67s with the original implementation).

Is this expected? 

PS: I am using a slightly fined tuned model: [here](https://huggingface.co/togethercomputer/GPT-NeoXT-Chat-Base-20B) , which is fined tune for chatbot-type tasks, as opposed to EleutherAI's original model. 

Thanks for your help!

**Comment by guillaumekln** [comment]
> GPU memory on ctranslate2 usingint8-float16quantized model (during conversion), with the same compute type, is 22568MB. The original implementation used 24028MB (using load_in_8bit = True)

In 8-bit mode, the memory usage cannot be less than the model size on disk so these numbers are expected.

> Inference time was largely the same (9.05s @ ctranslate2 vs 8.67s with the original implementation).

What are you measuring? Is it the generation time for a fixed length?

**Comment by palladium123** [comment]
> What are you measuring? Is it the generation time for a fixed length?

Yes. Although I must admit that benchmark was flawed because I didn't realise the difference in how both implementations count the number of tokens. The original implementation uses `max_new_tokens` (so the number of the tokens of the input does not count, even though it is included in the output. cTranslate2 uses `max_length` which counts the length of the input; I bypassed this by setting it to `len(input_token) + x` (where x is `max_new_tokens` in the original implementation). 

With that in mind, I ran a new benchmark, which showed cTranslate to be significantly faster @ 6.4s compared to 9.3s of the original implementation (max_new_tokens =32). However, the output is materially different. 

```
`Input:` "Rylai told Tuskar that she isn't interested in him romantically, but wants to remain friends. They have known each other for years. How is Tuskar likely to feel? "
```

cttranslate2 output (using `result = generator.generate_batch(
        [tokens], max_length = len(tokens)+32, include_prompt_in_result = True, sampling_topk=20, sampling_temperature = 0.01, 
        beam_size = 1`) : 

```
Rylai told Tuskar that she isn't interested in him romantically, but wants to remain friends. They have known each other for years. How is Tuskar likely to feel? 
(A) hurt and rejected (B) hurt and confused (C) hurt and happy
<bot>: B
<human>: In this task, you
```

Reference implementation output (using` outputs = model.generate(**inputs, max_new_tokens=32, do_sample=True, temperature=0.01`and `load_in_8bit=True` ): 

```
Rylai told Tuskar that she isn't interested in him romantically, but wants to remain friends. They have known each other for years. How is Tuskar likely to feel? 
(A) He will be sad because he likes Rylai and she doesn't like him back. (B) He will be happy because he likes
```

Some help would be appreciated.

**Comment by guillaumekln** [comment]
The different output is expected because you are using random sampling.

Also I don’t exactly know what `load_in_8bit = True` does so probably there are additional differences there.
