### ISSUE TITLE
Model running fine on cpu but not on gpu

### ISSUE THREAD

**Issue by mayanksinha900** [OpenNMT/CTranslate2#1207]
When I load my model using this method
```
generator = ctranslate2.Generator('./llama_ct2/')
sp = spm.SentencePieceProcessor("./llama_ct2/tokenizer.model")
```
The model runs fine and gives the output. My generator loop is:
```
step_results = generator.generate_tokens(
    prompt_tokens,
    sampling_temperature=0.8,
    sampling_topk=1,
    max_length=512,
)

output_ids = []

for step_result in step_results:
    is_new_word = step_result.token.startswith("▁")

    if is_new_word and output_ids:
        word = sp.decode(output_ids)
        print(word, end=" ", flush=True)
        output_ids = []

    output_ids.append(step_result.token_id)
    break

if output_ids:
    word = sp.decode(output_ids)
    print(word)
```
But when I load my model using this method
```
generator = ctranslate2.Generator('./llama_ct2/', device='cuda')
sp = spm.SentencePieceProcessor("./llama_ct2/tokenizer.model")
```
The for loop on `step_results` keeps on going without ending.

I am not sure what the error here is.

**Comment by niizam** [comment]
same for me, i can't use cuda on windows while on linux it works

**Comment by guillaumekln** [comment]
Can you try using the method `generate_batch` and see if an error is reported?

**Comment by tariq0101** [comment]
I think they found where the issue in this thread 
#https://github.com/Softcatala/whisper-ctranslate2/issues/11

**Comment by mayanksinha900** [comment]
> same for me, i can't use cuda on windows while on linux it works

I have this problem on linux as well.

When I tried to use `generate_batch`, I got a runtime error:
```RuntimeError: Library libcublas.so.11 is not found or cannot be loaded```. 

I think it maybe because of this, I will try and fix this. Will update whether this fixes the problem or not.

**Comment by guillaumekln** [comment]
Thanks. We should fix `generate_tokens` to properly raise the error.
