### ISSUE TITLE
Python Interface AutoModelConvert for Huggingface Transformers

### ISSUE THREAD

**Issue by michaelfeil** [OpenNMT/CTranslate2#1208]
Similar to the work in faster-whisper.

Download and convert models from huggingface hub on the fly.
All the steps are doable right now, by combining a few CLI calls, making the usage easier.

Idea:
- 1. check comparability of the huggingface-transformer architecture on Huggingface Hub.
- 2. download huggingface-transformer to `~/.cache/huggingface`
- 3. convert the model from `~/.cache/huggingface` to `~/.cache/ctranslate2` 
- 4. load model from  `~/.cache/ctranslate2` 

```python
import ctranslate2
import os

class AutoModelConverter:
    def __init__(self) -> None:
        pass
    
    def from_pretrained(model_name_or_path, quantization="int8_float16"):
        # 1. check compat
        from transformers import AutoConfig
        hf_config = AutoConfig.from_pretrained(model_name_or_path).to_dict()
        supported_ct2_architectures = ['T5ForConditionalGeneration', ..]

        if not all(supported_ct2_architectures in arch for arch in hf_config["architectures"]):
            raise ValueError("not supported: %s", hf_config["architectures"])
        
        converted_dir = f"~/.cache/ctranslate2/{model_name_or_path}"
        
        # 2. convert
        if not os.path.exists:
            converter = ctranslate2.converters.TransformersConverter(
                model_name_or_path,
            )
            converter.convert(output_dir=converted_dir, force=True, quantization="int8_float16")

        # 3. load  correct architecture
        return ctranslate2.Generator(converted_dir, quantization, "cuda")
        # or
        return ctranslate2.Translator(converted_dir, quantization, "cuda")
```

**Comment by guillaumekln** [comment]
We don't plan to add this kind of automatic conversion. I think I really want to keep the model conversion and usage separated. This way the dependency of the original model (PyTorch, TensorFlow, Transformers, etc.) are no longer needed to run the model.

> Similar to the work in faster-whisper.

Note that faster-whisper automatically downloads models that are already converted. There is no automatic conversion here.

**Comment by michaelfeil** [comment]
Makes sense to me, to keep dependencies separated. 
I pushed some models to https://pypi.org/project/hf-hub-ctranslate2/, e.g. usage of:
https://huggingface.co/michaelfeil/ct2fast-dolly-v2-12b
Would it make sense to support loading of converted models, or is a ad-hoc converted model with version 3.13 planned to be no longer compatible with version 3.1x?

**Comment by guillaumekln** [comment]
Converted models are always compatible with future versions. There could be incompatibility with a major version (e.g. v3 -> v4), but for now it never happened.

https://opennmt.net/CTranslate2/conversion.html#backward-compatibility
