### ISSUE TITLE
Support for Mosaic ML MPT 7B

### ISSUE THREAD

**Issue by praneetreddy017** [OpenNMT/CTranslate2#1212]
MPT 7B is a model developed by MosaicML which is powered by ALiBi allowing for a larger context window than other contemporary models 

https://huggingface.co/mosaicml/mpt-7b

Support for this model would be greatly appreciated

**Comment by gokulsabari22** [comment]
+1

**Comment by Apoorv7092** [comment]
+1

**Comment by baptistejamin** [comment]
It should be doable by pulling the configuration from here: https://github.com/0cc4m/GPTQ-for-LLaMa/blob/latestmerge/gptq/mpt.py

**Comment by vince62s** [comment]
FYI: we added support for MPT in OpenNMT-py. read this: https://forum.opennmt.net/t/finetuning-llama-7b-or-mosaicml-mpt-7b-reproduce-vicuna-alpaca/5272
CT2 converter will come later.
