### ISSUE TITLE
add fairseq nllb insttructions 

### ISSUE THREAD

**Issue by Omicronlawful** [OpenNMT/CTranslate2#1223]
i want to use the fairseq converter to convert the nllb models. The performance is better when using the fairseq converter.

i tested it with the m2m100_1.3b model. The fairseq model takes 1.3s while the model from huggingface takes 1.45s on average for the same sentence. could you add documentation for https://github.com/facebookresearch/fairseq/tree/nllb/examples/nllb/modeling

**Comment by guillaumekln** [comment]
There is no reason for the performance to be different. The model weights are the same.

However, there is a subtle difference in how the 2 models handle the special tokens `</s>` in the source side. See the corresponding [documentation](https://opennmt.net/CTranslate2/guides/transformers.html#special-tokens-in-translation). This could explain the difference you are observing.
