### ISSUE TITLE
Support for GPTBigCodeForCausalLM (StarCoder/ SantaCoder)

### ISSUE THREAD

**Issue by michaelfeil** [OpenNMT/CTranslate2#1231]
GPTBigCodeForCausalLM is GPT-2 with Multi-Query attention, I would assume it should be feasible to convert it.

Started a thread here:
https://forum.opennmt.net/t/converter-hints-for-converting-transformer-of-gptbigcodeforcausallm/5298

**Comment by michaelfeil** [comment]
Sure, I mean multi-query attention instead of MHA. 
https://github.com/bigcode-project/starcoder.cpp/blob/8d4b584506663398180e2e2568ba99b6cbba3a27/convert-hf-to-ggml.py#L182
starcoder.cpp just duplicates the K,V heads and performs a less efficent MHA. Maybe this could be a option.

No idea, how complicated it is to implement this in C++

**Comment by guillaumekln** [comment]
It makes sense to replicate the heads.

Can you try to write a converter where the KV weights are replicated accordingly?

If it works, I can take it from there and implement the multi-query optimization.

**Comment by michaelfeil** [comment]
Cool! Sounds great, I'll write a converter in with converting MQA to MHA (GPTBigCode-Style to GPT-2 Style). Then you can take it from there, and see if there is decent memory improvements / speedups  (probably), with a direct implementation of MQA, while you have the option to validate the newly implemented MQA end-to-end.

**Comment by michaelfeil** [comment]
Okay, done so far.
Works for:
- https://huggingface.co/bigcode/gpt_bigcode-santacoder
- https://huggingface.co/bigcode/starcoder

gpt_bigcode-santacoder seems quite fast, for starcoder, the large duplicated weights probably cause the exact memory transfer bottleneck described in the paper / documentation, I am curious how it will change once MQA is implemented natively.

**Comment by guillaumekln** [comment]
Thanks for the PR! It definitely helped me getting started on MQA. I will first merge your PR, then integrate MQA in a separate PR.

**Comment by guillaumekln** [comment]
Can you try with `include_prompt_in_result=False`?

See the newly added note in the documentation: https://opennmt.net/CTranslate2/python/ctranslate2.Generator.html#ctranslate2.Generator.generate_batch

**Comment by michaelfeil** [comment]
True, with include_prompt_in_result=False, it works better, around 2x speedup for starcoder.
