### ISSUE TITLE
Repeated text with Marian Model generation 

### ISSUE THREAD

**Issue by zzgsty** [OpenNMT/CTranslate2#1236]
CTranslate2   3.13.0

sp = spm.SentencePieceProcessor()
sp.load("opus-2021-02-23/source.spm")
list =  ["Hello."]
list = sp.encode_as_pieces(list)
print(list)
translator = ctranslate2.Translator("opusct2021")
results = translator.translate_batch(list)
for r in results:
    print(r.hypotheses[0])
    output = sp.decode(r.hypotheses[0])
    print(output)

out print:▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好▁你好

**Comment by guillaumekln** [comment]
Can I download this model somewhere?

If not, can you share the model configuration?

**Comment by woolz** [comment]
I have the same problem when I converted a model trained with Marian 1.12.0 and try batched translation
```
[['云澈', '、', '萧澈']]
[['angry', 'angry', 'disappear', 'angry', 'golden', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear']]
```
[model-config.yaml.txt](https://github.com/OpenNMT/CTranslate2/files/11587198/model-config.yaml.txt)

**Comment by woolz** [comment]
> ```
> [['angry', 'angry', 'disappear', 'angry', 'golden', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear', 'disappear']]
> ```

I have a src vocab size of 114k and target vocab size of 57k should it be a problem?

**Comment by guillaumekln** [comment]
The vocabulary size should not be an issue. However, I'm not sure the current converter handles correctly the parameter `tied-embeddings-all: false`.

Can you run the following code on the Marian model file (`.npz`) and share the output? It will list the weights saved in the model.

```python
import numpy as np
model = np.load("the_model.npz")
for key in sorted(model.keys()):
    print(key)
```

**Comment by guillaumekln** [comment]
@zzgsty I figured you are probably using this model:

https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/06edba8e66d4a99bed04780d21c69c4072992601/models/eng-zho#opus-2021-02-23zip

If that's the case you should add the target language tag as mentioned in this link. For example:

```python
source_tokens = [">>cmn_Hans<<"] + sp.encode("Hello.", out_type=str)
```

@woolz Your issue looks different. Can you open a different GitHub issue and provide the information that I asked in my previous comment?
