### ISSUE TITLE
Unable to follow the quickstart conversion of pytorch models

### ISSUE THREAD

**Issue by n2oblife** [OpenNMT/CTranslate2#1243]
My initial goal is to train a model on pytorch and then convert the weight and/or the model in order to run the inference in C++.
So I would like to convert a pretrained model, I first followed the [quickstart](https://opennmt.net/CTranslate2/quickstart.html), unfortunately I had the following issue : 

> ct2-opennmt-py-converter --model_path averaged-10-epoch.pt --output_dir ende_ctranslate2
`File "/home/user/project/py-env/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'onmt.inputters.text_dataset'`

I also tried to convert my customed model, and added to the state_dict a vocab key with the source and target, and also an Option class. Here is the core of my code : 

'
class Option :
    def __init__(self) -> None:
        self.encoder_type = 'transformer' # transformer or transformer-lm
        self.decoder_type = 'transformer' # transformer or transformer-lm
        self.self_attn_type = 'scaled-dot'
        self.pos_ffn_activation_fn = 'relu' # gelu or fast_gelu or relu
        self.position_encoding = True
        self.max_relative_positions = 0
        self.feat_merge = 'concat' # concat or sum

if __name__ == '__main__' :
    net = generate_model()
    optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
    dico = net.state_dict()

    # regularize for opennmt converter
    dico["vocab"] = {"src" : [], "tgt" : []}
    dico["opt"] = Option()

    path = 'path_to_save_dir/net.pt'
    torch.save(dico, path) 
'

> ct2-opennmt-py-converter --model_path path_to_save_dir/net.pt --output test_ct2
'File "/home/user/project/py-env/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'Option' on <module '__main__' from '/home/user/project/py-env/bin/ct2-opennmt-py-converter'>
'

Could you help me ?

**Comment by n2oblife** [comment]
Hi, I downgraded the version of OpenNMT-py to 2.3.0 and it worked well.
Furthermore I will train my model with OpenMT-py to avoid the other issue a shared.

Nevertheless, I would like to know if it is possible to train the model using pytorch and still convert the model ?

**Comment by guillaumekln** [comment]
The provided conversion scripts only support models that are trained directly with the corresponding framework. If you trained or saved the model with your own code it will probably not work.

In that case it can still be possible to convert it to CTranslate2 but you would need to create your own conversion script. You can use the existing converters as examples:

https://github.com/OpenNMT/CTranslate2/tree/master/python/ctranslate2/converters
