### ISSUE TITLE
Invalid resource handle when deleting ctranslate2.Translator

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#125]
Hi @guillaumekln 
There seems to be an issue when deleting a model from a device other than the 0th one.
```
import ctranslate2
translator = ctranslate2.Translator(
    "enes_general_medium_ctranslate2",
    device="cuda",
    device_index=0)
del translator
```
--> OK
```
import ctranslate2
translator = ctranslate2.Translator(
    "enes_general_medium_ctranslate2",
    device="cuda",
    device_index=1)
del translator
```
--> ERROR
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  /root/ctranslate2-dev/src/primitives/cuda.cu:72: CUDA failed with error invalid resource handle
Aborted (core dumped)
```
(Inference works fine though, it's only when deleting the object that it fails.)

EDIT: This also happens when using the cli entrypoint `ctranslate2/bin/translate`.

**Comment by guillaumekln** [comment]
Thanks for reporting. When testing, I found another behavior that should be improved: #127.

Let me know if there are other issues like these. I did not test the device placement thoroughly.

**Comment by francoishernandez** [comment]
Thanks for the quick fix.
This seems to fix the python case, but not the `translate` cli though.
(Pulled repo and rebuilt docker image from scratch.)

**Comment by guillaumekln** [comment]
Right. The API usage is slightly different.

**Comment by francoishernandez** [comment]
The issue seem to be appearing again on master:
```
>>> import ctranslate2
>>> translator = ctranslate2.Translator("ende_ctranslate2", device="cuda", device_index=0)
>>> translator.translate_batch([["▁H", "ello", "▁world", "!"]])
[[{'score': -1.736800193786621, 'tokens': ['▁Hallo', '▁Welt', '!']}]]
>>> del translator
>>> translator = ctranslate2.Translator("ende_ctranslate2", device="cuda", device_index=1)
>>> translator.translate_batch([["▁H", "ello", "▁world", "!"]])
[[{'score': -1.736800193786621, 'tokens': ['▁Hallo', '▁Welt', '!']}]]
>>> del translator
terminate called after throwing an instance of 'std::runtime_error'
  what():  /root/ctranslate2-dev/src/primitives/cuda.cu:72: CUDA failed with error invalid resource handle
Aborted (core dumped)
```
The error does not happen when deleting the object right after building it, without performing any translation.

**Comment by guillaumekln** [comment]
Thanks. I can reproduce this.

I will look to provide a more robust fix to this issue.
