### ISSUE TITLE
support for falcon 7b instruct model

### ISSUE THREAD

**Issue by GeorvityLabs** [OpenNMT/CTranslate2#1254]
@guillaumekln hope you could add support for falcon 7b instruct model.
https://huggingface.co/tiiuae/falcon-7b-instruct

**Comment by limcheekin** [comment]
I think should support all Falcon model as they just announced:
Falcon-[40B](https://huggingface.co/tiiuae/falcon-40b)/[7B](https://huggingface.co/tiiuae/falcon-7b) are now available under the Apache 2.0 license, TII has [waived all royalties and commercial usage restrictions](https://www.tii.ae/news/uaes-falcon-40b-worlds-top-ranked-ai-model-technology-innovation-institute-now-royalty-free).

You can see their announcement at https://huggingface.co/tiiuae

**Comment by Matthieu-Tinycoaching** [comment]
Hi @guillaumekln when do you think the next release with falcon model will be available?

**Comment by guillaumekln** [comment]
I'm preparing a new release for today.
