### ISSUE TITLE
 AttributeError: 'T5Config' object has no attribute 'dense_act_fn' 

### ISSUE THREAD

**Issue by Two222** [OpenNMT/CTranslate2#1255]
when i trandformer the model of t5-small ,i  met this problem?
who knows?

and i saw the config file ,it's no such config valiable

**Comment by guillaumekln** [comment]
You are probably using an older version of `transformers`. Try updating this module.

```
pip install --upgrade transformers
```

**Comment by Two222** [comment]
which version can solve this prob？



发自我的iPhone


------------------ Original ------------------
From: Guillaume Klein ***@***.***&gt;
Date: Wed,May 31,2023 7:03 PM
To: OpenNMT/CTranslate2 ***@***.***&gt;
Cc: Honda_J ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [OpenNMT/CTranslate2]  AttributeError: 'T5Config' object has no attribute 'dense_act_fn'  (Issue #1255)





 
You are probably using an older version of transformers. Try updating this module.
 pip install --upgrade transformers

**Comment by guillaumekln** [comment]
`transformers>=4.20`
