### ISSUE TITLE
is there python api to get gpu related infomation like name?

### ISSUE THREAD

**Issue by iorilu** [OpenNMT/CTranslate2#1257]
I checked the doc, only find this function

 get_cuda_device_count

so , is there any way to get more infomation about the gpu

like in torch
`gpu_name = torch.cuda.get_device_name(0)`

since i want to check it and display it like this

`you are using GPU: NVIDIA GeForce RTX 3060 Laptop GPU`

or , if there there are multiple gpus , I can make a list of gpu names for user to choose to use

**Comment by lx0126z** [comment]
maybe you wanna find this
ctranslate2.Generator(model_path,device="auto",device_index=1）

**Comment by guillaumekln** [comment]
There is currently no API to get the GPU name and I don't plan to add one at the moment.

PyTorch has already several functions to get the GPU properties. You should probably use those.
