### ISSUE TITLE
how does ctanslate2 find cudnn files

### ISSUE THREAD

**Issue by iorilu** [OpenNMT/CTranslate2#1267]
i am using faster-whisper to buildn app

it seems it works  fine on my development pc

after i use pyinstaller to build exe version,and copy some cudnn,cublas dlls to the same folder with exe file, and copy whole folder to another test pc, it didnt work well

using medium size model, only use 2.5G VRAM, but it cost 4G VRAM on my dev pc

I am not sure if cudnn or cublas is used on my test pc , since it use less VRAM

the files i copied and the folder looks like below
```
myapp.exe
cublasLt64_11.dll
cublas64_11.dll
zlibwapi.dll
cudnn_ops_infer64_8.dll
cudnn_cnn_infer64_8.dll
```

will this structure be ok to use ctranslate2 without install cuda tookit and cudnn to folder like "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\"

also need to confirm these dlls has any verion requirements , since my dev pc install 11.6 version , I just copied these file from folder "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\"

**Comment by iorilu** [comment]
thanks for the confirmation

**Comment by archive-r** [comment]
[os.add_dll_directory](https://docs.python.org/3/library/os.html#os.add_dll_directory) works fine, I was able to add the path with the following code before importing ctranslate2 (or faster-whisper).

```
from pathlib import Path

current_dir = Path.cwd()
os.add_dll_directory(str(current_dir))

import ctranslate2

...
```
