### ISSUE TITLE
Request to load json format vocabulary for huggingface models.

### ISSUE THREAD

**Issue by nemoramo** [OpenNMT/CTranslate2#1272]
For some special tokens in huggingface models like "<|im_start|>\n", "<|im_end|>\n", the current convertor will convert these tokens to txt file like:
"""
<|im_start|>

<|im_end|>

"""
which will cause vocabulary mismatch.
The suggestion is to use json like format loading instead using plain text.

**Comment by guillaumekln** [comment]
Thanks for the info. Can you share a link to a Hugging Face model using these tokens?

**Comment by nemoramo** [comment]
> Thanks for the info. Can you share a link to a Hugging Face model using these tokens?

The base model is a llama model, however we add some some special tokens like "<|im_start|>\n" into the original vocabulary.

**Comment by guillaumekln** [comment]
It makes sense to change the format. We already had issues in the past with token containing carriage returns (#1190). The JSON format should fix these cases.
