### ISSUE TITLE
Falcon: float16 vs bfloat16

### ISSUE THREAD

**Issue by juliensalinas** [OpenNMT/CTranslate2#1275]
Thank you for adding Falcon so quickly 👏🏻 

Quick question: as Falcon uses bfloat16 by default, wouldn't float16 quantization lead to accuracy issues?
Maybe `--quantization bfloat16` would be necessary?

Thank you @guillaumekln !

**Comment by NeonBohdan** [comment]
@juliensalinas  It was important for training
For inference you will not notice a problem not only with bfloat16->float16, but ->int8 too

**Comment by juliensalinas** [comment]
Ok thanks @NeonBohdan 👍🏻 
In any case I'll make my own tests and see for myself.
I said that because of this paragraph from HuggingFace:

> The models were trained using the bfloat16 datatype, so we recommend you use the same. This requires a recent version of CUDA and works best on modern cards. You may also try to run inference using float16, but keep in mind that the models were evaluated using bfloat16.

Source: https://huggingface.co/blog/falcon

**Comment by juliensalinas** [comment]
I will let you know if I notice accuracy drops @guillaumekln . For the moment let me close this issue then.
Thanks again for the great work.
