### ISSUE TITLE
Question for asynchronous in generate_batch

### ISSUE THREAD

**Issue by Snowdar** [OpenNMT/CTranslate2#1285]
There is a asynchronous parameter in the generate_batch, so I want to ask for some details based on Python asyncio:
1. When can async be triggered during generation? Can coroutine A be suspended when it starts to call cuda for inference and then execute coroutine B, so as to realize parallel inference of the two coroutines?
2. If so, does generate_tokens support this parameter?
3. If not, is there no way for python to achieve real parallelism (not batch-inference) based on Ctranslate2, whether it is a coroutine or multithreading with GIL?

**Comment by guillaumekln** [comment]
The asynchronous parameter is not based on Python asyncio. It is fully handled on the C++ side. With that mind:

1. When you set `asynchronous=True`, the generation is immediately running in a background C++ thread. There is noting to do from your side and there is no way to suspend the execution. The generation is actually running in parallel to the Python code.
2. `generate_tokens` uses this parameter internally. So when the method yields a new tokens, the generation keeps running in the background thread while you handle the generated token on the Python side.
3. There are multiple ways to achieve true parallelism. See the corresponding documentation: https://opennmt.net/CTranslate2/parallel.html#parallel-execution

**Comment by hobodrifterdavid** [comment]
Maybe this helps. If you want to run generator.generate_batch without blocking the event loop, you can use this snippet:
```
        def sync_func():
            return generator.generate_batch(
                tokens,
                beam_size=1,
                sampling_temperature=0.8,
                sampling_topk=10,
                num_hypotheses=1,
                max_length=80,
                min_length=1,
                include_prompt_in_result=False,
                max_batch_size=MAX_BATCH_SIZE,
                return_end_token=True,
                repetition_penalty=1.5
            )

        # Run sync_func asyncronously, so we don't block the event loop.
        # Allows other requests to be handled meanwhile.
        loop = asyncio.get_event_loop()
        results = await loop.run_in_executor(None, lambda: sync_func())
```
What's your use case? IIRC one generator.generate_batch will utilise the full gpu fairly well.
