### ISSUE TITLE
Generation is swallowing spaces perhaps?

### ISSUE THREAD

**Issue by hobodrifterdavid** [OpenNMT/CTranslate2#1287]
I'm trying to translate the flores translation dataset with llama-family models and scoring the translations using sacremoses, to test the models ability to do translation for different pairs, relative to other models and services, and also to see it's general ability in different languages.

I run a prompt like this:
```
USER: Translate the following text to ${'Spanish'}. Respond with the translation only, nothing else:

[text to translate]
ASSISTANT:
```
Because of the way I have batching set up, I generate a max of 80 tokens, then see if the generation contains either EOS token or 'USER:', if so, I consider the response complete. If not, I append the current generation to the prompt for the next generation call. So the second call to generate would have a prompt like this:
```
USER: Translate the following text to ${'Spanish'}. Respond with the translation only, nothing else:

The best food for hungry parrots are spinach and banana leaves. Raisins are also good.
ASSISTANT: La mejor comida para los loros son
```
Actual code is here:
![image](https://github.com/OpenNMT/CTranslate2/assets/16459990/7b5b8066-21a1-4ddf-a718-a432e46b6601)

The issue I'm seeing is that there are spaces missing at the boundries when I construct the translation in this way:
```
La mejor comida para los loros hambrientosson las hojas de plátano..
                                         ^^
    
```
I'm not sure why this is, it seems some code somewhere is swallowing them.. I expected the model to add an initial space when it does a continuation. I can't always add a space, because it's not appropriate in some asian languages.

Any ideas what could be causing this?

**Comment by guillaumekln** [comment]
How are you detokenizing the model output? Most likely the leading space is removed at this step.

**Comment by hobodrifterdavid** [comment]
I initialise the generator and the tokeniser like this:
```
model_dir = "/models/vicuna-13b-1.1_ct2"
generator = ctranslate2.Generator(model_dir, device="cuda", device_index=[0], compute_type='int8_float16')
sp = spm.SentencePieceProcessor(os.path.join(model_dir, "tokenizer.model"))
```
Then tokise, generate and detokenise like this (a little extra code to ensure the EOS token doesn't get removed during detokenisation..):
```
tokens: List[List[str]] = [["<s>"] + sp.encode(prompt, out_type=str) for prompt in prompts]

results = generator.generate_batch(
                tokens,
                beam_size=1,
                sampling_temperature=0.8,
                sampling_topk=10,
                num_hypotheses=1,
                max_length=80,
                min_length=1,
                include_prompt_in_result=False,
                max_batch_size=MAX_BATCH_SIZE,
                return_end_token=True,
                repetition_penalty=1.5
            )

def decode(this_result) -> str:

    if len(this_result.sequences) == 0:
        # No sequences..
        return ''

    if len(this_result.sequences[0]) == 0:
        # Sequence is len 0
        return ''

    hasEOS = this_result.sequences[0][-1] == '</s>'
    string: str = sp.decode(this_result.sequences_ids[0])
    if hasEOS:
        string += '</s>'
    # print('string: ')
    # print(string)
    return string

output: List[str] = [decode(result) for result in results]
```
Probably I should examine what is returned from generate_batch before it is detokenised..

**Comment by hobodrifterdavid** [comment]
I'm checking the decoded string against the tokens:
```
print(this_result.sequences[0])
print(f"|{string}|")
```
Seeing output like this:
```
['▁y', '▁la', '▁mal', 'aria', '▁a', '▁pa', 'ci', 'entes', '▁de', '▁países', '▁en', '▁v', 'ías', '▁de', '▁desarrollo', ',', '▁donde', '▁los', '▁í', 'nd', 'ices', '▁de', '▁super', 'v', 'iven', 'cia', '▁para', '▁c', 'án', 'cer', 'es', '▁como', '▁el', '▁del', '▁pe', 'cho', '▁pueden', '▁qued', 'ar', '▁redu', 'c', 'idos', '▁hasta', '▁en', '▁un', '▁', '5', '0', '%.', '</s>']     
|y la malaria a pacientes de países en vías de desarrollo, donde los índices de supervivencia para cánceres como el del pecho pueden quedar reducidos hasta en un 50%.</s>|
```
'▁y' should start with a space, but it's trimmed off. This should fix it:
```
                startsWithSpace = this_result.sequences[0][0][0] == '▁'
                hasEOS = this_result.sequences[0][-1] == '</s>'

                string: str = self.sp.decode(this_result.sequences_ids[0])
                if startsWithSpace:
                    string = ' ' + string
                if hasEOS:
                    string += '</s>'
```

**Comment by hobodrifterdavid** [comment]
Another issue, when running generate_batch with the code like this (with max_batch_size 6 on a 3090), and running a batch of 6 at a time in a loop:
```
tokens: List[List[str]] = [["<s>"] + sp.encode(prompt, out_type=str) for prompt in prompts]

results = generator.generate_batch(
                tokens,
                beam_size=1,
                sampling_temperature=0.8,
                sampling_topk=10,
                num_hypotheses=1,
                max_length=80,
                min_length=5,
                include_prompt_in_result=False,
                max_batch_size=6,
                return_end_token=True,
                repetition_penalty=1.5
            )
```
I am getting empty GenerationResult sometimes, and I can't see a reason for it. It seems to happen for about 20-30% of the generations when heavily loading.

GenerationResult(sequences=[[]], sequences_ids=[[]], scores=[])

I will try to make a clean test script to rule out any other factors. I've tried downgrading from 3.15.1 to 3.14. I remember reading about an issue with include_prompt_in_result, but I don't see it mentioned now so I guess it's been fixed.

**Comment by guillaumekln** [comment]
Please open a separate issue when you have more details about this empty result.

I'm closing this one since the missing space was related to the detokenization and not the generation code.
