### ISSUE TITLE
is translate_batch threadsafe

### ISSUE THREAD

**Issue by Omicronlawful** [OpenNMT/CTranslate2#1289]
I want to use ctranslate2 in rust, and i need to move it into a thread. Cxx wont let me compile it because it does not know if it is threadsafe. [Solution](https://github.com/dtolnay/cxx/issues/1175). This is how it would be solved, but the requirement is that it is threadsafe. So thats why i am asking if it is threadsafe

**Comment by guillaumekln** [comment]
Yes, the method is thread safe.
