### ISSUE TITLE
Converted and quantized int8 Fastchat-T5 model generate garbage?

### ISSUE THREAD

**Issue by limcheekin** [OpenNMT/CTranslate2#1295]
Hi there,

May I know did CTranslate2 support conversion and quantization of Fastchat-T5 model?
I converted and quantized an int8 model at https://huggingface.co/limcheekin/fastchat-t5-3b-ct2. But it is generating garbage at the moment.

Anyone here have any success experience using Fastchat-T5 model with CTranslate2?

Hope to hear from you soon!

Thanks.

**Comment by guillaumekln** [comment]
Hi,

See #1220.

**Comment by limcheekin** [comment]
My bad! I should search first before open the (duplicate) issue.

Thanks for showing me the way.
