### ISSUE TITLE
translate T5 model error

### ISSUE THREAD

**Issue by cowarder** [OpenNMT/CTranslate2#1297]
When translate t5 model with "ct2-transformers-converter --model t5-base --quantization float16 --output_dir t5-base-ct2
".
We get the error log:
"ValueError: Source vocabulary 0 has size 32228 but the model expected a vocabulary of size 32128"

It seems to be caused by special tokens, how to solve this problem?

**Comment by guillaumekln** [comment]
I'm not reproducing this error with the following environment:

```
certifi==2023.5.7
charset-normalizer==3.1.0
cmake==3.26.4
ctranslate2==3.15.1
filelock==3.12.2
fsspec==2023.6.0
huggingface-hub==0.15.1
idna==3.4
Jinja2==3.1.2
lit==16.0.6
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
PyYAML==6.0
regex==2023.6.3
requests==2.31.0
safetensors==0.3.1
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
tqdm==4.65.0
transformers==4.30.2
triton==2.0.0
typing_extensions==4.6.3
urllib3==2.0.3
```

Can you try updated the packages `transformers` and `ctranslate2`?

**Comment by cowarder** [comment]
Yes, we have the same version of transformers and ctranslate2. But in my checkpoint file of T5 model, I have 100 special tokens in the file "special_tokens_map.json". It seems to be caused by size mismatch of checkpoint and ctranslate.

How to solve the size mismatch while translating?

**Comment by cowarder** [comment]
> I'm not reproducing this error with the following environment:
> 
> ```
> certifi==2023.5.7
> charset-normalizer==3.1.0
> cmake==3.26.4
> ctranslate2==3.15.1
> filelock==3.12.2
> fsspec==2023.6.0
> huggingface-hub==0.15.1
> idna==3.4
> Jinja2==3.1.2
> lit==16.0.6
> MarkupSafe==2.1.3
> mpmath==1.3.0
> networkx==3.1
> numpy==1.24.3
> nvidia-cublas-cu11==11.10.3.66
> nvidia-cuda-cupti-cu11==11.7.101
> nvidia-cuda-nvrtc-cu11==11.7.99
> nvidia-cuda-runtime-cu11==11.7.99
> nvidia-cudnn-cu11==8.5.0.96
> nvidia-cufft-cu11==10.9.0.58
> nvidia-curand-cu11==10.2.10.91
> nvidia-cusolver-cu11==11.4.0.1
> nvidia-cusparse-cu11==11.7.4.91
> nvidia-nccl-cu11==2.14.3
> nvidia-nvtx-cu11==11.7.91
> packaging==23.1
> PyYAML==6.0
> regex==2023.6.3
> requests==2.31.0
> safetensors==0.3.1
> sympy==1.12
> tokenizers==0.13.3
> torch==2.0.1
> tqdm==4.65.0
> transformers==4.30.2
> triton==2.0.0
> typing_extensions==4.6.3
> urllib3==2.0.3
> ```
> 
> Can you try updated the packages `transformers` and `ctranslate2`?

Yes, we have the same version of transformers and ctranslate2. But in my checkpoint file of T5 model, I have 100 special tokens in the file "special_tokens_map.json". It seems to be caused by size mismatch of checkpoint and ctranslate.

How to solve the size mismatch while translating?

**Comment by guillaumekln** [comment]
I don't see this file in the original repository: https://huggingface.co/t5-base/tree/main

Maybe you can just delete it?
