### ISSUE TITLE
FAlcon-40B inference run out of memory

### ISSUE THREAD

**Issue by jgcb00** [OpenNMT/CTranslate2#1299]
Hi,
Thanks for the great job implementing Falcon-40B
The conversion works great and the inference allow me to reach 10 tok/s on a NVIDIA A40 with 46GB of effective VRAM
The model end loading with 39,4 GB of use.
After 1000 tokens, the GPU run out of memory, but 6.5 GB for only a thousand token is that in the right order of magnitude or they might be an issue ?

Regards,

**Comment by guillaumekln** [comment]
Hi,

Did you convert in "int8" or "int8_float16"? Prefer "int8_float16" to minimize the memory usage.

**Comment by jgcb00** [comment]
Hi,
I used "int8"
With "int8_float16" it's indeed far better, I have a stable memory conception at 42.7GB for 1000 tokens and a pick at  44.8GB at the end of the 2000 tokens inference.

I will see the impact of batching on the memory consumption,

Thanks a lot,
