### ISSUE TITLE
Adding several end_token in generate

### ISSUE THREAD

**Issue by jgcb00** [OpenNMT/CTranslate2#1309]
Hi,

Curently we can specify a stop sequence to the generator, so for exemple : 

If I want the generation to end on : `<|endoftext|>`
I start by tokenizing the string : 
```python
stopping_criteria = tokenizer.convert_ids_to_tokens(tokenizer.encode("<|endoftext|>"]))
```
And I can ask the model to stop generation with :
```python
generator.generate_batch(
                batch,
                end_token=stopping_criteria,
                )
```
But there is no way to stop the sequence on another token, so to stop either on `<|endoftext|>` or `###`
Could we have stopping criteria to be a list of criteria ?

Regards

**Comment by jgcb00** [comment]
Okay but I can't end the generation if there is a specific pattern, which include several token, can't I ?

**Comment by guillaumekln** [comment]
See #1244. There is no option to end on a specific sequence but it can be done via the callback function.
