### ISSUE TITLE
Moving model/translator object between devices

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#131]
I've started making adaptations to the OpenNMT-py rest server to allow the use of CTranslate2 models.
I'm thinking of some wrapping object in `onmt.translate.translation_server`, that would provide a similar API to `onmt.translate.translator`:
``` python
class CTranslate2Translator(object):
    """
    This should reproduce the onmt.translate.translator API.
    """

    def __init__(self, model_path, device, device_index, beam_size, n_best):
        import ctranslate2
        self.translator = ctranslate2.Translator(
            model_path,
            device=device,
            device_index=device_index,
            inter_threads=1,
            intra_threads=1,
            compute_type="default")
        self.beam_size = beam_size
        self.n_best = n_best

    def translate(self, texts_to_translate, batch_size=8):
        batch = [item.split(" ") for item in texts_to_translate]
        print(batch)
        preds = self.translator.translate_batch(
            batch,
            beam_size=self.beam_size,
            num_hypotheses=self.n_best
        )
        scores = [[item["score"] for item in ex] for ex in preds]
        predictions = [[" ".join(item["tokens"]) for item in ex] for ex in preds]
        return scores, predictions
```
This works fine for the translation API part.
Only remaining issue is that there is some logic in the server that requires models to move back and forth from/to CPU/cuda (`to_cpu` // `to_gpu` methods that call some `.to(device)` on the model).
Is this something we could easily add in the `ctranslate2.Translator` API?

**Comment by guillaumekln** [comment]
Given that CTranslate2 models are relatively fast to load from disk (1s or less on a SSD), I usually recommend to just re-create a translator. Could you try that as a first step and see if the performance is acceptable?

**Comment by francoishernandez** [comment]
I'm testing with some big/medium models also, and the load time is more like 2 seconds here.

**Comment by vince62s** [comment]
This kills the benefit of CTranslate2 in a realtime environment.

**Comment by guillaumekln** [comment]
Well, for realtime environments that frequently unload the translator from the main memory.

I will look to add an API to move the translator.

**Comment by vince62s** [comment]
The thing is that when we handle many many models on the same server, we have to unload/load very quickly.
But just to better understand: what does take time ? loading weights from the file or building the graph on the fly ? if so would it be possible to store the graph on disk ?

**Comment by guillaumekln** [comment]
Here is the time distribution when loading a big Transformer (without quantization) from the SSD to the GPU:

* loading variables from disk to the host memory: ~400ms (33%)
* loading 2 vocabularies: ~370ms (30%)
* Initializing TensorRT to check int8 support: ~230ms (19%)  (TODO: this value should be cached or lazily computed)
* moving variables to the GPU: ~180ms (~15%)

These 4 items cover 97% of the loading time. This does not include the Python overhead but I would expect it to be small. Note that there is no static graph to build in this project and creating the Translator instance takes less than a millisecond.

Given these numbers, a `to_gpu` method would take about 200ms.

**Comment by francoishernandez** [comment]
I noticed while testing further that what actually takes time is not only the loading of the model but the first translation. 
The construction of the `ctranslate2.Translator` seem to take 0.65 secs in this case (or are there some lazy components that may be built when performing the first translation?).

Is there some kind of graph initialization (even if the graph is not static as you mention)?

### First batch of requests
```
### 0
### 2.6428682804107666
### 1
### 0.2538185119628906
### 2
### 0.3555924892425537
### 3
### 0.35366272926330566
### 4
### 0.23731303215026855
### 5
### 0.31960248947143555
### 6
### 0.2709641456604004
### 7
### 0.30944347381591797
### 8
### 0.28797173500061035
### 9
### 0.17246484756469727
Total time: 5.203701734542847
```
### Second batch of (same) requests
```
### 0
### 0.34070539474487305
### 1
### 0.2528812885284424
### 2
### 0.35718202590942383
### 3
### 0.3629639148712158
### 4
### 0.21999645233154297
### 5
### 0.3210468292236328
### 6
### 0.2754957675933838
### 7
### 0.3108224868774414
### 8
### 0.2891225814819336
### 9
### 0.17138910293579102
2.9016058444976807
```

--> execution time is exactly the same between the two batches for all request, except the first one.

**Comment by guillaumekln** [comment]
Correct, some resources are initialized. For example:

* A Translator instance is spawning a new thread so we create new handles for cuDNN and cuBLAS (as recommended by the documentation).
* We recreate a TensorRT TopK layer.

and these 2 points already takes almost 1 second (cuDNN is the slowest).

**Comment by francoishernandez** [comment]
Ok, thanks for the explanation.
Would this overhead be reduced in the case of the `to_gpu` method or would it need to be initialized at each move?

**Comment by guillaumekln** [comment]
A `to_gpu` method would not change the active thread so these resources would not need to be reinitialized.

**Comment by guillaumekln** [comment]
@francoishernandez I have 2 questions:

* Do you confirm that after a `to_cpu`, the model is not used until `to_gpu` is called (i.e. we don't expect to run translations on CPU)?
* Does `to_gpu` always move the model to the GPU ID that was initially assigned to this model?

If the answer is yes for both questions, we could start with the following semantic:

* `unload_model(to_cpu=False)`: unload the model from the current device, and possibly move it to the CPU
* `load_model()`: load the model on the device configured initially

**Comment by francoishernandez** [comment]
> Do you confirm that after a to_cpu, the model is not used until to_gpu is called (i.e. we don't expect to run translations on CPU)?

Yes.

> Does to_gpu always move the model to the GPU ID that was initially assigned to this model?

For now yes. (We've been thinking of allowing the move to any available GPU but sticking to one GPU is fine for now.)

Indeed, this semantic looks perfect for the case.
