### ISSUE TITLE
strange results from conversion of fine tuned gpt-j model

### ISSUE THREAD

**Issue by silvacarl2** [OpenNMT/CTranslate2#1312]
we are converting a fine tuned gpt-j model that uses special tokens to ctranslate2 format.

the conversion works fine with no no issues.

but the inferencing is way off.

do we need to also load the tokenizer from the fine tuning instead of doing this:

tokenizer = transformers.AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")

do we need to do this:

tokenizer = transformers.AutoTokenizer.from_pretrained("../models/gpt-cmd-int8/")

?

**Comment by silvacarl2** [comment]
ok, quick update to this, turns out temperature setting makes a HUGE difference with ctranslate2.  we seem to get mostly predictable results if we set the temperature to 0.1 or 0.2.

any ideas?

**Comment by silvacarl2** [comment]
ok, so interesting results.  I can post the code if interested, but see below:

all below are using these parameters to get as close to the same results as possible, meaning temperature = 0.1 or its not possible to get consisten results to compare (all below have exact same parameters in the following curl example).  Anything greater than 0.1 produces some completions that are not consistent per above.

prompt="<START TRANSCRIPT>0202 1943. referral. Rita Thompson. I am trying to get my cirrhosis side refill.<END TRANSCRIPT>\n<START BIRTHDATE>"

curl -X "POST" -H "accept: application/json"  -H "Content-Type: application/json" -d "{ \"prompt\": [ \"$prompt\" ], \"bad_words\": [], \"temperature\": 0.1, \"top_k\": 50, \"top_p\": 1, \"min_length\": 0, \"max_length\": 20, \"penalty_alpha\": 0, \"repetition_penalty\": 1, \"early_stop\": false, \"end_sequence\": \"\", \"do_sample\": false, \"num_beams\": 1, \"return_prompt\": \"\", \"seed\": -1 }" -o gen-measure.json -s "http://0.0.0.0:9002/generate/"

fine tuned gpt-j based model untouched output run 10 times sequentially using no optimization, int8 inference, and int4 inference:
2/2/1943

this is what we expect.

same fine tuned gpt-j based model output converted to ctranslate format run 10 times sequentially:
int8, float16, int16, int8_float16: 
02-02-1943. I'm trying to get my cirrhosis side refill. I'm

it wouldnt be that big of a deal but when you vary the prompts the results returned can be different:

prompt="<START TRANSCRIPT>my birth date is august 8, 1942.<END TRANSCRIPT><START BIRTHDATE>"
august 8, 1942.

the fine tuned model always returns DOB in this format: M/D/YYYY

we can parse it of course using the "." as the delimiter then converting into M/D/YYYY, but we just want to know are we missing anything?

we can post all of the code if it would help.

here is another example:

<START TRANSCRIPT>I am calling about a patient with date of birth july fifth 1975.<END TRANSCRIPT><START BIRTHDATE> = 7-5-1975
<START TRANSCRIPT>I am calling about a patient with date of birth july fifth 1975.<END TRANSCRIPT><START BIRTHDATE> = July 5th 1975. I am calling about a patient with date of birth july fifth 1975. I

exact same parameters per above.

**Comment by guillaumekln** [comment]
You are using `do_sample=False` with HF so it is running basic greedy search.

With CTranslate2 you should remove all `sampling_*` parameters to match this behavior.

**Comment by silvacarl2** [comment]
NFW!  trying it now!!!!!!!!!!!

**Comment by silvacarl2** [comment]
ok, i took those out, and i also set this: include_prompt_in_result=False

here is what comes out now which is nearly 100% perfect:

prompt = <START TRANSCRIPT>Date of birth  10-18-1967. Being referred to Dr. Mayer from Dr. Aralu.<END TRANSCRIPT>\n<START BIRTHDATE>

10-18-1967. Being referred to Dr. Mayer from Dr. Aralu. Thank you.<|extratoken_2|><|extratoken_3|>10/18/1967<|extratoken_4|>10/18/1967<|extratoken_4|>10/18/1967<|extratoken_4|>10/18/1967<|extratoken_2|>10/18/1967<|extratoken_2|>10/18/1967<|extratoken_2|>10/18/1967<|extratoken_2|>

**Comment by silvacarl2** [comment]
nope.  i cannot determine how to get it to return the same resutls every time.  Here is the code, just plug in the gpt-j model instead of our fine tuned model, or i can post our fine tuned ct2 model here:

import ctranslate2
import transformers
import time
import subprocess
import psutil

def generate_test():
	prompt="<START TRANSCRIPT>I was born on sept 18th, 1963.<END TRANSCRIPT><START BIRTHDATE>"
	print("prompt [" + str(prompt) + "]")

	tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(prompt))
	# print(tokens)
	results = generator.generate_batch([tokens], 
#		sampling_temperature=0.1, 
#		sampling_topk=10, 
#		sampling_topp=1, 
#	        min_length=0, 
	        max_length=30, 
		repetition_penalty=1, 
		include_prompt_in_result=False, 
		beam_size=1)
#	print("results [" + str(results) + "]")
	text = tokenizer.decode(results[0].sequences_ids[0])
	print("text [" + str(text) + "]")

def benchmark_function(func, num_iterations=1):
    total_time = 0
    for i in range(num_iterations):
        start_time = time.time()  # get the current time before calling the function
        func()  # call the function
        end_time = time.time()  # get the current time after calling the function

        execution_time = end_time - start_time  # calculate the execution time
        total_time += execution_time

        print(f"Iteration {i+1}, Timestamp: {end_time}, Execution Time: {execution_time}")

    average_time = total_time / num_iterations
    print(f"Average Execution Time: {average_time}")

# load on GPU
generator = ctranslate2.Generator("/home/silvacarl/Desktop/models/gpt-cmd-float16/",device="cuda")

# load on CPU
# generator = ctranslate2.Generator("../models/gpt-cmd-float16/")

tokenizer = transformers.AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")
# tokenizer = transformers.AutoTokenizer.from_pretrained("../models/gpt-cmd-float16/")
print("tokenizer [" + str(tokenizer) + "]")

def get_gpu_memory():
    result = subprocess.check_output(
        [
            'nvidia-smi', '--query-gpu=memory.used',
            '--format=csv,nounits,noheader'
        ], encoding='utf-8')
    # Convert to GB
    gpu_memory = int(result) / 1024
    return gpu_memory

# Print GPU memory usage in GB
print('GPU Memory usage:', get_gpu_memory(), 'GB')

def get_cpu_memory():
    mem = psutil.virtual_memory()
    # Convert to GB
    cpu_memory = mem.used / (1024 ** 3)
    return cpu_memory

# Print CPU memory usage in GB
print('CPU Memory usage:', get_cpu_memory(), 'GB')

benchmark_function(generate_test)

**Comment by silvacarl2** [comment]
does not seem to make a difference.  i may just create code to compensate for what it returns.

**Comment by silvacarl2** [comment]
i jsut came across this example:

ct2-transformers-converter --model mosaicml/mpt-30b-chat --output_dir ~/tmp-ct2fast-mpt-30b-chat --force --copy_files tokenizer.json README.md tokenizer_config.json generation_config.json special_tokens_map.json .gitattributes --quantization int8_float16 --trust_remote_code

is there more extensive docuemtnation on this?

because we have fine tuned our model with special tokens, whihch could be why it is not working correctly when we convert it?

**Comment by guillaumekln** [comment]
Did you find a solution?
