### ISSUE TITLE
ct2-transformers-converter fails on falcon-rw-1b

### ISSUE THREAD

**Issue by julianmukaj** [OpenNMT/CTranslate2#1320]
Works fine on other Falcon model sizes however, we get ValueError: Vocabulary has size 50257 but the model expected a vocabulary of 
size 50304 on the 1b model. Similarly the MPT 1b model is also not supported, would be good to have for super fast inference models.

**Comment by guillaumekln** [comment]
The error for the Falcon model should be fixed with #1298.

Do you get the same error for the MPT model?

**Comment by guillaumekln** [comment]
This should be fixed in version 3.16.1. Feel free to reopen if you still get the error.

**Comment by princekore0911** [comment]
Getting error in converting falcon-rw-1b in ctranslate2. It was saying config is missing. I wrote that config, now it is converting falcon-rw-1b into ctranslate2. But the accuracy is not Good.
