### ISSUE TITLE
asynchronous translate_batch() causes python to break out of loop/with statements?

### ISSUE THREAD

**Issue by sigmareaver** [OpenNMT/CTranslate2#1325]
The example given for asynchronous generation/translation is causing my script to break out of it's `for` loop and `with` statements, causing the program to exit. No error is provided by the program. This is on the GPU.

I'd like to request a more thorough example of using the asynchronous and parallelism features of CTranslate2 correctly. Debugging multi-threaded applications is a huge time sync and a bit beyond me.

**Comment by guillaumekln** [comment]
Do you mean the process is crashing? Can you post a code snippet showing the issue?

Also please provide more details about your setup: OS, Python version, CTranslate2 version, etc.

**Comment by sigmareaver** [comment]
I resolved the issue by putting the example code into an async function definition and calling it with asyncio.run().

Example:
```python
if __name__ == '__main__':
    input_tokens = []
    async def translate():
        async_resullts = []
        async_results.extend(translator.translate_batch(input_tokens,
                                                             max_batch_size=32,
                                                             batch_type='examples', asynchronous=True,
                                                             max_input_length=512))
        for a in range(len(async_results)):
            result = async_results[a].result()
            # use result 
    asyncio.run(translate())
```
