### ISSUE TITLE
error inference seq2seq transformer model with multiquery: true

### ISSUE THREAD

**Issue by totaltube** [OpenNMT/CTranslate2#1328]
Just tested multiquery for nmt task and get get this error on inference with ctranslate2: 
```
File "/workspace/translate_mono.py", line 110, in translate_mono
    translations_res = translators[lang].translate_batch(
ValueError: MatMul: k dimension of inputs a and b should match
```
when add these options to opennmt.py train config:
```
pos_ffn_activation_fn: gelu
multiquery: true
```
I use int8 quantization.

**Comment by tuxchow** [comment]
Similar Error!
Only add ``multiquery: true`` to the train config of the EncDec model.
After convert to ct2_model with ``ct2-opennmt-py-converter --model_path model_step_50.pt --output_dir ct2_model``, I run inference and get this error:
```ValueError: new shape size (624) is incompatible with current size (640)```

Version:
Ctranslate2: 3.16.1
OpenNMT-py: 3.3.0

**Comment by guillaumekln** [comment]
At this time the multi-query attention is only implemented in the self-attention layers and not the cross-attention layers.

The only reason is that I don't have access to a pretrained encoder-decoder model using this configuration. Can you share a pretrained model or do you know where I can find one?

**Comment by totaltube** [comment]
> At this time the multi-query attention is only implemented in the self-attention layers and not the cross-attention layers.
> 
> The only reason is that I don't have access to a pretrained encoder-decoder model using this configuration. If I can avoid training one myself that would be better. Can you share a pretrained model or do you know where I can find one?

Sure, here is the trained nmt model English-Gujarati - https://drive.google.com/file/d/1DDo81TbyNvXMzxYvlPJ8MAy6HbDQZuWL/view?usp=drive_link
model config:
```
encoder_type: transformer
decoder_type: transformer

pos_ffn_activation_fn: gelu
multiquery: true
enc_layers: 8
dec_layers: 8
heads: 16
add_ffnbias: true
hidden_size: 768
word_vec_size: 768
transformer_ff: 4096
dropout: [0.1]
attention_dropout: [0.1]
share_decoder_embeddings: true
share_embeddings: true
position_encoding: true
position_encoding_type: 'SinusoidalConcat'
```

**Comment by guillaumekln** [comment]
Thanks for sharing the model and configuration, but the links are not public. Can you change the permission?

**Comment by totaltube** [comment]
> Thanks for sharing the model and configuration, but the links are not public. Can you change the permission?

Oh, sorry, now it's public.
