### ISSUE TITLE
While using the latest meta model (LLAMA-2-7b-chat-hf) converted with ctranslate2 ,getting ValueError: DequantizeGemmOutput: output should have a float type

### ISSUE THREAD

**Issue by Apoorv7092** [OpenNMT/CTranslate2#1351]
Model converted: LLama-2-7b-chat-hf
conversion CLI: `ct2-transformers-converter --model daryl149/llama-2-7b-chat-hf --quantization bfloat16 --output_dir llama-2-7B-chat-ct2
`
inference code:
```
tokenizer = sp.SentencePieceProcessor('llama_ct2/tokenizer.model') #enter your tokenizer path
generator = ctranslate2.Generator("llama-2-7B-chat-ct2", device = 'cuda',compute_type="int8_bfloat16")
base_prompt = "Have a friendly and interactive conversation with the User"
query = "Hello"
final_prompt = base_prompt + f"\nUSER:{query}\nASSISTANT:"
tokens = tokenizer.encode(final_prompt, out_type = str)
results = generator.generate_tokens(tokens, 
                                    sampling_temperature = 0.7,
                                    repetition_penalty = 2,
                                    sampling_topk=1)
resp = ''
token=0
t1 = time.time()
for ans in results:
    if ans.token.startswith("▁"):
        resp += ' '
    
    chars = tokenizer.decode([ans.token_id])
    resp += chars
    token+=1
    # print(resp)
    if ans.token == '</s>':
        resp = re.sub(r"USER.*(?:\n.*)*", "", resp)
        resp = re.sub(r"[\*<>:{}&^%$#@!\-]+","",resp)
        resp = re.sub(r'\[[A-Za-z]+\]','',resp)
        print(resp)
        t2=time.time()
        print(f"\nTotal tokens: {token}, Time: {t2-t1}, Speed: {token/(t2-t1)} tokens/sec")
```

Error: ValueError: DequantizeGemmOutput: output should have a float type

Please help @guillaumekln

**Comment by guillaumekln** [comment]
Thanks for reporting. This is an issue with the computation type "int8_bfloat16" we just added in the latest version. I will fix this ASAP.

Note that I'm not sure Llama-2 is immediately working with the current version of CTranslate2. It may require some changes in the conversion or library code. I will look into that as soon as I have access to the Llama-2 models.

**Comment by Apoorv7092** [comment]
Yes it does support LLama-2 model. Its working properly with fp16 and mixed(int8_float16)

**Comment by guillaumekln** [comment]
Oh ok, thanks for testing!

I read that Llama-2 is using GQA instead of MHA but I just found out only the 70B versions are using GQA. So 7B and 13B should indeed work.

**Comment by michaelfeil** [comment]
I can confirm that Llama-2-7b-chat-hf works.

Tested with model https://huggingface.co/michaelfeil/ct2fast-Llama-2-7b-chat-hf
`ctranslate2.__version__=='3.16.1'` and `int8_float16`

**Comment by hobodrifterdavid** [comment]
I'm testing the 13B model now :)

@ [michaelfeil](https://github.com/michaelfeil) It seems you are using the tokenizer.model file from the original llama model? Is that right? You might want to copy it into the hf repo with the other files, it's needed to run the models, but not certain. I think Guillaume's earlier convert script did this, but recently it doesn't.
