### ISSUE TITLE
Llama 2 fails with context length >> 2000

### ISSUE THREAD

**Issue by Joemgu7** [OpenNMT/CTranslate2#1363]
I have used both the 7b and 13b chat-hf models in different computation types (int8, int8_float16, int8_bfloat16) and both self converted from the Llama repo or directly from the hub (starting with `ct2fast-`), however I always run into the same issue.

When using the correct prompt format (I triple-checked) ex. for summarization and the whole input prompt is longer than 2048 tokens the generation fails and produces weird hallucinations, returning a long chain of special characters like #, ", etc. With input prompts shorter than 2000 tokens, but output can be 1024, the model correctly performs tasks. However if I input > 3000 tokens, no matter the set generation size, the output will always return gibberish.

It seems like as long both input sequence length and generated tokens combined are within 2048 tokens, everything works fine, but as soon as we start exceeding these 2048 tokens, the model starts to break down. I suspect (or at least it feels like) the model has only an effective context length of 2048. I can also notice the model starting to forget the initial instruction while generating tokens and exceeding this invisible 2048 token wall.

The models are converted with 3.17.1 and transformers 4.31, except the ones found on the hub converted with 4.32.0.dev0, and I still observe this behaviour. 

Can anyone reproduce this? Is there a way to avoid this issue and use the full 4096 context length of Llama 2? 

Edit: If it wasn't clear, inference is run with 3.17.1 and transformers 4.31.0

**Comment by guillaumekln** [comment]
Can you share the input tokens for this issue? Just to make it easier for me to look at this.

**Comment by Joemgu7** [comment]
input:
`[INST] <<SYS>>
You are a helpful Assistant designed to summarize transcripts. Here are a few guidelines you should follow when answering:
1. Answer in english, no matter the input language.
2. Your summary should be abstractive and balance conciseness and detail.
3. Answer in valid Markdown format. Here are a few tags you may use:
  - Generate titles by prefixing the text with `#`
  - Lists by prefixing each item with `-` or `*`
  - Bold and italic text by surrounding the text with `**` and `*`, respectively
  - Headings to chapterize the output by prefixing the text with `##` or `###`
  - Blockquotes by prefixing the text with `>`
4. Segment the summary into different chapters if a new subtopic is being discussed. Each chapter should have an appropriate heading.
5. After each detailed chapter in the summary, provide a highly concise summary of the chapter surrounded by blockquotes.
6. Mark the start of your summary with the following tag: '[SUM]' and end it with the following tag: '[/SUM]'.
<</SYS>>

Write a detailed summary of the following transcript:
Unknown: All right, welcome back, everybody. I hope the break was useful for you to digest what we've seen in the first part of the lecture. So I hope the sound is OK. You can hear me well in the lecture hall? Yes? OK. I put it to the max here because I know that in previous sentences it wasn't loud enough, but normally that should be OK. All right, so let's continue then. So we've seen that Hadoop is on a centralized architecture with the name nodes and the data nodes, and what we are going to do next is to go into the details of that. So the implementation of the Hadoop is all done in Java. That would be the native language of the HDFS, the same format we use and so on. But of course, there's APIs that allow you to access it from many other languages. Okay. Now, as promised, let's dive more into the details, and we are going to start with the NameNode. And this includes, actually, an answer to the question that one of you asked earlier about what there is on a name node. So let's look into what there is. What do you think there is on a name node? Yes? Maybe the catch box, where is it? Yeah, because this is the correct answer. Does it work? Yes. So probably mappings from blocks to each data node so that we know which data nodes contain what blocks? This is correct. There is indeed a mapping from the block IDs, so they're identified with IDs, from the block IDs to the data nodes where they are located. This is on the name nodes. Anything else? Yes? Does it perform some kind of load balancing so it would have information about which node has how many requests? Yes, indeed. So this actually is a consequence of what you said, right? Because you know exactly where the blocks are located. And indeed, the responsibility of the name node is to load balance a little bit, right? So this is, indeed, what it has to do. Now we are trying to find out what is stored. So basically, what information is in the memory of the data node? Can you make a guess, maybe, of something that you think, in addition to the mapping from the block IDs to the data node? Well, I thought in order to load balance, it would have to store information like where it sent previous requests. But if it just does it randomly, then it will be load balanced. So I guess not. Maybe let me try to give a clue. Imagine that the only thing that you store on the name node would be this mapping from each block ID to the data nodes. Do you have enough? to give me the content of an entire file. If I ask you for slash home slash Hadoop slash file.txt, can you give that to me with only that mapping? Or can you imagine what could be missing? Well, if each block stores a pointer to the next block of that file, then yes. Yes, exactly. This is getting close to it. So indeed you need this, you know, what we saw earlier, where it was, yes, here. You need to be able to replay the blocks that belong to the same file. Otherwise, it's just a random list of blocks that are stored in the cluster. You need to know that if you have a file, this is its first block, this is the second block, and so on. So you suggested that's actually an idea. It could be a linked list, right? That every block points to the next one. In fact, it's not done that way. It's done as a metadata on the name node that the name node keeps the sequence of the block IDs that belong to the same file. So this is also something that there is on the name node. Any other idea? Anybody else? Yes? file hierarchy? Yes, absolutely. The hierarchy of directories and files, you also need that in order to locate the files. So if we go back to where we are, here we are. So we have the file namespace, this is what you just said, the file to block mapping, so every file is associated with a list of blocks, and the block locations, which maps the block IDs to the data nodes on which we are, right? So these are the three things that the name node, sorry, these are the three things that the name node actually has in its memory, and if you think about it, everything you have here is enough to bring the service, to basically give the data to people who are accessing HDFS. OK, now let's go to the data node. So actually, it's almost boring where there is the data node, because this is just plenty of blocks, right? So these blocks are actually local files every data node. These are local files. You can actually, you can try later if you actually want to experiment around, if you create an AGFS cluster, you can actually try to log into one of the data nodes and look on the file system and try to find the block files. These are files. A question during the break that was asked that is very actually important is if the last block, so all the blocks are going to be one hundred and twenty eight megabytes, but the last block might be less, right? In fact, most of the time it will be less. There is no waste of space, right? So the last block will really take up just the space that it needs. If it's two megabytes and it's just a two megabyte file on the local file system of the data node. What's really important to understand, and here it's something that as a computer scientist I'm sure you will have no difficulty doing, is that from the perspective of HDFS, which is a file system, there's all these very large files and data sets accessible via the name node and cut into blocks that are on the data nodes. But if you zoom in on a data node and look inside, you will see that the blocks are in fact on the local file system. So do not confuse the local file system of every data node with the HDFS file system, right? It's very important to understand that these are two levels, two physical levels of things, all right? So these are files. What we also check, sorry, store with each block is a checksum. We also store along some checksum in order to check if the file goes corrupt and we check once in a while so the client always recomputes the checksum and will inform the name node if there is any issue. Okay. The data nodes can detect their own failure. So they will notice if, for example, they might have multiple drives. So if one drive crashes, then this can be reported. We'll see how. But this can be reported to the name node as a disk failure, of which we will recover. The block IDs, I haven't said anything about that. It's just sixty four bit sequences. It's just, you can consider it integers on sixty four bits, basically. These are the block IDs. OK. Something that here, I'm very cautious when I'm saying that because that might sound counterintuitive when I said we don't have random access. Nevertheless, we can still access within a block a sub part of a block, not the entire block, but we can just request to read a certain interval of the block. But do not make the mistake of thinking that gives you random access. Because again, of course, you have random access. You can access anywhere. But the question is, how fast can you get that? This is still slow. The main reason for that, we will see that it's because of MapReduce. But we'll see in a few weeks why this is actually useful to be able to read just part of a block and not the entire block. OK. So this is what there is, I'll come to you, this is what there is on the name nodes, this is what there is on the data nodes, and the next step is to communicate between the nodes on the cluster in order to figure out how the thing is orchestrated. Yes? Maybe the catch box, it's over there. I was going to ask, let's say you want to upload like a folder with a bunch of files in it, but they don't, let's say, total up to less, more than one hundred and eight megabytes. Do we still get like a different blocks for each of the files inside the folder? Collect them in one block. Yep. So in order to answer this question, it's interesting to, um, to think about what's actually going to happen when you do that. So let's say you're sitting on your laptop, and this is actually, as a data scientist, you will have to do these things, right? You want to upload the contents of a folder to the cluster. So first, What's going to happen is that you have some software on your laptop, some sort of clients of HDFS. Typically you can have a Java API actually that does that. It's actually, it fits into the Java way of doing IO stuff, right? With these input streams and output streams and so on. So basically you have this local library in Java, that's going to take care of uploading and downloading, in fact, as if it were local. From an API perspective, it doesn't really make a difference that it's local. You will see it's slower, of course. But it works in the same way. Now, if you try to do that, let's say, in a naive way, you try to use this API and say, OK, I'm going to upload these files and folders. probably this will just be an iteration on the file and that file by file you upload them directory by directory you run an mkd we will actually see it's an mkd also in hgfs so you create the directories but the consequence of that is that it's going to create every day for every file you will create a new block so if all the files are less than the hundred and twenty eight megabytes then you will have just one block per file What HDFS, though, will not do is group it together in a single block. That it will not do. However, as a user, you can still build some form of archive file. It's something that if some of you played around and you need to upload to a server, if you put it in a single file, it's a single upload. You can even compress it if you want. But basically, if you just do not put it in the same archive and output the entire hierarchy, one block for every file. Any other questions? Yes? This is more of a curiosity question, but thinking about the fact that here we are making use of more machines to sort of handle the fact that storage is unfortunately going to fail sometime. I know that this also came with the cost, but I was wondering what would have been the cost if we rather focused on perfecting the storage such that it doesn't fail? Or is that not even feasible? So indeed you could perfect the storage. In fact, there are technologies for that. For example, RAID, right? Redundant Array of Inexpensive Disks, right? Who knows RAID? I never used it, but I know it exists. So RAID is a technology like that, that you can just put several drives locally on your computer. And then you have many ways of making it work. Either you can have mirrors, so every drive is the same as the others, and you just replicate. You have other ways of just distributing the bits to read in parallel over the machines. So you have things like that. This sort of technology is designed to just be local on a single machine, right? So it's just running on your computer. You will not scale to a cluster. When you design a system like HDFS, in fact, you do not need RAID. So you do not need anymore to worry about making each drive not crash, basically. You just let the drives crash. I would say in the design, the mindset is it's just simpler to let the drives crash than to try to come up with something even more complex by buying even more drives. That would be just more expensive and more waste to do it that way. So that's the mindset. Does it make sense? Any other questions? Yeah, there's one from Zoom. Is NameNode the only responsible for checksum validation for blocks? There are no validation on data nodes and also fidelity of data during read-write can be affected at data nodes. Can we put, let me explain the communication, because then we can address this question, because then you will understand. [/INST]`

Add a `<s>` token before this input, all in all reaching a length of 3060.

The output looks sth like this:
`# 1000000000000000...`

**Comment by michaelfeil** [comment]
FYI, conversion args should be the following:

```python
model_id = "meta-llama/LLama2-7b-hf-chat"
from ctranslate2.converters import TransformersConverter
converter = TransformersConverter(
    model_id,
    activation_scales=None,
    copy_files=filtered_f,
    load_as_float16=True,
    revision=None,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
)
converter.convert(
    output_dir=str(tmp_dir),
    vmap = None, 
    quantization="int8_float16",
    force = True,
)
```

and then 
```python
import ctranslate2
import transformers

generator = ctranslate2.Generator(model_id, device="cuda")
tokenizer = transformers.AutoTokenizer.from_pretrained(model_id)

prompt = (
    "Girafatron is obsessed with giraffes, the most glorious animal on the face of this Earth. "
    "Giraftron believes all other animals are irrelevant when compared to the glorious majesty "
    "of the giraffe.\nDaniel: Hello, Girafatron!\nGirafatron:"
)

tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(prompt))

results = generator.generate_batch([tokens], sampling_topk=10, max_length=200, include_prompt_in_result=False)
output = tokenizer.decode(results[0].sequences_ids[0])

print(output)
```

**Comment by michaelfeil** [comment]
Which graphics card are you using for inference? @Joemgu7

**Comment by Joemgu7** [comment]
I tried to execute the same code, but still it returns only `& & & & & & & & & &...`

I'm using cuda 12.1.1-cudnn8-runtime together with a L4. Which cuda version are you running @michaelfeil ? I know that ctranslate2 has been compiled against cuda 11, but I didn't have any issues up to this point...

**Comment by michaelfeil** [comment]
I think Ctranslate2 mentions or even requires explicitly cuda 11 support. Please try if the issue persists with cuda 11.

**Comment by Joemgu7** [comment]
Yup, that was the issue, everything works great using 11.7, thanks for the help and sorry for wasting your time!
