### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by breaddance** [OpenNMT/CTranslate2#1365]
I apologize for bothering you, but I recently learned about this brilliant library you've written. I'd like to ask if ctranslate2 currently supports TensorRT. I noticed you had some related code before. Are you currently considering integrating TensorRT into ctranslate2 or implementing similar functionality within ctranslate2?

**Comment by guillaumekln** [comment]
What would be the benefits of integrating TensorRT? What do you mean by "similar functionality"? Can you be more specific?

**Comment by breaddance** [comment]
@guillaumekln Thank you very much for the author's response. In my personal opinion, TensorRT's quantization seems to be more effective. They might be using dynamic quantization, while our ctranslate2 quantization only quantizes weights. TensorRT may have similar approaches to ctranslate2, but I haven't delved into it deeply yet.

**Comment by guillaumekln** [comment]
CTranslate2 also uses dynamic quantization.

**Comment by breaddance** [comment]
@guillaumekln I apologize, author, I have recently started using ctranslate2, so I hope you can understand. I previously used ctranslate2 to quantize the whisper model and convert it to INT8. However, I found that its speed became even slower on the GPU. Can you provide some suggestions for this issue? Thank you, author.

**Comment by guillaumekln** [comment]
INT8 is not always faster on the GPU. It depends on several factors such as the model size, the GPU type, etc.

If you are comparing the performance against "float16", make sure to use "int8_float16" and not "int8".

**Comment by breaddance** [comment]
@guillaumekln In my personal opinion, the space for post-training quantization of the whisper model is not significant at the moment. If I want to further improve the inference performance, could the author provide suggestions in other aspects? Thank you, author.

**Comment by guillaumekln** [comment]
You can ask general questions about Whisper here: https://github.com/guillaumekln/faster-whisper/discussions

I'm closing this issue since it does not pinpoint specific issues or improvements for CTranslate2.
