### ISSUE TITLE
distilbert-base-uncased-mnli

### ISSUE THREAD

**Issue by AparnaAgrawal02** [OpenNMT/CTranslate2#1373]
can it support distilbert?

**Comment by guillaumekln** [comment]
I don't know the exact architecture of Distilbert but I expect it to be compatible with CTranslate2. We "just" need to add a converter for it, similar to the existing [BERT converter](https://github.com/OpenNMT/CTranslate2/blob/v3.17.1/python/ctranslate2/converters/transformers.py#L1394-L1470).

Contributions are welcome.
