### ISSUE TITLE
Marian converter and SPM Vocabulary

### ISSUE THREAD

**Issue by m-resta** [OpenNMT/CTranslate2#1375]
Is it possible to convert marian models that have a sentencepiece vocabulary?
`ct2-marian-converter` fails if i pass the path of a `.spm` file.

Is there a standard way to convert spm vocabulary file to a `.yaml `file?

Thanks in advance!

**Comment by guillaumekln** [comment]
You can try this small script to create a YAML vocabulary from a SentencePiece model:

```python
import yaml
import sentencepiece as sp

processor = sp.SentencePieceProcessor("source.spm")
vocab = {processor.id_to_piece(i): i for i in range(processor.vocab_size())}

print(yaml.safe_dump(vocab, sort_keys=False, allow_unicode=True))
```

**Comment by guillaumekln** [comment]
> To use the converted model I need to encode the text with my .spm vocab, and pass the output pieces to the translate_batch function am I right?

Yes.

> I did some tests and it seems that the inference with ctranslate2 in fp32 results in a loss of 0.7 BLEU for a model trained with marian in fp16.

Please post the Marian command line you are using and how you call translate_batch in CTranslate2.

Often these differences in BLEU can be explained by using different decoding parameters.

**Comment by m-resta** [comment]
> Please post the Marian command line you are using and how you call translate_batch in CTranslate2.
> 
> Often these differences in BLEU can be explained by using different decoding parameters.

It was my fault: after double-checking all the decoding parameters I noticed that I was removing the first decoded token after the translation step.

The scores are now perfectly aligned:

Marian fp16: 30.8
ctranslate-fp32: 30.8
ctranslate-int16: 30.8
ctranslate-int8: 30.6

Thanks for the help!
