### ISSUE TITLE
CT2 a custom fine-tuned LLAMA2 model?

### ISSUE THREAD

**Issue by salahzoubi** [OpenNMT/CTranslate2#1377]
I have a fine-tuned LLama2ForCausalLM (13B) model which I fine-tuned using QLORA and then merged into a single model (kind of similar to the result model from this [guide](https://www.philschmid.de/instruction-tune-llama-2) ). I'm trying to convert this model to CT2 for faster inference but I keep getting the following error: 

[2023-07-30 10:17:11,445] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.93it/s]
Traceback (most recent call last):
  File "/home/.conda/envs/final_try/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/.conda/envs/final_try/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 1610, in main
    converter.convert_from_args(args)
  File "/home/.conda/envs/final_try/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 57, in convert_from_args
    return self.convert(
  File "/home/.conda/envs/final_try/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 104, in convert
    model_spec.validate()
  File "/home/.conda/envs/final_try/lib/python3.8/site-packages/ctranslate2/specs/model_spec.py", line 571, in validate
    raise ValueError(
ValueError: Vocabulary has size 32001 but the model expected a vocabulary of size 32032

Not sure why this is happening when I have a custom tokenizer attached? Any idea how to fix?

One more thing, I'm using a particular sampling version in HF (classifier free guidance) is there any way to incorporate this into the sampling techniques of generator.generate? How would I go about doing this?

**Comment by guillaumekln** [comment]
The model was trained with a vocabulary of 32032 tokens, but the tokenizer's `get_vocab` method only returns 32001 tokens. Since you are using a custom tokenizer, you could update the method `get_vocab` to return all 32032 tokens.

> One more thing, I'm using a particular sampling version in HF (classifier free guidance) is there any way to incorporate this into the sampling techniques of generator.generate? How would I go about doing this?

This is not implemented so you would need to update the internal decoding code in C++.

**Comment by salahzoubi** [comment]
Thanks for your response, how would I know what tokens are missing to add? These should be added to the tokenizer.json['model']['vocab'] list right? 

Also would there be any harm if I just use the base tokenizer (the un-finetuned) llama tokenizer?

**Comment by guillaumekln** [comment]
The base Llama2 models have a vocabulary of 3200 tokens. I don't know what these additional tokens are. You should ask the authors of this fine-tuned model.

However, we can fix this error by adding generic extra tokens in the vocabulary, like we do for other models.

**Comment by salahzoubi** [comment]
Awesome, works now! Thanks for your help :)

**Comment by salahzoubi** [comment]
I'm running into the reverse issue, but can't seem to find a work-around for it. What if the tokenizer has more words in its vocab than the model, what would be a safe word-around here? I tried removing a token from the tokenizer and converting, but it completely destroys the generated output. 

`ValueError: Vocabulary has size 32001 but the model expected a vocabulary of size 32000`

**Comment by guillaumekln** [comment]
What model are you trying to convert? Looks like the same issue as https://github.com/OpenNMT/CTranslate2/issues/1415.

**Comment by salahzoubi** [comment]
I'm using the 7b model version of that fine-tuned model version, but I still get the same error after both fixes proposed (removing and manually modifying the added_tokens.json)

**Comment by guillaumekln** [comment]
As mentioned in the other issue #1415, these models have been fixed upstream so you should no longer get the error.
