### ISSUE TITLE
Question on CTranslate2 logprob precision of Llama model and missing bos_id in sp.decode()

### ISSUE THREAD

**Issue by ziyuwan** [OpenNMT/CTranslate2#1379]

**Comment by ziyuwan** [comment]
I try to use the converted Llama-7b model to do some text generation tasks. But when I check the output log probs with huggingface transformer version. I found the error is a little big (float32 model's inferences scores have a maximal logprob error at 1e-2 ).

While during validating this problem, I also find that, `spm.SentencePieceProcessor.decode` will drop the `bos_id` during generation, which may cause some strange text during generation. How can I fix this?

The following is the maximum output errors of scores between ct2 llama-7b model and hf llama-7b model.

`HF INFERENCE WITHOUT BOS_ID: 0.012301445007324219
HF INFERENCE WITH BOS_ID: 1.8236887454986572`

**Comment by ziyuwan** [comment]
here is the code
```
import ctranslate2
from ctranslate2.converters import TransformersConverter
from typing import Optional, List
from transformers import AutoModelForCausalLM, AutoTokenizer
import transformers
import torch
import sentencepiece as spm
import os
import numpy as np

cache_dir = None
model = AutoModelForCausalLM.from_pretrained("huggyllama/llama-7b",
                                                cache_dir=cache_dir)# .to(torch.bfloat16)
converter = TransformersConverter(
    "huggyllama/llama-7b",
    copy_files=["tokenizer.model"]
)
converter.convert("/data/ziyu/just_for_test/test_converter_llama/", force=True, quantization="float32")

model_dir = "/data/ziyu/just_for_test/test_converter_llama/"
generator = ctranslate2.Generator(model_dir, device="cuda", device_index=0, compute_type="float32")
sp = spm.SentencePieceProcessor(os.path.join(model_dir, "tokenizer.model"))

hf_device = torch.device("cuda:1")
model = AutoModelForCausalLM.from_pretrained("huggyllama/llama-7b",
                                             cache_dir=cache_dir).to(
                                                 dtype=torch.float,
                                                 device=hf_device)
tokenizer = AutoTokenizer.from_pretrained("huggyllama/llama-7b",
                                          cache_dir=cache_dir)
                                          
@torch.no_grad()
def hf_inference_prob(prompt_ids: list[int], output_ids: list[int], t=1.):
    query_len = len(prompt_ids)
    input_ids = torch.LongTensor(prompt_ids + output_ids).unsqueeze(0).to(hf_device)
    output_logits = model(input_ids).logits
    output_ids = input_ids[:, query_len:]
    temperature = torch.tensor(t).to(output_logits).view(1, 1, 1)
    logp = output_logits[:, query_len -
                         1:-1, :].div(temperature).softmax(-1).log()
    select_logp = logp.gather(2, output_ids[:, :, None]).squeeze(2)

    return select_logp[0].cpu().numpy().tolist()



temperature = 1.0

prompt = "LLaMA model is"
prompt_tokens = sp.encode(prompt, out_type=str)

step_results = generator.generate_tokens(
    prompt_tokens,
    sampling_temperature=1.0,
    sampling_topk=20,
    max_length=16,
    return_log_prob=True,
)
tok_ids = []
ct2_logp = []
for step_result in step_results:
    tok_ids.append(step_result.token_id)
    ct2_logp.append(step_result.log_prob)

prompt_ids = sp.encode(prompt)
hf_logp = hf_inference_prob(prompt_ids, tok_ids, temperature)
print("HF INFERENCE WITHOUT BOS_ID:", 
      np.max(np.abs(np.array(hf_logp) - np.array(ct2_logp))))

prompt_ids = sp.encode(prompt)
hf_logp = hf_inference_prob([1] + prompt_ids, tok_ids, temperature)
print("HF INFERENCE WITH BOS_ID:",
      np.max(np.abs(np.array(hf_logp) - np.array(ct2_logp))))
```

**Comment by guillaumekln** [comment]
I'm not sure I understand the issue. Why are you adding the BOS token to the sequence to score?

The absolute difference for the case "HF INFERENCE WITHOUT BOS_ID" looks great.

**Comment by guillaumekln** [comment]
If the Llama tokenizer should add the BOS token, then you can just add it in the `prompt_tokens`, no?

```python
prompt_tokens = ["<s>"] + sp.encode(prompt, out_type=str)
```

I don't understand why you mention `sp.decode` which is not used in the code snippet above.

**Comment by waterhorse1** [comment]
thanks for the help, yes we also find this simple solution!

**Comment by ziyuwan** [comment]
> If the Llama tokenizer should add the BOS token, then you can just add it in the `prompt_tokens`, no?
> 
> ```python
> prompt_tokens = ["<s>"] + sp.encode(prompt, out_type=str)
> ```
> 
> I don't understand why you mention `sp.decode` which is not used in the code snippet above.

thank you very much, I just want to find a more general way to solve this, since in your documentation,

**Comment by ziyuwan** [comment]
> If the Llama tokenizer should add the BOS token, then you can just add it in the `prompt_tokens`, no?
> 
> ```python
> prompt_tokens = ["<s>"] + sp.encode(prompt, out_type=str)
> ```
> 
> I don't understand why you mention `sp.decode` which is not used in the code snippet above.

sorry for the typo and really thanks for your solution.
