### ISSUE TITLE
token_type_ids for BERT models

### ISSUE THREAD

**Issue by hachall** [OpenNMT/CTranslate2#1383]
Hi, we have run into some problems when working with Ctranslate for BERT models, as for a number of tasks such as question answering and sentence pair comparison, they have been trained with token_type_ids as part of their inputs. 

Request:
We would like to inquire if there is a plan to address this limitation in the near future. If there is no such plan currently, we would like to express our willingness to contribute to the project by writing a patch that introduces support for token_type_ids.

Benefits:
* Improved BERT model performance by handling token_type_ids.
* Increased compatibility with tasks that require sentence pairs or multiple input sequences.
* Expanded usage of the library for a broader range of natural language processing tasks.

Would you consider accepting a patch for this issue if we were to implement it? We would be more than happy to collaborate with the community and follow any necessary guidelines to ensure that the patch aligns with the project's standards.

**Comment by guillaumekln** [comment]
Hi,

We accept contributions to support the token_type_ids.

The code currently sets all token_type_ids to 0:

https://github.com/OpenNMT/CTranslate2/blob/33ae226a4308719957a7578650d8d62f35e03cb0/src/models/language_model.cc#L362-L366

You would probably need to add new argument in this method, and then expose this argument all the way up to the Python wrapper.
