### ISSUE TITLE
Question about characters not allowed

### ISSUE THREAD

**Issue by homink** [OpenNMT/CTranslate2#1384]
Hi, I have the Bulkwalter based training/test data such as:

for the source
`ylbs H*A' A*A ysAfr wylbs nEAl A*A`

for the target
`he wears shoes if he travels and wears slippers when for the target`

And wonder if this type of source characters would be working OK in CTranslate2. We built the model using Marian NMT framework with this data and the inference works fine as expected. However, CTranslate2 conversion model using the command ct2-marian-converter gives garbage output for the inference although source_vocabulary.txt and target_vocabulary.txt are exactly identical with what we got in the Marian NMT. And I wonder if what characters are not allowed in CTranslate2. I was not able to locate the character handling except the vocab loading in the CTranslate2 conversion. Any comments?

**Comment by guillaumekln** [comment]
Hi,

There are no restrictions regarding the characters. The tokens can be any sequence of Unicode characters.

You should double check that the generated vocabulary files have the correct length and that you correctly apply the tokenization before running the CTranslate2.

If everything seems to look OK, you should provide more information about the training configuration and how the model was converted.

**Comment by homink** [comment]
It turned out that the vocabulary list was misaligned with the sentence piece model indeed. Thanks!
