### ISSUE TITLE
Bigger models unproportionally slower

### ISSUE THREAD

**Issue by NeonBohdan** [OpenNMT/CTranslate2#1385]
I'm testing open_llama 3/7/13 model sizes
And having

```
generator = ctranslate2.Generator(model_dir, intra_threads=4, compute_type="int8")

generator.generate_batch(
    [tokens],
    beam_size=1,
    max_length=200,
    min_length=200,
    include_prompt_in_result=False,
    return_end_token=True
)
```

And I'm getting unproportional slowdown on cpu considering model sizes equals exactly = [3.0, 6.7, 13.0]

Is it my error or expected behaviour?

**Comment by guillaumekln** [comment]
What do you mean exactly by "unproportional slowdown"? Can you post some numbers?

**Comment by NeonBohdan** [comment]
Thanks for Your response

I was using this 3 models
```
openlm-research/open_llama_3b_v2
openlm-research/open_llama_7b_v2
openlm-research/open_llama_13b
```
They only different by `hidden_size` and `num_hidden_layers`
___
Using the script [model_size.py](https://github.com/OpenNMT/CTranslate2/files/12231809/model_size.py.txt) I've got their sizes
3.4B, 6.7B, 13B
___
Here is the [benchmark.py](https://github.com/OpenNMT/CTranslate2/files/12231770/benchmark.py.txt) for getting `tokens/s` data

Got
```
3.4B, 6.5 tok/s
6.7B, 2.5 tok/s
13B, 1.7 tok/s
```
___
I can't really undestand the relation beetwen selected model and its' performance 
It has bad corelation with `num_hidden_layers` (considerind latency for example)
And a bit better with `num_parameters` but still very strange

**Comment by guillaumekln** [comment]
It is generally hard to predict the performance as it depends on many factors.

Your numbers looks mostly reasonable to me. You should try averaging the results over multiple runs to make the numbers more trustworthy.
