### ISSUE TITLE
How to sample multiple completions? 

### ISSUE THREAD

**Issue by arunpatro** [OpenNMT/CTranslate2#1387]
In the `generator.generate_batch(...)`, there is no argument for `num_return_sequences` or `samples` like features. What is the right way to do this without a loop?

**Comment by guillaumekln** [comment]
Use `num_hypotheses`.

**Comment by arunpatro** [comment]
Is it correct to say that `beam_size=n` and `num_hythosesis=n` are equivalent to `num_return_sequences=n` and `do_sample=True` in hugging face?

**Comment by guillaumekln** [comment]
* `num_hypotheses` is equivalent to `num_return_sequences`
* `do_sample=True` is equivalent to `beam_size=1, sampling_topk=50`

See this example in the document to sample multiple sequences for the same input:

https://opennmt.net/CTranslate2/decoding.html#random-sampling

The example uses `translate_batch` but the logic is the same for `generate_batch`.
