### ISSUE TITLE
AttributeError: module 'ctranslate2' has no attribute 'StorageView'

### ISSUE THREAD

**Issue by Geremia** [OpenNMT/CTranslate2#1390]
```python
>>> from faster_whisper import WhisperModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/faster-whisper/lib64/python3.9/site-packages/faster_whisper/__init__.py", line 2, in <module>
    from faster_whisper.transcribe import WhisperModel
  File "/tmp/faster-whisper/lib64/python3.9/site-packages/faster_whisper/transcribe.py", line 75, in <module>
    class WhisperModel:
  File "/tmp/faster-whisper/lib64/python3.9/site-packages/faster_whisper/transcribe.py", line 357, in WhisperModel
    encoder_output: Optional[ctranslate2.StorageView] = None,
AttributeError: module 'ctranslate2' has no attribute 'StorageView'
```
I built `CTranslate2` from master and installed `faster-whisper` with `pip` (in a `venv`).

**Comment by Geremia** [comment]
This was caused by not properly [compiling the Python wrapper](https://github.com/OpenNMT/CTranslate2/blob/master/docs/installation.md#compile-the-python-wrapper). I built and installed CTranslate2 into a custom directory and needed to specify the custom include directory in `setup.py` so it'd find the header files:

``python
include_dirs = [pybind11.get_include(), "/tmp/CTranslate2-DESTDIR/usr/local/include"]
```

**Comment by Geremia** [comment]
It seems somethings might be missing:

```python3
>>> import ctranslate2
>>> ctranslate2.
ctranslate2.converters  ctranslate2.models      ctranslate2.specs       ctranslate2.sys         ctranslate2.version
```

**Comment by Geremia** [comment]
It was a strange build or install issue. I rebuilt and now it works.

**Comment by NimraOnline** [comment]
make sure it is ctranslate2>=4.0,<5
