### ISSUE TITLE
Error in translating with alternatives

### ISSUE THREAD

**Issue by pdakwal** [OpenNMT/CTranslate2#1394]
Hi,

I am trying to generate alternatives at a position with a given prefix using the example given in the [documentation](https://opennmt.net/CTranslate2/decoding.html#alternatives-at-a-position)

```
input = "This project is geared towards efficient serving of standard translation models but is also a place for experimentation around model compression and inference acceleration."

model_name = 'model/'

translator = ctranslate2.Translator(model_name, 'cpu', compute_type="int8")

results = translator.translate_batch(
    [tokenize(input)],
    target_prefix=[tokenize("Dieses Projekt ist auf die")],
    num_hypotheses=5,
    beam_size=5,
    return_alternatives=True,
)

for hypothesis in results[0].hypotheses:
    print(hypothesis)
```

This gives me an error 

```
results = translator.translate_batch(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: MatMul: batch dimension of inputs a and b should match
```

It works alright without the alternatives when commenting `return_alternatives=True` but I need the alternatives.

Am I doing anything wrong or this is possibly a bug? I am using latest release. Please help

Thanks

**Comment by guillaumekln** [comment]
Hi,

What model are you running? Can you give more details about the model configuration and which converter you used?

I tried with the ENDE model from OpusMT but I don't reproduce the error.

**Comment by pdakwal** [comment]
@guillaumekln I just realized the model was converted using ctranslate2 version 3.8.0 for opennmt-py model. Following convertor was used but earlier I was testing with latest (3.17.1) version

`ct2-opennmt-py-converter --model_path model.pt --output_dir ctranslate2`

However, I tested the `translate_batch` with ctranslate2 3.8.0 and getting the same error. 

openNMT-py model was trained with onmt 2.3.0 version transformer big configuration

**Comment by guillaumekln** [comment]
I can reproduce the error with a model using relative positions. Do you confirm you trained the model with the option `max_relative_positions` > 0?

**Comment by pdakwal** [comment]
@guillaumekln yes `max_relative_positions ` = 16 was used
