### ISSUE TITLE
using whisper related c++ interface is slow

### ISSUE THREAD

**Issue by syq163** [OpenNMT/CTranslate2#1401]
I use the following code in my project,  ctranslate2 versions are the same with faster-whisper.
however, "genarate" function took twice the time compared with faster-whisper.
The CPU usage is also uncontrollable, by default occupying over 80 cores.

model = ::ctranslate2::models::Model::load(model_path, device_, 0, compute_type_);

std::unique_ptr<::ctranslate2::models::WhisperReplica>
            whisper_replica = ::ctranslate2::models::WhisperReplica::create_from_model(*params->model);

::ctranslate2::models::WhisperOptions default_whisper_options_;
        std::vector<::ctranslate2::models::WhisperGenerationResult> whisper_results =
            whisper_replica->generate(st_features, prompts, default_whisper_options_);

Is there a problem with the way the interface is being used?

**Comment by guillaumekln** [comment]
What's your OS and what build options did you use to compile the library?

**Comment by syq163** [comment]
OS：Linux version 3.10.0-1127.8.2.el7.x86_64
and add "-O3 -fPIC -std=c++17  -D_GLIBCXX_USE_CXX11_ABI=0" to $CMKAE_CXX_FLAGS when compile ctranslate2

**Comment by guillaumekln** [comment]
Did you solve the issue? What was it?

**Comment by syq163** [comment]
The problem was caused by my incorrect calling method. 
After referring to the interface in examples/wngt2020/main.cc, the speed and CPU usage became normal.













At 2023-08-08 14:51:15, "Guillaume Klein" ***@***.***> wrote:

Did you solve the issue? What was it?
