### ISSUE TITLE
Not able to convert falcon-rw-1b into ctranslate2

### ISSUE THREAD

**Issue by prince-0911** [OpenNMT/CTranslate2#1405]

**Comment by guillaumekln** [comment]
We need to add new converter for `FalconConfig` as it was defined in https://github.com/OpenNMT/CTranslate2/pull/1345 (this PR was later reverted).

However, this time we don't want to replace `RWConfig` as it is still used by some models. We should add a new loader instead. The new loader could inherit from `RWLoader` to avoid code duplication.

@natsegal Do you want to look at this if you have some time?

**Comment by natsegal** [comment]
Ok @guillaumekln , I'll look into this issue.

**Comment by prince-0911** [comment]
Hi, Any updates?
