### ISSUE TITLE
Error occur when cmake kernels_avx512.cc.o 

### ISSUE THREAD

**Issue by Faken93** [OpenNMT/CTranslate2#1408]
In file included from /workspace/CTranslate2/build/kernels_avx512.cc:7:0:
/workspace/CTranslate2/src/cpu/vec_avx512.h: In static member function 'static ctranslate2::cpu::Vec<float, (ctranslate2::cpu::CpuIsa)3>::mask_type ctranslate2::cpu::Vec<float, (ctranslate2::cpu::CpuIsa)3>::lt(ctranslate2::cpu::Vec<float, (ctranslate2::cpu::CpuIsa)3>::value_type, ctranslate2::cpu::Vec<float, (ctranslate2::cpu::CpuIsa)3>::value_type)':
/workspace/CTranslate2/src/cpu/vec_avx512.h:55:16: error: '_mm512_cmplt_ps_mask' was not declared in this scope
         return _mm512_cmplt_ps_mask(a, b);
                ^~~~~~~~~~~~~~~~~~~~
/workspace/CTranslate2/src/cpu/vec_avx512.h:55:16: note: suggested alternative: '_mm512_cmp_ps_mask'
         return _mm512_cmplt_ps_mask(a, b);
                ^~~~~~~~~~~~~~~~~~~~
                _mm512_cmp_ps_mask
CMakeFiles/ctranslate2.dir/build.make:1419: recipe for target 'CMakeFiles/ctranslate2.dir/kernels_avx512.cc.o' failed

**Comment by guillaumekln** [comment]
You should update your compiler to a more recent version. If you are using GCC, try with GCC 8 or above.

Alternatively, you can try applying the suggested change in the code: replace `_mm512_cmplt_ps_mask(a, b)` by `_mm512_cmp_ps_mask(a, b, 1)`. If the compilation works after this change, please send a PR.
