### ISSUE TITLE
KV caching?

### ISSUE THREAD

**Issue by bryanhpchiang** [OpenNMT/CTranslate2#1409]
How do I turn on KV caching if I'm doing some sort of chat application where the generated tokens are going to be a part of the prompt in subsequent generations? 

I see the `static_prompt` parameter but does that extend to newly generated tokens? Thanks!

**Comment by guillaumekln** [comment]
There is no KV caching except for fixed prompts (a.k.a. static/system prompts). See the explanation in #1210. Feel free to continue the discussion in this other issue.
