### ISSUE TITLE
Different translation results from converted CTranslate2 model and original OpenNMT-py model.

### ISSUE THREAD

**Issue by 13633491388** [OpenNMT/CTranslate2#1413]
I have trained a OpenNMT-py translation model (zh-en) and convert it into CTranslate2 model (without quantization). The translation results are different.
Source: 一个戴眼镜的，穿红色上衣的男性。他还穿着白色运动鞋。
Translated by OpenNMT-py: A male with glasses wearing a red top. He is also wearing white sneakers. (Correct)
Translated by CTranslate2 model: A male with a red-colored cap. He is also wearing white sneakers. He has dark glasses and is wearing a red top. The male has a red-colored top on and is wearing grey pants. He is also wearing white sneakers and has dark glasses.. (Incorrect, but it seems like a combination of different hypotheses?)
The network I used is transformer. And I have checked that the tokenized tokens are correct. 

**#=my converting operation**
onmt_release_model --model models/model.fren_step_15000.pt --format ctranslate2 --output ct2_models/

**#my translating code**
import ctranslate2
import time
import sentencepiece as spm
translator = ctranslate2.Translator("ct2_models/", device="cuda")
sp = spm.SentencePieceProcessor()
sp.load('~/OpenNMT-py/nmt/test/source.model')

text='一个戴眼镜的，穿红色上衣的男性。他还穿着白色运动鞋。'
text = text.strip()
line = sp.encode_as_pieces([text])

translations = translator.translate_batch(line,batch_type="tokens")
translations = [translation.hypotheses[0] for translation in translations]

sp.load('~/OpenNMT-py/nmt/test/target.model')
translations_desubword = sp.decode(translations)

I wonder if there is any bugs or any details neglected by me?

**Comment by guillaumekln** [comment]
Did you convert the correct model? The conversion command seems to use a fr-en model. (Maybe it is a just a bad copy-paste.)

If you can share the configuration you used to train the OpenNMT-py model, or even the model itself, that would be helpful.

**Comment by 13633491388** [comment]
> Did you convert the correct model? The conversion command seems to use a fr-en model. (Maybe it is a just a bad copy-paste.)
> 
> If you can share the configuration you used to train the OpenNMT-py model, or even the model itself, that would be helpful.

Thanks for help, it's just a bad copy-paste (I forgot to modify the model name when saving), this is my trained OpenNMT-py zh-en model: https://drive.google.com/file/d/1PCEFUmr8vQEtY6XrMucQBkWlbCOX8sZy/view?usp=sharing

**Comment by guillaumekln** [comment]
I don't reproduce the issue. I tested with this sequence of tokens:

```
▁这名男子穿着 蓝色裤子 。
```

Since I don't have access to the SentencePiece model, I picked the tokens directly from the vocabulary. I'm not sure it is a valid tokenized sequence, but we still expect both frameworks to output the same prediction, which is the case in my test. The prediction scores are also close.

### OpenNMT-py

```
onmt_translate --model model.fren_step_15000.pt --src input.txt --verbose
```

```
SENT 1: ['▁这名男子穿着', '蓝色裤子', '。']
PRED 1: ▁The ▁man ▁is ▁wearing ▁a ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁a ▁dark ▁shirt .
PRED SCORE: -0.1700
```

### CTranslate2

```
onmt_release_model --model model.fren_step_15000.pt --format ctranslate2 --output ct2_models/
```

```python
import ctranslate2

translator = ctranslate2.Translator("ct2_models/")

tokens = ["▁这名男子穿着", "蓝色裤子", "。"]
result = translator.translate_batch([tokens], beam_size=5, return_scores=True)[0]

print(result.scores[0], " ".join(result.hypotheses[0]))
```

```
-0.17707879841327667 ▁The ▁man ▁is ▁wearing ▁a ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁a ▁dark ▁shirt .
```

**Comment by 13633491388** [comment]
> I don't reproduce the issue. I tested with this sequence of tokens:
> 
> ```
> ▁这名男子穿着 蓝色裤子 。
> ```
> 
> Since I don't have access to the SentencePiece model, I picked the tokens directly from the vocabulary. I'm not sure it is a valid tokenized sequence, but we still expect both frameworks to output the same prediction, which is the case in my test. The prediction scores are also close.
> 
> ### OpenNMT-py
> ```
> onmt_translate --model model.fren_step_15000.pt --src input.txt --verbose
> ```
> 
> ```
> SENT 1: ['▁这名男子穿着', '蓝色裤子', '。']
> PRED 1: ▁The ▁man ▁is ▁wearing ▁a ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁a ▁dark ▁shirt .
> PRED SCORE: -0.1700
> ```
> 
> ### CTranslate2
> ```
> onmt_release_model --model model.fren_step_15000.pt --format ctranslate2 --output ct2_models/
> ```
> 
> ```python
> import ctranslate2
> 
> translator = ctranslate2.Translator("ct2_models/")
> 
> tokens = ["▁这名男子穿着", "蓝色裤子", "。"]
> result = translator.translate_batch([tokens], beam_size=5, return_scores=True)[0]
> 
> print(result.scores[0], " ".join(result.hypotheses[0]))
> ```
> 
> ```
> -0.17707879841327667 ▁The ▁man ▁is ▁wearing ▁a ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁blue ▁pants . ▁The ▁man ▁is ▁wearing ▁a ▁dark ▁shirt .
> ```

I also get the same results with this tokenized sentence, I will check if it is caused by the sentencepiece model. Thank you.

**Comment by 13633491388** [comment]
slove it, it's my fault.
