### ISSUE TITLE
Huggingface added_tokens.json creates size mismatch in converter

### ISSUE THREAD

**Issue by gbmarc1** [OpenNMT/CTranslate2#1415]
A non empty added_tokens.json will create a Vocabulary mismatch

```added_tokens.json
{
    "<pad>": 32000
}
```

```
ValueError: Vocabulary has size 32001 but the model expected a vocabulary of size 32000
```

To reproduce:
```
ct2-transformers-converter --model NousResearch/llama-2-70b-hf--copy_files tokenizer.model \
      --output_dir output --quantization int8_float16 --low_cpu_mem_usage
```

Conversion works if you manually modify added_tokens.json to:
```added_tokens.json
{
}
```

**Comment by guillaumekln** [comment]
This issue should be raised in the model repository.

The file should be removed, just like it was removed from the original Llama 2 models, e.g.:

https://huggingface.co/meta-llama/Llama-2-70b-hf/commit/de00c41a63fb46d805f85f92fe5418a9633bb97d

**Comment by salahzoubi** [comment]
@gbmarc1 Hi, I've a very similar problem to yours where I'm trying to convert a fine-tuned 7b nous-hermes version, but none of the fixes mentioned above are working for me. Any suggestions how I might be able to fix this?

**Comment by guillaumekln** [comment]
The file `added_tokens.json` is now removed from these Llama2 models and the conversion runs without error.
