### ISSUE TITLE
Distributed mode

### ISSUE THREAD

**Issue by EnricoBeltramo** [OpenNMT/CTranslate2#1416]
It's present or is planned a way to run inference in distribuited mode on multiple different machines?

**Comment by guillaumekln** [comment]
Can you specify what you mean exactly? Do you mean splitting the model on multiple machines (model/tensor parallelism), or loading the same model on multiple machines (data parallelism)?

**Comment by EnricoBeltramo** [comment]
I mean model parallelism, i.e when the model is too big to fit in a single machine vram

**Comment by MrigankRaman** [comment]
Yes I also want to know whether this is possible. Can we have something similar to what device_map="auto" does?

**Comment by guillaumekln** [comment]
As far as I know, device_map="auto" will not load a model on multiple machines. To load the model on multiple GPUs (on the same machine), see the existing issue #1052.

**Comment by japuiglaucia** [comment]
Distributed mode #1416

**Comment by japuiglaucia** [comment]
Distributed mode #1416

**Comment by minhthuc2502** [comment]
I closed this issue as completed. The tensor parallelism is currently supported in Ctranslate2.
