### ISSUE TITLE
Why do I need to "import torch" first so ct2-transformers-converter doesn't give "free(): invalid pointer"?

### ISSUE THREAD

**Issue by Geremia** [OpenNMT/CTranslate2#1422]
After installing [PyTorch Preview (Nightly) version](https://pytorch.org/#preview) so it'd be compatible with Cuda 12:
```bash
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
```
I needed to put an `import torch` line in `/tmp/venv/bin/ct2-transformers-converter`:
```python3
#!/tmp/venv/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import torch
from ctranslate2.converters.transformers import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
Otherwise, I'd get the ["free(): invalid pointer" error](https://github.com/OpenNMT/CTranslate2/issues/1417), issue #1417. 

Why is this?

**Comment by guillaumekln** [comment]
You recompiled the CTranslate2 Python package from the sources, right? In that case the binary is probably not ABI-compatible with the PyTorch package. It can happen when you compile with a compiler that is too recent.

You should learn about manylinux and auditwheel to produce "standard" wheels.

* https://github.com/pypa/manylinux
* https://github.com/pypa/auditwheel

For example the published binaries are built for manylinux2014.

**Comment by Geremia** [comment]
@guillaumekln 

>You recompiled the CTranslate2 Python package from the sources, right?

Yes.
