### ISSUE TITLE
Is batch streaming possible with the Text Generation functions?

### ISSUE THREAD

**Issue by suhjohn** [OpenNMT/CTranslate2#1423]
There doesn't seem to be good documentation on using `generate_iterable`. From just the name, I get the sense that this could potentially be used to batch stream. I'm looking to improve the performance of tgi / vllm and streaming is a crucial functionality that I would like to support but it's unclear if it's possible with CTranslate2.

**Comment by guillaumekln** [comment]
What do you mean by batch streaming exactly?

**Comment by guillaumekln** [comment]
The type hint is correct. This method takes a list of tokens, but not a batch of list of tokens.

For batch mode, see the "Tip" note in the related documentation:

https://opennmt.net/CTranslate2/generation.html#token-streaming

**Comment by SebastianBodza** [comment]
My bad, the tokenizer converts it to a list 😐. 

Thanks for the hint of the callback 👍

**Comment by guillaumekln** [comment]
I'm closing this issue, even though the term "batch streaming" was not clarified by OP.

* If it refers to token streaming in batch mode, there is already a callback parameter as discussed above.
* If it refers to continuous batching, see the existing issue #1333.
