### ISSUE TITLE
Token streaming and batch_ids

### ISSUE THREAD

**Issue by fergusbarratt** [OpenNMT/CTranslate2#1425]
# Token streaming from translate_batched (or generate_batched) seems to mix up the batch_ids?
I'm trying to use the tip [here](https://opennmt.net/CTranslate2/generation.html#token-streaming) to implement token streaming when inferring from a batch of inputs. If i'm understanding right, the callback should be called in series on a stream of GenerationStepResults, which have an attribute `batch_id` which refers to the index in the batch the generated token resulted from? I could be misunderstanding something, but it seems like these batch_ids are getting mixed up. 

The following is for a google/flan-t5-small model from huggingface converted.
```python
import ctranslate2
from transformers import AutoTokenizer

# Load the ctranslate model
optimized_model_path = (
    "./google/flan-t5-small/ct_output_models-float16/"
)
model = ctranslate2.Translator
generator = model(optimized_model_path, device="cpu")

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-small")

batch = [
    "hello",
    "goodbye",
    "so long",
]
encoded_texts = tokenizer(batch)

prompt_tokens = [
    tokenizer.convert_ids_to_tokens(encoded_text)
    for encoded_text in encoded_texts.input_ids
]

def callback(x):
    print(x)
    return False

generation_params = {}
generation_params.update({"beam_size": 1, "max_decoding_length": 1}) # set to single output token for debug
results = generator.translate_batch(
    prompt_tokens, callback=callback, **generation_params
)
print(results)
```
These are the tokenized inputs 
```python
[['▁hello', '</s>'], ['▁so', '▁', 'long', '</s>'], ['▁goodbye', '</s>']]
```

And this is the output i get (the model tends to repeat on these inputs):
```
GenerationStepResult(step=0, batch_id=0, token_id=78, token='▁so', log_prob=None, is_last=True)
GenerationStepResult(step=0, batch_id=1, token_id=21820, token='▁hello', log_prob=None, is_last=True)
GenerationStepResult(step=0, batch_id=2, token_id=23281, token='▁goodbye', log_prob=None, is_last=True)
[['▁hello'], ['▁goodbye'], ['▁so']]
```

**Comment by fergusbarratt** [comment]
I think its something to do with sorting the inputs by length? perhaps for the `max_batch_size` argument, to pack them into similar size batches. Is this a stable sort? if so i should be able to recover the batch ids

**Comment by zj2009** [comment]
`std::sort()` is surely not stable, perhaps `std::stable_sort()` is better for this case.

> I think its something to do with sorting the inputs by length? perhaps for the `max_batch_size` argument, to pack them into similar size batches. Is this a stable sort? if so i should be able to recover the batch ids

**Comment by guillaumekln** [comment]
Correct, there is a sort by length happening. However, this is an implementation detail so what you are observing is effectively a bug that should be fixed.

Thanks for reporting.
