### ISSUE TITLE
Size of converted "lmsys/vicuna-7b-v1.5" models

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [OpenNMT/CTranslate2#1427]
Hello,

I converted the `lmsys/vicuna-7b-v1.5` model (derived from Llama 2) with different quantization options (`float16`, `int8` and `int8_float16`), and was surprised by the size of the model files once converted.

Indeed, usually when using `float16` the model size is reduced by a factor 2 compared to the default model size, which is not the case here. Moreover, when using `int8` or `int8_float16`, there is ussually a reduction by a factor 4 of the model size compared to the default one, which is only a factor 2 here.

**Comment by guillaumekln** [comment]
Hi,

The model on the Hugging Face Hub is already saved in float16, so the relative sizes you are observing are expected.

**Comment by Matthieu-Tinycoaching** [comment]
Hi,

Thank you for your feedback!
