### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1428]
PLEASE PLEASE give examples of portions of the instructions where there are none...For example, I want to get statistics using "ctranslate2.ExecutionStats" but I simply can't get it to work in my Python script and there aren't any examples.

There are examples elsewhere, for example, with "get_supported_compute_types", which is very helpful.

Again, just some api classes/functions that need examples, but please add at least one example for each thing.  Thanks!

**Comment by guillaumekln** [comment]
It takes time to add and, most importantly, maintain the examples. So the online documentation typically highlights the most common and basic usages. If an API has no example in the online documentation, it's likely you can find some usage examples in the Python tests:

https://github.com/OpenNMT/CTranslate2/tree/master/python/tests

Regarding `ctranslate2.ExecutionStats`, this structure is only returned by the methods [`translate_file`](https://opennmt.net/CTranslate2/python/ctranslate2.Translator.html#ctranslate2.Translator.translate_file) and [`score_file`](https://opennmt.net/CTranslate2/python/ctranslate2.Translator.html#ctranslate2.Translator.score_file). It is not used anywhere else.
