### ISSUE TITLE
Is it possibile to controll the number of seconds the input audio file is chuncked in Ctraslate2 Whisper?

### ISSUE THREAD

**Issue by Lorenzoncina** [OpenNMT/CTranslate2#1433]
In Whisper Input audio file is chucked every 30 seconds and then transcribed.
Hugging face API allows, instead, to controll this value while loading the whisper model through the pipeline, check this for reference:https://huggingface.co/blog/asr-chunking

Is there a way to do this with faster-whisper/ ctransalte2? 

I saw features size is fixed [batch_size, 80, 3000], I guess one should mofigy the third dimension (3000) to do that

**Comment by guillaumekln** [comment]
The linked PR will relax the shape requirement. The third dimension can now be less than 3000.
