### ISSUE TITLE
HF and LangChain support

### ISSUE THREAD

**Issue by kripper** [OpenNMT/CTranslate2#1434]
Please support LangChain with CTranslate2.

EDIT: [hf_hub_ctranslate2](https://github.com/michaelfeil/hf-hub-ctranslate2) doesn't support Langchain either.

**Comment by kripper** [comment]
Reason for the down vote? Or for not having CTranslate2 and Langchain interoperation?

BTW, I ended up writing my own CTranslate2 chaining framework.

**Comment by guillaumekln** [comment]
Interoperability with specific frameworks like LangChain is not in the scope of the project.

In some cases we could adapt or extend the existing API to make to interoperability possible, but the actual code that integrates the 2 frameworks will not be added to this repository.

**Comment by kripper** [comment]
Done.

See: https://github.com/langchain-ai/langchain/commit/675d57df503bb1368d733dcfd89bcb68e0f06dc0

**Comment by BBC-Esq** [comment]
> Interoperability with specific frameworks like LangChain is not in the scope of the project.
> 
> In some cases we could adapt or extend the existing API to make to interoperability possible, but the actual code that integrates the 2 frameworks will not be added to this repository.

What is the scope of this project?  I see it as kind of rivaling GPTQ/GGUF/GGML formats, but I'm not a programmer by trade and want to be mindful of guillaujmekln the creator of the project so...I'm wonder the overall scope of it so I don't ask myself questions like "Why isn't it compatible with llama index" or even suggest a pull request for something like that.
