### ISSUE TITLE
Support for TinyLLama 1.1B

### ISSUE THREAD

**Issue by Apoorv7092** [OpenNMT/CTranslate2#1454]
Hello, I am trying to convert TinyLLama 1.1B model (PY007/TinyLlama-1.1B-step-50K-105b model checkpoint name), but getting some sort of shape mismatch error. Kindly look into this @guillaumekln 

Error screenshot: 
![Screenshot from 2023-09-05 21-25-48](https://github.com/OpenNMT/CTranslate2/assets/75771782/d65793c5-ef32-4f7c-939a-3de439d564d6)

**Comment by jncraton** [comment]
Conversion of this model worked for me. Are you definitely using the latest version of ct2? TinyLlama uses grouped query attention, which was [added to the converter](https://github.com/OpenNMT/CTranslate2/commit/d1d924e3f13442d8db3ff0a0d10d42fdc6a72d39) fairly recently. The error you are seeing looks like it could be related to this.

**Comment by Apoorv7092** [comment]
Yes I am using the latest ctranslate2==3.19.0 version but still getting this error. I am using the following command. Please share the command that you used. Thanks in advance
`ct2-transformers-converter --model PY007/TinyLlama-1.1B-step-50K-105b --quantization bfloat16 --output_dir tiny-l2-ct2`
