### ISSUE TITLE
cannot find the profiling information

### ISSUE THREAD

**Issue by zj2009** [OpenNMT/CTranslate2#1460]
I compiled the dynamic lib with `ENABLE_PROFILING=ON`, and then the whl file.

And after installation of the new whl file, I run `python3 test.py` in terminal to perform some inference tasks, but no extra information was printed in the terminal.

so where could I find the profiling information?

thanks~

**Comment by guillaumekln** [comment]
At this time you need to update the C++ code to start and stop the profiler around the function you are trying to profile. Here are the functions to call:

https://github.com/OpenNMT/CTranslate2/blob/feb6ed5b8a02a1865a5e26bca45f16923531f20e/include/ctranslate2/profiler.h#L32-L33

I wanted to expose a way to control the profiler from Python but never completed this task.

**Comment by zj2009** [comment]
I'll try it, thanks~

**Comment by prasad-pr-20** [comment]
@guillaumekln & @zj2009, it would be really helpful if you can you please point me to appropriate documentation as to how to use this profiling, with regards to CT2 transformer models. Thanks in advance.
