### ISSUE TITLE
support for gguf

### ISSUE THREAD

**Issue by thistleknot** [OpenNMT/CTranslate2#1465]
have a model here
https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF

The smallest file will run on 4GB of vram... but if I use the int 8 quantized version here... I get oom
https://huggingface.co/TitanML/ct2-int8-llama-2-7b-chat

**Comment by guillaumekln** [comment]
CTranslate2 has its own model format and there is no plan to support other formats.

There is another issue about int4 support #1104, which is what you are looking for it seems.
