### ISSUE TITLE
can ct2-transformers-converter support tensorflow models?

### ISSUE THREAD

**Issue by ILG2021** [OpenNMT/CTranslate2#1466]
I have fine tune a t5 model by tensorflow. But when I convert it to ctranslate2 model, it is not support.

**Comment by guillaumekln** [comment]
No plans to support TensorFlow models in the transformers converter.

You need to fine-tune the PyTorch model instead, or find a way to convert the TensorFlow model to PyTorch.

**Comment by ILG2021** [comment]
> No plans to support TensorFlow models in the transformers converter.
> 
> You need to fine-tune the PyTorch model instead, or find a way to convert the TensorFlow model to PyTorch.

ok i have solved it. in ctranslate2 load_model, just set from_tf=True in from_pretrained.
