### ISSUE TITLE
Llama 2 example producing gibberish / German at times

### ISSUE THREAD

**Issue by amrrs** [OpenNMT/CTranslate2#1471]
![image](https://github.com/OpenNMT/CTranslate2/assets/5347322/8b7b85aa-b6c7-49b4-935b-67c7497da3dc)

I'm not very sure what's going on, but I followed the Llama 2 example with this model - https://huggingface.co/NousResearch/Llama-2-7b-hf 

and it seems to be replying random gibberish things!

**Comment by amrrs** [comment]
Another example after converting model to `int8_float32` 
![Uploading image.png…]()

**Comment by guillaumekln** [comment]
The script only works with the chat versions of Llama2, for example: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

**Comment by amrrs** [comment]
Thanks, Let me try with that!
