### ISSUE TITLE
attempting to convert tiiuae/falcon-180B-chat

### ISSUE THREAD

**Issue by silvacarl2** [OpenNMT/CTranslate2#1472]
we are attempting to convert tiiuae/falcon-180B-chat to ct2 format.

this is the command:

ct2-transformers-converter --model tiiuae/falcon-180B-chat --output_dir tiiuae-falcon-180b-instruct-int8-float16 --force --copy_files tokenizer.json README.md tokenizer_config.json generation_config.json special_tokens_map.json --quantization int8_float16 --trust_remote_code

but we get this crash:

[2023-09-11 16:04:11,429] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|████████████████| 81/81 [02:28<00:00,  1.84s/it]
Traceback (most recent call last):
  File "/home/silvacarl/.local/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/silvacarl/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 1719, in main
    converter.convert_from_args(args)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/silvacarl/.local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/silvacarl/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 140, in _load
    spec = loader(model, tokenizer)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 192, in __call__
    spec = self.get_model_spec(model)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 1331, in get_model_spec
    self.set_decoder(spec.decoder, model.transformer)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 1359, in set_decoder
    self.set_layer_norm(layer_spec.input_layer_norm, layer.ln_attn)
AttributeError: 'TransformerDecoderLayerSpec' object has no attribute 'input_layer_norm'

any ideas?

we are running on it on A40 with 576 Gi RAM

**Comment by guillaumekln** [comment]
This specific error may require small changes in the converter, but there are currently more general issues related to very large models.

During conversion it will likely hit this other error #1324 which is a limitation in the current model serialization. Then during runtime, the model will require at least 180GB in int8 and would need to be split on multiple GPUs which is currently not supported in CTranslate2 #1052.

**Comment by japuiglaucia** [comment]
attempting to convert tiiuae/falcon-180B-chat #1472

**Comment by silvacarl2** [comment]
non issue now.

**Comment by aflah02** [comment]
@silvacarl2 How did you get this to work? I still get the same error as you posted for `falcon-40b`

**Comment by silvacarl2** [comment]
i didn't, we decide to try somehting else.  theres ten zillion choices now.

**Comment by silvacarl2** [comment]
sorry i thought you tried to do falcon-180b

this may work for 40b, i don't remember.

ct2-transformers-converter --model tiiuae/falcon-40b-instruct --output_dir tiiuae-falcon-40b-instruct-int8_float16 --force --copy_files tokenizer.json README.md tokenizer_config.json generation_config.json special_tokens_map.json --quantization int8_float16 --trust_remote_code 

it needs  88 Gb of RAM

**Comment by aflah02** [comment]
Thanks @silvacarl2 
Is there a way to do this without the int_8 quantization as well? As I tried the same command without the int8 quantization flags and got the same error as you had originally posted for the 180b model. I'm also curious about the 180b model, what way did you go with to run it?

**Comment by silvacarl2** [comment]
>Is there a way to do this without the int_8 quantization as well? 

yes, just use int8 instaead of int_8_float16

>'m also curious about the 180b model, what way did you go with to run it?

we gave up on it, there are many better chocies now.

**Comment by aflah02** [comment]
@silvacarl2 Thanks for the response!
I think you might've misunderstood my first question. I want to do this without any quantization and hence I did not use that flag but it did not work then and I got the error you mentioned in the this issue.

I agree there certainly are much stronger models now!

**Comment by silvacarl2** [comment]
got it.  well, thats as far as we went with it.  8-(

**Comment by aflah02** [comment]
Ah got it! Thanks for the help 😊
