### ISSUE TITLE
The impact of prompt length differences on inference speed

### ISSUE THREAD

**Issue by zj2009** [OpenNMT/CTranslate2#1480]
Suppose there were three prompts, `A`, `B` and `C`, where `len(A)=3000`, `len(B)=100`, `len(c)=10`.

with function `generate_batch`, and set `max_length` to a fixed small value, I found the inference of `[A, B, C]` was much slower than `[A, A, A]` (macbook, tested on both version `3.19.0` and `3.18.0`).

Then I made `A'` and `A''` with very little change on `A`, and there was no common prefix between them. Still, the inference of `[A, A', A'']` was much faster than `[A, B, C]`.

Is this the expected behavior?

**Comment by guillaumekln** [comment]
I suppose you are using `include_prompt_in_result=False`. In this case the behavior you are observing is consistent with the current implementation. This is mentionned in the documentation of `generate_batch`:

> If `include_prompt_in_result` is `False`, the start tokens are forwarded in the decoder at once to initialize its state (i.e. the KV cache for Transformer models). **For variable-length inputs, only the tokens up to the minimum length in the batch are forwarded at once. The remaining tokens are generated in the decoding loop with constrained decoding.**

https://opennmt.net/CTranslate2/python/ctranslate2.Generator.html#ctranslate2.Generator.generate_batch

Is is slower to ingest the prompt in the decoding loop.

**Comment by zj2009** [comment]
very helpful, thanks~
