### ISSUE TITLE
Support for all llama2 models not just ones ending in "-hf"

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1481]
At the instructions here https://opennmt.net/CTranslate2/guides/transformers.html it states:

"The models with the suffix “-hf” such as [meta-llama/Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) can be converted with the Transformers converter..."

I'm having trouble understanding...Does this mean that any models that DO NOT end specifically with "-hf" will not work with ctranslate2?  What does the "-hf" mean?  I noticed a lot of these models are "bfloat16."  I have the original llama2 and codellama models directly from Meta/Facebook...I want to convert the original "float32" to whatever I want...I don't want to convert from bfloat16.   Also, I want to quantize any and all models based on Llama2 regardless of whether they have "-hf."

If that's not possible, how can I convert a model to "-hf?"  After hours, I found the "convert_llama_weights_to_hf.py" script located here:

https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py

So I tried unsuccessfully to convert a random llama2-based model to "hf" format, whatever that is, and then to ctranslate2, couldn't get it to work...So difficult... :-(

**Comment by guillaumekln** [comment]
"Llama 2" usually refers to the latest Llama models released by Meta. See the [Llama Model Index](https://huggingface.co/meta-llama) which lists the Llama 2 models hosted on the Hugging Face Hub. From this table, only the model ending with "-hf" can be converted with `ct2-transformers-converter`. The other models are not compatible with the Transformers library and so cannot be converted with `ct2-transformers-converter`.

It seems you are generally referring to the Llama architecture. You can convert any Llama model with `ct2-transformers-converter` as long as the model is compatible with the Transformers library. Meta made it clear by adding the "-hf" suffix but other authors may not follow this convention. You should read the model card to determine whether the model is meant to be used with the Transformers library or something else.

I'm not sure to understand your point about the quantization. With CTranslate2 it does not matter whether the original model is in float32, float16, or bfloat16.

**Comment by BBC-Esq** [comment]
Thanks for your response. 

What I meant regarding the quantization is...and you can correct me if I'm wrong...But it's my understanding that most LLM start off as float32.

Regarding ctranslate2 specifically it's my understanding that it can:

1) convert a float32 model to float16/bfloat16/int8 etc.;

2) do inference with a model that's in float32/bfloat16/int8 etc.; and

3) do inference on a float32/bfloat16/int8 model, but specify the "d_type" at the time inference is done.

Regarding quantization generally, it's my understanding that:

1) once a float32 model is quantized from float32 to, say, int8, you cannot quantize it back to float32 with it having the same precision because the original data/precision has been lost;

2) If I quantize a model from float32 to bfloat16, and then to int8, it IS NOT the same quality as converting a float32 model directly to int8; and

3) if you do inference with a model in int8, for example, but specify a d_type of float32, this IS NOT the same as doing inference with the original float32 model...because, after all, the extra precision/data has been lost.

Therefore, based on my assumptions (and I may be wrong) I do not understand your comment of: "With CTranslate2 it does not matter whether the original model is in float32, float16, or bfloat16."

True, ctranslate2 can do inference with models in float32, float16, etc., and can even specify a "d_type" when doing inference (as opposed to converting the model beforehand), but I want to make sure I'm doing things properly...

I'm trying to convert original float32 models to the ctranslate2 format and a quantization level of, say, int8.  Based on the foregoing understandings...it seems better to start with the original float32 model?

**Comment by guillaumekln** [comment]
Everything you say is true. If disk space and memory are not a concern, you should convert the model in the highest precision possible. Then during inference you can possibly choose to run with a lower precision (e.g. int8).

In practice, LLMs are big and it is often useful to store them in lower precision. For example LLMs are now rarely uploaded in full float32 precision on the Hugging Face Hub. In this case the full precision is already lost in the original model.

I said "With CTranslate2 it does not matter whether the original model is in float32, float16, or bfloat16" mostly from a usage perspective. Of course the precision of these types is not the same, but the converter can convert or quantize any of these types.

In general I recommend converting into float16 or bfloat16 if the original model is already in bfloat16.

**Comment by BBC-Esq** [comment]
Wow.  It's actually heartening to hear that as a non-tech person I have a basic grasp it seems...

Please allow me to ask 2 follow-up questions...

First, is there any quality/precision difference between a model running in float32, but quantized to int8 at runtime...versus a model quantized to int8 before runtime.  Both are being run as int8 at runtime, correct?

Second, I'll use "CodeLlama-34b-Python" as an example...The only "-hf" version of this model is in bfloat16.  Someone else quantized it.  However, I have the original Float32 from facebook.  This is what it looks like:

![image](https://github.com/OpenNMT/CTranslate2/assets/108230321/fe270c37-1303-4c63-a0ba-2649809e1993)

I want to convert this to the "transformers-compatible" format like you mentioned, which is typically signified by "-hf" but not all people use this apparently...it's my understanding that ctranslate2 must have it in the "-hf" format in order to convert it to the ctranslate2 format?

Therefore, I want to convert the model to the "-hf" format and then (a) convert it to ctranslate2 format at my desired quantization level or (b) keep it at float32 and choose the "d_type" (apologies, I think your technology uses "compute_type") when I actually run the model.

How do I convert it to a "-hf" format so it can be converted again to the ctranslate2 format?  Ctranslate2 only uses .bin files at the time of conversion...not .pth files, whatever those mean...

**Comment by guillaumekln** [comment]
> First, is there any quality/precision difference between a model running in float32, but quantized to int8 at runtime...versus a model quantized to int8 before runtime. Both are being run as int8 at runtime, correct?

Yes, it is the same. The difference is when you apply the quantization (during conversion vs. loading).

> But my question still remains, how do I convert the original codellama models from facebook to the "-hf" format, which will enable me to convert to the ctranslate2 format?

You should use the conversion script you mentioned above:

https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py

However, I can't help you with this conversion script since it was created by the Hugging Face team.

**Comment by BBC-Esq** [comment]
Thank you, please feel free to mark as closed, although I'll probably have additional issues/questions as I strive to implement ctranslate2...

**Comment by BBC-Esq** [comment]
Closed.
