### ISSUE TITLE
Converting CodeLlama-34b-Python-hf

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1483]
I'm trying to convert the above model with the following command:

`ct2-transformers-converter --model "C:\Users\Airflow\Desktop\ctranslate2-llama\CodeLlama-34b-Python-hf\CodeLlama-34b-Python-hf.bin" --quantization int8 --output_dir CodeLlama-34b-Python-hf-int8 --copy_files tokenizer.model config.json tokenizer_config.json tokenizer.json special_tokens_map.json pytorch_model.bin.index.json generation_config.json --low_cpu_mem_usage --force`

You can obviously see that I'm trying to copy every .json file...However, it gives me the following error:

"OSError: It looks like the config file at 'C:\Users\Airflow\Desktop\ctranslate2-llama\CodeLlama-34b-Python-hf\CodeLlama-34b-Python-hf.bin' is not a valid JSON file."

Any idea?  It was giving me an out of memory error as well...but not always strangely?  I have 128 GB of RAM and pagefile.sys is set at 400GB.  If it doesn't give me the out of memory error, it's the json-related error...one or the other.  When it DOES give me the OOM error, I'm watching on Task Manager and it's only after using approximately 80 GB of RAM...

Here's a picture of the files for this model via gitclone...
![image](https://github.com/OpenNMT/CTranslate2/assets/108230321/decfa497-2872-4ccd-b730-08a2722abd86)

OH, I should also mention that before converting I merged all the .bin files using this command:

`COPY /B pytorch_model-00001-of-00007.bin + pytorch_model-00002-of-00007.bin + pytorch_model-00003-of-00007.bin + pytorch_model-00004-of-00007.bin + pytorch_model-00005-of-00007.bin + pytorch_model-00006-of-00007.bin + pytorch_model-00007-of-00007.bin CodeLlama-34b-Python-hf.bin`

I ended up running it again with the folder name this time, not pointing to the .bin file, and it gave me:

`ValueError: Tokenizer class CodeLlamaTokenizer does not exist or is not currently imported.`

**Comment by guillaumekln** [comment]
The option `--model` takes the path to a directory, as described in the command help output (`ct2-transformers-converter -h`):

> Name of the pretrained model to download, or **path to a directory** containing the pretrained model.

There is no need to modify the content of the pretrained model or concatenate the checkpoints

Regarding the tokenizer error, you should update the `transformers` package. CodeLlama was added [Transformers 4.33](https://github.com/huggingface/transformers/releases/tag/v4.33.1).

**Comment by BBC-Esq** [comment]
I will try this, thanks.
