### ISSUE TITLE
DeciLM-6b support

### ISSUE THREAD

**Issue by NeonBohdan** [OpenNMT/CTranslate2#1499]
There is an interesting model released [Deci/DeciLM-6b](https://huggingface.co/Deci/DeciLM-6b)
It has llama architecture with Grouped-Query Attention (GQA) like llama-70B

Is it possible to add support for this model in ctranslate2?
And will it be much faster than llama-7B as it's stated for GQA(maybe for ctransalte2 things will be a little bit different)?

**Comment by vince62s** [comment]
we can't support thousands of variations, just adapt the loaders.
