### ISSUE TITLE
Discussions!

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1500]
In my short time following this repository I noticed that there's a decent amount of discussions on non-bug stuff.  In github settings there's a checkbox for enabling "Discussions" as opposed to issues.  Might I suggest enabling that and moving all non-bug issues to there instead - e.g. new features or roadmaps etc.?  Might make it easier to separate issues from brainstorming stuff.

**Comment by vince62s** [comment]
So far, discussions happened here:
https://forum.opennmt.net/top

**Comment by BBC-Esq** [comment]
Thanks for the info.  I've seen that website but didn't know.  However, it still doesn't hurt to ask since ctranslate2-related conversations might be good on the ctranslate2-specific github as well.  What is opennmt.  I'm somewhat new to this field of compute science and am only familiar with ggml/gptq/gguf...and now ctranslate2 (throw in some Python coding).
