### ISSUE TITLE
utilizing embedding model

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1504]
Hello, I'm trying my best with this script...

```
import ctranslate2
import numpy as np

input_txt_file = "relevant_contexts.txt"
log_txt_file = "log.txt"

model_dir = r"C:\PATH\Scripts\LM Search Vector Database\v1_7 - working - ctranslate2\bge-large-en-v1.5"

def main():
    with open(input_txt_file, 'r') as file:
        lines = file.readlines()

    generator = ctranslate2.Generator(model_dir, device="cuda")

    generation_results = generator.generate_batch(
        start_tokens=[line.split() for line in lines],
        max_length=50,
        sampling_topk=20
    )

    embeddings = [result.tokens for result in generation_results]
    embeddings_str = "\n".join([" ".join(embed) for embed in embeddings])

    with open(log_txt_file, 'w') as file:
        file.write(embeddings_str)

if __name__ == "__main__":
    main()
```

However, I'm getting this error I've never seen before...

```
Traceback (most recent call last):
  File "C:\PATH\Scripts\LM Search Vector Database\v1_7 - working - ctranslate2\ct2_direct.py", line 35, in <module>
    main()
  File "C:\PATH\Scripts\LM Search Vector Database\v1_7 - working - ctranslate2\ct2_direct.py", line 17, in main
    generator = ctranslate2.Generator(model_dir, device="cuda")
RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v67324752. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)
```

Anyone have any idea what that means?

When I use a cool library named "hf_hub_ctranslate2" it works with a similar script so...not sure what's going on:

```
from hf_hub_ctranslate2 import CT2SentenceTransformer

input_txt_file = "relevant_contexts.txt"
log_txt_file = "log.txt"

model_name = "BAAI/bge-large-en-v1.5"

def main():
    with open(input_txt_file, 'r') as file:
        lines = file.readlines()

        model = CT2SentenceTransformer(model_name, compute_type="float32", device="cuda")

    embeddings = model.encode(
        lines,
        batch_size=32,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )

    embeddings_str = "\n".join([str(embed) for embed in embeddings])

    with open(log_txt_file, 'w') as file:
        file.write(embeddings_str)

if __name__ == "__main__":
    main()
```

**Comment by BBC-Esq** [comment]
Correct.  He previously sent this link: [https://gist.github.com/guillaumekln/fb125fc3eb108d1a304b7432486e712f](url).  I was hoping that someone might have some insight though since that script is specifically geared towards LaBSE, and included a specific disclaimer about how it might not work with other models.  Your comment is well taken...However, there's "comparatively extremely less examples of using ctranslate2 versus llama.cpp or gptq, for example, so where I come from it doesn't hurt to ask.  I'm sure the maintainer can close out this "issue" he deems necessary, or even advise me to not ask questions if he feels that I'm over-populating his forum...But I am genuinely struggling with ctranslate2 so...which I feel is a great technology BTW.  Take care.

**Comment by winstxnhdw** [comment]
> Simply replace the model name "sentence-transformers/LaBSE" to "BAAI/bge-large-en" and the example script should work directly.

It worked for me without a problem and I am using the same model as you.  Not really sure why you didn't give his attempt a try.

**Comment by BBC-Esq** [comment]
Thank you i will.  Probably an oversight by me, but it was late last night.  Will try and close out issue if resolved...

**Comment by BBC-Esq** [comment]
Closing.
