### ISSUE TITLE
Quantization of T5encorderonly models like instructor-xl.

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1505]
Can't find my prior post on this, but was wondering if there are any plans to make ctranslate2 compatible with the instructor-xl and related embedding models shown [HERE](https://github.com/xlang-ai/instructor-embedding)?!  These embedding models are hands down the best...but aren't supported...

I've struggled for months...Was able to quantize the model "dynamically" using the script they suggest on the github located [HERE](https://github.com/xlang-ai/instructor-embedding#quantization).  However, I can't utilize gpu-acceleration with the quantized model (only cpu).  Reportedly, this is a PyTorch limitation per [HERE](https://discuss.pytorch.org/t/does-dynamic-quantization-support-gpu/119231/5).  All the other embedding models on the leaderboard can be quantized (i.e. bert based), just on the instructor ones...

If Guill or someone could let me know if this is even worthy (I think it is...) to be worked on, I'd greatly appreciate it.  If not, I understand and can move on with my life. lol.  According to the model card/config.json, it's a "T5EncoderModel" architecture model so...not sure how hard it's be to create a class to make it compatible with ctranslate2 considering that T5 in general is already supported....

Sorry for the repeated post.  My limited technical knowledge is that more information about the architecture is described [HERE](https://huggingface.co/docs/transformers/model_doc/t5#transformers.T5EncoderModel).

**Comment by winstxnhdw** [comment]
This will probably be a low-priority because embedding models are usually 'fast' to run regardless of the inference engine. If I were you, I'd just use their `InstructorEmbedding` library.

**Comment by BBC-Esq** [comment]
There's just not enough activity with Ctranslate2 to make this a priority IMHO.  The new BGE embedding models are about as good and maybe better I've come to find out too...and they use slightly less resources and are faster.  Oh well.  Do hope that the Ctranslate2 gets formal Mistral support soon...saw some people working on that.
