### ISSUE TITLE
Support ARM for m1 or jetson?

### ISSUE THREAD

**Issue by johnnynunez** [OpenNMT/CTranslate2#1508]
It uses c++17 intel mkl, and it's incompatible with mac and jetson arm

**Comment by lpy-ET** [comment]
You can compile for Jetson using the -DWITH_MKL=OFF flag. Cheers!

**Comment by johnnynunez** [comment]
> You can compile for Jetson using the -DWITH_MKL=OFF flag. Cheers!

if I try to build in conda environments fail
