### ISSUE TITLE
Compiling for a particular combination of CUDA and GPU CC

### ISSUE THREAD

**Issue by sgjohnson1981** [OpenNMT/CTranslate2#1513]
I'm very new to machine learning. Just trying to find an inference library I can run on my hardware to play around with open-source LLMs on HuggingFace. My Nvidia Quadro K4200 supports CUDA 11.4 but its GPU Compute Capability is 3.0. The "hardware support" page in the documentation says CTranslate2 supports <3.5 only if you compile it yourself. I can't figure out exactly how to do that.

**Comment by winstxnhdw** [comment]
https://opennmt.net/CTranslate2/installation.html#install-from-sources
