### ISSUE TITLE
Llava support

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1514]
Any plans to support the Llava architecture as in the following shiny new models?

See here on huggingface.co: 

liuhaotian/llava-v1.5-7b
liuhaotian/llava-v1.5-13b

And any of the clip models by chance?

**Comment by BBC-Esq** [comment]
Here is an update link:

https://huggingface.co/liuhaotian/llava-v1.5-7b/tree/main

**Comment by japuiglaucia** [comment]
Llava support #1514

**Comment by BBC-Esq** [comment]
Closing for lack of response.
