### ISSUE TITLE
Implementation with Llama2 and llama index via langchain generates responses which includes context.

### ISSUE THREAD

**Issue by pranavbhat12** [OpenNMT/CTranslate2#1517]
Hi,

I was experimenting with Ctranslate2 library for inference purposes.So to get started built a simple pdf chatbot using llama index and Ctranslate wrapper from Langchain.The response that I get includes information about the context also.How should I get rid of this.Also is there any way to opt for streaming here via langchain.

**Code**: 
from llama_index.llms import LangChainLLM
from langchain.llms import CTranslate2

llm=LangChainLLM(
      llm=CTranslate2(
          model_path="../../llama-2-7b-chat-ct2",
          tokenizer_name=model_name,
          device="cuda",
          max_length=500,
          sampling_topk=50,
          sampling_temperature=0.5,
          repetition_penalty=1.2,
          include_prompt_in_result=False,
          static_prompt=system_prompt,
          num_hypotheses=0,
          cache_static_prompt=True,
      )
  )

**Question**:

When I ask this question "Can i get a standard loan of $50,000 with 2 year loan term. Give answer in Yes or No?" It gives this response:

Residential Home Loans Credit Guidelines – Version  11.1 
 
5 
  
1B. Loan Amount ( Guide only ) 
 
Credit Guidelines  
Minimum loan 
amount  $150,000  
Minimum principal 
increase amount  $25,000 
Maximum aggregate 
exposure per 
Borrower  $10,000,000  
 
1C. Loan Term  
 
Credit Guidelines  
Maximum l oan term  30 years  
Minimum loan term  5 years  
Maximum initial 
interest only period  Up to 5 years  
Interest only is unavailable within the last 20 years of a loan term. For example, if a loan term of 23 years is requested, a maximum interest only 
period of 3 years is available at origination, as interest only is not available in the last 20  years  of the loan term . 
Maximum 
subsequent interest 
only period  Up to 5 years , subject to credit approval.  The following add itional requirements apply:  
1. Satisfactory repayment history over the 6 month period prior to the  I/O rollover request  must be evident ; 
2. Capacity to service the loan  must be evident  using a P&I repayment over the remaining  P&I loan term at the assessment rate.  
Interest only is unavailable within the last 20 years of a loan term. For example, if the loan term has 23 years remaining, a  maximum interest only 
period of 3 years is available, however it cannot be in the last 20 years  of the loan term  
Interest Only  When an applicant requests an interest only loan, the application form must include at least one reason for the request which , including the desired 
interest only term, must be consistent with their loan purpose and needs and

This gives context also but with limited tokens its expected it gives only the answer to the question not the context.

**Comment by winstxnhdw** [comment]
This is a LangChain-specific issue/question. You should open an issue on their end instead.
