### ISSUE TITLE
Whisper inference with 10-second window

### ISSUE THREAD

**Issue by bil-ash** [OpenNMT/CTranslate2#1518]
I would like to perform whisper inference with 10 second audio in a long audio of 50seconds. Which option do I need to specify so that transcription is performed  on 10 second audio from 35s to 45s ? I searched faster-whisper and even there also did not get any relevant doc.

**Comment by Apoorv7092** [comment]
I am not sure of any specified method available with faster-whisper or original OpenAI's implementation of whisper which provides you an option for time sampled transcription. Although you can slice your audio for any given time t1 and t2. You can simply follow the below code(ngl, below code is generated by ChatGPT, although this is a simple time sampling so the code should work.

`import librosa
import numpy as np

# Load your audio file
audio_path = "your_audio.wav"
y, sr = librosa.load(audio_path)  # Load audio and get the sample rate

# Convert time to sample indices
t1_sample = int(t1 * sr)
t2_sample = int(t2 * sr)

# Extract the audio between t1 and t2
audio_segment = y[t1_sample:t2_sample]
`

**Comment by bil-ash** [comment]
Maybe I could not frame my question correctly. I would like faster-whisper to make inference on audio chunks of length 10s/12 s each instead of 30 s each. Could not find any relevant information/option in either faster-whisper or here in ctranslate2. Is it possible with ctranslate2/faster-whisper?

**Comment by bil-ash** [comment]
Update: Got an option in https://github.com/guillaumekln/faster-whisper/blob/5a0541ea7d054aa3716ac492491de30158c20057/faster_whisper/feature_extractor.py#L11 of chunk_length. I guess that is all I need.

**Comment by bil-ash** [comment]
Specifying the chunk length was the exact solution. I was getting transcriptions of only 12-14 s on a custom whisper model and specifying chunk length to 12 s lead to proper generation of transcription.  So, closing the issue
