### ISSUE TITLE
Inference issue after converting Bloom-7b1 to ct2

### ISSUE THREAD

**Issue by thanhnew2001** [OpenNMT/CTranslate2#1519]
Hello all

I use the following commands to convert the bloom model. 

ct2-transformers-converter --model bigscience/bloom-7b1 --output_dir ct2b --force --copy_files tokenizer.json README.md tokenizer_config.json  special_tokens_map.json .gitattributes --quantization int8_float16 --trust_remote_code

It worked then I upload it into https://huggingface.co/thanhnew2001/ct2-bloom-7b1

Now I tried to run inference and got this error:

RuntimeError: Cannot load the vocabulary from the model directory

But the vocabulary file is in the folder

Help me please.

**Comment by minhthuc2502** [comment]
I can't produce this error on my side. Try with other models if it works or not and using the latest version of ct2.

**Comment by thanhnew2001** [comment]
Actually I have to rename vocabulary.json to vocabulary.txt so that it works
