### ISSUE TITLE
Failing for the recent pull requests

### ISSUE THREAD

**Issue by homink** [OpenNMT/CTranslate2#1521]
Hi,

I observe failing for the recent pull requests and I think the following check caused it since this commit. Any suggestions?

https://github.com/OpenNMT/CTranslate2/commit/32071b37b9a834000eedab95fbaab2b5f2111222

**Comment by vince62s** [comment]
I just think 2023.0.0 is no longer available.
if you have yum on your system, can you run those lines ?

https://github.com/OpenNMT/CTranslate2/blob/master/python/tools/prepare_build_environment_linux.sh#L35-L38

if error, then try with "2023.2.0"
