### ISSUE TITLE
New Jina embedding model and ctranslate2 support

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1525]
Does ctranslate2 support the new 8k jina embedding models or does it plan to do so in the future?

[SEE HERE](https://jina.ai/news/jina-ai-launches-worlds-first-open-source-8k-text-embedding-rivaling-openai/)

[SEE ALSO HERE](https://huggingface.co/jinaai/jina-embeddings-v2-base-en?ref=jina-ai-gmbh.ghost.io)

**Comment by vilsonrodrigues** [comment]
is based in BERT so it is supported

**Comment by BBC-Esq** [comment]
No offense, but can someone else doublecheck this?  The reason I ask is because the architecture says it's "JinaBertForMaskedLM".  In a previous question, I asked if the [instructor-xl](https://huggingface.co/hkunlp/instructor-xl) was supported and was told that it was not because it's architecture is [T5EncoderModel](https://huggingface.co/hkunlp/instructor-xl/blob/main/config.json) and not merely T5, which [is supported](https://opennmt.net/CTranslate2/guides/transformers.html).

**Comment by vilsonrodrigues** [comment]
I tested it, it's not working because the Positional Enconding is 'Alibi'. It hopes it will be 'absolute'.

**Comment by BBC-Esq** [comment]
Understood, so does anyone with write authority for this repo know if ctranslate2 might support this in the near future?
