### ISSUE TITLE
Whisper large-v3 model!

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1535]
Now that whisper large-v3 model is supported, does anyone have the command to convert the float32 version by chance?  I know on huggingface.co they initially uploaded float16 but now there's a float32 I believe?

**Comment by tema2002** [comment]
did you add new version to the pip?
!pip install --upgrade pip
!pip install ctranslate2==3.21
ERROR: Could not find a version that satisfies the requirement ctranslate2==3.21 (from versions: 2.11.0, 2.12.0, 2.13.0, 2.13.1, 2.14.0, 2.15.0, 2.15.1, 2.16.0, 2.17.0, 2.18.0, 2.19.0, 2.19.1, 2.20.0, 2.21.0, 2.21.1, 2.22.0, 2.23.0, 2.24.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.5.1, 3.6.0, 3.7.0, 3.8.0, 3.9.0, 3.9.1, 3.10.0, 3.10.1, 3.10.2, 3.10.3, 3.11.0, 3.12.0, 3.13.0, 3.14.0, 3.15.0, 3.15.1, 3.16.0, 3.16.1, 3.17.0, 3.17.1, 3.18.0, 3.19.0, 3.20.0)
ERROR: No matching distribution found for ctranslate2==3.21
