### ISSUE TITLE
Build from code failed

### ISSUE THREAD

**Issue by CheshireCC** [OpenNMT/CTranslate2#1536]
I can not build 3.21.0 correctly from master, 

when I use faster-whisper, I get error 
```
AttributeError: module 'ctranslate2' has no attribute 'StorageView'
```

may be we need a .whl file that can be installed from pypi.

**Comment by avan06** [comment]
I can't wait to use version 3.21.0, but it seems that it hasn't been updated on PyPI yet. 
I also wanted to ask the OpenNMT developers, is there a plan to update CTranslate2 on PyPI from version 3.20.0 to 3.21.0? Thank you.

**Comment by blackpolarz** [comment]
You can actually build from wheel using the link in https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602. 
Simply download and extract the python wheel of your system and install it locally. 
Do remember to remove the older version as the version number in this wheel is not updated.

**Comment by tema2002** [comment]
> You can actually build from wheel using the link in https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602. Simply download and extract the python wheel of your system and install it locally. Do remember to remove the older version as the version number in this wheel is not updated.

Sorry, I cant see the link for Ubuntu here https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602 (( Can you help me pls?

**Comment by CheshireCC** [comment]
> You can actually build from wheel using the link in https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602. Simply download and extract the python wheel of your system and install it locally. Do remember to remove the older version as the version number in this wheel is not updated.

Thank you very much！
 I'll try that.😁

**Comment by CheshireCC** [comment]
> > You can actually build from wheel using the link in https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602. Simply download and extract the python wheel of your system and install it locally. Do remember to remove the older version as the version number in this wheel is not updated.
> 
> Sorry, I cant see the link for Ubuntu here https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602 (( Can you help me pls?

On the bottom of this page.But I think this build is also not correctly, I got same error `AttributeError: module 'ctranslate2.models' has no attribute XXXX ` with windows OS.

**Comment by CheshireCC** [comment]
> You can actually build from wheel using the link in https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602. Simply download and extract the python wheel of your system and install it locally. Do remember to remove the older version as the version number in this wheel is not updated.

thx for your help, but I got same error `AttributeError: module 'ctranslate2.models' has no attribute XXXX`  on Windows OS.
It looks like that some thing lost:
```
>>> dir(ctranslate2)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'add_dll_directory', 'converters', 'ctypes', 'glob', 'models', 'module_name', 'os', 'package_dir', 'pkg_resources', 'specs', 'sys', 'version']
```

**Comment by avan06** [comment]
> You can actually build from wheel using the link in https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602. Simply download and extract the python wheel of your system and install it locally. Do remember to remove the older version as the version number in this wheel is not updated.

Thank you for providing installation instructions for the wheel compiled by actions. I tested running faster-whisper with large-v3 on Windows, and finally, the issue of "model is English-only" no longer occurs due to incorrect is_multilingual judgment.

**Comment by vince62s** [comment]
It's on pypi now, there were some build issues because of Intel repos not being available

**Comment by CheshireCC** [comment]
> It's on pypi now, there were some build issues because of Intel repos not being available它现在在pypi上，由于英特尔存储库不可用，因此存在一些构建问题

thank you very much

**Comment by Fengyinjie** [comment]
I am running faster_whisper==faster_whisper-1.1.1 in a CPU environment and have downloaded the dependency package ctranslate2-4.5.0 (ctranslate2-4.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl). After installing it, I still encounter an error. I did not find the corresponding dependency wheel at https://github.com/OpenNMT/CTranslate2/actions/runs/6814821602.
