### ISSUE TITLE
Support for IBM Power10 and Matrix Math Extensions (MMA)

### ISSUE THREAD

**Issue by Dagamies** [OpenNMT/CTranslate2#1537]
IBM Power10 processor includes Matrix Math Extensions (MMA). 

I will add Ctranslate2 native support for IBM Power10. We have been currently running custom build CT2 on Power8/9 with CUDA, but CPU inferencing has been a no-go due missing optimizations for Power. IBM is kindly donating some Power10 capacity for the implementation and future release testing. 

Expected timeline: Initial working build 1/2024, production ready 3/2024

If there is anything special I should be aware, please let me know!

**Comment by vince62s** [comment]
Welcome to this world, nothing special to know beside reading the code.
