### ISSUE TITLE
Better catch of CUDA OOMs

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#154]
Hi,
While using the python `ctranslate2.Translator` API, it seems that an OOM can cause the whole python session to crash. 
``` python
>>> import ctranslate2
>>> translator = ctranslate2.Translator("ende_ctranslate2/")
>>> translator.translate_batch([["a"]*20000]) # very long dummy batch to force OOM for reproducibility
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to allocate memory
Aborted (core dumped)
```
Would it be possible to better catch such exceptions so that we can handle them python side?
Thanks!

**Comment by guillaumekln** [comment]
Thanks for reporting!

The issue is that the translation is run in a separate thread and I just found that exceptions raised in this thread are not catched by the main thread.
