### ISSUE TITLE
Support for LongT5 Model

### ISSUE THREAD

**Issue by Nick-infinity** [OpenNMT/CTranslate2#1557]
Hello, Do we already have support for LongT5 model or any plans to support it?

`ValueError: No conversion is registered for the model configuration LongT5Config (supported configurations are: BartConfig, BertConfig, BloomConfig, CodeGenConfig, DistilBertConfig, FalconConfig, GPT2Config, GPTBigCodeConfig, GPTJConfig, GPTNeoXConfig, LlamaConfig, M2M100Config, MBartConfig, MPTConfig, MT5Config, MarianConfig, MistralConfig, MixFormerSequentialConfig, OPTConfig, PegasusConfig, RWConfig, T5Config, Wav2Vec2Config, WhisperConfig, XLMRobertaConfig)
`

**Comment by vince62s** [comment]
No plan to support this in the short term.
https://arxiv.org/pdf/2112.07916.pdf
if it were just Local attention, it is similar to sliding windows used by mistral but TGlobal attention is not implemented in CT2.
