### ISSUE TITLE
'GenerationConfig' object has no attribute 'alignment_heads'

### ISSUE THREAD

**Issue by takenori-y** [OpenNMT/CTranslate2#1564]
[GenerationConfig](https://github.com/huggingface/transformers/blob/f70db28322150dd986298cc1d1be8bc144cc1a88/src/transformers/generation/configuration_utils.py#L40) does not seem to have an `alignment_heads` parameter.

Is this line correct?
https://github.com/OpenNMT/CTranslate2/blob/d963499e6ed496526e68fb149c908cb2da1f0255/python/ctranslate2/converters/transformers.py#L918

The problem is from #1546.

**Comment by vince62s** [comment]
@flyingleafe @funboarder13920 please check.

**Comment by minhthuc2502** [comment]
I just push a MR to solve this problem #1565 .

**Comment by takenori-y** [comment]
Will the bug-fixed version be released soon?
