### ISSUE TITLE
[Feature request] Allowing StorageView.to() method to support moving between devices

### ISSUE THREAD

**Issue by AtomAnu** [OpenNMT/CTranslate2#1575]
It seems that this feature has already been implemented at the C++ level ([here](https://github.com/OpenNMT/CTranslate2/blob/83caf67972751ac9ce41b4fe17e8bf1a42b95307/src/storage_view.cc#L90)). So, I am wondering if this can be implemented on the Python interface level to allow changing devices (GPU to CPU or vice versa) easily.

Thank you!

**Comment by AtomAnu** [comment]
@minhthuc2502 Thank you for your answer! However, looking at this [line](https://github.com/OpenNMT/CTranslate2/blob/83caf67972751ac9ce41b4fe17e8bf1a42b95307/python/cpp/storage_view.cc#L191) in `cpp/storage_view.cc`, it seems that the function `to` only supports `dtype` as the input argument.

**Comment by ozancaglayan** [comment]
Hi

Are there any near-term plans to implement this?

**Comment by ozancaglayan** [comment]
FYI, I started working on bringing `move_to` to `python`.

**Comment by ozancaglayan** [comment]
@AtomAnu you can close this issue as the PR is now merged
