### ISSUE TITLE
GEMM operator calculates the `c` output shape incorrectly when input `a` is transpose?

### ISSUE THREAD

**Issue by kandrio** [OpenNMT/CTranslate2#1583]
Hey everyone!

I believe I have found a bug in the GEMM operator.

To the best of my knowledge, the output shape of the `c` StorageView in the GEMM operator should always be: `{m, n}`.

However, `Gemm::compute()` calcultes the shape of `c` incorrectly if `a` is transpose (`a` has shape `{k, m}` instead of `{m, k}`).

Take a look at this piece of code: https://github.com/OpenNMT/CTranslate2/blob/4f8a4f334c59588223b6f1f24b707d7e8d5fe08c/src/ops/gemm.cc#L84-L88

- `Shape output_shape(a.shape());`: sets `output_shape` to: `{k, m}`
- `output_shape[output_shape.size() - 1] = n;`: sets `output_shape` to: `{k, n}`
- `c.resize(std::move(output_shape));`: resizes `c` to `{k, n}`.

Am I missing something here?

Bare in mind that there are no unit tests to catch this currently.

**Comment by minhthuc2502** [comment]
Hello,
This is only the high level of gemm ops. The shape of a is always ``{m, k}``. The private member of ``Gemm`` class is  ``_trans_a`` which is used in the low level of gemm ops for the computation later in [src/cpu/primitives.cc](https://github.com/OpenNMT/CTranslate2/blob/4f8a4f334c59588223b6f1f24b707d7e8d5fe08c/src/cpu/primitives.cc#L623)

**Comment by minhthuc2502** [comment]
Hello, you are right, I think we never handle the case where a is transpose. I will do the fix asap. Thank you for your report.
