### ISSUE TITLE
Bad Performance after convert the OpenNMT-py model to ct2 model

### ISSUE THREAD

**Issue by CreamyLong** [OpenNMT/CTranslate2#1584]
I convert the normal transformer model trained by OpenNMT-py 0.4.1 to the ct2 model. However, the ct2 model generates the random content. There is no warning or error message when converting, but the model.pt size is 338.06M, and the model.bin is 83.28M.

**Comment by vince62s** [comment]
0.4.1 is 5 year old .....

**Comment by CreamyLong** [comment]
> 0.4.1 is 5 year old .....
I know ....， what is the possible reason for this, or Do I have to change the CT2 to a specific version

**Comment by minhthuc2502** [comment]
Try to test model with new version of OpenNMT-py. The new release of CT2 does not guarantee the compatibility for very old version.

**Comment by minhthuc2502** [comment]
I'll close this issue. Feel free to open other issues  if you have another question.
