### ISSUE TITLE
sqlcoder (7b) from mistral model

### ISSUE THREAD

**Issue by JunHyungKang** [OpenNMT/CTranslate2#1591]
during converting sqlcoder(7b), following errors are occured. 
As I know, sqlcoder is fine-tuned from mistral which is supported by CT2.

`!ct2-transformers-converter --model defog/sqlcoder-7b --quantization int8_bfloat16 --output_dir ./sqlcoder-7b_int8_bfloat16_ct2 --force --trust_remote_code`

`!ct2-transformers-converter --model defog/sqlcoder-7b --quantization int8_bfloat16 --output_dir ./sqlcoder-7b_int8_bfloat16_ct2 --force --trust_remote_code`

**Comment by vince62s** [comment]
you posted a command line not an error.
