### ISSUE TITLE
Qwen Support

### ISSUE THREAD

**Issue by Vincent131499** [OpenNMT/CTranslate2#1602]
Excellent work!
Do you support the Qwen-1_8B-Chat model? 
Looking forward to your reply.

**Comment by Vincent131499** [comment]
Looking forward to reply.

**Comment by minhthuc2502** [comment]
Actually, we don't have plan to support this model yet, it'll be in the backlog for the future

**Comment by BBC-Esq** [comment]
Is there any update on this?  Qwen 2.5 has been released - both regular and coding models - and they're state of the are for open source models.

**Comment by minhthuc2502** [comment]
#1820 merged. Qwen2 will be included in the next version.
