### ISSUE TITLE
When is flash attention supported

### ISSUE THREAD

**Issue by dingjingzhen** [OpenNMT/CTranslate2#1626]
There may be a big performance boost

**Comment by minhthuc2502** [comment]
There is any plan now, I don't know If there is any optimization in inference since this issue #1300 . Anyway, this is a interesting feature.

**Comment by BBC-Esq** [comment]
New work on this here:

https://github.com/OpenNMT/CTranslate2/pull/1651

**Comment by minhthuc2502** [comment]
Flash attention is now supported from version [4.2.0](https://github.com/OpenNMT/CTranslate2/releases/tag/v4.2.0)
