### ISSUE TITLE
Please support gemma arch

### ISSUE THREAD

**Issue by NeonBohdan** [OpenNMT/CTranslate2#1627]
It's a unique model
With 256K tokenizer like MT5 but decoder only
So hoping for good multi language capabilities comapared to llama tokenizer version

Hoping it will be easy enough(like llama -> mistal)
As I see this project is now harder to maintain
But better than llama.cpp or vllm in my opinion  

https://huggingface.co/google/gemma-7b-it

Maybe this will help:
https://github.com/ggerganov/llama.cpp/pull/5631
https://github.com/vllm-project/vllm/issues/2960

**Comment by minhthuc2502** [comment]
Support Gemma soon with #1631

**Comment by NeonBohdan** [comment]
@ymoslem, I haven't compiled ctranslate2 to test it yet, and I'm waiting for the release.
However, there seems to be an issue with Gemma-it, compared to Mistral. 
The situation strengthens with quantization. 

You can try using a `repetition penalty`, but overall, I've observed this problem as well.

**Comment by ymoslem** [comment]
Thanks, @NeonBohdan for your response! I tried `repetition_penalty` but it does not seem to help.
I suspect it can be an issue with quantization. I will try without it and see.

**Comment by ymoslem** [comment]
Thanks @NeonBohdan! Are you aware of any quantization implementation that solves this issue, or is it something to do with the model itself?

**Comment by NeonBohdan** [comment]
@ymoslem read [this](https://unsloth.ai/blog/gemma-bugs)

Right now Gemma isn't fully fixed 
Two biggest problems
1) gelu vs apriximation
2) different dtype for different layer for best stability 

So even at bfloat16 or float16 you may see problems (Maybe float16 less problematic, because of embedding scaling)

And if you add quantization for this model it may be critical to leave some layers unquantized (witch ctranslate2 don't support)
_____
So I don't really see a solution exept of waiting 
Or trying:
vllm (without quantization may work better, with may not work)
or llama.cpp (quantization works, but no beam search)

But I like ctranslate2 the most 
It's the most production ready package

**Comment by ymoslem** [comment]
Thanks @NeonBohdan for the explanations.
