### ISSUE TITLE
Problem with GPU allocation after updating to CTranslate2 4.0.0

### ISSUE THREAD

**Issue by carolinaxxxxx** [OpenNMT/CTranslate2#1628]
When the device_index = 1 parameter (GPU 1), the GPU 0 is charged with low value data (in my case about 263 MB) and GPU itself shows signs of work, although it should not. This is clearly the result of the CTranslate2 4.0.0. After returning to ctranslate2 3.24.0 the problem disappears.

![306856309-6f1b5824-3b02-4496-bf3e-9b90b95e6554](https://github.com/OpenNMT/CTranslate2/assets/76022443/ffcb8a52-468e-437c-b1c9-fc756a515732)

The above example is for the whisper model, but I also tried with llm models and the same result.

**Comment by jordimas** [comment]
I have seen https://github.com/OpenNMT/CTranslate2/issues/1628

Thanks for reporting this

**Comment by minhthuc2502** [comment]
This is not a bug, just from CUDA 12, it seems that it takes more memory for initializing GPU. The logic is the same as the version before. I have a small fix [here](https://github.com/OpenNMT/CTranslate2/pull/1633) to prevent initializing unused GPU. Thank you for reporting it.
