### ISSUE TITLE
Translator.unload_model(to_cpu=True) takes long time

### ISSUE THREAD

**Issue by anterart** [OpenNMT/CTranslate2#1642]
Hello everyone.
First of all, thank you for your great work, you have an amazing project going on here, which helped me to decrease my models inference times greatly💪.

I wonder if you can help me with an issue I'm having.
The bottom line of the issue is that running this code:
`Translator.unload_model(to_cpu=True)`
takes a long time (~5 seconds).

**More details:**
I have multiple different Flan-T5 models, all of them together don't fit inside 1 GPU RAM.
Thus, I want to keep 1 model in GPU at all times and quickly replace it with another model if needed.
I noticed that models can be unloaded in the following way:
`Translator.unload_model(to_cpu=True)`
which then makes it possible to load them to GPU much faster (~1 seconds instead of ~5 seconds).
Thus, during initialization of the model serving instance, I load to GPU and then unload to CPU all models sequentially.
The problem arises later, when serving the models, each time a request arrives:
1. Model is loaded (~ 1 seconds)
2. Translate_batch executes
3. Model is unloaded to CPU (~ 5 seconds).
5 seconds during unload is too expensive for me.

I had an idea to copy the Translator instance after it is loaded to CPU, then load the original translator to GPU and then unload it completely (unloading the model completely takes just several milliseconds), thus remaining with a copy of the original Translator loaded in CPU. But sadly Translator instances are not serializable and I can't copy them.

I would be thankful if you have any advice on how to tackle this problem in my use case.
Also I'm interested why the command
`Translator.unload_model(to_cpu=True)`
takes ~5 seconds to complete, but after running it, then this command
`Translator.load_model()`
takes just ~1 seconds.
I expected that unloading model from GPU to CPU and loading the model from CPU to GPU would have similar runtimes since I believe that in both cases similar operations are done, just in reverse order.

**Comment by minhthuc2502** [comment]
Hello, I think the data transfer from Host to Device is more optimized than Device to Host. Additionally, the time for model transfer includes the allocation data time. As far as I know, the allocation on CPU takes more time than once on GPU, so it is not surprising that the unloading process takes more time.

I found some tests [here](https://stackoverflow.com/questions/61615160/device-host-vs-host-device-copy-performance-in-cuda)

**Comment by anterart** [comment]
@minhthuc2502 thanks for the reply.
Since posting the issue I went to study the code a bit and found something that can solve the issue in my use case.
I noticed that every call for `Translator.load_model` or `Translator.unload_model` clears performs `_cached_models.clear()`.
If I understand correctly, the existing of non-empty `_cached_models` are responsible for quick quick loading of the translator to host.
I thought that if it's possible to make clearing `_cached_models` optional (maybe add additional optional argument clear_cacge( then it will make the following possible:
1. During initialization: `Translator.unload_model(to_cpu=True)` - this will still be slow which is ok.
2. During request and before inference: `Translator.load_model(clear_cache=False)` - will be optimized because we have non empty `_cached_models` and also it will not delete the `_cached_models`
3. During request and after inference `Translator.unload_model(clear_cache=False)` will unload the model fast and keep the cache to load the model fast next time.

Here is the relevant lines in the code:
[https://github.com/OpenNMT/CTranslate2/blob/bfa0cb3c03ba02df0d53659aa5235611d701c574/python/cpp/translator.cc#L299](https://github.com/OpenNMT/CTranslate2/blob/bfa0cb3c03ba02df0d53659aa5235611d701c574/python/cpp/translator.cc#L299)

**Comment by minhthuc2502** [comment]
Yes in your use case, you can keep the unloaded model in cache to avoid unloading it all time in the future. Only loading model is needed.

**Comment by anterart** [comment]
It was a bit tougher then I thought, but I think I got it working.
I had to write a new method to clone the cached models instead of moving them.
So now it works in the following way:
**load model:**
1. loads the models to gpu
2. moves the models to cpu
3. clones the models while they are in cpu
4. moves the models clones to gpu
**unload_model:**
Never moves the models.
If it is called with to_cpu=True, just clears the cahced models in gpu, else: clears both in cpu and gpu.

It still works a bit funny though. These are now the steps I need to do in order to initialize the model:
```
translator = Translator(model_path, "cuda", compute_type) #  (takes ~6 seconds)
translator.unload_model(to_cpu=True) # (takes a few ms)
translator.load_model() # (takes ~14 seconds)
```
And from here on it works as I intended, no matter how many times I do it (which is what I wanted 😁):
```
translator.unload_model(to_cpu=True) # (takes a few ms)
translator.load_model() # (takes ~1.5 seconds)
```
And it unloads fully when I call: `translator.unload_model()`

I'm a bit rusty on my C++, so the code might be not suitable for everyone, but these are the changes I introduced to the module `python/cpp/translator.cc`:

```
      void unload_model(const bool to_cpu) {
        if (to_cpu && _device == Device::CPU)
          return;

        // Do not unload the model if some batches are still being processed.
        if (_pool->num_active_batches() > 0)
          return;

        // If the lock is not acquired immediately it means the model is being used
        // in another thread and we can't unload it at this time.
        std::unique_lock lock(_mutex, std::try_to_lock);
        if (!lock || !_model_is_loaded)
          return;

        _gpu_cached_models = _pool->detach_models();
        if (!to_cpu)
          _cpu_cached_models.clear();
        else
          _gpu_cached_models.clear();

        // We clear the CUDA allocator cache to further reduce the memory after unloading the model.
        if (_device == Device::CUDA)
          _pool->clear_cache();

        _model_is_loaded = false;
      }

      void load_model() {
        std::unique_lock lock(_mutex);
        if (_model_is_loaded)
          return;

        if (_cpu_cached_models.empty()) {
          _cpu_cached_models = _model_loader.load();
          move_cached_models(Device::CPU, std::vector<int>(_cpu_cached_models.size(), 0), _cpu_cached_models);
          _gpu_cached_models = _model_loader.load();
        } else {
          _gpu_cached_models = copy_cached_models(_device, _device_index);
          move_cached_models(_device, _device_index, _gpu_cached_models, _num_replicas_per_device);
        }

        _pool->set_models(_gpu_cached_models);
        _gpu_cached_models.clear();
        _model_is_loaded = true;
      }

    private:
      const Device _device;
      const std::vector<int>& _device_index;
      const size_t _num_replicas_per_device;
      std::vector<std::shared_ptr<const models::Model>> _cpu_cached_models;
      std::vector<std::shared_ptr<const models::Model>> _gpu_cached_models;
      bool _model_is_loaded;

      // Use a shared mutex to protect the model state (loaded/unloaded).
      // Multiple threads can read the model at the same time, but a single thread can change
      // the model state (e.g. load or unload the model).
      std::shared_mutex _mutex;

      void assert_model_is_ready() const {
        if (!_model_is_loaded)
          throw std::runtime_error("The model for this translator was unloaded");
      }

      void move_cached_models(Device device,
                              const std::vector<int>& device_index,
                              std::vector<std::shared_ptr<const models::Model>> _cached_models,
                              size_t num_models_per_device = 1) {
        for (size_t i = 0; i < _cached_models.size(); ++i) {
          auto& model = const_cast<models::Model&>(*_cached_models[i]);
          model.set_device(device, device_index[i / num_models_per_device]);
        }
      }

      std::vector<std::shared_ptr<const models::Model>> copy_cached_models(Device device,
                                                                           const std::vector<int>& device_index,
                                                                           size_t num_models_per_device = 1) {
        std::vector<std::shared_ptr<const models::Model>> copied_models;
        for (size_t i = 0; i < _cpu_cached_models.size(); ++i) {
          auto& model = const_cast<models::Model&>(*_cpu_cached_models[i]);
          auto copied_model = model.copy_to(device, device_index[i / num_models_per_device]);
          copied_models.push_back(copied_model);
        }
        return copied_models;
      }
    };
```
I would be happy if you can suggest how can I avoid calling `translator.load_model()` directly after invoking the Translator constructor? I couldn't understand which code is executed when the constructor is called and how can I make it do the same actions that my updated `load_model` method does?
Also if you have any other suggestions I would be happy to hear 😁.

**Comment by anterart** [comment]
I improved the code quality and also implement it in a way that preserves also the old behavior by adding a flag for persistent_cpu_cache.
I opened a PR for this change.
[https://github.com/OpenNMT/CTranslate2/pull/1645](https://github.com/OpenNMT/CTranslate2/pull/1645)

**Comment by minhthuc2502** [comment]
Hello, I think this PR is specific to your use case only. The behavior becomes more complex. The parameter ``persist_cpu_cache`` is not relevant when a ``Translator`` is created. It makes more sense when loading or unloading a model.  As far as I understand, you can just avoid cache clearing when loading model, something like this:
```
      void load_model(bool keep_cache) {
        std::unique_lock lock(_mutex);
        if (_model_is_loaded)
          return;

        if (_cached_models.empty()) {
          _cached_models = _model_loader.load();
        } else {
          move_cached_models(_device, _device_index, _num_replicas_per_device);
        }

        _pool->set_models(_cached_models);
        if (!keep_cache)
          _cached_models.clear();
        _model_is_loaded = true;
      }

      void unload_model(const bool to_cpu) {
        if (to_cpu && _device == Device::CPU)
          return;

        // Do not unload the model if some batches are still being processed.
        if (_pool->num_active_batches() > 0)
          return;

        // If the lock is not acquired immediately it means the model is being used
        // in another thread and we can't unload it at this time.
        std::unique_lock lock(_mutex, std::try_to_lock);
        if (!lock || !_model_is_loaded)
          return;
       
        if (_cached_models.empty) {
          _cached_models = _pool->detach_models();
          if (to_cpu)
            move_cached_models(Device::CPU, std::vector<int>(_cached_models.size(), 0));
          else
            _cached_models.clear();
        }

        // We clear the CUDA allocator cache to further reduce the memory after unloading the model.
        if (_device == Device::CUDA)
          _pool->clear_cache();

        _model_is_loaded = false;
      }

```

**Comment by artyabramovich-cyera** [comment]
Thank you for the reply. :)
Creating an argument in the Translator constructor avoids the need to call the `Translator.unload_model(to_cpu=True)` and then `Translator.load_model` in order to make sure every next call to this method is optimized.
But maybe my code really favors my use case too heavily.
I will check if your idea & code works as intended and consider changing the PR.

**Comment by anterart** [comment]
Thank you for the reply. :)
Creating a Translator instance with persist_cpu_cache=True avoids the need to call the Translator.unload_model(to_cpu=True) and then the Translator.load_model methods in order to make sure every next call to these methods is optimized.
But maybe my code really favors my use case too heavily.
I will check if your idea & code works as intended and consider changing the PR.
