### ISSUE TITLE
[Gemma] GELU should be approx tanh not exact

### ISSUE THREAD

**Issue by NeonBohdan** [OpenNMT/CTranslate2#1658]
From the initial release of Gemma some fixes were made to make it stable (as it should have been)

https://unsloth.ai/blog/gemma-bugs
Here is the summary

3-7 looks like a play with dtype per layer, which isn't a case for ctranslate2, as there is no dtype per layer settings

8 may be very useful and was loud case about gemma
https://github.com/huggingface/transformers/pull/29729

Is it possible to use approximate gelu for Gemma in ctranslate2?

**Comment by NeonBohdan** [comment]
I see GeluTanh already implemented in ctranslate2 
https://github.com/OpenNMT/CTranslate2/blob/8994330bf1258dad0f5f747499154074f4d21526/src/ops/activation.cc#L21

So fix should be just a config update here with `gelu_pytorch_tanh`
https://github.com/OpenNMT/CTranslate2/blob/8994330bf1258dad0f5f747499154074f4d21526/python/ctranslate2/converters/transformers.py#L1297

**Comment by minhthuc2502** [comment]
Hello, Thank you for your information. I will update the converter asap. For the point 7, we create RoPE following the dtype of input (not always float32) but I think it should be ok if my understanding is correct.
