### ISSUE TITLE
4.2.0 release build for python 3.9

### ISSUE THREAD

**Issue by anterart** [OpenNMT/CTranslate2#1663]
Hello!
Will the new release be built for Python 3.9 versions?

**Comment by minhthuc2502** [comment]
Hello,
Yes it is. But after integrating the flash attention, the package is heavier (> 100MB) so we can't push it now to Pypi. I currently sent a request to increase the limit size.
I tried to decrease the package's size or think about another way to release but it is quite completed and I don't have any idea about that now. Therefore, we have to wait now for the release 4.2.0

**Comment by anterart** [comment]
And the 4.2.0 release for Python 3.10 has the same features, but the package is lighter?

**Comment by anterart** [comment]
I see on Pypi the 4.2.0 version is published for Python 3.10, but the package size is far less than 100MB, so I wondered whether it has the same functionality listed in the release?
![image](https://github.com/OpenNMT/CTranslate2/assets/26201666/7dc1fd68-c6f7-4807-8795-162a61216a96)

**Comment by minhthuc2502** [comment]
No, the pipeline just broke after the first push of python3.10. The versions pushed run on the platform which does not support CUDA (so flash attention does not exist), that's why the size is small (~15MB). 

It is missing other packages which run on linux x86-64 or windows even with python310.

**Comment by winstxnhdw** [comment]
v4.2.0 breaks poetry install on Python 3.12. Seems like the wheel is not supported.

**Comment by minhthuc2502** [comment]
Currently, v4.2.0 does not work. As I mentioned above, the size of package exceeds the 100 MB so I can't push it to Pypi. The request to change the limit size was sent to Pypi support.

**Comment by BBC-Esq** [comment]
> Currently, v4.2.0 does not work. As I mentioned above, the size of package exceeds the 100 MB so I can't push it to Pypi. The [request](https://github.com/pypi/support/issues/3870) to change the limit size was sent to Pypi support.

Thanks for clarifying. I tried building from source but couldn't get that to work...likely nothing on your guys' end, it's just me.  I've failed with errors I can't resolve every time I've tried...can't cmake anything. lol

**Comment by minhthuc2502** [comment]
Hello, you can base on this [script](https://github.com/OpenNMT/CTranslate2/blob/master/python/tools/prepare_build_environment_windows.sh) to compile on Windows. Cmake should work if you follow this.

**Comment by BBC-Esq** [comment]
Thanks, but I'm on Windows.  I could in theory try to recreate this script though, which does provide a good roadmap off sorts...

**Comment by BBC-Esq** [comment]
Any idea when the newest version will be pushed to pypi now that the cap has been increased?

**Comment by minhthuc2502** [comment]
The release v4.2.1 is building and will be released soon when the pipeline finishes

**Comment by BBC-Esq** [comment]
It's been published...ok to close this issue?
