### ISSUE TITLE
`unload_model` support for `Generator`

### ISSUE THREAD

**Issue by NeonBohdan** [OpenNMT/CTranslate2#1665]
unload_model [here](https://opennmt.net/CTranslate2/python/ctranslate2.Translator.html#ctranslate2.Translator.unload_model) is a unique feature of ctranslate2
But it's supported only for Translator

Can it also be supported for Generator models?
It will optimize memory management for them alot

**Comment by George0828Zhang** [comment]
+1, can this support Whisper models as well?

**Comment by minhthuc2502** [comment]
Hello, we can support it for Generator and Whisper of course. I will add it when I have time.

**Comment by BBC-Esq** [comment]
In the meantime, hit me up if you want some quick code snippets on how to delete the model object, perform torch.cuda freeing of vram, garbage collection, etc., which is what I've resorted to...
