### ISSUE TITLE
No kernel image is available for execution on the device

### ISSUE THREAD

**Issue by McCloudS** [OpenNMT/CTranslate2#1666]
Trying to use a Quadro K2200, which runs CC 5.0 (Maxwell).  I'm running it on CUDA12.  Is the precompiled whl (on PyPi) not building for 5.0 on CUDA 12?

CMakeLists.txt only shows it building for CUDA 11, right?

![image](https://github.com/OpenNMT/CTranslate2/assets/64094529/2d589055-a88f-497f-81f0-8e65f255c807)

**Comment by sn260591** [comment]
> For the compute 5.0, it works only with CUDA 11. See it [here](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/).

The link contains incorrect information, in fact cuda 12 supports Maxwell https://docs.nvidia.com/cuda/archive/12.4.1/cuda-compiler-driver-nvcc/index.html#gpu-feature-list
