### ISSUE TITLE
Does fairseq transform align can returns the alignment result?

### ISSUE THREAD

**Issue by itaybar** [OpenNMT/CTranslate2#1668]
I am using fairseq transform align and Im trying to get the alignment results with no success. this is possible somehow?

**Comment by minhthuc2502** [comment]
I think I don't have much knowledge about this. @vince62s Do you have any idea?

**Comment by vince62s** [comment]
it is supported I think: https://github.com/OpenNMT/CTranslate2/blob/master/docs/guides/fairseq.md?plain=1#L1-L9
but never used

**Comment by itaybar** [comment]
I run the model successfully but cant get the align output (an extra output in this architecture that represent the alignments)

**Comment by ymoslem** [comment]
My understanding is that this also applies to models trained with the [guided alignment](https://opennmt.net/OpenNMT-tf/alignments.html) feature in OpenNMT-tf. According to issue https://github.com/OpenNMT/CTranslate2/issues/767, the feature is not explicitly available; however…
> Alignments can be easily inferred from the attention vectors
For a model trained with Fairseq Transformer Align, I am not sure if this would work, but I assume it depends on the model itself.

**Comment by itaybar** [comment]
Its working, Thanks
