### ISSUE TITLE
Congrats on flash attention, now how do I run it???

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1675]
Saw that the release finally uploaded to pypi and am excited to test FA...how do I do it?  I saw instructions somewhere about setting a boolean parameter??

**Comment by BBC-Esq** [comment]
Nevermind, found it.

**Comment by MrigankRaman** [comment]
> Nevermind, found it.

Can you help me find it?

**Comment by BBC-Esq** [comment]
> > Nevermind, found it.
> 
> Can you help me find it?

[https://opennmt.net/CTranslate2/python/ctranslate2.Generator.html?highlight=flash](url)
