### ISSUE TITLE
How to run FA

### ISSUE THREAD

**Issue by MrigankRaman** [OpenNMT/CTranslate2#1677]
Thanks for supporting FA!! I was wondering where to find the code changes needed to be done to use FA

**Comment by minhthuc2502** [comment]
You just set the ``flash_attention`` parameter when create the Generator:
```
generator = ctranslate2.Generator(model_dir, device="cuda", flash_attention=True)
```

**Comment by BBC-Esq** [comment]
You can also go to the documents and search for "flash" and it'll give you links to how to use it for the "generator" as well as other parts of CT2!  
![image](https://github.com/OpenNMT/CTranslate2/assets/108230321/8b4d5c98-bb50-4ef8-8670-df4dcf06542a)
