### ISSUE TITLE
New Flash Attention Error

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1682]
Trying to test Microsoft's Orca2 model based on Llama2, running in "int8," but I received this error that I've never seen before:

https://huggingface.co/microsoft/Orca-2-7b

```
    generator = ctranslate2.Generator(model_dir, device="cuda", compute_type="int8", flash_attention=True, intra_threads=intra_threads)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: FlashAttention only support fp16 and bf16 data type
```

Never encountered this error before despite running multiple other models converted to "int8"...

**Comment by minhthuc2502** [comment]
As mentioned in the error's message, the Flash attention support only float16 or bfloat16 models. The ``orca-2-7b`` has the type float32 which is not supported.

**Comment by panosk** [comment]
During conversion, you have to explicitly set the conversion type to int8_float16

**Comment by BBC-Esq** [comment]
I see, so there's no point in trying ```int8_float16``` since, if I understand correctly, the "quantization" into ctranslate2 format wouldn't affect the layers pertinent to flash attention...those, apparently, remain in float32, which is incompatible with flash attention.

BTW, I'd love to learn about model architectures so I could actually understand the words you just said...did you get my message with links where I asked about a good starting point?

**Comment by BBC-Esq** [comment]
Asked and answered...closing this issue but please let me know regarding resources to start learning about LLM architectures so I can create a converter.
