### ISSUE TITLE
Facing issues with Ctranslate2 when working with Intel built-in GPU and oneDNN

### ISSUE THREAD

**Issue by prasad-pr-20** [OpenNMT/CTranslate2#1715]
HI All,

I'm trying to build CTranslate2 with oneDNN support enabled which internally uses the Intel GPU. When I execute the benchmark tests, I don't see any output, when gpu is enabled. 

When I run the oneDNN examples, I observe that the GPU is enabled, which is not observable in the case of CTranslate2. 

Thanks in advance for your suggestions and help. Below are the steps to replicate and system configuration.

**Below is the my system configuration:**
	

> **Operating System**: windows 11
**Intel Processor**: Intel 12th gen i9
**Intel graphics**: Intel UHD Graphics 770 driver.

**Steps to replicate**:

1. Enable oneapi environment "C:\Program Files (x86)\intel\oneAPI\setvars.bat"
2. `git clone https://github.com/oneapi-src/oneDNN.git`
3. `cmake -DCMAKE_BUILD_TYPE=Release -DONEDNN_BUILD_TESTS=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icx -G Ninja ..`
4. `cmake --build . --config Release --target install --parallel 8`
5. `git clone --recursive  https://github.com/OpenNMT/CTranslate2.git`
6. `set CTRANSLATE2_ROOT=Path to ctranslate2_dir`
7. `mkdir build && cd build`
8. `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:\Program Files (x86)\oneDNN" -DCMAKE_INSTALL_PREFIX=%CTRANSLATE2_ROOT% -DWITH_DNNL=ON ..`
9. `cmake --build . --config Release --target install --parallel 8`
10. Copy the .dlls to build\tests\Release\
11. set ONEDNN_VERBOSE=1
12. set CT2_VERBOSE=1
13. set CT2_WITH_DNNL=1

Then upon running the `benchmark_ops.exe conv1d cpu fp32`. I get the below output.
![cpu_log_with configuration](https://github.com/OpenNMT/CTranslate2/assets/95696901/cec47276-bf91-4edb-830b-11582fcc1fa7)

Now to see if GPU is being used, I modify the source code at 

https://github.com/OpenNMT/CTranslate2/blob/3b248f135d53fc21972c3321d0a0d3119392baed/src/ops/conv1d_cpu.cc#L17 

changing the engine from **cpu to gpu**. And build using the same commands earlier.

Expectation was the observe some outputs as above with gpu as the engine, but all I see is system configuration and nothing much as below:
![ct2_with_gpu](https://github.com/OpenNMT/CTranslate2/assets/95696901/62b0cb12-8193-4284-9f53-f7b6f1c3ee72)

Is this an expected output or can anyone guide me as to what might have gone wrong.

**Comment by minhthuc2502** [comment]
Even with cpu, you don't have the output returned by benchmark_ops like: ``benchmarking ...``, but any error is shown. Try to recompile code by checking this script https://github.com/OpenNMT/CTranslate2/blob/master/python/tools/prepare_build_environment_windows.sh .

**Comment by prasad-pr-20** [comment]
Thank you for your reply @minhthuc2502. 
Sorry I couldn't capture the whole of the output as it is quite long as I had set oneDNN_VERBOSE=1. 
Upon resetting, I get the below output on CPU. The function executes and terminates.
![cpu_log](https://github.com/OpenNMT/CTranslate2/assets/95696901/b2d4589b-4490-4f1b-b164-e9abd392eb61)

While in case of GPU, the test performs a silent termination, i.e., there is not output. 
Is this the expected output or do I need to try something else.

**Comment by prasad-pr-20** [comment]
Also, I've followed the same steps as in https://github.com/OpenNMT/CTranslate2/blob/master/python/tools/prepare_build_environment_windows.sh, while building oneDNN with `-DONEDNN_GPU_OPTIONS=SYCL`. But I've built with `-DONEDNN_LIBRARY_TYPE=SHARED` 
when built it as a shared library. So can you please guide if Ctranslate expects a static library or shared library from oneDNN?

**Comment by minhthuc2502** [comment]
Hello, CT2 does not support Intel GPU before so I'm not sure your change can make it work (I don't have also Hardware to test it).

Otherwise, you can try build library as shared library, make sure you have the correct PATH like: ``C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/oneapi/dnnl/latest/lib`` where it contains dnnl.dll and try to copy it late to Ctranslate_root/bin

**Comment by prasad-pr-20** [comment]
@minhthuc2502, sorry for the delayed response. Thank you for providing your valuable sugestions. I observed that Intel oneDNN is enabled for Conv layer. Hence was trying with that. Yes I followed the shared library you suggested and found the issue. It was a memory related issue. Working on it to fix the same. 
Thank you once again.

**Comment by DDXDB** [comment]
> @minhthuc2502, sorry for the delayed response. Thank you for providing your valuable sugestions. I observed that Intel oneDNN is enabled for Conv layer. Hence was trying with that. Yes I followed the shared library you suggested and found the issue. It was a memory related issue. Working on it to fix the same. Thank you once again.

hi! Have you made any progress? If possible, I can help test running on Intel ARC dGPU!

**Comment by prasad-pr-20** [comment]
HI @DDXDB, sorry for the late response. This issue has been resolved. 
The fix is the absence of .dlls necessary for build. 
We need to either copy all .dlls in the compiler of oneapi to `CTRanslate2/python/ctranslate2/` dir or the other alternate is to set path to the dlls using command `set PATH=%PATH%;C:\path\to\dlls`

**Comment by Purfview** [comment]
@prasad-pr-20

Did it made it work faster, did you made any benchmarks?

**Comment by frederik-uni** [comment]
@Purfview it shouldnt have as the gpu backend is disabled by default and he didnt enable it....
