### ISSUE TITLE
Adding a layer to an existing model?

### ISSUE THREAD

**Issue by milot-mirdita** [OpenNMT/CTranslate2#1726]
I am working on porting a protein language model to CTranslate2 in [my fork](https://github.com/milot-mirdita/CTranslate2). The base model was easy enough to convert from transformers with a slightly modified conversion script. The model doesn't use a decoder, but has a CNN trained on top to emit the predictions. I built a Conv2D implementation and added this as its own layer.

Now executing the following works perfectly well:
```
  ctranslate2::Encoder enc(model_loader, pool_config);
  auto out = enc.forward_batch_async(input);
  auto ys = out.get().last_hidden_state;
  ctranslate2::layers::ProstT5CNN prost_t5_cnn(conv0, bias0, conv1, bias1);
  ctranslate2::StorageView conv_out(device, cnnDtype);
  prost_t5_cnn(ys, conv_out);
```

However, I would like to add my own layer into the model, so all the thread pool stuff works as is. Is this somehow possible?

**Comment by minhthuc2502** [comment]
Hello, You can take a look the [pooler_dense](https://github.com/OpenNMT/CTranslate2/blob/master/include/ctranslate2/models/language_model.h#L161) . I think you just create a new layer and then add it to the ``EncoderReplica``. In the [Encoder's forward](https://github.com/OpenNMT/CTranslate2/blob/master/src/models/language_model.cc#L386), you can add the prost_t5_cnn layer's forward and set the result to the ``EncoderForwardOutput``.

**Comment by milot-mirdita** [comment]
Thanks a lot for the quick reply.

I found that code, but it seems to be that would require me to to change the `EncoderReplica`, which would mean changing the code directly within CT2, with little chance to upstream these changes.

I was hoping to upstream all the unrelated changes to ProstT5 (at some point), include ctranslate2 as a library in my project and keep the ProstT5 changes outside of the ctranslate2 within my project.

**Comment by minhthuc2502** [comment]
The architecture actual does not support loading dynamically a layer to a model so I can't give you a solution.

**Comment by milot-mirdita** [comment]
I hacked it into the EncoderReplica as you suggested. Thanks a lot!
