### ISSUE TITLE
Segmentation fault when using `return_alternatives` flag on NLLB model on cuda

### ISSUE THREAD

**Issue by Mukhammadsaid19** [OpenNMT/CTranslate2#1731]
I'm experiencing a problem with using a translator for returning alternatives as explained [here](https://opennmt.net/CTranslate2/decoding.html#alternatives-at-a-position). My model is a fune-tuned NLLB and I'm using the following code: 

```python
target_prefix = preproc(request.target_prefix)

source = [source_lang] + self.tokenizer.tokenize(sent) + ['</s>']

results = self.translator_alternative.translate_batch(
    [source],
    target_prefix=[[target_lang] + self.tokenizer.tokenize(target_prefix)],
    num_hypotheses=5,
    return_alternatives=True,
    min_alternative_expansion_prob=0.001,
)
```

The field `translator_alternative` is initialized like this:

```python
translator_alternative = ctranslate2.Translator(model_name, device="cuda")
```

Segmentation fault occurs only when I used "cuda" as my device. When using "cpu", there's no error. My cuda version is 12.2, I'm using Nvidia L4 GPUs.

**Comment by minhthuc2502** [comment]
Can you give the full script ? I'll try on my side with NLLB model.

**Comment by minhthuc2502** [comment]
Thank you for your report. I found the problem due to updating cuda data on host.
