### ISSUE TITLE
Add gemma2 support

### ISSUE THREAD

**Issue by Theodotus1243** [OpenNMT/CTranslate2#1735]
It should be a minor extension 
It shares gemma and llama features 
And also a powerful model by itself 
MMLU 71

[paper](https://storage.googleapis.com/deepmind-media/gemma/gemma-2-report.pdf)
[model config](https://huggingface.co/google/gemma-2-9b-it/blob/main/config.json)

**Comment by BBC-Esq** [comment]
Is gemma2 supported yet??

**Comment by Theodotus1243** [comment]
Done here 
https://github.com/OpenNMT/CTranslate2/pull/1772
