### ISSUE TITLE
The version of CUB in your include path is not compatible with this release of Thrust.

### ISSUE THREAD

**Issue by Tarinaky** [OpenNMT/CTranslate2#1742]
I am struggling to get CTranslate2 to build under Debian. I got it to build on this machine once before, but it's suddenly stopped working and I don't know why.

I am attempting to build with `cmake . -DWITH_CUDA=ON -DOPENMP_RUNTIME=COMP -DWITH_MKL=OFF -DWITH_CUDNN=ON && make`

I am getting two issues, intermittently, most of the time I get the error message 

```
error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
```

But on a couple of occasions, I have managed to, instead, get the error message (I don't know if they're related)

```
CTranslate2/third_party/cutlass/include/cute/atom/copy_traits_sm90_tma.hpp(71): error: namespace "cute::detail" has no member "is_prefetch"
      if constexpr (detail::is_prefetch<CopyOp>) {
```

I have, checked out, tag v4.3.1.

If there's any version strings for any packages or any other diagnostics let me know, I have CUDA 12 installed and cudnn9-cuda-12.

If there an updated list of build dependencies somewhere? python/tools/prepare_build_environment_linux.sh is specifically for RHEL.

**Comment by minhthuc2502** [comment]
It seems like you do not use the correct version of third_party libs in CTranslate2, make sure git submodule pull the correct version defined in Ctranslate2.
```
git submodule update --recursive
git submodule status

```
