### ISSUE TITLE
Docker images not published

### ISSUE THREAD

**Issue by ales-t** [OpenNMT/CTranslate2#1754]
There are new releases being made but it seems that Docker images are no longer being published: https://hub.docker.com/r/opennmt/ctranslate2/tags

**Comment by minhthuc2502** [comment]
The Docker image is currently pushed here: https://github.com/OpenNMT/CTranslate2/pkgs/container/ctranslate2

**Comment by ales-t** [comment]
Thank you! I'm happy to close the issue then, or feel free to close it @minhthuc2502 🙏
