### ISSUE TITLE
How to early stop an encoding call?

### ISSUE THREAD

**Issue by mariano54** [OpenNMT/CTranslate2#1768]
I am calling encode from whisperX/faster-whisper.

Since encode can take 200ms in my use case, and I am calling it very often for many users, I would like for the ability to do early stopping in the model forward for encode, through something like a callback.

Is this possible, and if so, could someone point me to how to do it, or what it would take to add this feature? I am happy to contribute a PR if this is something useful to others.

**Comment by mariano54** [comment]
Otherwise, would it be possible to do something like a streaming encode, where I pass in more audio data as it comes, in like 10ms chunks, to reduce the latency? Or is the total encoding time not linear in the data size?

**Comment by minhthuc2502** [comment]
Hello, I don't have any suggestion for stopping early the current call. we don't have any way to access the forward of the calling encoder. 

In the ctranslate2, it have not yet support the continuous batching. There is a discussion here  #1333

**Comment by mariano54** [comment]
Ok, thank you!
