### ISSUE TITLE
Implement GPU TopK without TensorRT

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/CTranslate2#178]
We should look into implementing the TopK layer with a custom CUDA kernel instead of using TensorRT. The motivation is to remove the TensorRT and cuDNN dependencies (cuDNN is a dependency of TensorRT).

The benefits are:

* make it easier to build Python wheels with GPU support (cuBLAS would be the only external NVIDIA dependency);
* reduce the total installation size.

**Comment by vince62s** [comment]
What is the performance impact ?

**Comment by guillaumekln** [comment]
The goal would be to maintain the same level of performance.

I'm not sure how the TopK from TensorRT compares to other implementation, such as the one from PyTorch. I used it because it was the easiest to integrate.

**Comment by guillaumekln** [comment]
Possible reference implementations:

* PyTorch: https://github.com/pytorch/pytorch/blob/4ced22c5de4d5500aac45a1ecb0e7751e1e4a092/aten/src/THC/THCTensorTopK.cuh#L26
* ONNX runtime: https://github.com/microsoft/onnxruntime/blob/86eaa71ec69fe8961dd58a364052d61831dae5ed/onnxruntime/core/providers/cuda/math/topk_impl.cu

**Comment by guillaumekln** [comment]
Looks like the 2 candidates mentioned above are significantly slower than TensorRT's TopK. We might not be able to easily get rid of TensorRT.

**Comment by vince62s** [comment]
do you have numbers? good to know though.

**Comment by guillaumekln** [comment]
Yes.

Here are some execution times of the TopK layer with K = 4 and an input with shape [32, 4 * 32000] (a typical input shape during batched beam search):

| TopK | Execution time (ms) |
| --- | --- |
| TensorRT | 0.233461 |
| ONNX Runtime | 1.55496 |
| PyTorch | 2.78814 |

Here are some tokens/s when running translation with batch = 32 and beam = 4:

| TopK | Tokens/s |
| --- | --- |
| TensorRT | 1969.13 |
| ONNX Runtime | 1848.19 |
| PyTorch | 1790.37 |

Given the poor result of PyTorch's TopK, we could think I did something wrong during the integration. That's possible. However, there are [some open issues](https://github.com/pytorch/pytorch/search?q=topk&type=issues) on the PyTorch repository regarding the poor TopK performance.

**Comment by vince62s** [comment]
I don't get how we can have an order of magnitude in the first table vs a few % differences in the second.

**Comment by guillaumekln** [comment]
The TopK layer only accounts for a few % of the total runtime. That's why the impact appears smaller when running a full translation.

**Comment by breaddance** [comment]
@guillaumekln Excuse me, author. Have you considered adding support for TensorRT in ctranslate2?
