### ISSUE TITLE
Support EuroLLM 🤖

### ISSUE THREAD

**Issue by carolinaxxxxx** [OpenNMT/CTranslate2#1827]
@minhthuc2502 Please consider support for EuroLLM.

The EuroLLM project has the goal of creating a suite of LLMs capable of understanding and generating text in all European Union languages as well as some additional relevant languages. EuroLLM-9B is a 9B parameter model trained on 4 trillion tokens divided across the considered languages and several data sources: Web data, parallel data (en-xx and xx-en), and high-quality datasets. EuroLLM-9B-Instruct was further instruction tuned on EuroBlocks, an instruction tuning dataset with focus on general instruction-following and machine translation.

Collection: https://huggingface.co/collections/utter-project/eurollm-66b2bd5402f755e41c5d9c6d

**Comment by vince62s** [comment]
did you try already? it's a plain llama model so should work out of the box.

**Comment by jncraton** [comment]
This model appears to work fine for me without any modifications required. I've uploaded the [quantized 1.7B instruct model](https://huggingface.co/jncraton/EuroLLM-1.7B-Instruct-ct2-int8) if anyone is looking for a quick way to test this.

This issue can probably be closed.
