### ISSUE TITLE
[QUESTION] [MULTI-TO-MULTI] How specify source and target language with mBart (multi-to-multi) from C++ to translate text...

### ISSUE THREAD

**Issue by wcdr** [OpenNMT/CTranslate2#1831]
Removed same problem with python standard usage.

**Comment by lin-xiaosheng** [comment]
Hello, I encountered the same issue as you did. The multilingual translation of the many-to-many model failed after passing through CTranslate2. How did you resolve it?

**Comment by wcdr** [comment]
I don't :(
