### ISSUE TITLE
Proper configuration for server

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/CTranslate2#195]
Hi,
I've been digging around for a while in code integration but it is not clear to me which argumets are necessary. I guess "model" and "ct2_model" are not required at the same time...
Thanks

**Comment by guillaumekln** [comment]
Are you referring to the OpenNMT-py server? If yes, you should open a topic on the [forum](https://forum.opennmt.net/) for general support or open an issue on [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) if you found a bug.

**Comment by francoishernandez** [comment]
Answered in https://forum.opennmt.net/t/proper-configuration-for-server/3743/2
