### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/CTranslate2#221]
It would be nice to provide an efficient execution on ARM. This architecture is widespread on mobile devices and will be used for future Apple Mac CPUs. AWS also provides [instances based on ARM](https://aws.amazon.com/ec2/graviton/).

To do:

1. Figure out what is required to cross-compile to ARM.
1. Look into the [ARM Compute Library](https://github.com/ARM-software/ComputeLibrary) which has GEMM primitives optimized for ARM NEON.
1. Add ARM NEON vectorization for CPU kernels, and update automatic ISA dispatch accordingly.

**Comment by iamweiweishi** [comment]
Any plan on this?

**Comment by LukaRistic009** [comment]
Hello
should i fix these issues?

**Comment by guillaumekln** [comment]
You could look at this if you are interested. Any comments, research, or experiments that you can share are appreciated.

**Comment by keichi** [comment]
Hi, can I work on this? I have a fork that runs on Apple M1 using NEON and vecLib.

**Comment by guillaumekln** [comment]
Sure. I don't think anyone else is actively working on this.

**Comment by harishankar-gopalan** [comment]
Hi, from which version is support for MAC M1 available ?

**Comment by guillaumekln** [comment]
Let's discuss Mac M1 support in the issue #724.
