### ISSUE TITLE
Much slower with CUDA 10.1 than with 10.0

### ISSUE THREAD

**Issue by jhnwnd** [OpenNMT/CTranslate2#23]
I haven't tested this extensively but a small test seems to indicate slower times when using CUDA 10.1 (Update 2 - i.e., latest) vs CUDA 10.0 (as is used in the Docker file). It's around 1.5 times slower. Have you tried using CUDA 10.1 and have you seen similar results?

**Comment by guillaumekln** [comment]
Thanks for pointing this out. We did not test with CUDA 10.1.

My first guess is that it comes from changes in [Thrust 1.9.4](https://github.com/thrust/thrust/releases/tag/1.9.4):

> All Thrust synchronous algorithms for the CUDA backend now actually synchronize. Previously, any algorithm that did not allocate temporary storage (counterexample: thrust::sort) and did not have a computation-dependent result (counterexample: thrust::reduce) would actually be launched asynchronously. Additionally, synchronous algorithms that allocated temporary storage would become asynchronous if a custom allocator was supplied that did not synchronize on allocation/deallocation, unlike cudaMalloc/cudaFree. So, now thrust::for_each, thrust::transform, thrust::sort, etc are truly synchronous. **In some cases this may be a performance regression**; if you need asynchrony, use the new asynchronous algorithms.

If confirmed and until we find a good way to mitigate this performance regression, we should freeze Thrust to 1.9.3.

**Comment by guillaumekln** [comment]
I tried Thrust 1.9.5 with CUDA 10 and also saw a performance regression. Could you try using Thrust 1.9.3 with CUDA 10.1? The change above allows setting a custom Thrust location.

**Comment by jhnwnd** [comment]
Confirmed that Thrust 1.93 with CUDA 10.1 is achieving the same times as with CUDA 10.0. Thanks.
The readme change you made was to the cuBLAS line, not the Thrust line, where it ought to be.

**Comment by guillaumekln** [comment]
Ah, went too fast on the readme. Thanks!
