### ISSUE TITLE
Are there any plan on TransformerAAN?

### ISSUE THREAD

**Issue by iamweiweishi** [OpenNMT/CTranslate2#236]
Hi, 

I was trying to use TransformerAAN to train a translation model. But I found that CTranslate2 does not support TransformerAAN for now. 
Any plan on this kind of architecture?
Many thanks.

Regards

**Comment by guillaumekln** [comment]
There is no plan to add this architecture at the moment.

If the motivation to use this architecture is about speed, we found that AAN is barely faster than a Transformer model with proper caching, as implemented in CTranslate2.

**Comment by iamweiweishi** [comment]
Yes. I tried to train a fast Transformer.
So, I would use Base Transformers directly.
Thank you.
