### ISSUE TITLE
add .pc file for ctranslate2 

### ISSUE THREAD

**Issue by gyin-ai** [OpenNMT/CTranslate2#253]
Can we add .pc file for ctranslate2 so that it can easily be wrapped into Golang? Just like sentencepiece https://github.com/google/sentencepiece/blob/706b35a37271170175baa3f11f823428f0c9041a/sentencepiece.pc.in. Since golang is quite popular for cloud micro services.

**Comment by guillaumekln** [comment]
Thanks for the request.

I'm not familiar with the Go environment, so hopefully someone else can send a PR for this one.

**Comment by gyin-ai** [comment]
> Thanks for the request.
> 
> I'm not familiar with the Go environment, so hopefully someone else can send a PR for this one.

Thanks. Just leave a quick solution here using `#cgo LDFLAGS: -lctranslate2` would be able to get it. Another dump question is that examples for TranslatorPool are all files. https://github.com/OpenNMT/CTranslate2/blob/7ebba2e89430b563afa6a74c56cb7159363f5e9c/examples/wngt2020/main.cc#L76

How can we send a string to the TranslatorPool to get results?

**Comment by guillaumekln** [comment]
Check out the Python wrapper which forwards a batch of strings to the pool of translators:

https://github.com/OpenNMT/CTranslate2/blob/v1.12.1/python/translator.cc#L218

**Comment by guillaumekln** [comment]
I'm closing this issue as a quick solution is provided.
