### ISSUE TITLE
call the GPU lib from python client

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/CTranslate2#255]
I want to call GPU translation from python client.
I see there is a .so file in the docker, just want to know if the .so file has exported all need funcition.

would be better if there is a sample.

**Comment by guillaumekln** [comment]
Can you clarify what you want to do and what you tried so far? I'm not sure why you are referring to the .so if you are looking to use Python.

**Comment by WangYongzhao** [comment]
I wrongly thought translate with GPU is only working in C++ mode.

Root cause is that when I translate in python , I use the device default value, so GPU is not used.

Then I try to seek a way to call C++ lib in python instead.


```
translator = ctranslate2.Translator(
    model_path: str                 # Path to the CTranslate2 model directory.
    device: str = "cpu",            # The device to use: "cpu", "cuda", or "auto".
```
