### ISSUE TITLE
Question about compute_type

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/CTranslate2#265]
I found that when I set the compute_type to  "float16", or "float", their latecy are all larger than "default".

I was using V100, Compute Capability should be ok.

```
translator = ctranslate2.Translator(
    model_path: str                 # Path to the CTranslate2 model directory.
    device: str = "cuda",            # The device to use: "cpu", "cuda", or "auto".
    device_index: int = 0,          # The index of the device to place this translator on.
    compute_type: str = "default"   # The computation type: "default", "int8", "int16", "float16", or "float",
                                    # or a dict mapping a device to a computation type.

```

does this mean that if I use float16 instead of "default", it's slow due to I actually convert some int operation to float16 operation?

```
    default: {
      // By default, the compute type is the type of the saved model weights.
      // To ensure that any models can be loaded, we enable the fallback.

      ComputeType inferred_compute_type = ComputeType::FLOAT;
      switch (weights_type) {
      case DataType::INT16:
        inferred_compute_type = ComputeType::INT16;
        break;
      case DataType::INT8:
        inferred_compute_type = ComputeType::INT8;
        break;
      case DataType::FLOAT16:
        inferred_compute_type = ComputeType::FLOAT16;
        break;
      default:
        inferred_compute_type = ComputeType::FLOAT;
        break;
      }
```

**Comment by guillaumekln** [comment]
What type (or quantization) did you use during model conversion?

**Comment by WangYongzhao** [comment]
I miss that part and didn't specify that parameter during model conversion. So I use None.
converting and serving with float16 should be faster than default (None in convert, default in serving), right?

```
        parser.add_argument("--quantization", default=None, choices=["int8", "int16", "float16"],
                            help="Weight quantization type.")
```

**Comment by guillaumekln** [comment]
So the default compute type for your model is `float`. Setting `float` as compute type should have the exact same output and latency as `default`.

When setting `float16`, you should consider that dimensions should be a multiple of 8 in order to activate Tensor Cores. Can you try setting the batch size to a multiple of 8?

**Comment by WangYongzhao** [comment]
emm, actually different latency and same output for me.

I was trying to do a real-time serving, batch size is 1. I tried set beam size to 16, but seems not work.

**Comment by guillaumekln** [comment]
How do you measure the latency?

**Comment by WangYongzhao** [comment]
I use a test file with 100,000 lines, each line has 2 words.

to test this, the only diff is compute type `self.translator = ctranslate2.Translator(truemodelpath, _devicetype,0,_compute_type)`

latency metric is 95 percentile in ms.

default | 95PercentileInMs
-- | --
default | 7.7
float16 | 23.2
float | 38.3


attach my model config
```
vocabulary size: 100000
decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
enc_layers: 3
dec_layers: 1
transformer_ff: 1024
heads: 8
```

**Comment by WangYongzhao** [comment]
BTW, I am not using the docker, I build the lib in windows, following other post of this projects.

attach my enviroment

```
1.cuda:			cuda_10.1.243_426.00_win10.exe
2.cudnn:		cudnn-10.1-windows10-x64-v7.6.5.32
3.tensorrt:		TensorRT-6.0.1.5.Windows10.x86_64.cuda-10.1.cudnn7.6
4.boost:		boost_1_73_0.zip
5.MKL:                  https://software.intel.com/content/www/us/en/develop/tools/math-kernel-library/choose-download/windows.html
```

**Comment by WangYongzhao** [comment]
I did another experiment with ct2-opennmt-py-converter and quantization, the convert model size is like below.
is this expected?

quantization | size of model.bin
-- | --
float16 | 970MB
default | 647MB
int16 | 328MB

**Comment by guillaumekln** [comment]
That's not expected. I will take a second look at the float16 conversion but this looks surprising.

**Comment by guillaumekln** [comment]
The PR above fixes the bug when converting a model with `--quantization float16`.

However, I'm not able to reproduce the performance issue. In particular, `--compute_type default` and `--compute_type float` should have the same performance for a non quantized model. Are you sure your measurements are correct?

**Comment by WangYongzhao** [comment]
I will take a see, to see if anything suspicious. I did  caching allocator configuration for better latency, not sure it will have impacts.

BTW, with the convert fix. By design, the latency number below should be equal.

config |converter quantization | serveing compute_type
-- |-- | --
setup-1 | float16 | default
setup-2 | default | float16

**Comment by aj7tesh** [comment]
I have a doubt. When I train model on OpenNMT-py, usinf default value for model_dtype will build a fp32 model. Using ctranslate2 when we convert the model with quantization= None , this should convert the model into the type of the original OpenNMT-py model, right? 
Because my OpenNMT py model was around 1.4GB(pt file), When I converted it using quantization= None , it reduced to around 500 mb and also when converted the model with quantization= int8 then also the size was around 500 mb only. Hence confused wrt quantization.

**Comment by guillaumekln** [comment]
By default, no quantization is applied. 500MB sounds about right for a model without quantization. However, selecting int8 quantization should make the model smaller.

Can you show how you did the conversion?

**Comment by aj7tesh** [comment]
I used below 
output_dir = converter.convert(
    output_dir: str,          # Path to the output directory.
    model_spec: ModelSpec,    # A model specification instance from ctranslate2.specs.
    vmap: str = None,         # Path to a vocabulary mapping file.
    quantization: str = None, # Weights quantization: "int8" or "int16".
    force: bool = False)
this is without quantization
and for int8 I put quantization = int8

However I using ctranslate2 version 1.8.0 and not the latest. will try with latest also.
Also to convert the OpenNMT-py original model(1.4 gb .pt model) i need to use default/None quantization right if I want to keep the orignal model weights as it is in the converted binaries
