### ISSUE TITLE
Could the model be run on Windows without GPUs?

### ISSUE THREAD

**Issue by iamweiweishi** [OpenNMT/CTranslate2#266]
Hi,
My PC only have CPUs, so could the ctranlate2 models run on this kind of platform?
Thank you.

**Comment by guillaumekln** [comment]
Yes, CTranslate2 can run without a GPU.

**Comment by iamweiweishi** [comment]
Hi,
I tried to compile the source codes on **Windows 10**.
I cloned the repository, and then run 'mkdir build && cd build && cmake ..'. Till now, everything works fine.

But, when I run 'make -j4', error reported:
_Makefile error, make *** no targets specified and no makefile found. stop_

I am not sure what I have done is correct since I followed the same steps as on Ubuntu ([link](https://github.com/OpenNMT/CTranslate2#building)).

Could you please give me some advice?
Thank you.

**Comment by guillaumekln** [comment]
Maybe the easiest is to install the Python package `ctranslate2` under [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?
