### ISSUE TITLE
Illegal memory access with target_prefix and beam search

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#275]
Hey there,
Just stumbled upon some instances where an illegal memory access error is raised when decoding with target_prefix.
It is not systematic though.
Also, it does not seem to happen with some anterior versions (1.12.1 for instance).
EDIT: it does seem to happen in 1.12.1 as well in fact.
EDIT2: tested as far back as 1.7.0, same behavior.

Some example with the 'traditional' en_de model from the website:
```python
src = ['▁This', '▁is', '▁a', '▁test', ',', '▁and', '▁another', '▁one', '...']
tgt_prefix = ['▁Dies', '▁ist', '▁ein', '▁Test']
translator = ctranslate2.Translator("ende_ctranslate2/", device="cuda", device_index=0, compute_type="default")
translator.translate_batch([src], target_prefix=[tgt_prefix]) # no issue
translator.translate_batch([src], target_prefix=[tgt_prefix], beam_size=6) # error
```
The last call throws:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  /root/ctranslate2-dev/src/primitives/cuda.cu:46: CUDA failed with error an illegal memory access was encountered
Aborted (core dumped)
```

**Comment by guillaumekln** [comment]
This happens when using multiple beam size values in the same process. [A layer](https://github.com/OpenNMT/CTranslate2/blob/v1.13.2/src/ops/topk_gpu.cu#L81) is cached with the value of the first beam size and reused for all translations. I will fix that.
