### ISSUE TITLE
Decoding with target prefix not going beyond prefix length

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#277]
Hey again,
We stumbled upon some strange cases where some inference with target prefix do not go beyond the prefix even when they should.
(Not necessarily easy to share a reproducible example here for now, sorry.)

1. Is this kind of behaviour expected?
2. Would it be possible to have some kind of mode where the predictions are "forced" to be of length at least len(prefix)+1?
(Sure there is the min_decoding_length parameter but it seems to be a float, hence it would be applied for all examples of the batch.)

Thanks in advance!
cc @vince62s

**Comment by guillaumekln** [comment]
1. The decoding is allowed is to produce the end of sentence token past the prefix so it can be expected.
2. Not sure about this. If the user feeds a prefix that is already the complete translation, we don't want to produce a random token. The mode `return_alternatives` on the contrary has this constraint of "len(prefix)+1" because we are specifically interested in the next token. But the use case is different.

Let's see how we can debug that:

* How frequently does this occur? What is similar about the examples having this issue?
* When setting `min_decoding_length`, are the following tokens correct (or reasonable)
* Did you try with OpenNMT-py as well? If yes, any differences?
* Does using batch vs non batch mode makes a difference?

**Comment by francoishernandez** [comment]
1. Makes sense.
2. Agreed. Just thought we could have some similar mode via some flag without having to use `return_alternatives`. (Also not too sure when we would have the complete translation in prefix, but why not -- to each his own use cases :) )

> How frequently does this occur? What is similar about the examples having this issue?

Not too often.
Not easy to get some similarity. It often happens on some quite long segments (and prefix). But some similarly long segments/prefixes also do well in some cases...

> When setting min_decoding_length, are the following tokens correct (or reasonable)

Seems like it.

> Did you try with OpenNMT-py as well? If yes, any differences?

This issue does not seem to arise, at least not for the cases it does with CT2.

> Does using batch vs non batch mode makes a difference?

Appears in both cases. 

I'll try and post more details when possible.

**Comment by guillaumekln** [comment]
It seems I can reproduce with the usual ENDE model. I generated prefixes of random length based on the true target and looked for translations that are the same as the prefix.

Notes:

* It does not seem to happen for beam size < 5. 
* Interestingly the second hypothesis is correct.

```python
import ctranslate2

def translate(source, target_prefix, beam_size=6):
    print("Source:")
    print("\t%s" % source)
    print("Prefix:")
    print("\t%s" % target_prefix)
    source_tokens = [source.split()]
    target_tokens = [target_prefix.split()]
    outputs = translator.translate_batch(
        source_tokens, beam_size=beam_size)
    print("Translation without prefix:")
    print("\t%s" % " ".join(outputs[0][0]["tokens"]))
    outputs = translator.translate_batch(
        source_tokens, target_tokens, beam_size=beam_size, num_hypotheses=2)
    print("Translation with prefix")
    print("\t%s" % " ".join(outputs[0][0]["tokens"]))
    print("\t%s" % " ".join(outputs[0][1]["tokens"]))
    print("")

translator = ctranslate2.Translator("ende_transformer")

translate(
    "▁\" Back ▁in ▁the ▁middle ▁of ▁the ▁20 th ▁century , ▁it ▁was ▁called ▁a ▁' psy ch ia tric ▁emergency , ' \" ▁said ▁Dr e scher .",
    "▁„ Mit te ▁des ▁20.",
)

translate(
    "▁Under ▁the ▁director ship ▁of ▁Herman n ▁Schneid er , ▁the ▁choir ▁will ▁be ▁accompanied ▁by ▁the ▁wind ▁ensemble ▁of ▁the ▁F roh sinn ▁Ten n en bro n n ▁Music ▁Society , ▁and ▁by ▁No e mi ▁Lo ko di ▁on ▁the ▁organ .",
    "▁Unter ▁der ▁Leitung ▁von ▁Herman",
)

translate(
    "▁This ▁Friday ▁evening , ▁the ▁\" Pu mp ▁this ▁party \" ▁event ▁will ▁be ▁taking ▁place , ▁while ▁one ▁day ▁later , ▁on ▁Saturday ▁evening , ▁fest iv ities ▁will ▁continue ▁with ▁an ▁over - 25 s ▁party .",
    "▁Am ▁heutige",
)

```

```text
Source:
        ▁" Back ▁in ▁the ▁middle ▁of ▁the ▁20 th ▁century , ▁it ▁was ▁called ▁a ▁' psy ch ia tric ▁emergency , ' " ▁said ▁Dr e scher .
Prefix:
        ▁„ Mit te ▁des ▁20.
Translation without prefix:
        ▁" Zu rück ▁in ▁der ▁Mitte ▁des ▁20. ▁Jahrhunderts ▁wurde ▁es ▁als ▁" psy chi at rische ▁Not fall " ▁bezeichnet ", ▁sagte ▁Dr e scher .
Translation with prefix
        ▁„ Mit te ▁des ▁20.
        ▁„ Mit te ▁des ▁20. ▁Jahrhunderts ▁wurde ▁es ▁als ▁„ psy chi at rische ▁Not lage “ ▁bezeichnet “, ▁sagte ▁Dr e scher .

Source:
        ▁Under ▁the ▁director ship ▁of ▁Herman n ▁Schneid er , ▁the ▁choir ▁will ▁be ▁accompanied ▁by ▁the ▁wind ▁ensemble ▁of ▁the ▁F roh sinn ▁Ten n en bro n n ▁Music ▁Society , ▁and ▁by ▁No e mi ▁Lo ko di ▁on ▁the ▁organ .
Prefix:
        ▁Unter ▁der ▁Leitung ▁von ▁Herman
Translation without prefix:
        ▁Unter ▁der ▁Leitung ▁von ▁Herman n ▁Schneid er ▁wird ▁der ▁Chor ▁vom ▁Wind en en s em ble ▁der ▁Musik gesellschaft ▁F roh sinn ▁Ten n en bro n n ▁und ▁von ▁No e mi ▁Lo ko di ▁an ▁der ▁Or gel ▁begleitet .
Translation with prefix
        ▁Unter ▁der ▁Leitung ▁von ▁Herman
        ▁Unter ▁der ▁Leitung ▁von ▁Herman n ▁Schneid er ▁wird ▁der ▁Chor ▁vom ▁Wind en en s em ble ▁der ▁Musik gesellschaft ▁F roh sinn ▁Ten n en bro n n ▁und ▁von ▁No e mi ▁Lo ko di ▁an ▁der ▁Or gel ▁begleitet .

Source:
        ▁This ▁Friday ▁evening , ▁the ▁" Pu mp ▁this ▁party " ▁event ▁will ▁be ▁taking ▁place , ▁while ▁one ▁day ▁later , ▁on ▁Saturday ▁evening , ▁fest iv ities ▁will ▁continue ▁with ▁an ▁over - 25 s ▁party .
Prefix:
        ▁Am ▁heutige
Translation without prefix:
        ▁An ▁diesem ▁Freitag ▁Abend ▁findet ▁die ▁Veranstaltung ▁" Pu mp ▁this ▁party " ▁statt , ▁währ end ▁ein ▁Tag ▁später , ▁am ▁Samstag abend , ▁die ▁Feier lichkeiten ▁mit ▁einer ▁über ▁25 - jährige n ▁Party ▁fort gesetzt ▁werden .
Translation with prefix
        ▁Am ▁heutige
        ▁Am ▁heutige n ▁Freitag ▁Abend ▁findet ▁die ▁Veranstaltung ▁" Pu mp ▁this ▁party " ▁statt , ▁währ end ▁ein ▁Tag ▁später , ▁am ▁Samstag abend , ▁die ▁Feier lichkeiten ▁mit ▁einer ▁über ▁25 - jährige n ▁Party ▁fort gesetzt ▁werden .
```

**Comment by francoishernandez** [comment]
Interesting.
For what it's worth it happened with a beam size == 5 on my end.

**Comment by guillaumekln** [comment]
So I'm trying to refine the search algorithm to avoid these obvious issues, but at the moment it's not clear to me what is the best approach. I probably need to sleep on this. :)

Alternatively, we can add the mode that you suggested. Maybe a flag to exclude the prefix length from `min_decoding_length` and `max_decoding_length`. It could be generally useful.

As a current workaround, `length_penalty` should help.
