### ISSUE TITLE
When to support  python api   gpu

### ISSUE THREAD

**Issue by huifengshiwu** [OpenNMT/CTranslate2#278]

**Comment by guillaumekln** [comment]
The Python API does support using the GPU.

There are currently 2 ways to use the GPU from Python:

* Running your Python code inside a GPU Docker image, for example  `opennmt/ctranslate2:latest-ubuntu18-cuda10.2`
* Building the Python package by following the instructions in [`Dockerfile.ubuntu-gpu`](https://github.com/OpenNMT/CTranslate2/blob/master/docker/Dockerfile.ubuntu-gpu)

**Comment by aj7tesh** [comment]
Does this mean I cannot use GPU for inference without a docker? @guillaumekln

**Comment by guillaumekln** [comment]
You can build the Python package from the source without Docker. I linked to the file [Dockerfile.ubuntu-gpu](https://github.com/OpenNMT/CTranslate2/blob/master/docker/Dockerfile.ubuntu-gpu) because it basically contains all instructions to build a Python package with GPU support.

However, it is usually way easier to install Docker and pull an existing image. The published Docker images are optimized and contain everything to use CTranslate2 on CPU or GPU.

(Note that if we address #178, we might be able to write simpler GPU build instructions in the README.)

**Comment by aj7tesh** [comment]
So basically I have my own python server.py where I am translating sentences using models trained on OpenNMT py. Earlier I was using OpenNMT py server.py t host my model where in conf.json I had option of chosing gpu id to decide whether to host my model on gpu or not. Similar thing can I achieve in ctranslate2? Basically in my server.py I import ctranslate2 which was installed using pip. I directly use  translator.translate_batch([i_final],beam_size = 5,num_hypotheses=num_hypotheses). @guillaumekln

**Comment by Zer0-dev115** [comment]
I have build an docker image using [Dockerfile.ubuntu-gpu](https://github.com/OpenNMT/CTranslate2/blob/master/docker/Dockerfile.ubuntu-gpu). How can I use this image to translate sentence? @guillaumekln

**Comment by guillaumekln** [comment]
@aj7tesh For GPU translation, the easier would be to just run your `server.py` inside the Docker image. CTranslate2 is already installed:

```bash
docker run --entrypoint pip opennmt/ctranslate2:latest-ubuntu18-cuda10.2 list
Package     Version
----------- -------
ctranslate2 1.13.2
numpy       1.19.1
pip         20.2.2
setuptools  50.0.0
six         1.15.0
wheel       0.35.1
```

@Zer0-dev115 What exactly are you trying to do? I would suggest posting on https://forum.opennmt.net/ which is a better place to ask general support questions.

**Comment by aj7tesh** [comment]
1.In my project I have all these packages installed including ctranslate2 1.13.2 and other. 
2. Then I create a docker image of above project/workspace
3. docker run --name [name][image]
does the below parameter override default executable. Could you explain me why are we using pip in the command?
--entrypoint pip opennmt/ctranslate2:latest-ubuntu18-cuda10.2 list

**Comment by guillaumekln** [comment]
I used `pip` to show that the `ctranslate2` package is already installed inside the image. You should use this preinstalled package for GPU support, and not the one you manually installed with `pip install`.

**Comment by aj7tesh** [comment]
Thanks @guillaumekln I will try that

**Comment by anderleich** [comment]
> @aj7tesh For GPU translation, the easier would be to just run your `server.py` inside the Docker image. CTranslate2 is already installed:
> 
> ```shell
> docker run --entrypoint pip opennmt/ctranslate2:latest-ubuntu18-cuda10.2 list
> Package     Version
> ----------- -------
> ctranslate2 1.13.2
> numpy       1.19.1
> pip         20.2.2
> setuptools  50.0.0
> six         1.15.0
> wheel       0.35.1
> ```
> 
> @Zer0-dev115 What exactly are you trying to do? I would suggest posting on https://forum.opennmt.net/ which is a better place to ask general support questions.

How ca we run onmt_server from inside the docker? OpenNMT-py should be installed inside
