### ISSUE TITLE
The package published on PyPI does not support GPU

### ISSUE THREAD

**Issue by lsjiiia** [OpenNMT/CTranslate2#282]
I want to ask when the package published on PyPI will support GPU?

**Comment by huifengshiwu** [comment]
同问

**Comment by guillaumekln** [comment]
Thanks for opening this issue.

We don't have a specific date for that unfortunately. Most likely we first need to finish #178, otherwise the dependency management would be complex.

For now, you have 2 solutions:
* Use a GPU Docker image (e.g. `opennmt/ctranslate2:latest-ubuntu18-cuda10.2`): it includes the Python package with GPU support  
* Run translation on CPU: this is not really a solution but you can actually go pretty far with just a CPU (look into `inter_threads`, `intra_threads`, `max_batch_size`, `beam_size`, etc. to optimize for speed)

**Comment by lsjiiia** [comment]
Now my GPU Docker image have cuda and tensorRT, but it disconnect with network. 
I am new palyer of docker, i don't know how to write simple Dockerfile to compile.
thanks in advance!

**Comment by lsjiiia** [comment]
My dockerfile doesnot run.  the simple dockerfile:

FROM gpu_eurleros_trt as builder

WORKDIR /root/ctranslate2-dev

COPY third_party third_party
COPY cli cli
COPY include include
COPY src src
COPY CMakeLists.txt .


ARG CXX_FLAGS
ENV CXX_FLAGS=${CXX_FLAGS}
ARG CUDA_ARCH_LIST
ENV CUDA_ARCH_LIST=${CUDA_ARCH_LIST:-"Common"}
ENV CTRANSLATE2_ROOT=/root/ctranslate2

RUN mkdir build && \
    cd build && \
	source scl_source enable devtoolset-8 && \
	cmake -DCMAKE_INSTALL_PREFIX=${CTRANSLATE2_ROOT} \
	      -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DWITH_CUDA=ON -DWITH_MKL=OFF -DWITH_TENSORRT=ON  \
	      -DOPENMP_RUNTIME=NONE -DCUDA_ARCH_LIST="${CUDA_ARCH_LIST}" .. && \
    VERBOSE=1 make -j4 && \
    make install

**Comment by guillaumekln** [comment]
Why are you not using Docker images that are already built?

See https://hub.docker.com/r/opennmt/ctranslate2

**Comment by lsjiiia** [comment]
thanks a lot！ 
I try to start this image(centos7), but it prompt missing model.  is the model parameter necessary?
and how do i start the docker container and use python api

**Comment by lsjiiia** [comment]
I am very happy to see that you are preparing to publish ctranslate2 supporting gpu on pypi.  
Could you tell me when it will be released?  I want to use it to deploy our service,  thank you~

**Comment by guillaumekln** [comment]
The next version of the package will have an experimental GPU support. It should be released in a few days.

**Comment by guillaumekln** [comment]
You can try the latest version that is now available on PyPI. Please open a new issue if you find a bug.

**Comment by aj7tesh** [comment]
@guillaumekln 
to use gpu
translator = ctranslate2.Translator(
    model_path: str                 # Path to the CTranslate2 model directory.
    device: str = "cuda",            # The device to use: "cpu", "cuda", or "auto".
    device_index: int = 0,          # The index of the device to place this translator on.
    compute_type: str = "default"   # The computation type: "default", "int8", "int16", "float16", or "float",
                                    # or a dict mapping a device to a computation type.
    inter_threads: int = 1,         # Maximum number of parallel translations (CPU only).
    intra_threads: int = 4)  

in the above funtion we need to change device = "cuda
is that it or some other changes? I am using ctranslate2 as pypi package

**Comment by guillaumekln** [comment]
No other changes.

**Comment by lsjiiia** [comment]
> You can try the latest version that is now available on PyPI. Please open a new issue if you find a bug.

Thanks in advance!
But our deploy environment just support cuda=10.0,  could you publish Compile Python wheels with CUDA 10.0 on PyPi~

**Comment by guillaumekln** [comment]
CUDA 10.0 is no longer supported by both PyTorch and TensorFlow so I don't see why we would downgrade.

The package does not need CUDA 10.1 installed. It just needs a GPU driver >= 418.39. Can you check that?

**Comment by lsjiiia** [comment]
When I loaded the model(translator = ctranslate2.Translator(model_path, device='cuda', inter_threads=inter_threads, intra_threads=intra_threads)), 
I encountered this error:
	RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version
	
my gpu driver: 410.104  cuda version: 10.0

**Comment by lsjiiia** [comment]
Or Could you send me a python(cp36 and cp37) wheel that supports cuda10.0? thanks in advance!

**Comment by guillaumekln** [comment]
I don't think I will do more work here since it is easier to update your GPU driver. If you can't easily update your production server, you should probably use Docker by now, and we do provide a Docker image using CUDA 10.0.

Also, this is not recommended but you can also copy the wheel out of the Docker image and install it on the host system. See an example [here](https://forum.opennmt.net/t/ctranslate2-in-python/3149/4?u=guillaumekln).

**Comment by lsjiiia** [comment]
ok, i will try it. thanks a lot!

**Comment by lsjiiia** [comment]
I'm here to disturb you again~ now my environment is (gpu driver: 410.104, cuda version: 10.0, cpython3.7), i don't find suitable docker image or python wheel.

**Comment by lsjiiia** [comment]
could you send the suitable python wheel to my email?  thanks in advance~

**Comment by guillaumekln** [comment]
Sorry, I can't build a different package for every user.

See the README for instructions to build the project:

* core library: https://github.com/OpenNMT/CTranslate2#example-ubuntu
* Python package: https://github.com/OpenNMT/CTranslate2#python

**Comment by lsjiiia** [comment]
Thanks for your patience

**Comment by lsjiiia** [comment]
> I don't think I will do more work here since it is easier to update your GPU driver. If you can't easily update your production server, you should probably use Docker by now, and we do provide a Docker image using CUDA 10.0.
> 
> Also, this is not recommended but you can also copy the wheel out of the Docker image and install it on the host system. See an example [here](https://forum.opennmt.net/t/ctranslate2-in-python/3149/4?u=guillaumekln).

I'm here to disturb you again. when I extract the ctranslate2 wheel from gpu docker image then move it to other machine and install. it encountered an error when i start server:
AttributeError: module 'ctranslate2' has no attribute 'Translator'

**Comment by guillaumekln** [comment]
Please post your question on the [forum](https://forum.opennmt.net/). It is not related to the current issue.

**Comment by lsjiiia** [comment]
thanks. I also create account and need to wait for a staff member reviews my posts

**Comment by lsjiiia** [comment]
I have post my question to [https://forum.opennmt.net/t/install-ctranslate2-wheel-from-gpu-docker-image/4050](url)

**Comment by lsjiiia** [comment]
[https://forum.opennmt.net/t/install-ctranslate2-wheel-from-gpu-docker-image/4050](url)
