### ISSUE TITLE
Docker and import Python

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/CTranslate2#300]
Hi,

If I want to use OpenNMT server with ctranslate2 how can I install Ctranslate2 in order to work? It should be in the virtual environment, shouldn't it? Is it possible to install it with the docker or do I need to install it manually?

Thanks

**Comment by guillaumekln** [comment]
Can you be more specific about your issue?

You can install CTranslate2 with just `pip install ctranslate2`.

**Comment by anderleich** [comment]
I want GPU support in CTranslate2 and be able to use OpenNMT-py's onmt_server command

**Comment by anderleich** [comment]
The following Dockerfile should fit my needs.  Thanks
```

FROM opennmt/ctranslate2:latest-ubuntu18-cuda10.2

RUN pip install OpenNMT-py

# Reset entrypoint
ENTRYPOINT []
```

**Comment by guillaumekln** [comment]
Looks like the error is pretty clear. See here for the required driver version: https://docs.nvidia.com/deploy/cuda-compatibility/index.html (Table 1)

**Comment by anderleich** [comment]
Aren't the drivers installed? I didn't find this explained in the documentation

**Comment by guillaumekln** [comment]
There are many resources online explaining how to run Docker with GPU support.

Here's one from the official website: https://docs.docker.com/config/containers/resource_constraints/#access-an-nvidia-gpu

**Comment by anderleich** [comment]
Ok, thanks for your time and information! I finally managed to install everything.

**Comment by anderleich** [comment]
It might not be related but, when I set the entrypoint in exec mode:
`ENTRYPOINT ["onmt_server"]`
 I get an encoding issue:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 396: ordinal not in range(128)`

However, when executing in shell form
`ENTRYPOINT onmt_server`
 it works perfectly. Any guess?

**Comment by aj7tesh** [comment]
@anderleich @guillaumekln 
Below is my Dockerfile

FROM opennmt/ctranslate2:latest-ubuntu18-cuda10.2
COPY / /app
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY start.sh /usr/bin/start.sh
RUN chmod +x /usr/bin/start.sh
CMD ["python", "/app/app.py"]


when I am trying to run built my image it is giving error as "missing model"

However when I run like below
FROM python:3.6.9
COPY / /app
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY start.sh /usr/bin/start.sh
RUN chmod +x /usr/bin/start.sh
CMD ["python", "/app/app.py"]

It work fine.
In this case ctranslate2 package is in my requirements.txt file.

What could be the issue?

**Comment by guillaumekln** [comment]
> when I am trying to run built my image it is giving error as "missing model"

Use `ENTRYPOINT` instead of `CMD` to override the image entrypoint. The default entrypoint of the image is defined here: 

https://github.com/OpenNMT/CTranslate2/blob/master/docker/Dockerfile.ubuntu-gpu#L116

**Comment by anderleich** [comment]
Hi
I have another issue. How should I configure Apache to serve the `onmt_server`? I guess I need Apache or similar to run it in production... Should I configure Apache inside the docker?
Thanks

**Comment by guillaumekln** [comment]
This is unrelated to CTranslate2 so you should probably ask this question elsewhere. You can try asking on the [forum](https://forum.opennmt.net/)

**Comment by aj7tesh** [comment]
> to override the image entrypoint.

When I use ENTRYPOINT instead CMD in Dockerfile:

FROM opennmt/ctranslate2:latest-ubuntu18-cuda11.0
COPY / /app
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip3 install -r src/requirements.txt
ENTRYPOINT ["python", "/app/src/app.py"]

I get below errror
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled 
@guillaumekln

**Comment by aj7tesh** [comment]
@guillaumekln 
Getting this error
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

Although I have the latest driver NVIDIA-SMI 455.32.00    Driver Version: 455.32.00 
I am using below Dockerfile

FROM opennmt/ctranslate2:latest-ubuntu18-cuda11.0
COPY / /app
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip3 install -r src/requirements.txt
ENTRYPOINT ["python3", "/app/src/app.py"]

**Comment by aj7tesh** [comment]
@guillaumekln  
the python version in this image opennmt/ctranslate2:1.16.2-ubuntu18-cuda11.0
does not support perl based command?? is it slim version?

Below one works fine for me
FROM python:3.6.9

**Comment by guillaumekln** [comment]
Only the components required to run CTranslate2 are installed in the image.

You can install additional packages by extending the CTranslate2 image. First, create a new `Dockerfile` for example:

```text
FROM opennmt/ctranslate2:1.16.2-ubuntu18-cuda11.0
RUN apt-get update && apt-get install -y perl
```

Then build it.
