### ISSUE TITLE
About alignment

### ISSUE THREAD

**Issue by copperdong** [OpenNMT/CTranslate2#313]
Hi, CTranslate2 plans to support "alignment"? Thanks

**Comment by guillaumekln** [comment]
The API already returns some attention weights. Currently, it can return the weights from the first attention head of the last decoder layer. This is compatible with the [guided alignment](https://opennmt.net/OpenNMT-tf/alignments.html) feature of OpenNMT-tf.

See `return_attention` in the [translation API](https://github.com/OpenNMT/CTranslate2/blob/master/docs/python.md#translation-api).

**Comment by copperdong** [comment]
> The API already returns some attention weights. Currently, it can return the weights from the first attention head of the last decoder layer. This is compatible with the [guided alignment](https://opennmt.net/OpenNMT-tf/alignments.html) feature of OpenNMT-tf.
> 
> See `return_attention` in the [translation API](https://github.com/OpenNMT/CTranslate2/blob/master/docs/python.md#translation-api).

Oh, Thanks!

**Comment by robinp** [comment]
For posterity: https://github.com/OpenNMT/CTranslate2/issues/565 made this configurable and the model conversion allegedly takes it into account, if specified by the original model.
