### ISSUE TITLE
MKL and DNNL paths have changed in oneAPI Base toolkit 

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#341]
It seems MKL and DNNL are now included in Intel's oneAPI toolkit and the paths are now different than the ones in `CMakeLists.txt`. All stuff is now installed under `Intel/oneAPI` instead of `IntelSWTools`. I could modify the `CMakeLists.txt` but I guess we have to also keep the old paths for older versions, right?

**Comment by guillaumekln** [comment]
Modifying the CMakeLists may not be required. You should be able to set different search paths using [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html), e.g.:

```
cmake -DCMAKE_PREFIX_PATH="<mkl_path>;<dnnl_path>" ..
```

**Comment by panosk** [comment]
OK, thanks!

**Comment by guillaumekln** [comment]
Actually if you have some time, I would indeed accept a PR that updates the paths on Windows to make it work with the new oneAPI toolkit. I just did that for Linux in #345.

Ideally it should also work with the previous paths but it is not a strong requirement for Windows. Let me know.

**Comment by panosk** [comment]
Sure, I'll work on that!
