### ISSUE TITLE
Replicating optimizations mentioned in WNGT20 paper.

### ISSUE THREAD

**Issue by Raghava14** [OpenNMT/CTranslate2#343]
Hi the results and optimizations mentioned in the paper [Efficient and High-Quality Neural Machine Translation with OpenNMT](https://www.aclweb.org/anthology/2020.ngt-1.25.pdf) are very interesting. I would like to experiment with  the optimizations you mentioned in the paper (discussed in table 5 and section 3). Are these optimizations implemented as a part of ctranslate2 ? From what I searched they are not, correct me if I am wrong. Can you let me know how to replicate the optimizations.
Thanks in advance.

**Comment by guillaumekln** [comment]
Hi,

All optimizations mentioned in the paper are implemented in CTranslate2. We actually provide the Dockerfile and code that were used for the WNGT 2020 submissions:

https://github.com/OpenNMT/CTranslate2/tree/master/examples/wngt2020

**Comment by Raghava14** [comment]
Hi thanks for the reply, so this is how these are done right 
1. int8 quantization : should be called explicitly [here](https://github.com/OpenNMT/CTranslate2/blob/master/docs/python.md#model-conversion-api) by passing `quantization=int8`
2. local sorting: need not be explicitly called and is implemented by default in ctranslate2 as mentioned  [here](https://github.com/OpenNMT/CTranslate2/pull/324)
3. packed GEMM : can you please point me to the location where this is done. Is it implemented by default in ctranslate2 ?
4. vocabulary reduction : So here we get alignments using  fast_align from a large corpus and create a vocabulary with source and target tokens  based on alignments  and pass the vocabulary file as `vmap` argument [here](https://github.com/OpenNMT/CTranslate2/blob/master/docs/python.md#model-conversion-api) Can you  elaborate a bit more on this like what is the format of the vmap file and did you use the whole data for training the fast-align model etc 
5. Decoder projections caching : implemented by default during translation, can you please point me to the relevant code.
6. How can I use the files you mentioned in https://github.com/OpenNMT/CTranslate2/tree/master/examples/wngt2020 . I trained a model in OpenNMT-Py for translation and used this for conversion 
```
ct2-opennmt-py-converter --model_path checkpoint.pt --model_spec TransformerBase \
    --output_dir converted_int8_dir --quantization int8
```

Thank you for your patience.

**Comment by guillaumekln** [comment]
All items are either mentioned in the README or in the documentation.

1. Yes.
1. There are 2 ways to enable local sorting:
   * When using `translate_batch` set `max_batch_size` > `len(source)`
   * When using `translate_file` set `read_batch_size` > `max_batch_size`
1. Packed GEMM should be enabled via an environment variable. See the [related documentation](https://github.com/OpenNMT/CTranslate2/blob/master/docs/performance.md#packed-gemm). You can also search the code for "pack" for implementation details.
1. These [scripts](https://github.com/OpenNMT/papers/tree/master/WNMT2018/vmap) can be used to generate the vmap file. During translation you should set the option `use_vmap` to enable it.
1. Look for `cached_keys` and `cached_values` in the [code](https://github.com/OpenNMT/CTranslate2/blob/v1.16.2/src/layers/attention.cc#L161).
1. If you already trained and converted a model, you can directly use a [translation client](https://github.com/OpenNMT/CTranslate2#translating) and set the options that you need (see for examples the options set in [main.cc](https://github.com/OpenNMT/CTranslate2/blob/v1.16.2/examples/wngt2020/main.cc) from WNGT 2020).

**Comment by Raghava14** [comment]
Thanks! I am trying these will reopen in case of any issues.
