### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by aj7tesh** [OpenNMT/CTranslate2#347]
On the Readme benchmark section it is written  that enlish german model trained using Opennmt-py and interference generated using ctranslate2 gives throughput of 537 tokens per sec on c5.2xlarge machine.
Does that mean below sentence  should take 0.0074 sec to translate??
"▁H", "ello", "▁world", "!"

Actually I am testing the same model on i5 16 gb ram CPU system and on an average it is taking 0.076 sec per token translation. (~14 tokens per second) which is way slower than your benchmarks. 
Is it due the system only or some part I am missing.?
I am running
>>> import ctranslate2
>>> translator = ctranslate2.Translator("ende_ctranslate2/")
>>> translator.translate_batch([["▁H", "ello", "▁world", "!"]])

**Comment by guillaumekln** [comment]
Please read the note in **bold** in the benchmark section:

> **Please note that the results presented below are only valid for the configuration used during this benchmark: absolute and relative performance may change with different settings.**

So the benchmark that you run can not be compared to the numbers presented in the README since execution settings are very different.

You can re-run the [benchmark script](https://github.com/OpenNMT/CTranslate2/tree/master/tools/benchmark) to get numbers for your system.

**Comment by Sujit27** [comment]
Does the benchmark metric 'Tokens per second' measure time for the translation_batch step or the whole tokenization + translation pipeline in your execution ?

**Comment by guillaumekln** [comment]
The metric does not include the tokenization. We only want to benchmark and compare the actual model performance.

**Comment by aj7tesh** [comment]
@guillaumekln 
When we are keeping the batch_type as "examples", i.e sending source list
then in this case the order of the ouput is always same as that of source input list.? Means the same indices of each sentence in source list and output list ?

**Comment by guillaumekln** [comment]
Yes, the sentence order is always preserved.

**Comment by aj7tesh** [comment]
thank you
