### ISSUE TITLE
vectorized_map_reduce_all returns incorrect result If array size is larger than vector length

### ISSUE THREAD

**Issue by keichi** [OpenNMT/CTranslate2#351]
Here is the issue:

https://github.com/OpenNMT/CTranslate2/blob/89382b1ce68d28e401a60dbb25e33dcc096df091/src/cpu/kernels.cc#L84-L90

If `size` is indivisible by `Vec<T, ISA>::width`, `width` becomes smaller than `Vec<T, ISA>::width` in the last remainder iteration. However, the above code ignores this fact and uses the whole vector to do the map and reduce.

**Comment by keichi** [comment]
Here is a test case to reproduce this issue. It passes if the generic backend is forced via `CT2_FORCE_CPU_ISA=GENERIC` but doesn't pass with AVX or AVX2.

```cpp
TEST_P(OpDeviceFPTest, LogSoftMax) {
  const Device device = GetParam().first;
  const DataType dtype = GetParam().second;
  StorageView x({2, 10}, std::vector<float>{
      -0.2, 3.0, 1.2, -1.1, 0.0, 0.2, -3.0, -1.2, 1.1, 0.0,
      4.6, 3.3, 0.2, -1.6, 1.0, -4.6, -3.3, -0.2, 1.6, -1.0}, device);
  StorageView expected({2, 10}, std::vector<float>{
      -3.638294, -0.438294, -2.238294, -4.538294, -3.438294, -3.238294, -6.438294, -4.638294, -2.338294, -3.438294,
      -0.319434, -1.619434, -4.719434, -6.519434, -3.919434, -9.519434, -8.219434, -5.119434, -3.319434, -5.919434}, device);
  StorageView y(dtype, device);
  ops::LogSoftMax()(x.to(dtype), y);
  expect_storage_eq(y.to_float(), expected, 1e-2);
}
```

**Comment by guillaumekln** [comment]
Thanks for reporting!

Looks like we need to process the remaining elements in a separate loop. Do you want to send a PR?

**Comment by keichi** [comment]
Sure, I can open a PR. Which one do you prefer?

1. Add a new argument to `vectorized_iter()` that receives the scalar version of the functor and perform the scalar remainder loop in  `vectorized_iter()`.
2. Treat this as a special case and perform the scalar remainder loop in `vectorized_map_reduce_all()`

**Comment by guillaumekln** [comment]
I would prefer 2. for now.
