### ISSUE TITLE
issue in the installation of  ctranslate2 with pip

### ISSUE THREAD

**Issue by younesaitmha** [OpenNMT/CTranslate2#353]
ERROR: Could not find a version that satisfies the requirement ctranslate2==1.16.2
ERROR: No matching distribution found for ctranslate2==1.16.2

**Comment by keichi** [comment]
Are you running macOS or Windows? Currently, CTranslate2 only provides wheels for Linux.

**Comment by eadmaster** [comment]
i am on Ubuntu Bionic and got the same error, i've also tried installing manually via the wheel:
````
$ pip3 install ctranslate2-1.16.2-cp36-cp36m-manylinux2010_x86_64.whl 

ctranslate2-1.16.2-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform.
````

**Comment by guillaumekln** [comment]
What is your `pip` version? The wheel requires `pip` >= 19.0.

**Comment by eadmaster** [comment]
ok, after upgrading pip with `pip3 install --upgrade pip` it installed correctly.

**Comment by PJ-Finlay** [comment]
Are there any plans to publish wheels for MacOS or Windows?

**Comment by PJ-Finlay** [comment]
Nevermind I see #133

**Comment by guillaumekln** [comment]
@younesaitmha Did you find a solution for your problem in this thread?

**Comment by younesaitmha** [comment]
yes i switched from macOs to linux and it works 
please i wanna know if there is plans to make wheels fro macOs i wanna contribute

**Comment by guillaumekln** [comment]
macOS support is tracked by #133.
