### ISSUE TITLE
Compilation issues with MSVC

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#370]
Compilation with MSVC is no longer successful. I was able to spot this in `cpu_isa.h`:

```C++
#define SINGLE_ARG(...) __VA_ARGS__
#ifdef CT2_WITH_CPU_DISPATCH
#if defined(__x86_64__)
#  define CPU_ISA_DISPATCH(STMTS)                             \
  switch (cpu::get_cpu_isa()) {                               \
    CPU_ISA_CASE(cpu::CpuIsa::AVX2, SINGLE_ARG(STMTS))        \
    CPU_ISA_CASE(cpu::CpuIsa::AVX, SINGLE_ARG(STMTS))         \
    CPU_ISA_DEFAULT(cpu::CpuIsa::GENERIC, SINGLE_ARG(STMTS))  \
  }
```
which leaves `CPU_ISA_DISPATCH` undefined in `dequantize_cpu.cc`. The following patch seems to fix this and moves compilation further

```C++
< #if defined(__x86_64__)

> #if defined(__x86_64__) || defined( _WIN64)
```

But then it fails with a ton of unresolved external symbol linker errors.

I will look further into this during the weekend.

**Comment by guillaumekln** [comment]
Thanks for reporting!

Let's add a minimal Windows job in the CI to catch these compilation errors. I did that in the linked PR and fixed the compilation.
