### ISSUE TITLE
Convert Transformer model with shared embeddings

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#401]
Hi,

Do I have to create a custom converter through the Python API if I want to convert a transformer model trained with shared embeddings? Alternatively, is OpenNMT-tf able to export such a model in CTranslate2 format during training?

Thanks!

**Comment by guillaumekln** [comment]
Hi,

Shared embeddings do not need a custom converter. They are detected automatically. So you should not need to do anything, whether you are using a conversion script or OpenNMT-tf export.

**Comment by panosk** [comment]
Thanks for the quick reply. To be precise, I'm puzzled with the transformer spec and how should I pass it to `ct2-opennmt-tf-converter`: In order to train a TransformerBig with shared embeddings, I should use a custom model definition, for example [transformer_shared_embedding.py](https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/transformer_shared_embedding.py). So, as long as the values in the custom model definition match these of the TransformerBig specifications, I can just define `--model_spec TransformerBig` in the conversion script and all is good?

**Comment by guillaumekln** [comment]
In CTranslate2 the model specification is the same whether embeddings are shared or not. So if you defined a custom model like transformer_shared_embedding.py with the sizes of a "big" Transformer (num_units=1024, num_heads=16, ffn_inner_dim=4096), you can use `--model_spec TransformerBig` during conversion.

Alternatively, you can rely on OpenNMT-tf export to not have to deal with model specifications.

**Comment by panosk** [comment]
Great, thanks a lot!
