### ISSUE TITLE
pip install ctranslate2 error

### ISSUE THREAD

**Issue by ZiBinNGUP** [OpenNMT/CTranslate2#405]
> pip install ctranslate2
ERROR: Could not find a version that satisfies the requirement ctranslate2
ERROR: No matching distribution found for ctranslate2

What's happen?pls.

**Comment by guillaumekln** [comment]
Try updating the `pip` package:

```
pip install --upgrade pip
```

If that does not work, please describe the system where you are trying to install CTranslate2 (OS, processor, etc.).

**Comment by ZiBinNGUP** [comment]
Thank your answer, but It does not work.
OS:windows 10, Python version:3.8.5.

**Comment by guillaumekln** [comment]
Please read the README before opening a new issue. It is said that the published Python package requires Linux or macOS:

https://github.com/OpenNMT/CTranslate2#python-package

**Comment by yywing** [comment]
python version: 3.6.9
pip version: 21.3.1

uname -a
`Linux iZbp1978lespq3h2zzqh4qZ 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:47:36 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`



got 
`Could not find a version that satisfies the requirement ctranslate2`

**Comment by guillaumekln** [comment]
Currently, there is no prebuilt binaries for AArch64 and users should compile from the sources.

The list of published Python wheels can be found on PyPI: https://pypi.org/project/ctranslate2/#files

**Comment by neverdimed** [comment]
i see this error with:
ubuntu 18.04
pip 9.0.1
python 2.7.17

i guess my system is just too old?

**Comment by guillaumekln** [comment]
You can now find the requirements in the [documentation website](https://opennmt.net/CTranslate2/installation.html#install-with-pip). In particular:

> * Python version: >= 3.6
> * pip version: >= 19.3
