### ISSUE TITLE
compilation error with MKL-DNN

### ISSUE THREAD

**Issue by mtu** [OpenNMT/CTranslate2#41]
Hi, I try to compile with MKL-DNN, but the following error occurs：
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc: In static member function 'static void ctranslate2::primitives<D>::gemm(const In*, const In*, bool, bool, size_t, size_t, size_t, float, float, Out*) [with In = signed char; Out = int; ctranslate2::Device D = (ctranslate2::Device)0; size_t = long unsigned int]':
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc:546:39: error: invalid conversion from 'const char*' to 'char' [-fpermissive]
                           c, &ldc, &co),
                                       ^
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc:546:39: error: invalid conversion from 'const char*' to 'char' [-fpermissive]
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc:546:39: error: invalid conversion from 'const char*' to 'char' [-fpermissive]
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc:546:39: error: invalid conversion from 'int*' to 'dnnl_dim_t {aka long int}' [-fpermissive]
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc:546:39: error: invalid conversion from 'int*' to 'dnnl_dim_t {aka long int}' [-fpermissive]
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc:546:39: error: invalid conversion from 'int*' to 'dnnl_dim_t {aka long int}' [-fpermissive]
/data/work/c-translator/CTranslate2-1.2.0/src/primitives/cpu.cc:546:39: error: cannot convert 'float*' to 'float' for argument '7' to 'dnnl_status_t dnnl_gemm_s8s8s32(char, char, char, dnnl_dim_t, dnnl_dim_t, dnnl_dim_t, float, const int8_t*, dnnl_dim_t, int8_t, const int8_t*, dnnl_dim_t, int8_t, float, int32_t*, dnnl_dim_t, const int32_t*)'
CMakeFiles/ctranslate2.dir/build.make:758: recipe for target 'CMakeFiles/ctranslate2.dir/src/primitives/cpu.cc.o' failed
make[2]: *** [CMakeFiles/ctranslate2.dir/src/primitives/cpu.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ctranslate2.dir/all' failed
make[1]: *** [CMakeFiles/ctranslate2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
================================================
The related infos. are :
MKL > 2019.5
MKL-DNN: 1.1.1

**Comment by guillaumekln** [comment]
Please have a look at the dependencies: https://github.com/OpenNMT/CTranslate2#dependencies

The project currently requires MKL-DNN 0.x and not the latest version.

**Comment by mtu** [comment]
It solved, thanks.
I use MKL-DNN 0.21.2 .
I translate some sentences, and get the following results,
============================================================
int8 cost 185.15305924415588s
int16 cost 2.5031533241271973s
float cost 3.605872869491577s
============================================================
It seems the int8 mode cost much more time than int16 and float mode.
Is it weird ?

**Comment by guillaumekln** [comment]
Did you link MKL-DNN with MKL? If not, int8 is only optimized on CPUs supporting AVX512.

See [MKL-DNN documentation](https://github.com/intel/mkl-dnn/tree/rls-v0.21#using-intel-mkl-optional) or the [Ubuntu Dockerfile](https://github.com/OpenNMT/CTranslate2/blob/v1.2.1/docker/Dockerfile.ubuntu#L37-L47) to link against MKL.

**Comment by mtu** [comment]
thanks, I will try and report the result.

**Comment by mtu** [comment]
I rebuilt the MKL-DNN with MKL, and verified MKL-DNN with its official examples.
Then rebuilt c-translator with the newly generated MKL-DNN.
The results are:
int8 cost 52.733083963394165s
int16 cost 2.9197397232055664s
float cost 3.4072117805480957s
===========================================================
int8 costs less time than last time, but still much more than int16/float.

**Comment by guillaumekln** [comment]
What are you running exactly? As a general recommendation, make sure to translate a large enough test set and compare "tokens per second" as reported by the `--log_throughput` option.

You should also compare with the official Docker images which produced the [benchmark numbers](https://github.com/OpenNMT/CTranslate2#speed) from the readme.

**Comment by mtu** [comment]
==============INT16=========================
./translate --model ../../tests/data/models/v2/int16 --src ../../tests/data/tst/zh --batch_size 1 --compute_type int16 --max_sent_length 20 --log_throughput
To go directly to someone or something as soon as you arrive <\s> 10 in the rain or something as
I got to the party and made a be@@ eline for Susan . <\s> . <\s> now . <\s> .
He made a be@@ eline for the booth as soon as he arrived . <\s> now he arrived . <\s>
To get ride of everything or everyone to start a new <\s> him or everyone to start a new <\s>
The police made a clean sweep of the area by arre@@ sting everyone . <\s> es of them to imagine
To become successful again after having been away from the scene or society for a long time <\s> now .
The little girl made a scene every time her mother did n't immediately buy her what she wanted . <\s>
You 'll have to make a come@@ back and take over the company . <\s> time the now . <\s>
Con@@ tor@@ t your face , make a strange expression often used with ' at someone ' <\s> them .
She t@@ asted the soup and made a face . <\s> caught him a face . <\s> now . <\s>
100

==============FLOAT=========================
./translate --model ../../tests/data/models/v2/float32 --src ../../tests/data/tst/zh --batch_size 1 --compute_type float --max_sent_length 20 --log_throughput
To go directly to someone or something as soon as you arrive <\s> 10 in the rain or something as
I got to the party and made a be@@ eline for Susan . <\s> . <\s> now . <\s> .
He made a be@@ eline for the booth as soon as he arrived . <\s> now he arrived . <\s>
To get ride of everything or everyone to start a new <\s> him or everyone to start a new <\s>
The police made a clean sweep of the area by arre@@ sting everyone . <\s> es of them to imagine
To become successful again after having been away from the scene or society for a long time <\s> now .
The little girl made a scene every time her mother did n't immediately buy her what she wanted . <\s>
You 'll have to make a come@@ back and take over the company . <\s> time the now . <\s>
Con@@ tor@@ t your face , make a strange expression often used with ' at someone ' <\s> them .
She t@@ asted the soup and made a face . <\s> caught him a face . <\s> now . <\s>
66.6667

==============INT8=========================
 ./translate --model ../../tests/data/models/v2/int8 --src ../../tests/data/tst/zh --batch_size 1 --compute_type int8 --max_sent_length 20 --log_throughput
To go directly to someone or something as soon as you arrive <\s> 10 in the rain or something as
I got to the party and made a be@@ eline for Susan . <\s> . <\s> now . <\s> .
He made a be@@ eline for the booth as soon as he arrived . <\s> now he arrived . <\s>
To get ride of everything or everyone to start a new <\s> him or everyone to start a new <\s>
The police made a clean sweep of the area by arre@@ sting everyone . <\s> es of them to imagine
To become successful again after having been away from the scene or society for a long time <\s> now .
The little girl made a scene every time her mother did n't immediately buy her what she wanted . <\s>
You 'll have to make a come@@ back and take over the company . <\s> time the now . <\s>
Con@@ tor@@ t your face , make a strange expression often used with ' at someone ' <\s> them .
She t@@ asted the soup and made a face . <\s> caught him a face . <\s> now . <\s>
4.87805

==========================================================
The speed computed by --log_throughput option can roughly match the latency I reported above.
int8 v.s. int16 v.s float
latency: 52s v.s. 2.9s v.s 3.4s
speed:  4.9 v.s. 100 v.s. 66.7

==========================================================
Maybe the MKL-DNN is not well supported by our hardware.
So if I want to modify/improve the int8 gemm part of the codes with other libraries, could  you give some suggestions about it (e.g library/methods,  anything is welcomed) ?

**Comment by guillaumekln** [comment]
The int8 GEMM is located here: https://github.com/OpenNMT/CTranslate2/blob/v1.2.1/src/primitives/cpu.cc#L514-L551

**Comment by mtu** [comment]
Thanks
