### ISSUE TITLE
Potential GPU memory leak?

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#426]
Hi @guillaumekln 
While stress testing some components, I stumbled upon what looks like a GPU memory leak.
To reproduce:
```python
from ctranslate2 import Translator
import GPUtil
translators = []
for i in range(10):
    print(GPUtil.getGPUs()[0].memoryUsed)
    translator = Translator("model1", device="cuda", device_index=0)
    translators.append(translator)
    translator.translate_batch([["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]]*32)
    translator.unload_model(to_cpu=True)
```
OUTPUT:
```
4.0
547.0
715.0
881.0
1049.0
1215.0
1383.0
1551.0
1717.0
1885.0
```
---> GPU memory is not fully released.

With enough iterations of such load/unload, the GPU memory ends up full.
Is it expected to retain some objects in GPU memory when unloading to CPU?
If not, do you have any idea where this behavior could come from?
I'm testing with the `1.18.3-ubuntu18-cuda10.1` docker image. (Tested cuda 11.0 as well, with the same behavior.)
Thanks!

**Comment by francoishernandez** [comment]
Same sample code but with `opennmt/ctranslate2:1.17.0-ubuntu18-cuda11.0`:
```
1.0
413.0
427.0
435.0
443.0
453.0
459.0
469.0
477.0
487.0
```

**Comment by francoishernandez** [comment]
It looks like this was introduced with `1.18.0`, probably linked to the multi-GPU feature?

**Comment by guillaumekln** [comment]
Hi François,

Thanks for testing that.

This behavior was indeed introduced in 1.18. Each translator now has its own memory allocator and associated cache (for performance reasons). When the translator is used, its own cache will be initialized and use about ~200MB of memory. We should clear this cache when `unload_model` is called.
