### ISSUE TITLE
Ctranslate2 on NVIDIA Jetson

### ISSUE THREAD

**Issue by neso613** [OpenNMT/CTranslate2#440]
I am trying to get Ctranslate2 on GPU(Nvidia Jetson).
For this I tried to compile
But stuck with this error - 
`-- Compiling for multiple CPU ISA and enabling runtime dispatch
-- A library with BLAS API found.
-- Autodetected CUDA architecture(s): 7.2
-- NVCC compilation flags: -std=c++11;-gencode;arch=compute_72,code=sm_72
-- Found CUB include directory: /home/gpu-ctranslate/CTranslate2/third_party/cub
-- Found Thrust include directory: /home/gpu-ctranslate/CTranslate2/third_party/thrust
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
linked by target "ctranslate2" in directory /home/gpu-ctranslate/CTranslate2

-- Configuring incomplete, errors occurred!
See also "/home/gpu-ctranslate/CTranslate2/CMakeFiles/CMakeOutput.log".
See also "/home/gpu-ctranslate/CTranslate2/CMakeFiles/CMakeError.log".

what I have to add more.`

**Comment by guillaumekln** [comment]
How did you install the CUDA toolkit?

**Comment by neso613** [comment]
> CUDA toolkit

CUDA is there.
nvcc: NVIDIA (R) Cuda compiler driver
Built on Wed_Oct_23_21:14:42_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by guillaumekln** [comment]
Is the cuBLAS library installed? If yes, can you check where it is installed?

**Comment by keichi** [comment]
I was able to reproduce this error on my Jetson Nano. Turns out it's an issue with old CMake versions. Once I switched to the latest CMake (3.20.0), I was able to configure and compile.

```
keichi@naist:~/CTranslate2/build$ /home/keichi/cmake-3.20.0-linux-aarch64/bin/cmake -DWITH_CUDA=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=COMP -DBUILD_TESTS=ON ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Compiling for multiple CPU ISA and enabling runtime dispatch
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Using OpenMP: /usr/lib/gcc/aarch64-linux-gnu/7/libgomp.so;/usr/lib/aarch64-linux-gnu/libpthread.so
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "10.0")
-- Autodetected CUDA architecture(s):  5.3
-- NVCC compilation flags:  -std=c++11 -Xcompiler=-fopenmp;-gencode;arch=compute_53,code=sm_53
-- Found CUB include directory: /home/keichi/CTranslate2/third_party/cub
-- Found Thrust include directory: /home/keichi/CTranslate2/third_party/thrust
-- Found Python: /usr/bin/python3.6 (found version "3.6.9") found components: Interpreter
-- Configuring done
-- Generating done
-- Build files have been written to: /home/keichi/CTranslate2/build
```

**Comment by neso613** [comment]
> I was able to reproduce this error on my Jetson Nano. Turns out it's an issue with old CMake versions. Once I switched to the latest CMake (3.20.0), I was able to configure and compile.
> 
> ```
> keichi@naist:~/CTranslate2/build$ /home/keichi/cmake-3.20.0-linux-aarch64/bin/cmake -DWITH_CUDA=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=COMP -DBUILD_TESTS=ON ..
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Compiling for multiple CPU ISA and enabling runtime dispatch
> -- Found OpenMP_C: -fopenmp (found version "4.5")
> -- Found OpenMP_CXX: -fopenmp (found version "4.5")
> -- Found OpenMP: TRUE (found version "4.5")
> -- Using OpenMP: /usr/lib/gcc/aarch64-linux-gnu/7/libgomp.so;/usr/lib/aarch64-linux-gnu/libpthread.so
> -- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "10.0")
> -- Autodetected CUDA architecture(s):  5.3
> -- NVCC compilation flags:  -std=c++11 -Xcompiler=-fopenmp;-gencode;arch=compute_53,code=sm_53
> -- Found CUB include directory: /home/keichi/CTranslate2/third_party/cub
> -- Found Thrust include directory: /home/keichi/CTranslate2/third_party/thrust
> -- Found Python: /usr/bin/python3.6 (found version "3.6.9") found components: Interpreter
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/keichi/CTranslate2/build
> ```

OHH!! I will try this and let you know.

**Comment by francoishernandez** [comment]
Hey @neso613 , once you get it working could you post a few benchmark numbers? I'm genuinely curious about how that would perform on such hardware.

**Comment by neso613** [comment]
> Hey @neso613 , once you get it working could you post a few benchmark numbers? I'm genuinely curious about how that would perform on such hardware.

@francoishernandez Compiled libctranslate2.so is 16M.
Thank you so much @keichi @guillaumekln for quick response.

**Comment by neso613** [comment]
Ctranslate2 is compiled but it not uses GPU.

**Comment by francoishernandez** [comment]
I was wondering about speed (throughput/latency) actually. I guess you would still have to distill quite a bit to get proper performance on such limited hardware.

**Comment by neso613** [comment]
> I was wondering about speed (throughput/latency) actually. I guess you would still have to distill quite a bit to get proper performance on such limited hardware.

Yes @francoishernandez You are right. I have to put more efforts. I expects latency in seconds if running on GPU.
