### ISSUE TITLE
Question about benchmark report (batch size impact)

### ISSUE THREAD

**Issue by gyin-ai** [OpenNMT/CTranslate2#441]
Since the batch_size is set as 32, does it mean tokens per second include 32 batch size output? Would it be different from batch size as 1 (common in production)? If it is different, do we have any result for that? Thanks a lot.

**Comment by guillaumekln** [comment]
> Since the batch_size is set as 32, does it mean tokens per second include 32 batch size output?

I'm not sure to understand what you mean here. Tokens per seconds is just the total number of generated tokens divided by the total time in seconds.

> Would it be different from batch size as 1 (common in production)? If it is different, do we have any result for that?

Yes, the results will be different with a different batch size.

It should be quite easy to run the benchmark with a different batch size: just edit the `BATCH_SIZE` value in [run.sh](https://github.com/OpenNMT/CTranslate2/blob/v1.19.0/tools/benchmark/run.sh#L7) and then follow the instructions in the [README](https://github.com/OpenNMT/CTranslate2/tree/master/tools/benchmark).

**Comment by gyin-ai** [comment]
if we set the batch_size as 32, it means 32 input sequences would be fed into the model. And then the number of generated tokens are from 32 output sequences. Is that right?

**Comment by guillaumekln** [comment]
We count the total number of tokens at the file level, so it does not change when you are using a different batch size. Only the total time will change in this case.

**Comment by gyin-ai** [comment]
Got it. Then a smaller batch size would need more time to generate the same number of input sentences. Hence the tokens per second would decrease.

**Comment by gyin-ai** [comment]
When I tried it in my local macOS laptop and set BATCH_SIZE=1 and BEAM_SIZE=1, it is wired that ctranslate2 int8 would be much slower than ctranslate2 float. (I used top 200 lines from wmt14-en-de.src and wmt14-en-de.tgt to speed up test)

```
cpu-ctranslate2-float;27.25;125.6;450;0
cpu-ctranslate2-float;27.25;123.1;465;0
cpu-ctranslate2-int8;27.21;26.7;176;0
cpu-ctranslate2-int8;27.21;26.7;176;0
```

Any suggestion or idea on it? @guillaumekln Thanks a lot.

**Comment by guillaumekln** [comment]
Does your MacBook have an Intel CPU?

Here's the numbers I get on my Linux laptop with BATCH_SIZE=1 and BEAM_SIZE=1:

```text
cpu-ctranslate2-float;27.25;145.2;449;0
cpu-ctranslate2-int16;26.40;240.7;278;0
cpu-ctranslate2-int8;27.21;394.2;173;0
cpu-ctranslate2-int8-vmap;26.92;660.4;175;0
```

**Comment by gyin-ai** [comment]
Yes. My local MacBook CPU is `2.4 GHz 8-Core Intel Core i9`. I will try it on linux instance then.

**Comment by gyin-ai** [comment]
Personally, I think adding batch_size=1 CPU and GPU benchmark report in the document would be very instructive for production inference. Since many text generation services at the runtime would usually get one request query.

**Comment by guillaumekln** [comment]
> Since many text generation services at the runtime would usually get one request query.

In practice, these services usually batch the requests coming from different users. Typically the server waits for 1 to 10 milliseconds to aggregate incoming requests and then run batch translation.

**Comment by gyin-ai** [comment]
Right. It is like the batch scheduling in tf serving. I am still curious how we can derive the single client request latency. If we use batch size as 1, we can approximately calculate it as #target tokens per sentence * #latency per token. I am not sure about large batch size like 32.

**Comment by guillaumekln** [comment]
I think you should benchmark throughput and latency separately. For example a large batch size will increase the latency but also increase the throughput.

**Comment by gyin-ai** [comment]
Totally agree. That is a trade-off. Just wonder how fast the latency can be without considering the throughput.

**Comment by gyin-ai** [comment]
I still couldn't get the result on the linux instance (CPU benchmark). The ctranslate2 Dockerfile is `opennmt/ctranslate2:1.17.0-ubuntu18-cuda11.0`. Do I need to change it to anything else?

**Comment by gyin-ai** [comment]
`git submodule update --init` may be needed before docker image building section in README.md.

Otherwise, it would fail with the following error. `docker build -t opennmt/ctranslate2-local:ubuntu18-gpu-cuda11.0 -f docker/Dockerfile.ubuntu-gpu . --build-arg CUDA_VERSION=11.0`

```
#19 1.343 CMake Error at CMakeLists.txt:341 (message):
#19 1.343   CUB library not found
#19 1.343
#19 1.343
#19 1.344 -- Configuring incomplete, errors occurred!
#19 1.344 See also "/root/ctranslate2-dev/build/CMakeFiles/CMakeOutput.log".
#19 1.344 See also "/root/ctranslate2-dev/build/CMakeFiles/CMakeError.log".
```

**Comment by guillaumekln** [comment]
There should be no need to rebuild the Docker image or configure anything. For example, to get the CPU benchmark numbers in the README I typically just start a `c5.metal` instance on AWS with Ubuntu 18.04, then I install Docker and the benchmark requirements.

> (I used top 200 lines from wmt14-en-de.src and wmt14-en-de.tgt to speed up test)

Do you still have these local changes? Can you show what you changed exactly?

**Comment by gyin-ai** [comment]
I just truncated the test file to top 200 lines. 
`head -n 200 wmt14-en-de.src > wmt14-en-de-mini.src`
`head -n 200 wmt14-en-de.tgt > wmt14-en-de-mini.tgt`
Then I changed the python script's src and tgt to this small test file.

```
PREFIX="python3 benchmark.py --num_samples 1 --num_threads $NUM_THREADS --src wmt14-en-de-mini.src --tgt wmt14-en-de-mini.tgt --sp_model wmtende.model"
```

**Comment by gyin-ai** [comment]
@guillaumekln the CPU benchmark works for me now. But I have another problem with GPU benchmark in Tesla V100 32G. The float and int8 (slightly worse) have a very close performance 600 tokens/s for beam size 1. Any suggestion or idea? Thanks.

**Comment by guillaumekln** [comment]
> the CPU benchmark works for me now.

What did you change to make it work?

> But I have another problem with GPU benchmark in Tesla V100 32G. The float and int8 (slightly worse) have a very close performance 600 tokens/s for beam size 1. Any suggestion or idea? Thanks.

What is the batch size in this case?

**Comment by gyin-ai** [comment]
CPU: I just tried different instances and it is probably due to the CPU version.

GPU: the batch size is 1 as well.

**Comment by guillaumekln** [comment]
> GPU: the batch size is 1 as well.

Then the result is expected. Batching is very important for the GPU to receive enough work. Otherwise you are mostly paying the fixed price of interacting with the GPU and don't benefit much from quantization.

Still, the CTranslate2 GPU performance with batch_size=1 and beam_size=1 is much better than TensorFlow and PyTorch (~5x faster on a Tesla T4).
