### ISSUE TITLE
python3 docker image?

### ISSUE THREAD

**Issue by mali-nuist** [OpenNMT/CTranslate2#46]
All docker images in docker hub are python2 environemnt. What should i do if i want to build a docker image including python3 environment ?

**Comment by guillaumekln** [comment]
The Ubuntu Docker images include a Python 3 wheel. You can define a simple Dockerfile that installs Python 3 and this wheel:

```dockerfile
FROM opennmt/ctranslate2:1.2.1-ubuntu18-gpu
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3-pip && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install /opt/ctranslate2/*cp3*.whl
```

```bash
docker build -t ctranslate2-py3 -f Dockerfile .
```

**Comment by mali-nuist** [comment]
> The Ubuntu Docker images include a Python 3 wheel. You can define a simple Dockerfile that installs Python 3 and this wheel:
> 
> ```dockerfile
> FROM opennmt/ctranslate2:1.2.1-ubuntu18-gpu
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends python3-pip && \
>     rm -rf /var/lib/apt/lists/*
> RUN pip3 install /opt/ctranslate2/*cp3*.whl
> ```
> 
> ```shell
> docker build -t ctranslate2-py3 -f Dockerfile .
> ```

Tanks for you reply!  Best wishes!
