### ISSUE TITLE
Pull Request for Anti-Flicker Algorithm Implementation

### ISSUE THREAD

**Issue by scotfang** [OpenNMT/CTranslate2#473]
Hi,

I work for DiDi Research America, in a private NLP research lab headed by Kevin Knight.  Recently, I implemented the decoding algorithm described in [Re-Translation Strategies For Long Form, Simultaneous, Spoken Language Translation](https://arxiv.org/abs/1912.03393) within CTranslate2.

In a nutshell, this decoding algorithm reduces the number of corrections/erasures/modifications when performing real-time, incremental translation--e.g. streaming speech translation.  This reduces the "flicker" of streaming translations, and makes them easier to read.  For example, imagine we are translating into English as the target language, and the real-time incremental translations looks like this:
- Timestep 0: I desire 
- Timestep 1: I want a canine
- Timestep 2: I would like a dog to walk

You can see that the phrase changes significantly after each timestep.  On the other hand, if we decode using this "anti-flicker" algorithm, we might see something more like this:
- Timestep 0: I desire
- Timestep 1: I desire a canine
- Timestep 2: I desire a canine to walk

The advantage of this algorithm is that it produces much more readable captions in a speech translation system, as we've tested extensively within our lab.  The trade-off is that with less "flicker", the accuracy of the translations and BLEU score also go down.  However, as described in the paper, and realized by our own testing, this simple algorithm can improve flicker significantly (2-3x less word erasure) with small reductions in BLEU (<0.1, <0.5).

Our lab has found this algorithm very useful for speech translation applications, and would like to open-source it.  If you're interested in merging it into CTranslate2, you can take a look at my implementation, the main commit is [here](https://github.com/scotfang/biased_decoding/commit/8838e228aa3df365c610139d98e61f2ffea481b4).  I've added unittests and also tested extensively within applications in our lab.  It's written in a way such that the parallelization primitives and memory optimizations are preserved with doing "biased-decoding".  Note that the algorithm takes place within beam-search exclusively.

Please let me know your thoughts, this is the first time I've submitted a significant pull request to an open-source project, so I'm open to anything and feedback as well! Thanks!

**Comment by guillaumekln** [comment]
Hi,

Thank you for your interest in contributing! This feature sounds interesting and it looks like something we can include. I appreciate that you already implemented it and added several tests.

Would this be a one-time contribution or are you willing to maintain it in the future?

I see that you commit mentions "ops::Log() only supports FLOAT, not FLOAT16". It looks like something we can easily support. Maybe you can first open a PR for that and then look into opening another PR for the feature?

**Comment by scotfang** [comment]
Hi Guillaume,

Glad to hear you're interested, and I appreciate the prompt response!

Ideally it would be a one-time contribution, but maybe you can describe
what maintenance would look like?  I guess future changes to beam-search
might require revisions to this anti-flicker code?

I can look into extending ops::Log() to support FLOAT16.  So you're saying
implement Log() for FLOAT16 myself and submit a PR for that right?  Sorry
I'm really new to contributing to open-source projects and Git!

**Comment by scotfang** [comment]
I can be around to help with bugs/issues/support!

I will start working on a smaller PR for extending log to FLOAT16! Thanks
for the prompt responses again!

**Comment by scotfang** [comment]
Regarding how to proceed, should I clean up this [larger change](https://github.com/scotfang/biased_decoding/commit/8838e228aa3df365c610139d98e61f2ffea481b4), rebase, and submit a new pull request that implements the anti-flicker algorithm?

**Comment by guillaumekln** [comment]
Hi @scotfang, thanks for opening the PR! Sorry for the delay. I currently have a few days off so I will review your PR next week.

**Comment by scotfang** [comment]
No worries, thanks for the update!

**Comment by guillaumekln** [comment]
Merged: https://github.com/OpenNMT/CTranslate2/pull/476
