### ISSUE TITLE
What does compute_type parameter in ctranslate.translator () function mean

### ISSUE THREAD

**Issue by rkoystart** [OpenNMT/CTranslate2#498]
compute_type parameter says
```
 The computation type: "default", "auto", "int8", "int16", "float16", or "float",
    # or a dict mapping a device to a computation type.
```

So does that mean , even if we load a int 8 model , the computational type would be "default" (fp32) and for performing the computation in int8 for the int8 model, we need to specify the computational type as int8.

Please correct me if i my understanding is wrong.
Thanks in advance!!!!!!!!!!

**Comment by guillaumekln** [comment]
I just added a documentation about this: https://github.com/OpenNMT/CTranslate2/blob/master/docs/quantization.md

With "default", the int8 model will be run in int8. But there are exceptions depending on your system which are described in the link above.

**Comment by guillaumekln** [comment]
The document should answer the question. Closing this issue.
