### ISSUE TITLE
Support ONNX graphs

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/CTranslate2#5]
This is a general issue to discuss and track ONNX support.

The current limitation of the project is that only weights are extracted from pretrained models and the computation graph is redefined in the code itself. This could be mitigated by loading and executing ONNX graphs.

**Comment by neso613** [comment]
I am also looking forward for onnx support to transformer and fairseq models.

**Comment by guillaumekln** [comment]
What model architecture, which is not currently supported, are you looking to execute?

**Comment by neso613** [comment]
> What model architecture, which is not currently supported, are you looking to execute?

I am trying to convert opennmt-py transformer model into onnx.

**Comment by guillaumekln** [comment]
You should ask on the Fairseq repository for the ONNX conversion.

If you want to use CTranslate2, we already provide a Fairseq converter that does not use ONNX. See the converter script `ct2-fairseq-converter`.

**Comment by dearchill** [comment]
> You should ask on the Fairseq repository for the ONNX conversion.
> 
> If you want to use CTranslate2, we already provide a Fairseq converter that does not use ONNX. See the converter script `ct2-fairseq-converter`.

Hi, thank you for your kind reply. I have used _ct2-fairseq-converter_ to deploy models on the web, thanks for your great job to support fairseq. Now I'm trying to deploy on the mobiles. I need to convert to ONNX, but I can't do it successfully. I found the Fairseq repository discussions about this are quiet few, the official convert supported is TorchScript model instead which didn't match our need. So I search in the github and then found ONNX support is also your future plans.

**Comment by guillaumekln** [comment]
Note that this issue is not about converting to ONNX but being able to load ONNX graphs and run them with CTranslate2. In that case you would still need to get CTranslate2 to run on mobile.

**Comment by dearchill** [comment]
Sorry, I made a mistake. I'll figure out how to convert then.

**Comment by guillaumekln** [comment]
I'm closing this issue as this is no longer something we plan to do. There is already mainstream solutions like [onnxruntime](https://github.com/microsoft/onnxruntime) to run ONNX models efficiently. 

I think it's preferable and more manageable for us to continue focusing on specific models and implementing optimizations that are specific to them.

**Comment by MrRace** [comment]
@guillaumekln  If I optimize an ONNX model, can I directly load it with CTranslate2? Or, in other words, will this feature be supported in the future?
