### ISSUE TITLE
how to ensure if Ctranslate is using intel mkl after pip installing it

### ISSUE THREAD

**Issue by vigneshmj1997** [OpenNMT/CTranslate2#500]
I installed ctranslate2 via pip 
how do i ensure if ctranslate2 is using mkl or not
thanks in advance

**Comment by guillaumekln** [comment]
You can set the environment variable `CT2_VERBOSE=1` to know whether Intel MKL is used or not. For example when running your Python script:

```bash
CT2_VERBOSE=1 python my_script_using_ctranslate2.py
```

**Comment by vigneshmj1997** [comment]
thanks a lot for the the speed reply 
Is there any way to force ctranslate2 to use intel mkl using code rather than using CT2_USE_MKL argument 
thanks in advance

**Comment by guillaumekln** [comment]
Intel MKL is used by default on Intel CPUs. When do you need to force CTranslate2 to use Intel MKL?

**Comment by vigneshmj1997** [comment]
when i used command the following command 
 CT2_VERBOSE=1 python python_code.py 
i got the following result 
[ct2_verbose] CPU: AuthenticAMD (SSE4.1=true, AVX=true, AVX2=true, NEON=false)
[ct2_verbose]  - Selected ISA: AVX2
[ct2_verbose]  - Use Intel MKL: false
[ct2_verbose]  - SGEMM backend: DNNL
[ct2_verbose]  - GEMM_S16 backend: NONE
[ct2_verbose]  - GEMM_S8 backend: DNNL (u8s8 preferred: true)
[ct2_verbose]  - Use packed GEMM: false

but when i used
CT2_USE_MKL=1 CT2_VERBOSE python python_code.py 
i get  
[ct2_verbose] CPU: AuthenticAMD (SSE4.1=true, AVX=true, AVX2=true, NEON=false)
[ct2_verbose]  - Selected ISA: AVX2
[ct2_verbose]  - Use Intel MKL: true
[ct2_verbose]  - SGEMM backend: MKL
[ct2_verbose]  - GEMM_S16 backend: MKL
[ct2_verbose]  - GEMM_S8 backend: MKL (u8s8 preferred: true)
[ct2_verbose]  - Use packed GEMM: false

so i assumed CT2_USE_MKL forces code to use mkl , forgive if i am wrong 
and my processor is amd but i have intel mkl installed is it because of that i am not able to use intel mkl

**Comment by guillaumekln** [comment]
Intel MKL does not support AMD CPUs. That is why CTranslate2 decides to not use it when a AMD CPU is detected. This is mentioned in the README:

> In particular, they are compiled with both Intel MKL and oneDNN so that Intel MKL is only used on Intel processors where it performs best, whereas oneDNN is used on other x86-64 processors such as AMD.

https://github.com/OpenNMT/CTranslate2#what-hardware-is-supported

If you want to force the usage of Intel MKL, you can set `CT2_USE_MKL=1` as you found out.

**Comment by vigneshmj1997** [comment]
yeah so that's my question is there any way to force ctranslate2 to use intel-mkl in AMD processor in script rather passing CT2_USE_MKL=1 argument

**Comment by guillaumekln** [comment]
You can do that:

```python
import os
os.environ["CT2_USE_MKL"] = "1"

import ctranslate2
# rest of your code
```

But note that Intel MKL will be very slow on AMD.

**Comment by vigneshmj1997** [comment]
thanks a lot
