### ISSUE TITLE
how to force ctraslate2 not to use intel mkl 

### ISSUE THREAD

**Issue by vigneshmj1997** [OpenNMT/CTranslate2#505]
i have to compare performance gain on using intel mkl ,So is there any way to disable usage of intel mkl in intel processors
i installed ctranslate2 from pip  
i ran code with CT2_VERBOSE python python3_code.py 
it uses imtel mkl by default

**Comment by guillaumekln** [comment]
I think we already discussed this in https://github.com/OpenNMT/CTranslate2/issues/500? Just set the environment variable `CT2_USE_MKL=0`.

**Comment by vigneshmj1997** [comment]
yeah but when i do it in code as u said , by including following line
os.environ["CT2_USE_MKL"] = "0"

I still get 
[ct2_verbose] CPU: GenuineIntel (SSE4.1=true, AVX=true, AVX2=true, NEON=false)
[ct2_verbose]  - Selected ISA: AVX2
[ct2_verbose]  - Use Intel MKL: true
[ct2_verbose]  - SGEMM backend: MKL
[ct2_verbose]  - GEMM_S16 backend: MKL
[ct2_verbose]  - GEMM_S8 backend: MKL (u8s8 preferred: true)
[ct2_verbose]  - Use packed GEMM: false 

on running CT2_VERBOSE=1 python python3_code.py

**Comment by guillaumekln** [comment]
I just tested and it works as expected:
```
$ CT2_VERBOSE=1 python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ["CT2_USE_MKL"] = "0"
>>> import ctranslate2
[ct2_verbose] CPU: GenuineIntel (SSE4.1=true, AVX=true, AVX2=true, NEON=false)
[ct2_verbose]  - Selected ISA: AVX2
[ct2_verbose]  - Use Intel MKL: false
[ct2_verbose]  - SGEMM backend: DNNL
[ct2_verbose]  - GEMM_S16 backend: NONE
[ct2_verbose]  - GEMM_S8 backend: DNNL (u8s8 preferred: true)
[ct2_verbose]  - Use packed GEMM: false
>>> ctranslate2.__version__
'2.1.0'
```

Make sure to set the environment variable **before** importing CTranslate2.

**Comment by vigneshmj1997** [comment]
yeah its working problem was i was importing ctransalte2 before 
os.environ["CT2_USE_MKL"] = "0"
thanks a lot for fast reply
