### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/CTranslate2#510]
Hi,

I'm trying to convert a Fairseq model to use it with Ctranslate2.

`ct2-fairseq-converter`

However, I get the following error:

`ModuleNotFoundError: No module named 'fused_layer_norm_cuda'`

Any clues?

**Comment by guillaumekln** [comment]
Hi,

There are similar issues here: https://github.com/NVIDIA/apex/search?q=fused_layer_norm_cuda&type=issues

I don't think you need the Apex module. You can try uninstalling it with `pip uninstall apex`.
