### ISSUE TITLE
compilation needs the <algorithm> header for std::max with MSVC

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#52]
Hi @guillaumekln,

I was trying to compile under Visual Studio 2019 and I got an error that `'max': is not a member of 'std'` in `layer_norm_cpu.cc` (line 30). Adding the `<algorithm>` header does the trick. After a bit of searching it seems this is because some Windows headers (WinDef.h) define their own macros for `max` and `min`. 
Maybe it would be better to fix this in the `CMakeLists.txt` instead of adding the header just for Windows, so I tried adding a block
```
if(MSVC)
  add_definitions(-D_USE_MATH_DEFINES)
  add_definitions(-DNOMINMAX)
endif()
```
but it won't work --to be more specific, the error disappears but the build is not fully successful and no libraries are created.

**Comment by guillaumekln** [comment]
Thanks for reporting. We keep getting into these type of issues because there is no proper Windows CI at the moment.

Could you send a PR with the missing include? It should be enough. Thanks.
