### ISSUE TITLE
Add a 8-bit integer GEMM backend on AArch64

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/CTranslate2#521]
We should look into adding a 8-bit integer GEMM backend that is optimized for AArch64.

**Comment by keichi** [comment]
Hello @guillaumekln, I would like to help with this. Do you have a specific library in your mind? 
[google/gemmlowp](https://github.com/google/gemmlowp) appears at the top if I google for "8-bit GEMM", but it seems like it's been superseded by [google/ruy](https://github.com/google/ruy) according to [this](https://groups.google.com/g/gemmlowp/c/oA6t7xKoq7w) announcement.

**Comment by guillaumekln** [comment]
Hi @keichi, thanks for your interest!

I don't have any specific library in mind. You could pick the one that is the most convenient to integrate. I also found the [ARM Compute Library](https://github.com/ARM-software/ComputeLibrary) but the GEMM API also seems quite [high level](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_n_e_g_e_m_m_lowp_matrix_multiply_core.xhtml).

For reference, the 8-bit GEMM function is currently located [here](https://github.com/OpenNMT/CTranslate2/blob/v2.3.2/src/cpu/primitives.cc#L711). The input/output types are "int8 * int8 -> int32" but it can also be "uint8 * int8 -> int32" [if declared by the backend](https://github.com/OpenNMT/CTranslate2/blob/v2.3.2/src/cpu/backend.cc#L95-L98).
