### ISSUE TITLE
Unable to load model with shared_vocabulary.txt

### ISSUE THREAD

**Issue by scotfang** [OpenNMT/CTranslate2#526]
Hi Guillaume, I can't seem to load a model with a "shared_vocabulary.txt" file. 

The model directory only contains "shared_vocabulary.txt" and "model.bin".

The ctranslate2 version is 2.0.0

The line of code is ctranslate2.Translator(path_to_model_dir, device="cuda").

This line of code seemed to work on a different machine/environment, maybe it is and I made sure the tensorflow package-version was consistent, not sure why it's happening.

Here's the error: 
Traceback (most recent call last):
    translator = ctranslate2.Translator(model_dir), device="cuda")
RuntimeError: Unable to open file 'source_vocabulary.txt'

**Comment by guillaumekln** [comment]
Hi,

It tries to open `source_vocabulary.txt` if it was not able to open `shared_vocabulary.txt` first. Can you check that you have the permission to open and read the file `shared_vocabulary.txt`?

**Comment by guillaumekln** [comment]
Closing this issue. Feel free to reopen with more information if you think there is a bug.
