### ISSUE TITLE
Understanding of inter_threads and batch_size

### ISSUE THREAD

**Issue by rkoystart** [OpenNMT/CTranslate2#531]
I have a doubt between inter_threads  in ctranslate2.Translator function and batch_size in translator.translate_batch function

So inter_threads means how many parallel translation it can perform.If suppose i set it to 2 and set the batch_size as 2 and give a list of 4 tokenized sentences. So now does that mean that the these 2 batches are translated in parallel or each sentences in the batch is getting translated in parallel.

Thanks in advance.

**Comment by guillaumekln** [comment]
You would have 2 batches that are translated in parallel.

**Comment by rkoystart** [comment]
Thanks for the speed reply @guillaumekln . 
What if I set inter_threads to 2 in Translator function and max_batch_size in translate_batch function to 0 ?
So would it be like all the sentences will be  translated one after another ?

**Comment by guillaumekln** [comment]
Then it will translate a single batch of 4 sentences. In this case, inter_threads will not make a difference.

**Comment by rkoystart** [comment]
Thanks @guillaumekln
