### ISSUE TITLE
Understanding about max_decoding_length

### ISSUE THREAD

**Issue by rkoystart** [OpenNMT/CTranslate2#533]
I came across parameter max_decoding_length(default value is 250) in translate_batch(). Please let me know whether my understanging about it is right.

1) when i give a tokenized list containing 1024 tokes to the translate_batch function and i set the max_decoding_length to 250, the ctranslate will only do predictions for 250 tokens, after that it wont proceed with the prediction and it will return the output.

2) when i give a tokenized list containing only 2 tokens to the translate_batch funtion with max_decoding_length to 250, it will only return a list containing 2 tokens (assuming it should return only 2 tokens). It will not extend the prediction to 250 tokens and return a output containing 250 tokens.
Right ?
Thanks in advance!!!!

**Comment by guillaumekln** [comment]
1. Correct, the decoding stops after producing 250 tokens.
2. Correct, the decoding stops when the translation is finished.

**Comment by rkoystart** [comment]
Hi , I have doubt 
If my input list contains 2 list, where the first list contains 200 tokens and second list contains 150 tokens and the batch_size is 128. If I set the max_decoding_length to 2000 , is this value limited to the total input/batch or is it limited to each list of tokens in the input list.

**Comment by guillaumekln** [comment]
I'm not sure I understand your question.

`max_decoding_length` works as you would expect: it limits the output length of each example in the batch.

**Comment by guillaumekln** [comment]
I'm closing this issue. You can reopen if you have more concerns regarding the `max_decoding_length` option.
