### ISSUE TITLE
Model loading/inference hangs with GELU activation on GPU

### ISSUE THREAD

**Issue by funboarder13920** [OpenNMT/CTranslate2#534]
Hello,

I have an issue while trying to use ctranslate2, the program hangs during model loading/inference on GPU without any good way to understand what is happening.

Model loading and inference work well on CPU.
It works on GPU when replacing GELU with RELU during OpenNMT-py model conversion.

I can't figure out what the issue is, there is no error message and I am not familiar with debugging ctranslate2 but I am still looking.
Do you have any idea what could cause GELU to make the program hang on GPU ?

Best

**Comment by guillaumekln** [comment]
Hi,

I can indeed reproduce this bug. That's strange. I'll look into it.

**Comment by guillaumekln** [comment]
I was able to identify and fix the issue. Thanks for reporting!

I'll make a new version tomorrow with this change.

**Comment by funboarder13920** [comment]
Thank you for the fix, and for your work on OpenNMT.
