### ISSUE TITLE
Ctranslate and Gunicorn conflict

### ISSUE THREAD

**Issue by rkoystart** [OpenNMT/CTranslate2#539]
Hi, I have a ctranslate model that needs to be loaded into the ram and serve it using gunicorn. I have the following queries:
1)I am having a problem to load the ctranslate model when starting the gunicorn server with `preload_app` argument as True. But with `preload_app` argument as False i am able to server the model. 
2) There is a argument called `workers` in gunicorn which indicates how many request can be served simultanously. There is same ram memory usage for different workers count with `preload_app` True(pytorch model). But with `preload_app` False the ram memory usage for different workers count was increasing as the worker count increase.
3) Also would like to know whether the ctranslate model is dependent on pytorch library during inference?
Can i know what needs to be done for using the ctranslate model with `preload_app` as True.

**Comment by guillaumekln** [comment]
According to the [Gunicorn documentation](https://docs.gunicorn.org/en/stable/settings.html?highlight=preload#preload-app),  `preload_app` means:

> Load application code before the worker processes are forked.

However, the `ctranslate2.Translator` is not fork-safe. So you should either disable this argument and have one model per worker, or keep a single worker and increase the number of threads instead.

**Comment by rkoystart** [comment]
Thanks for the response @guillaumekln .
