### ISSUE TITLE
Segmentation fault when import pyonmttok before ctranslate2.

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/CTranslate2#543]
I'm using pyonmttok and ctranslate2 at the same time. 
```
import pyonmttok
import ctranslate2

translator = ctranslate2.Translator("mount/ct2_convert")
translator.translate_batch([["▁H", "ello", "▁world", "!"]])
```
It works fine.
But when I change the order of the two libraries, it raises the "Segmentation default" error. 
![捕获](https://user-images.githubusercontent.com/25839309/128812642-e857df85-8340-468c-ae77-32ed617b76d8.PNG)

**Comment by guillaumekln** [comment]
Yes, I also found this bug recently. Will try to debug when I go back to the office.

The workaround is to change order of import as you did.

**Comment by guillaumekln** [comment]
I verified and this will be fixed in the next version of the `pyonmttok` package.

**Comment by BrightXiaoHan** [comment]
Oh, thanks.
