### ISSUE TITLE
Build from source code and get cannot open shared object file error

### ISSUE THREAD

**Issue by SefaZeng** [OpenNMT/CTranslate2#545]
I try to build the python and cpp module from source code. I run the following commands first:
```
git submodule update --init --recursive
mkdir build && cd build
cmake -DWITH_MKL=ON -DWITH_CUDA=ON ..
make -j4
```
Then I get the libctranslate2.so and cli/translate . I try to build the python library from these commands:
```
# Install the CTranslate2 library.
cd build && make install && cd ..

# Build and install the Python wheel.
cd python
pip install -r install_requirements.txt
python setup.py bdist_wheel
pip install dist/*.whl
```
I found a missing ctranslate2.lib directory under the installation path compared to the pip installation. And when I try to transform the model to ctranslate file using this command:
`ct2-opennmt-py-converter --model_path $1 --quantization int8 --output_dir int8_model_ctranslate2 --force`
It returns this error:
```
Traceback (most recent call last):
  File "/root/miniconda2/envs/torch1.8/bin/ct2-opennmt-py-converter", line 5, in <module>
    from ctranslate2.converters.opennmt_py import main
  File "/root/miniconda2/envs/torch1.8/lib/python3.6/site-packages/ctranslate2/__init__.py", line 2, in <module>
    from ctranslate2.translator import Translator
ImportError: libctranslate2.so: cannot open shared object file: No such file or directory
```
Did I miss something? Is there any methods to solve this?

**Comment by guillaumekln** [comment]
Try setting the environnent variable `LD_LIBRARY_PATH` to the directory that contains `libctranslate2.so`, for example:

```bash
LD_LIBRARY_PATH=/path/to/the/directory ct2-opennmt-py-converter --model_path $1 --quantization int8 --output_dir int8_model_ctranslate2 --force
```

**Comment by SefaZeng** [comment]
> Try setting the environnent variable `LD_LIBRARY_PATH` to the directory that contains `libctranslate2.so`, for example:
> 
> ```shell
> LD_LIBRARY_PATH=/path/to/the/directory ct2-opennmt-py-converter --model_path $1 --quantization int8 --output_dir int8_model_ctranslate2 --force
> ```

Thank you so much. That's really works to me.
