### ISSUE TITLE
compiled client doesn't work as expected in Windows

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#55]
So I managed to compile everything with MSVC but I can't figure out why the client doesn't translate as expected. With short sentences containing only a few words (~10), it seems to be working fine. With longer sentences, I get very short, truncated, and irrelevant translations or just a single irrelevant word. Under OS X, it works wonderfully, no matter the length of the sentence. In both systems I'm using the same converted tf model and the same sentencepiece model.
The only weird thing I can notice is that the special underscore character from sentencepiece in `shared_vocabulary.txt` has encoding issues under Windows and appears as an empty box.

**Comment by guillaumekln** [comment]
Is there a specific length for which it starts to fail? Does it work with a previous version of CTranslate2?

**Comment by panosk** [comment]
It happens at around 70 characters. I switched to tag 1.2.0 and it stills happens (although this tag no longer requires the <algorithm> header for min/max...). Which tag should I check?

**Comment by guillaumekln** [comment]
Windows compilation was only added in 1.2.0.

@jhnwnd Did you get a similar issue on Windows?

**Comment by panosk** [comment]
Actually, I just noticed that the problem is probably not with the source length but with the translation produced. I tested with some short English sentences ~55-60 characters that should have longer translations, and indeed the problem appears in the translations.

**Comment by guillaumekln** [comment]
Did you try with the pretrained model that is used in the README?

**Comment by panosk** [comment]
I tried and the problem is there too for longer sentences.
FWIW, I couldn't install latest tensorflow 2 in Windows due to `tensorflow-addons` which is still not available, so I'm using tensorflow 1.15.

**Comment by panosk** [comment]
@guillaumekln 
A bit more testing shows that the problem is broader. I mentioned the tensorflow version above because the converter script needs tensorflow so I don't know if that could affect the model conversion. 
So, when I translate even a small sentence multiple times, the output is different, and sometimes irrelevant, each time. If I can help in any way spot the issue, please let me know.

**Comment by guillaumekln** [comment]
Some questions so that I can gather more information.

* What CPU is it running on?
* Which Intel MKL version did you install?
* If you can give more details on the compilation procedure (compiler, version, etc.) that could also help.

**Comment by panosk** [comment]
Here it is:
- I'm testing in 2 laptops, one MacBook Pro (with Windows on Bootcamp) and an older Dell, both with Intel Core i7
- MKL 2019 Update 5 for Windows (the latest version 2019.5.281). I've installed only "Intel MKL core libraries for C/C++ for Intel 64" and "Intel TBB threading support for Intel 64".
- I compile with MSVC 2019 v14.24.28314.

**Comment by jhnwnd** [comment]
I can confirm that I too am not getting expected translations with `device=cpu` on Windows. Using `device=cuda` works fine on Windows. Am also getting different outputs with different values of `intra_threads` (which is not respected). @guillaumekln I didn't notice this before, but my testing was very limited.

**Comment by panosk** [comment]
So far I've found that the MSVC compiler supports only OpenMP 2.0 (and that's indeed the version listed by CMake) --could that be relevant?

**Comment by guillaumekln** [comment]
It seems the translations are correct when OpenMP flags are not passed during compilation:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7a190f6..5c9f170 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -57,7 +57,7 @@ endif()
 find_package(Threads)
 find_package(OpenMP)
 if(OpenMP_CXX_FOUND)
-  add_compile_options(${OpenMP_CXX_FLAGS})
+  #add_compile_options(${OpenMP_CXX_FLAGS})
 endif()
 
 set(INCLUDE_DIRECTORIES
```

Can you try this diff?

**Comment by panosk** [comment]
Hi @guillaumekln,

Indeed that works. Thank you!

**Comment by guillaumekln** [comment]
Another solution is to compile with `libmkl_sequential.lib` instead of `libmkl_intel_thread.lib` but it is clearly not an option.
