### ISSUE TITLE
What does this parameter  "use_vmap" mean.

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/CTranslate2#550]
I'm confused about this parameter.  Where should I get this mapping file? What can it do?

**Comment by guillaumekln** [comment]
There is a link in the [Frequently asked questions](https://github.com/OpenNMT/CTranslate2#how-do-i-generate-a-vocabulary-mapping-file) section of the README.

This mapping can be used to dynamically reduce the output vocabulary and so increase the decoding speed.
