### ISSUE TITLE
Build from source with OpenBLAS

### ISSUE THREAD

**Issue by harishankar-gopalan** [OpenNMT/CTranslate2#552]
I have been trying to build CTranslate2 from source using OpenBLAS back end. I have been able to build it successfully however when I build a wheel from the python package of ctranslate2 and use auditwheel it does not package all the required shared objects stating the below same limitation stated in auditwheel. I have tried a lot to understand and try to go around it, tried using manylinux docker images and also the docker image given in the repository but to no success.

"""Ref - https://github.com/pypa/auditwheel#limitations
There's nothing we can do about "fixing" binaries if they were compiled and linked against a too-recent version of libc or libstdc++. These libraries (and some others) use symbol versioning for backward compatibility. In general, this means that code that was compiled against an old version of glibc will run fine on systems with a newer version of glibc, but code what was compiled on a new system won't / might not run on older system.

So, to compile widely-compatible binaries, you're best off doing the build on an old Linux distribution, such as a manylinux Docker image.
"""

Is this expected because OpenBLAS has dependencies on recent symbols ? What is the best way to package CTranslate2 with OpenBLAS backend ? Should I manually find all the shared object files and put it under a specific folder and set LD_LIBRARY_PATH ? Just a gentle nudge in the right direction might help me go ahead.

**Comment by guillaumekln** [comment]
Can you post the full auditwheel output? If it can't locate a shared library you should indeed help it by setting the `LD_LIBRARY_PATH` environment variable.

**Comment by harishankar-gopalan** [comment]
Hi @guillaumekln , Thanks for the very swift response.

--------------------------------------------------
Below is the output for:
`auditwheel repair ctranslate2-2.3.0-cp38-cp38-linux_x86_64.whl`

auditwheel repair ctranslate2-2.3.0-cp38-cp38-linux_x86_64.whl 
INFO:auditwheel.main_repair:Repairing ctranslate2-2.3.0-cp38-cp38-linux_x86_64.whl
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot repair "ctranslate2-2.3.0-cp38-cp38-linux_x86_64.whl" to "manylinux_2_5_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain
---------------------------------------------

And here is the output for:
`auditwheel show ctranslate2-2.3.0-cp38-cp38-linux_x86_64.whl`
ctranslate2-2.3.0-cp38-cp38-linux_x86_64.whl is consistent with the
following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libgcc_s.so.1 with versions
{'GCC_3.0'}, libpthread.so.0 with versions {'GLIBC_2.2.5'}, libc.so.6
with versions {'GLIBC_2.14', 'GLIBC_2.2.5'}, libstdc++.so.6 with
versions {'GLIBCXX_3.4.14', 'GLIBCXX_3.4.15', 'GLIBCXX_3.4.19',
'CXXABI_1.3.3', 'GLIBCXX_3.4.18', 'GLIBCXX_3.4.9', 'CXXABI_1.3.9',
'CXXABI_1.3.11', 'GLIBCXX_3.4.20', 'GLIBCXX_3.4', 'CXXABI_1.3.5',
'GLIBCXX_3.4.11', 'GLIBCXX_3.4.21', 'CXXABI_1.3', 'CXXABI_1.3.2'}

This constrains the platform tag to "manylinux_2_27_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.

------------------------------------

**Comment by guillaumekln** [comment]
This is more a auditwheel issue than CTranslate2 I think. If you are not compiling in a manylinux Docker image you should configure the option `--plat` to match your current platform. See `auditwheel repair -h`.

**Comment by harishankar-gopalan** [comment]
Sure yea will go through it more over the net..Thanks for looking into it..
