### ISSUE TITLE
Investigating computation differences between OpenNMT-py and CT2 in custom implementation

### ISSUE THREAD

**Issue by funboarder13920** [OpenNMT/CTranslate2#555]
Hello Guillaume,

We are currently trying to use CTranslate2 to improve decoder only/GPT inference time with OpenNMT-py models.

We have a considerable gap (10% drop) between CTranslate2 and OpenNMT-py. Part of it was coming from the gelu function, the fix reduced the drop to 6%. Based on the improvement provided by the fix, I think there might be another issue.

The OpenNMT-py model was trained in fp16. CTranslate2 quantization is not currently used. Within Ctranslate the output is the same between CPU/GPU and with masking/with step by step prefix insertion. Between OpenNMT and Ctranslate2, Logprobs are different as well as topk. If there is an issue, it is not in the input, not in masking, not in the activation function and I didn't find any in the network implementation for now.

I will look deeply into layers outputs and mistakes in my implementation. Before that, I want to ask if such a difference is indeed unexpected or if differences between OpenNMT and CTranslate inference can be quite big ? Without more details, do you have an idea of what may cause computation differences ?

Best,
Valentin

**Comment by guillaumekln** [comment]
Hi,

Unless there is a bug, differences should be unexpected. For example on the pretrained Transformer model the outputs are the same and the cumulated prediction scores are within 10e-5 of each other. And that's a cumulated score so intermediate numerical outputs are even closer.

The difficulty with CTranslate2 is that the exact architectures should be reimplemented. It's very easy to miss something. There could be subtle differences in the model architecture or the decoding logic. For example, the embeddings could scaled by a factor in one implementation and not the other. Or one implementation adds an end of sentence token to the source and not the other.

I usually debug this by printing and comparing tensor values in a binary search fashion. So you start by comparing the encoder output and then move either to the encoder layers or decoder layers based on the result.

Let me know if you find anything.

**Comment by guillaumekln** [comment]
Also, what was the issue with the GELU implementation?

**Comment by funboarder13920** [comment]
We are using exact gelu in OpenNMT-py, fast gelu is the one used in CTranslate2.
I changed the activation function to fast gelu in my model to match CTranslate2.

The inference issue was in OpenNMT-py, even if it was the implementation with the higher score.

**Comment by funboarder13920** [comment]
Can you clarify what the add_depth_broadcast function is supposed to do ?

I think it modifies my log_probs scores (or moves the values/pointers) and I don't understand why it should.

**Comment by guillaumekln** [comment]
```cpp
void add_depth_broadcast(const T* a, const T* b, T* c, dim_t a_size, dim_t b_size)
```

The function adds the vector `a` to each column of matrix `b` (`a` is broadcasted in the depth dimension).
* `a` has shape `[a_size]`
* `b` has shape `[a_size, b_size / a_size]` 

See for example how the beam scores are added to the log probs:

https://github.com/OpenNMT/CTranslate2/blob/v2.4.0/src/decoding.cc#L297-L303
