### ISSUE TITLE
Can Tensor2Tensor Export to Ctranslate2 Format?

### ISSUE THREAD

**Issue by scotfang** [OpenNMT/CTranslate2#559]
Hi, 

Wasn't able to find great information on this, but do you know if https://github.com/tensorflow/tensor2tensor#translation supports exporting to Ctranslate2 format? 

Thanks!
--Scot

**Comment by guillaumekln** [comment]
Hi,

Currently there is no converters for Tensor2Tensor, but it should not be too complicated to add one. Contributions are welcome.

**Comment by smcdufff** [comment]
I’m really interested to this as well…

**Comment by amrnablus** [comment]
Hello,
What's required to support tensor2tensor? I can work out the code details

**Comment by guillaumekln** [comment]
A converter should be added to load and register weights from a T2T checkpoint. You can explore how existing converters are defined: https://github.com/OpenNMT/CTranslate2/tree/master/python/ctranslate2/converters

**Comment by guillaumekln** [comment]
The tensor2tensor repository is now archived so we are not adding an "official" converter.

However, it is still possible to write your own converter using the existing ones as examples.
