### ISSUE TITLE
OpenNMT-tf 2.0 supported?

### ISSUE THREAD

**Issue by gxzks** [OpenNMT/CTranslate2#56]
I trained a Transformer model using OpenNMT-tf 2.0. The converter ran well but the translation result became weird. Does CTranslate2 support OpenNMT-tf 2.0?
Here are versions:
OpenNMT-tf == 2.3.0
tensorflow-gpu == 2.0.0

**Comment by guillaumekln** [comment]
Yes, it should work. Can you describe a bit more what you did and what you observe? Thanks.

**Comment by fangtanchen** [comment]
I meet the similar issues. 
I found that "translation from ctranslate2 model" is 4 point bleu lower than "translation from saved_model".

**Comment by gxzks** [comment]
@guillaumekln I trained a TransformerBase model using OpenNMT-tf 2.3.0 with mixed precision. Decoding ran well and the result was normal. But after I used the opennmt_tf_converter to convert the model to binary form, the result became weird. Here is the convert command I used:
`python -m ctranslate2.bin.opennmt_tf_converter --model_path export/ --output_dir enzh_ctranslate2 --model_spec TransformerBase --force --src_vocab=source_vocab_txt --tgt_vocab=target_vocab_txt`

 For example, I used this command to test:
`echo "▁Civil ▁rights ▁group ▁issues ▁travel ▁warning ▁for ▁Missouri" | nvidia-docker run -i --rm -v $PWD:/data opennmt/ctranslate2:latest-ubuntu18-gpu --model /data/enzh_ctranslate2 --device cuda`
the result was `乡 ▁权利 ▁宣传 ▁代表团 ▁鼓励 ▁妻子 ▁(8`
But the origin result in OpenNMT-tf was ` ▁民权 ▁团体 ▁针对 ▁密苏里 州 ▁发出 ▁旅行 ▁警告`

**Comment by gxzks** [comment]
My bad. I set the wrong vocab when converting the model.

**Comment by guillaumekln** [comment]
@gxzks Good to know that you made it works. The converter script could probably check that the vocabulary size is correct.

@fangtanchen This seems unrelated. You could open another issue if you can provide more information (data to reproduce are even better!). Thanks.
