### ISSUE TITLE
Can I get word alignments while translating?

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/CTranslate2#563]
In opennmt-py, I can generate word alignments while translating by passing "--report_align" option. How can I do the same things in Ctranslate2?

**Comment by guillaumekln** [comment]
See the `return_attention` translation option. It currently returns the first attention head of the last decoder layer.

**Comment by BrightXiaoHan** [comment]
Does it mean I need to calculate the aligned words manually? Is it possible to return the alignment directly?

**Comment by guillaumekln** [comment]
The aligned words are just the maximum attention weights so it should be easy to compute.

**Comment by BrightXiaoHan** [comment]
Ok，thanks.
