### ISSUE TITLE
Does CTranslate2 support source features?

### ISSUE THREAD

**Issue by RakshaPRao** [OpenNMT/CTranslate2#596]
Hi, I was wondering as [source features](https://opennmt.net/OpenNMT-py/FAQ.html#how-can-i-use-source-word-features) have been added to ONMT-py, if CTranslate2 runtime is compatible?

Thanks!

**Comment by dearchill** [comment]
Hi, I have a similar situation, where I used the Fairseq transformer arch, and modified it with adding more features, then concatenated token_embedding and other embeddings together while forward_embedding. However, when I decided to export the model with ctranslate2,  I found it looks like not supported for this, there's only _module.embed_tokens.embeddings_ are exported. So I'm wondering if there's anyway I can modify it with a little work?

**Comment by guillaumekln** [comment]
It requires modifications in the C++ implementation, so I don't think it can be considered little work unless you are already familiar with the codebase.

**Comment by dearchill** [comment]
> It requires modifications in the C++ implementation, so I don't think it can be considered little work unless you are already familiar with the codebase.

Thanks for the reply. Got it. I'll try something else.

**Comment by BrightXiaoHan** [comment]
I'm also interested in this feature. Are you planning to add this feature in the recent release?

**Comment by anderleich** [comment]
Same here

**Comment by anderleich** [comment]
I'm using the standard Transformer architecture with `--feat_merge` either `sum` or `concat`. In case of `concat` word embedding size is decreased in order to match the default total 512 embedding size (Ex.: 496+16=512).

**Comment by dearchill** [comment]
I'm using Fairseq and rewrite the standard Transformer architecture with input embeddings concatenation. So it would be nice if there's more general way to do this. Thanks in advance.

**Comment by guillaumekln** [comment]
@dearchill Since this architecture is not available in Fairseq, we would need more information to know if it could be supported. For example, did you update the [embeddings scaling factor](https://github.com/pytorch/fairseq/blob/v0.10.2/fairseq/models/transformer.py#L323) to the total embedding size?

**Comment by dearchill** [comment]
> @dearchill Since this architecture is not available in Fairseq, we would need more information to know if it could be supported. For example, did you update the [embeddings scaling factor](https://github.com/pytorch/fairseq/blob/v0.10.2/fairseq/models/transformer.py#L323) to the total embedding size?

No, I didn't update that.

**Comment by guillaumekln** [comment]
The PR above is adding support for source features. As described in the PR, the features should be added to the string tokens directly using the special separator ￨. This is mostly to simplify the integration and avoid updating all interfaces.

@dearchill Since you are using a user architecture not available in Fairseq, the converter will not convert it out of the box. However, it should be fairly easy to extend it to support your model (just need to register the additional embeddings and vocabularies).

**Comment by tomsbergmanis** [comment]
Hi! I just learned about CTranslate2 project! Impressive work! 
My organization heavily use Marian models with source/target factors which use .fsv vocabularies, which ct2-marian-converter does not seem to know how to handle. Is that something that is not supported, or is it me doing something wrong? 

Looking into it a bit more, it looks like CTranslate2 doesn't support factored marian at all. See https://github.com/marian-cef/hackathon-factors-tutorial for the reference. 

Is that something that could be added?

**Comment by guillaumekln** [comment]
Hi,

Unfortunately these models are currently not supported. It looks like it would quite some work to support them fully, especially the target factors which are currently not implemented at all and would require changes to the decoding code.

At the moment this is not something we plan to add ourselves as the logic is generally very specific to Marian.
