### ISSUE TITLE
Link error/warning in OS X with --start-group and --end-group

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#62]
The linker in OS X (LLVM 10) doesn't understand the `--start-group` and `--end-group` linking options. When building with the default Apple's toolset, removing these options allows building the project, although with a ton of warnings due to linking order and particularly related to `boost::program_options`. At least it builds and runs fine, as far as I have tested it.
If I change the compiler to gcc-9, it won't link at all. 
I tried but I couldn't find a solution (maybe ordering the libraries manually?)

**Comment by guillaumekln** [comment]
So would something like this be enough to get started?

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7a190f6..f7632d4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -179,7 +179,7 @@ if(WITH_MKL)
     endif()
   endif()
   list(APPEND INCLUDE_DIRECTORIES ${MKL_INCLUDE_DIR})
-  if(WIN32)
+  if(WIN32 OR APPLE)
     list(APPEND LIBRARIES ${MKL_LIBRARIES})
   else()
     list(APPEND LIBRARIES -Wl,--start-group ${MKL_LIBRARIES} -Wl,--end-group)
```

**Comment by panosk** [comment]
I had already tried that but it still throws the warnings (with Apple's clang) and the errors (with gcc-9). Here is the last line of the warning and the error:

clang:
```
ld: warning: direct access in function 'virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >::rethrow() const' from file '/usr/local/lib/libboost_program_options.a(value_semantic.o)' to global weak symbol 'typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >' from file 'CMakeFiles/translate.dir/translate.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
gcc-9:
```
"virtual thunk to std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from:
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libboost_program_options.a(options_description.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by guillaumekln** [comment]
How did you install Boost?

Does it work if you run `cmake` with `-DCMAKE_CXX_FLAGS="-fvisibility=hidden"`?

**Comment by panosk** [comment]
I installed boost with brew package manager. When I pass this flag to CMake, then the `undefined symbols` problem is passed to `benchmark_ops` and linking fails both with clang and gcc. If I comment out the `add_subdirectory(tests)` from CMakeLists.txt to skip the tests, then the problems appears again in boost. When I run CMake, this is what I see about boost:

`
CMake Warning at /usr/local/lib/cmake/boost_program_options-1.71.0/libboost_program_options-variant-static.cmake:59 (message):
  Target Boost::program_options already has an imported location
  '/usr/local/lib/libboost_program_options-mt.a', which will be overwritten
  with '/usr/local/lib/libboost_program_options.a'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_program_options-1.71.0/boost_program_options-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  cli/CMakeLists.txt:2 (find_package)

-- Found Boost: /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components:  program_options 
`

**Comment by panosk** [comment]
Hm, this is probably a bug with boost-1.71, at least that's what I found in a few search results. I can compile fine only the library without the client and the boost dependency. I will verify this and let you know (and close the bug if that's indeed the case). Thanks!

**Comment by panosk** [comment]
Boost 1.72 is out, but the problem remains. I checked the changelog but couldn't find any fix for this. For now, I'll put the blame on boost and I'm closing this issue.

**Comment by guillaumekln** [comment]
Surely there is something we need to do to avoid this error. That being said, it would be nice to get rid of Boost. We are only using it to handle the command line options of the client binary.

**Comment by panosk** [comment]
I agree, still there are way too many options to handle them directly in `main()`, so I guess we could look into another library. I found [cxxopts](https://github.com/jarro2783/cxxopts), which is header-only. If you approve it, I could work on that.

**Comment by guillaumekln** [comment]
Yes this sounds good. We could probably include it as a Git submodule to simplify installation (e.g. in `third_party` directory).
