### ISSUE TITLE
CTranslate using cuda on Windows

### ISSUE THREAD

**Issue by bimbsms** [OpenNMT/CTranslate2#623]
Thank you for releasing python wheel for windows. I tried to use device="cuda" on windows, but met with "This Ctranslate2 package was not compiled with CUDA support". Hope it will be supported soon.

**Comment by guillaumekln** [comment]
I'm experimenting a Windows wheel with CUDA support. Can you help testing?

If you have some time, please go to this [build page](https://github.com/guillaumekln/CTranslate2/actions/runs/1463054747), download the artifact "python-wheels" (see at the bottom of the page), extract the archive, and install the appropriate Python wheel.

If it's working well, we could include this change in a future version.

**Comment by bimbsms** [comment]
Thank you for fast reply. 

Try it just now, got "cublas64_11.dll not found" when tried to translate text. Tried installing cuda toolkit but error persist. Not sure where to put the dll from cuda toolkit.

**Comment by bimbsms** [comment]
Successfully make it work by copying cublas64_11.dll, cublasLt64)_11.dll, nvblas64_11.dll into ctranslate2 folder, and add on line 15 of _init_.py I added "cublas64_11".

**Comment by guillaumekln** [comment]
> using pip to install cublas

This is not needed, but you need to update the `PATH` environment variable to include the CUDA toolkit binary directory, e.g.:

```text
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin
```

**Comment by bimbsms** [comment]
I see, let me try that too.

**Comment by bimbsms** [comment]
The cuda toolkit installation have added the path, so I am confused how "library cublas64_11.dll not found" message appear.

**Comment by guillaumekln** [comment]
It seems the CUDA toolkit adds the environment variable `CUDA_PATH` but it does not extend the global `PATH` variable. At least that's what I observed in my virtual machine.

I updated the code to also search the cuBLAS DLL in `$CUDA_PATH\bin`. Can you try the latest binary?

https://github.com/OpenNMT/CTranslate2/actions/runs/1467460440

**Comment by bimbsms** [comment]
Its working great now, thanks a lot!

**Comment by guillaumekln** [comment]
Let's keep this issue open until the changes are merged.

Let me know if there are other issues when running GPU translation on Windows. Thanks!
