### ISSUE TITLE
Produce <unk> while using Biased decoding

### ISSUE THREAD

**Issue by dearchill** [OpenNMT/CTranslate2#639]
Hi, when I used the Biased decoding to force a translation to start with the _target_prefix_, I found while encountered with rare words in the original sentence, the decoding output may have _<unk>_, I guess maybe because I used the bpe method. In the original decoding it's normal. So did the biased decoding not supported the bpe?

**Comment by dearchill** [comment]
The decoding output may have <unk>

**Comment by dearchill** [comment]
The decoding output may have "unk"

**Comment by guillaumekln** [comment]
Did you tokenize the target prefix?

**Comment by dearchill** [comment]
> Did you tokenize the target prefix?

Yes, I have tokenized the target prefix using moses_tokenizer without bpe.

**Comment by guillaumekln** [comment]
I'm not sure to understand. In the first post you said you are using the BPE method, so why not tokenizing the target prefix with BPE?

Can you provide an example showing the translation input, the target prefix, and the output?

**Comment by dearchill** [comment]
> I'm not sure to understand. In the first post you said you are using the BPE method, so why not tokenizing the target prefix with BPE?
> 
> Can you provide an example showing the translation input, the target prefix, and the output?

Sorry, I mistook the target prefix's tokenize method, I applied bpe on the target prefix then and it looked good. Thank you for your reply.
