### ISSUE TITLE
Could ctranslate2 server add '--ban_unk_token' function ? 

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/CTranslate2#641]
when i run ctranslate2 server, it will return so many 'unk' token in result.   To prevent unk token generation by setting unk proba to 0 like openmt-py's Decoding tricks
Could ctranslate2 server add '--ban_unk_token' function to prevent unk token generation by setting unk proba to 0 like openmt-py?   @guillaumekln 
Thanks in advance !!!

**Comment by guillaumekln** [comment]
We can consider this feature, or a more general `unk_penalty` option to apply a soft penalty on \<unk> tokens.

However, there is probably an issue with your model or tokenization if the output contains many unknown tokens. I suggest looking at [SentencePiece](https://github.com/google/sentencepiece) for example if you don't use it already.

**Comment by Andrewlesson** [comment]
I use the following function. There is no parameter(unk_penalty) in it like you said . I mean, I hope there is a parameter like '--ban_unk_token'  in it to ensure that the returned result does not contain <unk> tokens.

![image](https://user-images.githubusercontent.com/10346684/144023529-b589397a-9c54-4263-a24d-d53fbd634bf0.png)

**Comment by guillaumekln** [comment]
I meant I would prefer adding a new option `unk_penalty` (soft penalty) instead of `ban_unk_token` (hard penalty).

Also, you should consider that the model is producing \<unk> because your training data contains these tokens. Another solution is to fix your training data.

**Comment by Andrewlesson** [comment]
> We can consider this feature, or a more general `unk_penalty` option to apply a soft penalty on <unk> tokens.
> 
> However, there is probably an issue with your model or tokenization if the output contains many unknown tokens. I suggest looking at [SentencePiece](https://github.com/google/sentencepiece) for example if you don't use it already.

i have used it already,  It may be that the training data does not cover all the test data .  And I have tested that the effect of ‘'--ban_unk_token’ option  a training is much better than that of ‘replace_unk’ option training

**Comment by Andrewlesson** [comment]
> I meant I would prefer adding a new option `unk_penalty` (soft penalty) instead of `ban_unk_token` (hard penalty).
> 
> Also, you should consider that the model is producing <unk> because your training data contains these tokens. Another solution is to fix your training data.

ok  , got it , Thank you for your answer and look forward to adding this parameter as soon as possible .

**Comment by guillaumekln** [comment]
The PR above is adding the option `disable_unk` which is a hard penalty as you suggested. I figured a soft penalty is not very useful in practice.

**Comment by Andrewlesson** [comment]
> The PR above is adding the option `disable_unk` which is a hard penalty as you suggested. I figured a soft penalty is not very useful in practice.

Thank you very much !!!
