### ISSUE TITLE
Does vmap cause so many 'unk' token ?

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/CTranslate2#643]
Is Vmap trained separately and applied in the infer stage after training the translation model, or is it trained together with the translation model and used in the reasoning stage? 
I trained Vmap separately follow the README and used it in the server infer stage. but the final effect was very bad with so many 'unk' , i don't know why ?
VMap has too many parameters. Could you give us a complete and detailed case of using VMap?
Thanks in advance !!!

**Comment by guillaumekln** [comment]
The vmap is generated after training the model. You should make sure that the data used to generate the vmap have the same tokenization as the data used to train model. Enabling the vmap should not lead to more \<unk> tokens unless the model without the vmap also produces these tokens.

You can try this [vmap](https://github.com/OpenNMT/CTranslate2/files/7624529/vmap.txt) with the model that is used in the [Quickstart](https://github.com/OpenNMT/CTranslate2#quickstart).

**Comment by Andrewlesson** [comment]
> The vmap is generated after training the model. You should make sure that the data used to generate the vmap have the same tokenization as the data used to train model. Enabling the vmap should not lead to more <unk> tokens unless the model without the vmap also produces these tokens.
> 
> You can try this [vmap](https://github.com/OpenNMT/CTranslate2/files/7624529/vmap.txt) with the model that is used in the [Quickstart](https://github.com/OpenNMT/CTranslate2#quickstart).

as your said, i used the same tokenization from sentencepiece to train translation model , and then i trained Vmap separately follow the README   [How do I generate a vocabulary mapping file](https://github.com/OpenNMT/papers/tree/master/WNMT2018/vmap)    ,  and generated phrase-table.gz firstly, then use build-vmap.py to produce vmap.txt .  and use the below command below. 
1.  ct2-opennmt-py-converter --model_path model_step_best.pt --output_dir int8_ctranslate2 --vocab_mapping vmap.txt --quantization int8
2.  set use_vmap true in  translator.translate_batch  function
but the result contains a lot of 'unk'  tokens and a bad effect. Is there anything wrong with my steps?

**Comment by guillaumekln** [comment]
The steps look correct.

As an example, can you post a translation output with and without the vmap?

**Comment by Andrewlesson** [comment]
> The steps look correct.
> 
> As an example, can you post a translation output with and without the vmap?

I counted the number of Unks using VMap and not using VMap respectively. if VMap is not used, 4820 lines contain unk, a total of 5473 unk tokens; Using VMap, 12922 lines contain unk, 22017 in total unk tokens
the example below using VMap:

![image](https://user-images.githubusercontent.com/10346684/144793733-26e3e244-e52e-41ed-b53d-5048b2c2ef12.png)

**Comment by guillaumekln** [comment]
Is this a SentencePiece tokenization? Usually the underscores are not detached from the tokens so I think there was an issue when you prepared the data and the vocabulary. I suggest retraining a model from scratch.

**Comment by Andrewlesson** [comment]
> Is this a SentencePiece tokenization? Usually the underscores are not detached from the tokens so I think there was an issue when you prepared the data and the vocabulary. I suggest retraining a model from scratch.


as you said , i put source1 from a sentencepiece tokenization in function translator.translate_batch , but return  temp_res,  result are detached from the tokens

![image](https://user-images.githubusercontent.com/10346684/144838303-7e6ba022-1bb1-44a9-b6ec-426bf5bf1d9a.png)

![image](https://user-images.githubusercontent.com/10346684/144838034-8b7bfc52-4290-4a5c-b612-a3109e284b95.png)

**Comment by Andrewlesson** [comment]
> Is this a SentencePiece tokenization? Usually the underscores are not detached from the tokens so I think there was an issue when you prepared the data and the vocabulary. I suggest retraining a model from scratch.

i put source from sentencepiece tokenization in function translator.translate_batch, but the return temp_res which is detached from the underscores

![image](https://user-images.githubusercontent.com/10346684/144851760-e8742e08-f851-4081-83c5-643696982c0f.png)

**Comment by guillaumekln** [comment]
If the original model already outputs unknown tokens frequently, using a vmap can only make the situation worse since there are less candidate tokens.

Let me close this issue as it does not clearly demonstrate a bug in the code.

You can track #641 if you are looking to work around your model issue. In the meantime, you should probably rework your data preparation and retrain your model to produce less unknown tokens by default.
