### ISSUE TITLE
No SGEMM backend on CPU

### ISSUE THREAD

**Issue by alexvs-sysoev** [OpenNMT/CTranslate2#646]
Hi! I am trying to run the c++ version of CTranslate2. I builds CTranslate2 with the following parameters: 
`cmake -DWITH_MKL=OFF -DWITH_CUDA=OFF --WITH_MKL=OFF --DOPENMP_RUNTIME=NONE ..`
File CMakeLists includes the following lines:
```
target_include_directories(testProject PUBLIC "/workdir/src/CTranslate2/include") 
target_link_directories(testProject PUBLIC "/workdir/src/CTranslate2/build")  
target_link_libraries(testProject ctranslate2)
```
Source code:
```
#include <iostream>
#include <ctranslate2/translator.h>
int main() {
    const size_t num_translators = 1;
    const size_t num_threads_per_translator = 4;
    ctranslate2::Translator translator("/workdir/src/ende_ctranslate2/", ctranslate2::Device::CPU);
    const std::vector<std::vector<std::string>> batch = {{"H@@", "ello", "world@@", "!"}};
    const std::vector<ctranslate2::TranslationResult> results = translator.translate_batch(batch);
    for (const auto& token : results[0].output())
        std::cout << token << ' ';
    std::cout << std::endl;
    return 0;
}
```
The project builds successfully.  But after running, the following error occurs: 
**terminate called after throwing an instance of 'std::runtime_error'
  what():  No SGEMM backend on CPU**
How can I solve this problem?

**Comment by guillaumekln** [comment]
Hi,

You should enable at least 1 backend to run the model. So at least one CMake option starting with `WITH_` should be set to `ON`. See the list of CMake options [here](https://github.com/OpenNMT/CTranslate2#build-options).

**Comment by alexvs-sysoev** [comment]
Thank you so much for your help
