### ISSUE TITLE
adaptive softmax support

### ISSUE THREAD

**Issue by jothan706** [OpenNMT/CTranslate2#649]
Hello, do you have any plan to support adaptive_softmax in the decoder part, which will be very helpful for the decoder speed. Although VMAP is good, it will increase some memory, which is not very friendly for low memory devices

**Comment by guillaumekln** [comment]
Hi,

As far as I know, adaptive softmax is only faster during training where the full target is known. In that case we only compute a subset of clusters depending on the target tokens contained in the minibatch.

On the other hand, the target tokens are not known during inference so we would need to compute all clusters to find the output tokens with the highest probability. It would be slower than computing the full output probabilities in one pass.

Let me know if this is not correct.

**Comment by guillaumekln** [comment]
Let me close this issue. Feel free to reopen if my previous comment is incorrect.
