### ISSUE TITLE
Using a ModelReader with a TranslatorPool

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#658]
It seems that a `ModelReader` can only be used directly with the `Translator` class through `set_model` and not with a `TranslatorPool`. Is there a workaround for this? If not, would you be interested if I worked for a PR to add this functionality?

**Comment by guillaumekln** [comment]
There is currently no workaround.

Feel free to send a PR. I suggest converting the `model_dir` string argument to a `ModelReader` as soon as possible, and then only work with the `ModelReader` instance.

Thanks!
