### ISSUE TITLE
Top-p (nucleus) sampling support.

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/CTranslate2#664]
I have read the [api doc](https://github.com/OpenNMT/CTranslate2/blob/master/docs/python.md), finding that the decode options do not support Top-p (nucleus) sampling which described in this blog
https://huggingface.co/blog/how-to-generate#top-p-nucleus-sampling

Is it possible to support this feature in the future release?

**Comment by guillaumekln** [comment]
If anyone wants to help, I started implementing the corresponding operator in #1274 but it is missing the CUDA kernel. That's the most difficult part.
