### ISSUE TITLE
Multi-GPU Translator parallelism Suspended

### ISSUE THREAD

**Issue by Zaoyee** [OpenNMT/CTranslate2#665]
Hi, I try the following code with `translator = ctranslate2.Translator("_model_path", device='cuda', device_index=[0, 1])`
The process looks suspended and it may get locked somehow cuz I can see two model was created successfully in GPU 0 and 1...
Also I noticed that the suspended process could not be killed by `ctrl-c`.
I was wondering if there is any way to fix it? Thanks.

**Comment by guillaumekln** [comment]
Hello,

What is the version you are using?

**Comment by Zaoyee** [comment]
I am using the lastest version of Ctransate2,
CUDA 11.0
NVIDIA-SMI 450.142.00 
Dual Tesla V100-PCIE Cards

**Comment by guillaumekln** [comment]
Does it work with the previous version 2.9.0?

**Comment by guillaumekln** [comment]
I can reproduce the issue with the latest version. The change #657 is causing the issue.

**Comment by guillaumekln** [comment]
A fix is released in version 2.10.1. Thanks for reporting.

**Comment by Zaoyee** [comment]
Thanks
