### ISSUE TITLE
The error when I run  the fastertransformer doker in script " benchmark_pretrained.py"

### ISSUE THREAD

**Issue by michelleqyhqyh** [OpenNMT/CTranslate2#672]
![image](https://user-images.githubusercontent.com/45490378/147811609-95db86eb-d4b0-41bd-ba4b-1faa51fdaccb.png)

Can you run the fastertransformer doker sucessfully? I think it cann't work.

**Comment by guillaumekln** [comment]
The FasterTransformer Docker image is configured to run on a GPU with Compute Capability 7.5:

https://github.com/OpenNMT/CTranslate2/blob/v2.10.1/tools/benchmark/pretrained_transformer_base/fastertransformer/Dockerfile#L7

You might need to change this value to match the Compute Capability of your GPU.

**Comment by guillaumekln** [comment]
@michelleqyhqyh Did you solve this error?
