### ISSUE TITLE
Add arm64 packages for pypi to ci

### ISSUE THREAD

**Issue by nettnikl** [OpenNMT/CTranslate2#673]
## Problem
There are not pypi packages available for arm64.

## Background
It seems there should be support for arm64 / aarch64, and the used build files indicate that the pipeline would support CI including automatic testing and building. (see https://github.com/OpenNMT/CTranslate2/blob/master/.github/workflows/ci.yml#L90)
However, i can't find anything related to building on arm64 but https://github.com/OpenNMT/CTranslate2/issues/405#issuecomment-982427155, which indicates that i should build it by myself. This however complicates the deployment of projects based on this project considerably.
Consider e.g. this usecase: https://github.com/LibreTranslate/LibreTranslate/issues/186

## Workaround
In my case a option would be to build the project during the building of the other software. This however is slow, not straightforward, complicates maintenance and introduces other related issues.

## Solution
Please kindly explain which problems it would introduce to build arm64 build to the github ci, and if possible, do implement the necessary changes or propose where help is needed.

**Comment by guillaumekln** [comment]
The PR above is building Python wheels for AArch64.

Can you help testing? You can download the latest packages on the [build page](https://github.com/OpenNMT/CTranslate2/actions/runs/1650145487). Download the archive "python-wheels", extract it, and install the "aarch64" wheel corresponding to your Python version. Thanks!

**Comment by nettnikl** [comment]
I'm not really familiar with this library, as i only use it through argostranslate+libretranslate, however i noticed that while everything dependent on ctranslate2 compiles and starts happily, during an actual translation, it crashes with an 132 exit code, i guess it's a "Illegal Instruction". Could this be caused by ctranslate2? Could also be one of the other libraries, or even caused by slow hardware, however i cannot test on more bulky arm64 hardware.

**Comment by nettnikl** [comment]
Okay, tested w/o frontend, argos-translate also crashes with `Illegal instruction (core dumped)`.

**Comment by guillaumekln** [comment]
Ideally you should test the CTranslate2 library directly.

Using argos-translate, I reproduced the error on a server using a ARM Cortex-A72 processor (same as the Raspberry Pi 4). The error is coming from PyTorch not CTranslate2. You should check with the argos-translate developers for a workaround.
