### ISSUE TITLE
How to make ct2 translate with int8,fp16 and int8+fp16

### ISSUE THREAD

**Issue by michelleqyhqyh** [OpenNMT/CTranslate2#680]
![681`65C9}AMTJB{{S59FG)X](https://user-images.githubusercontent.com/45490378/148710008-6574c6b8-d487-4b2d-89fc-021f3dfdc0ba.png)
When I run the file  benchmark_pretrained.py  to test time on CT2 with fp32,fp16,in8,in8+fp16, I checked the translate.sh in ./CTranslate2/tools/benchmark/pretrained_transformer_base/ctranslate2, and found it defaults COMPUTE_TYPE. I think it only tests fp32, so how should I modify here to test time on CT2 with fp16,in8 and in8+fp16?

**Comment by michelleqyhqyh** [comment]
![PH3@OX} WJUP5YBF_(62P@2](https://user-images.githubusercontent.com/45490378/148712753-41af7d5e-d923-443a-93a2-af6c982b45e9.png)
This is my test on CT2. I used 1 GPU (V100). I don't know why it seems there is not significant difference on time with fp32,int8,fp16?

**Comment by guillaumekln** [comment]
The script `benchmark_pretrained.py` is setting the different values of compute type.

On V100, you should probably increase the batch size to see a more visible difference.
