### ISSUE TITLE
The result of translation seems strange

### ISSUE THREAD

**Issue by michelleqyhqyh** [OpenNMT/CTranslate2#681]

**Comment by michelleqyhqyh** [comment]
![image](https://user-images.githubusercontent.com/45490378/148730476-19a328b2-2648-4266-9264-d65ab119687a.png)
![image](https://user-images.githubusercontent.com/45490378/148730519-47daf988-a5f3-4ed8-a852-5bcd8e911da9.png)

Beside, when I used "gpu", it cann't work. How should I use my GPU(V100)?

**Comment by michelleqyhqyh** [comment]
![image](https://user-images.githubusercontent.com/45490378/148730644-dff8acd2-9957-4c1b-8afa-a4ef65150c73.png)
![image](https://user-images.githubusercontent.com/45490378/148730667-b27df719-a499-4d67-973c-3a35146cc8d7.png)
When I used my model to run with cpu, the result of tranlation is too many.

![image](https://user-images.githubusercontent.com/45490378/148730753-9e5312dd-f63c-428e-bdb6-abaf6787be1a.png)
![image](https://user-images.githubusercontent.com/45490378/148730769-89f59c46-7174-47c3-82d1-60f746eee9fe.png)
When I used your model to run with cpu, there is no result of translation. 

Do you know what's wrong with these problem?

**Comment by guillaumekln** [comment]
For the first example, is it an OpenNMT model? What output do you get with the framework you used for training?

For the second example, it seems you picked the wrong line from the Quickstart. Try with this instead:

```python
translator.translate_batch([["▁H", "ello", "▁world", "!"]])
```
