### ISSUE TITLE
CUDA failed with error out of memory when using cudaMallocAsync

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/CTranslate2#690]
I export my model from opennmt-py, my ctranslate2 version is 2.9.0.
When I load my model by ctranslate2-2.11.0, the error raised:
```
CUDA failed with error out of memory
```

**Comment by Jourdelune** [comment]
it means that you don't have enough ram memory (I don't know if it's only in your gpu, or the ram of your computer).
I don't know the size of your model, but if it is too big, this error can happen (personally I always have this problem when I try to train the m2m100 model with google colabs).

**Comment by BrightXiaoHan** [comment]
No, I use A100 gpu, and the device memory is empty.

**Comment by guillaumekln** [comment]
Does the error happen immediately after loading the model? Can you try with the previous version 2.10.1?

**Comment by BrightXiaoHan** [comment]
Yes, it happened immediately when loading the model. And it works fine with 2.10.1.

**Comment by guillaumekln** [comment]
If you are using a Python script, can you try to set the following environment variable before importing CTranslate2 2.11.0:

```python
import os
os.environ["CT2_CUDA_ALLOCATOR"] = "cub_caching"

import ctranslate2
```

**Comment by BrightXiaoHan** [comment]
This env solve the problem. But why did this happened?

**Comment by guillaumekln** [comment]
The default value of this environment variable changed in version 2.11.0 (see the [release note](https://github.com/OpenNMT/CTranslate2/releases/tag/v2.11.0)).

We should investigate how this error can happen.

**Comment by guillaumekln** [comment]
@BrightXiaoHan Can you post a minimal code snippet raising this error with version 2.11.0?

Also, what is the GPU driver version?

**Comment by BrightXiaoHan** [comment]
I install cudatoolkit by anaconda, the version is
```
cudatoolkit               10.2.89
```
The cuda version on my host is 
```
cuda-11.3
```
my code
![image](https://user-images.githubusercontent.com/25839309/150045115-2d34a54e-cfbc-45ee-8ba3-198dab53594f.png)

```py
import ctranslate2

ctranslate2.Translator("/path/to/model", device="cuda", device_index=0)
```

**Comment by guillaumekln** [comment]
For now I can't find a way to reproduce this issue.

I found similar issues in other projects where users got unexpected out of memory errors. In some cases, updating the driver and/or rebooting the system fixed the issue.

**Comment by BrightXiaoHan** [comment]
Ok, thanks.
