### ISSUE TITLE
M2M100 wrong Translation

### ISSUE THREAD

**Issue by Jourdelune** [OpenNMT/CTranslate2#702]
Hello, I have a bug with m2m100 and ctranslate2. When I try to translate this text from English to French, this is what I get:
`Oh, ICQ! that's when dinosaurs were?`
Result: `That's it, that's it, that's it, that's it, that's it, that's it, that's it, that's it, that's it, that's it.`

I report it as due to ctranslate2 because with the same model in hugging face I don't have this problem.

**Comment by guillaumekln** [comment]
Hi,

I can't reproduce this output using the 418M model and CTranslate2 2.11.0. I'm getting the following output:

```text
Oh, ICQ ! c’est quand les dinosaures étaient ?
```

using this code:

```python
import os
import ctranslate2
import sentencepiece as spm
import tempfile

model_dir = "/home/klein/models/facebook/m2m_100"
with tempfile.TemporaryDirectory() as tmp_dir:
    converter = ctranslate2.converters.FairseqConverter(
        os.path.join(model_dir, "418M_last_checkpoint.pt"),
        model_dir,
        fixed_dictionary=os.path.join(model_dir, "model_dict.128k.txt"),
    )
    converter.convert(tmp_dir, force=True)

    translator = ctranslate2.Translator(tmp_dir, device="cpu")
    sp_processor = spm.SentencePieceProcessor(model_file=os.path.join(model_dir, "spm.128k.model"))

    def translate(source_lang, target_lang, text):
        tokens = ["__%s__" % source_lang] + sp_processor.encode(text, out_type=str)
        results = translator.translate_batch([tokens], target_prefix=[["__%s__" % target_lang]])
        return sp_processor.decode(results[0].hypotheses[0][1:])

    print(translate("en", "fr", "Oh, ICQ! that's when dinosaurs were?"))
```

Can you provide the exact steps to reproduce the issue?

**Comment by Jourdelune** [comment]
Okay, that's very strange but I just saw that it doesn't do it for me every time, I had to translate 2 sentences to get it to do it, I'll wait until tonight to give you the steps. Otherwise you can try to translate the same sentence twice and maybe it will do it for you, I made an api so it doesn't restart at each translation

**Comment by guillaumekln** [comment]
I ran the request multiple times and it always returns the correct output "Oh, ICQ! c'est quand les dinosaures étaient ?".

I'm testing with the 418M model. Are you using a different version?

**Comment by Jourdelune** [comment]
I use the same version, it is extremely strange, why only on my pc. I will recompile the model (you never know) and retest. If you make the requests via the ip I put, you can see this bug.

**Comment by guillaumekln** [comment]
It seems I can reproduce the incorrect output by disabling Intel MKL (with the environment variable `CT2_USE_MKL=0`). So I suppose you are using an AMD CPU, right?

**Comment by guillaumekln** [comment]
You can fix this output by increasing the beam size. Add for example `beam_size=4` when calling `translate_batch`.

**Comment by Jourdelune** [comment]
Hi, thanks for your answer! I'm on intel but I don't have intel mlkit (what does it allow?). The problem is that if I increase beam_size, the translation time will increase, am I wrong?

**Comment by guillaumekln** [comment]
> I'm on intel but I don't have intel mlkit (what does it allow?)

Intel MKL is a library for matrix multiplication. It is already included in the Python package and used by default on Intel CPUs.

So if you are running this on an Intel CPU, I'm not sure why you are seeing this output. Can you enable the CTranslate2 info logs and report the output? Make sure to set the environment variable before the import:

```python
import os
os.environ["CT2_VERBOSE"] = "1"

import ctranslate2
```

> The problem is that if I increase beam_size, the translation time will increase

Correct.

**Comment by Jourdelune** [comment]
Ok, I'll try this, I have to know that I run the program on a vps with avx only, not avx2 or other

**Comment by Jourdelune** [comment]
It seems that Intel mlkit is used (mkl if it's right)

**Comment by guillaumekln** [comment]
Ok, it can also be reproduced when Intel MKL is used with AVX (`MKL_CBWR=AVX`).

I simply suggest increasing the beam size. Note that HuggingFace uses a beam size of 5 for this model while CTranslate2 uses 2 by default.

**Comment by Jourdelune** [comment]
ok, thanks for your answer^^

**Comment by grantmk** [comment]
Just a tip - not sure if it applies to your case. I've found the M2M models will give you repeated text if you have an out of memory error somewhere. Best to check your gunicorn / unicorn logs or run unicorn live and watch the output. 

Some language pairs (eg: Thai) VASTLY increase memory usage whether on CPU or GPU so watch for that! I have script that translates 5000+ word documents from every language to every other language. Each transaction logs the GPU mem usage (via Nvidia-smi) and free mem. That way I can see what's causing the OOM errors. By removing the 'problem' languages I can run this on a 1080 8gb and stay within memory range.

Hope that helps!
