### ISSUE TITLE
NMT Pre-trained Models from Desktop Translator - and plugins

### ISSUE THREAD

**Issue by drkhateeb** [OpenNMT/CTranslate2#730]
Hello developers
how to use these models here
NMT Pre-trained Models
https://www.machinetranslation.io/nmt-pretrained-models
with desktopTranslator

2- is there any plugin to connect (desktop translator) to Trados Studio 2021
3- is there any GUI tool to train/adapt new models using TMX parallel dataset?
regards

**Comment by guillaumekln** [comment]
Hi,

It is not the right place to ask about this. You should probably contact the author @ymoslem directly.
