### ISSUE TITLE
Getting error when translating using parameter "replace_unknowns=True"

### ISSUE THREAD

**Issue by vigneshmj1997** [OpenNMT/CTranslate2#731]
I converted a OpenNmtpy model to ctranslate2 model
when I use the given example in the readme and translate text i am getting a proper output 
but when i use **"replace_unknowns=True"** in translate_batch() params 
I am getting the following error  
**ValueError: can't index dimension 1 for a storage with rank 0**

**Comment by guillaumekln** [comment]
I would need more information since I don't immediately find an issue with this option.

What is the CTranslate2 version? What other translation options are you using?

**Comment by vigneshmj1997** [comment]
I have tried using *ctranslate2 (2.13.1)* and *ctranslate2 (2.12.0)*
The options that I am setting are :
``` 
translator = ctranslate2.Translator("ctranslate",intra_threads=4,device="CPU")
translator.translate_batch(batch,replace_unknowns=True,beam_size=5)
```
The ctranslate model used is *int8* quantized *(Binary version: 5)* and *(Model specification revision: 4)*, my CPU is a *AMD* processor and I  installed ctranslate using pip

**Comment by guillaumekln** [comment]
Are you using a Transformer model with less than 3 layers?

**Comment by vigneshmj1997** [comment]
No, i am using Transfomer with embedding size 512, encoder layers 12, and decoding layer 1, I have trained it on English to Dutch dataset in OpenNmt
When I use Ctranslate (2.6.0) I am not getting the above-mentioned error

**Comment by guillaumekln** [comment]
> decoding layer 1

I was thinking about the number of decoder layers specifically, which is indeed less than 3 in your case.

The issue is that the default value of `--alignment_layer` in OpenNMT-py is -3 meaning the third decoder layer from the end. This layer does not exist in your model so CTranslate2 can not extract any attention vectors which are required to implement `replace_unknowns`.

Can you try using `--replace_unk` in OpenNMT-py and see if it works there?

**Comment by vigneshmj1997** [comment]
I am getting a proper output when I infer using `--replace_unk' in OpenNmt-py (2.2.0)

**Comment by guillaumekln** [comment]
Thanks. I will update the converter to ignore the options `--alignment_layer` and `--alignment_heads` when the model was not trained with alignments (i.e. when `--lambda_align` is 0).
