### ISSUE TITLE
Support more general transformers (examples) such as GPT2?

### ISSUE THREAD

**Issue by jinfagang** [OpenNMT/CTranslate2#740]
Support more general transformers (examples) such as GPT2?

**Comment by guillaumekln** [comment]
Yes, we plan to support GPT-2.

**Comment by funboarder13920** [comment]
Hello @guillaumekln , last September I modified CTranslate2 to perform GPT2 inference.
I didn't create a PR as it was not easy to factorize GPT and seq2seq inferences.

Here is the code:
https://github.com/funboarder13920/CTranslate2/compare/funboarder13920:4340ca5b908c75fa5661e820654ee6355b1ccb0f...6b14d9a948c5d30c08cba8c9d20c49e73de97523

**Comment by guillaumekln** [comment]
Hi @funboarder13920, thanks for sharing! It's good to know you managed to integrate the LM model in the code.

I will probably add a new high-level class `Generator` so there is indeed some code to move around to factorize LM and seq2seq logics.

**Comment by jinfagang** [comment]
@guillaumekln Hi, wanna ask a question. we all know that GPT2 only large models can perform very well, all we want deploy large models. But the model is so huge, I have a GPT2 model was 7.6GB.

So just wonder, does this lib provides more decent techniques on deploy such huge models? Currently, the model is so huge no way to deploy it, except we have giant GPUs, It must quantized and shrink down to deploy, wonder how many advantages does this lib make to deploy huge models.

**Comment by guillaumekln** [comment]
CTranslate2 supports quantization which reduces the model size. For example the OpenAI GPT-2 model with 1.5B parameters is about 5.9GB. With 8-bit quantization the size goes down to 1.5GB.

**Comment by jinfagang** [comment]
@guillaumekln Waooo. that was exactly I want to achieve. Does there any tutorials to do same deploy on my customized model? I usually train the using Megatron-LM or HuggingFace, or export them to onnx. In which does CTranslate using to quantize?

**Comment by jinfagang** [comment]
@guillaumekln  thanks, that is promising. Which training framework will worked on gpt2 like models? such as megatron or huggingface? Seems these 2 are most popular among community

**Comment by guillaumekln** [comment]
The library is designed to work with any training framework as long as the model architecture is supported. We provide ready-to-use conversion scripts for selected training frameworks, but new conversion scripts can easily be added for other frameworks.
