### ISSUE TITLE
Crash on GPU with Compute Capability 5.0

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#758]
Hi Guillaume,

Just wanted to confirm: when the device type is `CUDA`, the `device_index` is referring only to the CUDA device number and not to any GPU installed on the system, right?
I'm trying to fix a creepy bug in a laptop that has integrated Intel graphics and a Geforce 940MX. My application detects if there is a CUDA device and sets the `device_index` to 0. Unfortunately, it crashes (logging has yet to be implemented to see what's going on...). When the app is used in a desktop with a single RTX 3070 GPU, it works fine. The Geforce 940MX has compute capability 5.0,  the drivers on the machine are the most recent (515.x I think), and the cublas dlls come from CUDA 11.4.
Thanks for any insights.

**Comment by guillaumekln** [comment]
Hi,

Yes, the index only refers to CUDA devices.

**Comment by guillaumekln** [comment]
Can you post the error message when you get it?

I think the Compute Capability 5.0 is this issue. We build CUDA kernels for the "common" Compute Capabilities as returned by CMake. It seems they recently removed CC 3.5 and 5.0 from this list when building with CUDA 11. These Compute Capabilities are indeed deprecated, but we should continue building for them until they are fully removed from CUDA.

**Comment by panosk** [comment]
Unfortunately, I can't get a log atm, and when the app crashes no errors are shown. I'll soon add some logging in that part of the code and then I can share it. I could see though through nvidia-smi in a brief remote session on that machine that the model is indeed loaded, but as soon as a translation is requested, the app crashes. I just created a custom patch that removes GPU support for this client and now all is good.
Moreover, I searched a bit about this GPU and it's not clear if it is supported for CUDA work. The Nvidia catalog with CUDA-enabled GPUs does not include it, others say it should be supported, etc.
So, until these CC are officially removed, is there a way I could demand a higher CC during build or runtime?

**Comment by guillaumekln** [comment]
What do you mean by "demand a higher CC"? Do you want to raise an error if the CC is unsupported?

**Comment by panosk** [comment]
My understanding is that as long as CC >=3.5, then `get_gpu_count()` will return >0 and `has_gpu` will return `true`, so as it is now I can't raise an error. Since 3.5 and 5 are not enough to have a working executable, can't we just raise the requirement in the CMakeLists? Will sth like that work? https://stackoverflow.com/questions/48274058/how-do-i-set-cuda-architecture-to-compute-50-and-sm-50-from-cmake-3-10-version

**Comment by guillaumekln** [comment]
The solution is to compile the code for these older architectures. If you are compiling from the source, you could manually select the CC to compile for:

```bash
cmake -DWITH_CUDA=ON -DCUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6;8.6+PTX" ..
```

We will include CC 3.5 and 5.0 in the default list for the next version.

**Comment by panosk** [comment]
I see, so no support is built for them. I just checked and support is indeed built for 5.3 and upwards. So, is there a way to work the other way around? I mean, how can I remove support for 3.5 and 5 so `has_gpu` returns `false`?

**Comment by guillaumekln** [comment]
> I mean, how can I remove support for 3.5 and 5 so has_gpu returns false?

The CC should be checked in the code. Currently we call `cudaGetDeviceCount` which returns the number of devices with CC >= 2.0. The minimum CC is not configurable here. An additional logic is needed to filter the devices based on the CC.

**Comment by panosk** [comment]
> The CC should be checked in the code. Currently we call `cudaGetDeviceCount` which returns the number of devices with CC >= 2.0. The minimum CC is not configurable here. An additional logic is needed to filter the devices based on the CC.

Thanks a ton!
