### ISSUE TITLE
GPU usage with pip install

### ISSUE THREAD

**Issue by MathieuGrosso** [OpenNMT/CTranslate2#760]
Hello, 
I wanted to know when the PyPI package will support GPU execution ? As I cannot use the docker image it is really long to generate sentences. 
I am trying to benchmark M2M VS specialized model on Tatoeba-challenge dataset. As I am working on many pairs, it is really long to do. If GPU was included it would be really helpful. 
Thanks a lot. 
Mathieu

**Comment by guillaumekln** [comment]
Hi,

The PyPI package already supports GPU execution. Do you get an error?

Make sure to check the current requirements in the [README](https://github.com/OpenNMT/CTranslate2#installation).

**Comment by MathieuGrosso** [comment]
Hello, 
First thanks a lot for quick reply. Sorry, I was using a too old version on my env so that was why I thought you had not add gpu execution. Thanks 

By the way, now that I have updated ctranslate I get this error: 
Runtime error: Library libcublas.so.11 is not found or connot be loaded
when using ctranslate2.Translator(..,device='cuda'). 

I have checked requirements and it was all ok so I was wondering if you know why ? Thanks anyway :)

**Comment by guillaumekln** [comment]
Which CUDA version did you install and how did you install it?

**Comment by MathieuGrosso** [comment]
Cuda version:  10.1.
And I have installed via docker with the image :nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04. I saw that on requirements the cuda version was optional so I don't know if the error can come from this. 
Thanks.

**Comment by guillaumekln** [comment]
The CUDA version is not optional if you want to use GPU. You should install CUDA 11 as indicated in the requirements.
