### ISSUE TITLE
How to decode on Multi-CPU

### ISSUE THREAD

**Issue by Mr-wang2016** [OpenNMT/CTranslate2#768]
Hi:

I hava a machine with cpu only. I compile the ctranslate2 with 'cmake -DWITH_MKL=ON -DWITH_CUDA=OFF -DOPENMP_RUNTIME=NONE ..' cmd.
When i run the C++ API, I set num_translators=2 and num_threads_per_translator=4. I expect it to use multiple cpu. But the process uses only one CPU core and the utilization is 100%. Is this normal and am I missing something?

**Comment by panosk** [comment]
Hi there,

You should compile with `-DOPENMP_RUNTIME=INTEL`.

**Comment by Mr-wang2016** [comment]
Thanks for your fast response.
I try with -DOPENMP_RUNTIME=INTEL. The result is that the number of cpus used is half of the total number of machine cpus. I can't control it via  num_translators and num_threads_per_translator. Do you have any suggestions please?

**Comment by panosk** [comment]
Does your machine have multiple physical CPUs or a single CPU with multiple cores? If it's a single CPU, then you can set `num_translators` to half the number of all your physical and virtual (multithreading) cores and `num_threads_per_translator` to 2. This works fine on my machines. If your PC has multiple physical processors, then you should set accordingly `device_index`.

**Comment by Mr-wang2016** [comment]
Yeah, I have a 2 physical CPUs with 64 cores. I set device_index to 0.
 I tried multiple times and when I set num_translators=6 and  num_threads_per_translator=2, the cpu usage reached 3200%. I changed the value of num_translators, but the cpu usage remains the same. It seems that num_translators doesn't work, i don't know why..

**Comment by guillaumekln** [comment]
How are you running the translation?

To benefit from the translators running in parallel (`num_translators`), you should send multiple input batches at once. For example you can call `translate_batch_async` multiple times, or you can call `translate_batch` and set `max_batch_size`.

See this Python documentation which is also relevant to the C++ API (the exact methods name may be different): https://github.com/OpenNMT/CTranslate2/blob/master/docs/python.md#note-on-parallel-execution

**Comment by Mr-wang2016** [comment]
I'm sorry, I'm afraid there are some environmental issues on my previous machine. After I replaced a machine, the problem disappeared.
Thank you very much for your help! !
