### ISSUE TITLE
How should I pass user_dir when converting a fairseq trained model?

### ISSUE THREAD

**Issue by zhuyl96** [OpenNMT/CTranslate2#781]
Hi, I am using this ctranslate2 to convert my model trained with **fairseq**.

I defined my own model structure (still based on Transformer) using `user_dir` when training the fairseq model, registered the arch name of the model as `transformer_mid_12e3d`.

My question is: how should I pass in my `user_dir` when converting the model using `ct2-fairseq-converter`?

**Comment by guillaumekln** [comment]
Hi,

The linked PR adds a `--user_dir` option to the Fairseq converter. You should be able to convert your custom model after this change.

**Comment by zhuyl96** [comment]
Awesome, thank you so much!
