### ISSUE TITLE
OpenNMT Multi-Source feature Conversion

### ISSUE THREAD

**Issue by smcdufff** [OpenNMT/CTranslate2#789]
We have a model with 7 features in opennmt-tf.

The conversion tools seem to only support one vocabulary.

ct2-opennmt-tf-converter --model_path averaged-ende-ckpt500k-v2 --output_dir ende_ctranslate2 \
    --src_vocab averaged-ende-ckpt500k-v2/wmtende.vocab \
    --tgt_vocab averaged-ende-ckpt500k-v2/wmtende.vocab \
    --model_type TransformerBase

Also, does CTranslate2 supports custom Transformer from OpenNMT-Tf ? 

 source_inputter=opennmt.inputters.ParallelInputter(
                [
                    opennmt.inputters.WordEmbedder(embedding_size=512),
                    opennmt.inputters.WordEmbedder(embedding_size=16),
                    opennmt.inputters.WordEmbedder(embedding_size=16),
                    opennmt.inputters.WordEmbedder(embedding_size=16),
                    opennmt.inputters.WordEmbedder(embedding_size=16),
                    opennmt.inputters.WordEmbedder(embedding_size=16),
                ],
                reducer=opennmt.layers.ConcatReducer(),
            ),

 train_features_file:
        - input-1-2.fr
        - input-1-3.fr
        - input-1-4.fr
        - input-1-5.fr
        - input-1-6.fr
        - input-1-7.fr
  train_labels_file: input-1-1.fr

  source_1_vocabulary: vocab-2.txt
  source_2_vocabulary: vocab-3.txt
  source_3_vocabulary: vocab-4.txt
  source_4_vocabulary: vocab-5.txt
  source_5_vocabulary: vocab-6.txt
  source_6_vocabulary: vocab-7.txt

  target_vocabulary: vocab-1.txt

**Comment by guillaumekln** [comment]
We should update this converter to better support custom models and additional source features, which are supported by CTranslate2.

**Comment by smcdufff** [comment]
Wow! Thank you! I will try it!
