### ISSUE TITLE
Compilation error with MKL: undefined reference to `cblas_sgemm_batch_strided`

### ISSUE THREAD

**Issue by raphaelmerx** [OpenNMT/CTranslate2#800]
Trying to compile CTranslate2 on CPU after installing MKL 2022.1.0-223 (through `intel-oneapi-mkl-devel`), getting the following error during compilation:

```bash
[100%] Linking CXX executable translate
/usr/bin/ld: ../libctranslate2.so: undefined reference to `cblas_sgemm_batch_strided'
```

Tried installing MKL 2021.4.0 instead through `apt install intel-oneapi-mkl-devel-2021.4.0`, but got the same error.

**Comment by guillaumekln** [comment]
Can you share the full compilation logs?

```bash
cd build
rm CMakeCache.txt
cmake ..
VERBOSE=1 make
```

**Comment by raphaelmerx** [comment]
Thanks for your response. I re-created a VPS today, same OS and all, and could compile without error. The only difference I can think of is that the VPS that threw the compile error above had initially installed MKL from `apt install intel-mkl`...

I ran into more compile errors though when running `python setup.py bdist_wheel`:
```
building 'ctranslate2.translator' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/root/tetuntranslator/venv/lib/python3.8/site-packages/pybind11/include -I/root/tetuntranslator/venv/include -I/usr/include/python3.8 -c translator.cc -o build/temp.linux-x86_64-cpython-38/translator.o -std=c++17
translator.cc:11:10: fatal error: ctranslate2/translator_pool.h: No such file or directory
   11 | #include <ctranslate2/translator_pool.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

After looking at `setup.py` I added `CTRANSLATE2_ROOT=<path>` to my env, which fixes that error by adding the include dir to `include_dirs`, however I then run into another error:

```
building 'ctranslate2.translator' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/root/tetuntranslator/venv/lib/python3.8/site-packages/pybind11/include -I/root/CTranslate2/include -I/root/tetuntranslator/venv/include -I/usr/include/python3.8 -c translator.cc -o build/temp.linux-x86_64-cpython-38/translator.o -std=c++17
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 build/temp.linux-x86_64-cpython-38/translator.o -L/usr/lib -lctranslate2 -o build/lib.linux-x86_64-cpython-38/ctranslate2/translator.cpython-38-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lctranslate2
```

Let me know if you prefer I open a separate issue for this.

**Comment by guillaumekln** [comment]
What is the directory structure of `/root/CTranslate2/`?

**Comment by raphaelmerx** [comment]
Apologies I hadn't run `make install`, only `make`. Python install works now.

`/root/CTranslate2/` was this repository cloned, with `build` and `python` dirs underneath.

Thanks again for this project, hugely useful for getting fast(er) inference for translation models.
