### ISSUE TITLE
Transformers Marian produces translation that ends in gibberish for multilingual models

### ISSUE THREAD

**Issue by raphaelmerx** [OpenNMT/CTranslate2#832]
### Description

Some Marian models support multiple language targets through the usage of a language code at the beginning of string e.g. `>>ind<< I'm coming`. This seems to result in a correct translation + gibberish appended after conversion through cTranslate2, even though the bilingual models work fine.

#### Convert model `opus-mt-en-roa`
```bash
ct2-transformers-converter --model Helsinki-NLP/opus-mt-en-roa --output_dir ct2-opus-mt-en-roa
```

### Translate
```python
import ctranslate2
import transformers

translator = ctranslate2.Translator("ct2-opus-mt-en-roa")
tokenizer = transformers.AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-roa")

sentences = ['The Prime Minister is coming back tomorrow.']

batch = [tokenizer.convert_ids_to_tokens(tokenizer.encode(f'>>ind<< {sentence}')) for sentence in sentences]

results = translator.translate_batch(batch)
target = results[0].hypotheses[0]

print(tokenizer.decode(tokenizer.convert_tokens_to_ids(target)))
# Perdana Menteri akan datang kembali besok.@info@info: tooltip@info@info: tooltip@info/ plain _BAR_ _BAR_ _BAR_ _BAR__________________________________________________________________________________________________________________________________________________________________________________________________________________________
```

Translation should end at "besok.", yet continues with "@info....", even though the `</s>` is present in the encoded sentence.

**Comment by guillaumekln** [comment]
Thanks for reporting.

A bias term used by this model is ignored by the Transformers converter. The linked PR will fix this issue.

**Comment by raphaelmerx** [comment]
Great many thanks for the quick fix

**Comment by redthing1** [comment]
I'm still having this issue.

Source model: https://huggingface.co/Helsinki-NLP/opus-mt-ru-en

I verified that it works fine with HF.

Converting model:
`ct2-transformers-converter --model ./opus-mt-ru-en --output_dir ct2-opus-mt-ru-en-f32`

Then I load tokenizer from `source.spm`, and do inference with the input:

`Я предпочитаю покупать сыр в местном магазине.`

HF output: `I prefer to buy cheese at the local store.` (correct)
CT2 output: ` I prefer to buy cheese cheese at a local local store in the local local shop-- local shop... and, uh, I prefer me more than buying cheese.`

Unsure what is wrong here. Any idea?

Inference code:
```py
import ctranslate2
import sentencepiece as spm
from sys import argv
import os
 
MODEL = argv[1]
PROMPT = argv[2]

sp = spm.SentencePieceProcessor(f"{MODEL}/spiece.model")

if os.path.exists(PROMPT):
    with open(PROMPT, 'r') as f:
        prompt = f.read()
else:
    prompt = PROMPT

prompt_tokens = sp.encode(prompt, out_type=str)
print('input tokens', prompt_tokens)

print('Loading model...')
translator = ctranslate2.Translator(MODEL, device="cpu")
print('Executing model...')
results = translator.translate_batch(
    [prompt_tokens],
    beam_size=5,
    repetition_penalty=1.1,
    sampling_topk=40,
    sampling_temperature=0.8,
    return_scores=True,
    num_hypotheses=1,
)

print('results', results[0])
output_str = ''.join(results[0].hypotheses[0]).replace('▁', ' ')

print('output:', output_str)
```

**Comment by guillaumekln** [comment]
You are using random sampling (`sampling_topk`), so it is expected that the output is different.

What parameters are you setting for HF generation? You should try to use the same parameters with CT2.

**Comment by redthing1** [comment]
Well, for HF I am simply using the defaults: https://huggingface.co/Helsinki-NLP/opus-mt-ru-en/blob/main/generation_config.json

And then I call ct2 like this:
```
results = translator.translate_batch(
    [prompt_tokens],
    beam_size=6,
    return_scores=True,
    num_hypotheses=1,
)
```

Still getting weird output: `I'd prefer to buy cheese cheese at a local local store in a local local local store... local store... and I prefer I prefer to buy cheese at a local local store.`

**Comment by redthing1** [comment]
Apologies, I don't know why I missed that. Thank you very much; it solves my issue!
