### ISSUE TITLE
Repeated text with Marian Model generation

### ISSUE THREAD

**Issue by ArtanisTheOne** [OpenNMT/CTranslate2#836]
Using the example put in your docs regarding Transformers conversion, I am using the Spanish model instead
```python
import ctranslate2
import transformers

translator = ctranslate2.Translator("opus-mt-en-es")
tokenizer = transformers.AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-es")

source = tokenizer.convert_ids_to_tokens(tokenizer.encode("Hello world!"))
results = translator.translate_batch([source])
target = results[0].hypotheses[0]

print(tokenizer.decode(tokenizer.convert_tokens_to_ids(target)))
```
The result is the following:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/52015929/173931178-598d6adc-8273-46ba-a19a-9c7246dc48ff.png">

Model has not been quantized in anyway and I used the same conversion args provided in docs [here](https://opennmt.net/CTranslate2/guides/transformers.html#marianmt)

I've attempted setting repetition penalty but the model works around it and generates different words instead. This seems to just be a ctranslate2 conversion issue as the model itself doesn't seem to have these issues. I tried finetuning the model a bit thinking it was an issue with the transformer model but to no effect. This issue seems to be present in other marian models as well but to varying extenses (russian has the issue with some texts but not others). 

`Version: 2.18.0`
`Using: CPU`

**Comment by ArtanisTheOne** [comment]
An example;
<img width="782" alt="image" src="https://user-images.githubusercontent.com/52015929/173933645-40ff338b-91f7-46f6-b55e-c2650fd7657e.png">

<img width="430" alt="image" src="https://user-images.githubusercontent.com/52015929/173933663-f70f2b0b-2fb0-45ae-866d-a604f76b6111.png">

**Comment by guillaumekln** [comment]
Thanks for reporting.

It is actually the same issue as #832 which is already fixed on master. We will release a new version soon.

**Comment by ArtanisTheOne** [comment]
My bad, didn't see it. Thank you
