### ISSUE TITLE
Quantizing model with int8 produces gibberish content

### ISSUE THREAD

**Issue by santha96** [OpenNMT/CTranslate2#847]
Hi,

I trained my translation student model with fairseq toolkit. I converted the fairseq model to the ctranslate model using ct2-fairseq-converter and used int8 quantization but observed some gibberish content in translation output. could you please help?

student model configs:
architecture : transformer
encoder layers : 12
decoder layers : 2
enc/dec embedding dim : 512
fp16 - enabled
Total parameters: 93M

source sentence:
Michael Jackson wore tape on his nose to get front pages, former bodyguard claims

translation output :
student model op:
Michael Jackson nosil pásku na nose, aby dostal titulní strany, tvrdí bývalý bodyguard

with int8 quantization:
ginearta,хунхунхунхунхунхунхунхунхунхунхунхунхунхунхунgineхун.хунgineхунхунхун.хунхунхунхун.хунхунхунхун

with float16 quantization:
Michael Jackson si na nose na nose, aby se dostal na titulní strany, tvrdí bývalý bodyguard

observed translation output like this (int8) for all the source sentences.

Note: FP16 works well.

**Comment by guillaumekln** [comment]
Hi,

Are you able to share this model? It's difficult to determine the issue without running the model.

**Comment by guillaumekln** [comment]
I'm closing this issue for lack of update. Feel free to reopen if you can provide more information to reproduce the issue.
