### ISSUE TITLE
error when translating with cuda

### ISSUE THREAD

**Issue by kkeleve** [OpenNMT/CTranslate2#862]
Hi , I convert the fairseq model to ctran2, it works fine when I use cpu to translate, but I get an error when I use gpu to translate 
**code:**
`ct2-fairseq-converter --model_path $model_save  --data_dir $data_bin  --output_dir /root/ckpt/baseline_s1/ckpt_ctranslate2`

```
translator = ctranslate2.Translator("/root/ckpt/baseline_s1/ct2_model/", device="cuda",device_index=0)
results = translator.translate_batch(input_data)
```
**error:**
Traceback (most recent call last):
  File "ctran2_infer.py", line 19, in <module>
    results = translator.translate_batch(input_data)
RuntimeError: Library libcublas.so.11 is not found or cannot be loaded

**Comment by guillaumekln** [comment]
Hi,

You should install CUDA 11 on the system. You can find installation instructions here: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by kkeleve** [comment]
hi , my system is currently installed with cuda11
![image](https://user-images.githubusercontent.com/73747121/176991850-488bbc24-87c5-4fd8-920a-abc7e2669b36.png)
Also , I run the command you mentioned in the other issue and get the following output
![image](https://user-images.githubusercontent.com/73747121/176991964-cdec5340-6579-43d7-b04a-4204c025c018.png)

**Comment by guillaumekln** [comment]
It seems you installed the GPU driver for CUDA 11, but you did not install the CUDA 11 toolkit. You should follow the instructions in the link I posted earlier.

**Comment by kkeleve** [comment]
Hi, @[guillaumekln](https://github.com/guillaumekln) thanks for your help, I have solved the above problem.
I am facing another problem now , please how to apply length penalty = 1.6 like fairseq ? I only found in the documentation how to apply beamsearch

**Comment by BrightXiaoHan** [comment]
Hi @kkeleve, follow this [api document](https://opennmt.net/CTranslate2/python/ctranslate2.Translator.html#ctranslate2.Translator.translate_batch). Paramater "length_penalty" is all you need.

**Comment by guillaumekln** [comment]
Thanks for the help @BrightXiaoHan.

@kkeleve Looks like all your issues are resolved for now. Feel free to open other issues if needed. Also make sure to browse the documentation first which already has a lot of useful information.
