### ISSUE TITLE
Ctranslate2 Model RAM Utilization

### ISSUE THREAD

**Issue by santha96** [OpenNMT/CTranslate2#870]
Hi,
I converted the fairseq model to ctranslate2 using ct2-fairseq-converter using int8 quantization. The resultant model size is 67MB (vmap is not included). Loaded this model into the RAM and served it using a gunicorn.a configured number of workers as "one" and preload_app as "false".Verified RAM usage after loading model which is 267MB.After sending the initial request, the RAM usage spiked to 751MB. may I know whether the above-mentioned functionality is expected?. if so, could you pls explain why?

**Comment by guillaumekln** [comment]
Depending on how you are running the translator, this memory usage is possible.

Can you try using the CTranslate2 translator directly (not via a Gunicorn server) and report your observations?

You should also post the code snippet you are running.

**Comment by santha96** [comment]
ctranslate model file size that i used for verifying memory usage is 67MB (int8 quantized file).Executed the CTranslate2 translator directly without Gunicorn server.Pasted the code below.
`import ctranslate2
import os, psutil
import numpy as np
def ctranslate(translator,input_sentences):
    batch = []
    output = []
    for i in input_sentences:
        batch.append(i.split(" "))
        lengths = np.array([len(t) for t in batch])
        translations = translator.translate_batch(
            batch,
            max_batch_size=128,
            beam_size=3,
            max_decoding_length=max(lengths) * 2,
            replace_unknowns=True,
            use_vmap=False,
        )
        output = [" ".join(i[0]["tokens"]) for i in translations]
    return output


print("The memory is taken to load packages:(in MB)")
process = psutil.Process(os.getpid())
print(float(process.memory_info().rss)/1048576)
print("The memory is taken to load the ctranslate model file: (in MB)")
translator = ctranslate2.Translator("ctranslate/",device="cpu", inter_threads=1, intra_threads=4)
process = psutil.Process(os.getpid())
print(float(process.memory_info().rss)/1048576)
test_sen=open("sent_test_10.ENG","r")
print("The memory taken to process requests:(in MB)")
output=ctranslate(translator,test_sen.readlines())
process = psutil.Process(os.getpid())
print(float(process.memory_info().rss)/1048576)
`
output:
The memory is taken to load packages:(in MB)
40.98046875
The memory is taken to load the ctranslate model file: (in MB)
113.3203125
The memory taken to process requests:(in MB)
151.94140625

Here, the usage is normal. I ll further check with the Gunicorn server.
