### ISSUE TITLE
Add support for microsoft/DialoGPT input

### ISSUE THREAD

**Issue by NeonBohdan** [OpenNMT/CTranslate2#879]
CTranslate2 has support of regular GPT2
It also succesfuly converts [DialoGPT-medium](https://huggingface.co/microsoft/DialoGPT-medium)

The problem appears on inference stage
DialoGPT is a conversational model. It uses `'<|endoftext|>'` to separate speakers in sequence.

When I provide regular input it works as regular GPT-2 generating sequence until `EOS token` 
But when I pass `Hello<|endoftext|>` it returns just `Hello`
But normal DialoGPT returns `Hello<|endoftext|>Hello! :D<|endoftext|>`
____
As I understand it sees `EOS token` and immideately stops generation
But I need a bit different logic, generate until next `EOS token`

I see a great increase in performance comparing to pytorch version
None of [ctranslate2.Generator.generate_batch](https://opennmt.net/CTranslate2/python/ctranslate2.Generator.html?highlight=generate_batch#ctranslate2.Generator.generate_batch) input params can fix it

Can it be somehow implemented?

**Comment by guillaumekln** [comment]
Thank you for opening this issue.

The easiest change in the code seems to not stop the decoding if EOS is coming from the user input instead of the model output.

**Comment by NeonBohdan** [comment]
Agree. Pretty simple, it just never happened before. Thanks a lot

**Comment by NeonBohdan** [comment]
Thanks for being so responsive, now it works, patiently waiting for sub-release
Compiled from source

Input: `Hello how are you<|endoftext|>`
Output: `Hello how are you<|endoftext|>I'm good, how are you?`

**Comment by guillaumekln** [comment]
I just released version 2.21.0 which includes this change.
