### ISSUE TITLE
converted BART summaries are just <s> tokens

### ISSUE THREAD

**Issue by sorenmc** [OpenNMT/CTranslate2#885]
Hi, thanks for an absolutely amazing and intuitive inference framework - been using this for translation for some time! 

I recently noticed that other sequence2sequence tasks are also supported, and more specifically BART! I am trying to use a BART model for summarization with the CTranslate2 framework. I converted the model https://huggingface.co/knkarthick/MEETING_SUMMARY which is a finetuned version of https://huggingface.co/facebook/bart-large-xsum. The command i used for conversion was

```bash
ct2-transformers-converter --model knkarthick/MEETING_SUMMARY --quantization float16 --output_dir knkarthick_meeting_summary
```

The tokenizer i use is the one supplied by the huggingface repository in https://huggingface.co/knkarthick/MEETING_SUMMARY

And the inference code i use is 

```python
#
# from transformers import AutoTokenizer
# import ctranslate2
# self.model = ctranslate2.Translator(path_to_converted_model, device="cuda")
# self.tokenizer = AutoTokenizer.from_pretrained("knkarthick/MEETING_SUMMARY")

summaries: List[str] = []
for i in range(0, len(texts_to_summarize), batch_size):
   batch: List[str] = texts_to_summarize[i : i + batch_size]
   # tokenize texts
   batch_tokenized = [self.tokenizer.convert_ids_to_tokens(tokenized) for tokenized in self.tokenizer(batch, truncation=True)["input_ids"]]
   batch_summarized_tokenized = self.model.translate_batch(batch_tokenized,
                                          beam_size=4, 
                                          allow_early_exit=True,
                                          max_decoding_length=128,
                                          min_decoding_length=32)
   batch_summarized = [self.tokenizer.decode(self.tokenizer.convert_tokens_to_ids(result.hypotheses[0]), skip_special_tokens=True) for result in batch_summarized_tokenized]
   summaries.extend(batch_summarized)
```

This code works perfectly for the translator, [and looking at the documentation](https://opennmt.net/CTranslate2/guides/transformers.html#bart) this should work. However the output is just a sequence of "< s>".

 I have been looking into other issues with BART like https://github.com/OpenNMT/CTranslate2/issues/816, so i am speculating whether it could be that the specific model architecture of `bart-large-xsum` is somehow different than `bart-large-cnn`?

**Comment by guillaumekln** [comment]
Hi,

It seems this model will naturally produce a sequence of `<s>` unless this is blocked with the parameter `no_repeat_ngram_size`. The configurations of `facebook/bart-large-xsum` and this fine-tuned model use `no_repeat_ngram_size=3`.

You should get the expected output if you apply the same decoding parameters as defined the model configuration. Try the following parameters:

```python
results = translator.translate_batch(
    batch_tokenized,
    beam_size=6,
    allow_early_exit=False,
    normalize_scores=True,
    no_repeat_ngram_size=3,
    min_decoding_length=11,
    max_decoding_length=62,
)
```

**Comment by sorenmc** [comment]
Thank you so much for the quick reply! Will try this in a moment to check it out!

**Comment by sorenmc** [comment]
Sorry for the delay!
This worked perfectly, again thanks for the quick reply and help.
Closing as this solved the problem.
