### ISSUE TITLE
Support for armv7  (Raspberry)

### ISSUE THREAD

**Issue by ecxod** [OpenNMT/CTranslate2#891]
I tried to pip ctranslate2>=2.17.0 and I found out that there is no such package

```
# uname -a
Linux blackpi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

# pip install ctranslate2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement ctranslate2
ERROR: No matching distribution found for ctranslate2
```

for amd64 seems no problem. Could you please upload a armv7 version?

**Comment by guillaumekln** [comment]
We publish Python packages for ARMv8, but not for v7.

The main reason is that the Python build ecosystem does not support ARMv7 as far as I know. We use [manylinux](https://github.com/pypa/manylinux) and [cibuildwheel](https://github.com/pypa/cibuildwheel) to build the Python packages and both do not support ARMv7. You can refer to these issues:

* https://github.com/pypa/cibuildwheel/issues/642
* https://github.com/pypa/manylinux/issues/84

**Comment by guillaumekln** [comment]
Realistically we will not build packages for ARMv7 as part of our automated builds. It's too much additional work for a platform that is quite old and generally not powerful enough to run the models covered by CTranslate2. It should still be possible to manually compile the library on ARMv7 but we will not actively support this use case. Thank you for your understanding.
