### ISSUE TITLE
module 'ctranslate2' has no attribute 'Translator'

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/CTranslate2#90]
Command line installation results in:

module 'ctranslate2' has no attribute 'Translator'

**Comment by guillaumekln** [comment]
Which installation procedure did you follow? https://github.com/OpenNMT/CTranslate2#installation

**Comment by anderleich** [comment]
Manual compilation following Docker file

**Comment by guillaumekln** [comment]
You can remove the `try`/`except` to see why the `translator` is not loaded: https://github.com/OpenNMT/CTranslate2/blob/master/python/ctranslate2/__init__.py

Otherwise, you could just use one of the prebuilt Docker images: https://hub.docker.com/r/opennmt/ctranslate2/tags

**Comment by anderleich** [comment]
This is what I get:
ImportError: libctranslate2.so: cannot open shared object file: No such file or directory

**Comment by anderleich** [comment]
I get no error when removing the try/except block. I can istall it succesfully, but it still doesn't fing the Translator attribute

**Comment by guillaumekln** [comment]
Did you update the `LD_LIBRARY_PATH` environment variable as in the [Dockerfile](https://github.com/OpenNMT/CTranslate2/blob/v1.4.0/docker/Dockerfile.ubuntu-gpu#L136)?

**Comment by anderleich** [comment]
Thanks!! That solved my issue
