### ISSUE TITLE
Method  generate_batch  is missing a parameter   eos_token_id

### ISSUE THREAD

**Issue by Nightbringers** [OpenNMT/CTranslate2#907]
The model doesn't know when to stop generating, because it  missing a parameter  eos_token_id.  eos_token_id (int, optional) — The id of the end-of-sequence token.

**Comment by guillaumekln** [comment]
The generation uses the EOS token that is defined by the model's tokenizer.

Do you want to set another EOS token? If yes, see the existing issue #896.

**Comment by Nightbringers** [comment]
> 
Yes, my opinion is the same as his. This feature is  very useful right now. We use OPT, the model continues to generate even after the EOS token is generated. It would be awesome if your generate_batch() function could support eos_token_id 
 parameter.

**Comment by Nightbringers** [comment]
Now i know, i set  <|endoftext|>  to be the EOS token , you should say in the documentation that the default is </s>.

**Comment by guillaumekln** [comment]
The EOS token depends on the model. You can check it in the model configuration:

```python
>>> import transformers
>>> model = transformers.AutoModel.from_pretrained("facebook/opt-125m")
>>> model.config.eos_token_id
2
>>> tokenizer = transformers.AutoTokenizer.from_pretrained("facebook/opt-125m", use_fast=False)
>>> tokenizer.decode(model.config.eos_token_id)
'</s>'
```

I'm closing this issue since the correct EOS token is already used by the model. Issue #896 is still open to allow setting another EOS token.
