### ISSUE TITLE
Does ctranslate2 support the deep transformer model?

### ISSUE THREAD

**Issue by AIikai** [OpenNMT/CTranslate2#908]
As the title, I see a deep model architecture based on fairseq -- https://github.com/libeineu/GPKD, and I want to train a translation model with it. If I want to use ctranslate2, what can I do? Do I need to change something? Can you give me some advice? thank you.

**Comment by AIikai** [comment]
`model: odict_keys(['encoder.version', 'encoder.embed_tokens.weight', 'encoder.embed_positions._float_tensor', 'encoder.layers.0.self_attn.in_proj_weight', 'encoder.layers.0.self_attn.in_proj_bias', 'encoder.layers.0.self_attn.relative_position_keys', 'encoder.layers.0.self_attn.out_proj.weight', 'encoder.layers.0.self_attn.out_proj.bias', 'encoder.layers.0.fc1.weight', 'encoder.layers.0.fc1.bias', 'encoder.layers.0.fc2.weight', 'encoder.layers.0.fc2.bias', 'encoder.layers.0.layer_norms.0.weight', 'encoder.layers.0.layer_norms.0.bias', 'encoder.layers.0.layer_norms.1.weight', 'encoder.layers.0.layer_norms.1.bias', 'encoder.layers.1.self_attn.in_proj_weight', 'encoder.layers.1.self_attn.in_proj_bias', 'encoder.layers.1.self_attn.relative_position_keys', 'encoder.layers.1.self_attn.out_proj.weight', 'encoder.layers.1.self_attn.out_proj.bias', 'encoder.layers.1.fc1.weight', 'encoder.layers.1.fc1.bias', 'encoder.layers.1.fc2.weight', 'encoder.layers.1.fc2.bias', 'encoder.layers.1.layer_norms.0.weight', 'encoder.layers.1.layer_norms.0.bias', 'encoder.layers.1.layer_norms.1.weight', 'encoder.layers.1.layer_norms.1.bias', 'encoder.layers.2.self_attn.in_proj_weight', 'encoder.layers.2.self_attn.in_proj_bias', 'encoder.layers.2.self_attn.relative_position_keys', 'encoder.layers.2.self_attn.out_proj.weight', 'encoder.layers.2.self_attn.out_proj.bias', 'encoder.layers.2.fc1.weight', 'encoder.layers.2.fc1.bias', 'encoder.layers.2.fc2.weight', 'encoder.layers.2.fc2.bias', 'encoder.layers.2.layer_norms.0.weight', 'encoder.layers.2.layer_norms.0.bias', 'encoder.layers.2.layer_norms.1.weight', 'encoder.layers.2.layer_norms.1.bias', 'encoder.layers.3.self_attn.in_proj_weight', 'encoder.layers.3.self_attn.in_proj_bias', 'encoder.layers.3.self_attn.relative_position_keys', 'encoder.layers.3.self_attn.out_proj.weight', 'encoder.layers.3.self_attn.out_proj.bias', 'encoder.layers.3.fc1.weight', 'encoder.layers.3.fc1.bias', 'encoder.layers.3.fc2.weight', 'encoder.layers.3.fc2.bias', 'encoder.layers.3.layer_norms.0.weight', 'encoder.layers.3.layer_norms.0.bias', 'encoder.layers.3.layer_norms.1.weight', 'encoder.layers.3.layer_norms.1.bias', 'encoder.layers.4.self_attn.in_proj_weight', 'encoder.layers.4.self_attn.in_proj_bias', 'encoder.layers.4.self_attn.relative_position_keys', 'encoder.layers.4.self_attn.out_proj.weight', 'encoder.layers.4.self_attn.out_proj.bias', 'encoder.layers.4.fc1.weight', 'encoder.layers.4.fc1.bias', 'encoder.layers.4.fc2.weight', 'encoder.layers.4.fc2.bias', 'encoder.layers.4.layer_norms.0.weight', 'encoder.layers.4.layer_norms.0.bias', 'encoder.layers.4.layer_norms.1.weight', 'encoder.layers.4.layer_norms.1.bias', 'encoder.layers.5.self_attn.in_proj_weight', 'encoder.layers.5.self_attn.in_proj_bias', 'encoder.layers.5.self_attn.relative_position_keys', 'encoder.layers.5.self_attn.out_proj.weight', 'encoder.layers.5.self_attn.out_proj.bias', 'encoder.layers.5.fc1.weight', 'encoder.layers.5.fc1.bias', 'encoder.layers.5.fc2.weight', 'encoder.layers.5.fc2.bias', 'encoder.layers.5.layer_norms.0.weight', 'encoder.layers.5.layer_norms.0.bias', 'encoder.layers.5.layer_norms.1.weight', 'encoder.layers.5.layer_norms.1.bias', 'encoder.layers.6.self_attn.in_proj_weight', 'encoder.layers.6.self_attn.in_proj_bias', 'encoder.layers.6.self_attn.relative_position_keys', 'encoder.layers.6.self_attn.out_proj.weight', 'encoder.layers.6.self_attn.out_proj.bias', 'encoder.layers.6.fc1.weight', 'encoder.layers.6.fc1.bias', 'encoder.layers.6.fc2.weight', 'encoder.layers.6.fc2.bias', 'encoder.layers.6.layer_norms.0.weight', 'encoder.layers.6.layer_norms.0.bias', 'encoder.layers.6.layer_norms.1.weight', 'encoder.layers.6.layer_norms.1.bias', 'encoder.layers.7.self_attn.in_proj_weight', 'encoder.layers.7.self_attn.in_proj_bias', 'encoder.layers.7.self_attn.relative_position_keys', 'encoder.layers.7.self_attn.out_proj.weight', 'encoder.layers.7.self_attn.out_proj.bias', 'encoder.layers.7.fc1.weight', 'encoder.layers.7.fc1.bias', 'encoder.layers.7.fc2.weight', 'encoder.layers.7.fc2.bias', 'encoder.layers.7.layer_norms.0.weight', 'encoder.layers.7.layer_norms.0.bias', 'encoder.layers.7.layer_norms.1.weight', 'encoder.layers.7.layer_norms.1.bias', 'encoder.layers.8.self_attn.in_proj_weight', 'encoder.layers.8.self_attn.in_proj_bias', 'encoder.layers.8.self_attn.relative_position_keys', 'encoder.layers.8.self_attn.out_proj.weight', 'encoder.layers.8.self_attn.out_proj.bias', 'encoder.layers.8.fc1.weight', 'encoder.layers.8.fc1.bias', 'encoder.layers.8.fc2.weight', 'encoder.layers.8.fc2.bias', 'encoder.layers.8.layer_norms.0.weight', 'encoder.layers.8.layer_norms.0.bias', 'encoder.layers.8.layer_norms.1.weight', 'encoder.layers.8.layer_norms.1.bias', 'encoder.layers.9.self_attn.in_proj_weight', 'encoder.layers.9.self_attn.in_proj_bias', 'encoder.layers.9.self_attn.relative_position_keys', 'encoder.layers.9.self_attn.out_proj.weight', 'encoder.layers.9.self_attn.out_proj.bias', 'encoder.layers.9.fc1.weight', 'encoder.layers.9.fc1.bias', 'encoder.layers.9.fc2.weight', 'encoder.layers.9.fc2.bias', 'encoder.layers.9.layer_norms.0.weight', 'encoder.layers.9.layer_norms.0.bias', 'encoder.layers.9.layer_norms.1.weight', 'encoder.layers.9.layer_norms.1.bias', 'encoder.layers.10.self_attn.in_proj_weight', 'encoder.layers.10.self_attn.in_proj_bias', 'encoder.layers.10.self_attn.relative_position_keys', 'encoder.layers.10.self_attn.out_proj.weight', 'encoder.layers.10.self_attn.out_proj.bias', 'encoder.layers.10.fc1.weight', 'encoder.layers.10.fc1.bias', 'encoder.layers.10.fc2.weight', 'encoder.layers.10.fc2.bias', 'encoder.layers.10.layer_norms.0.weight', 'encoder.layers.10.layer_norms.0.bias', 'encoder.layers.10.layer_norms.1.weight', 'encoder.layers.10.layer_norms.1.bias', 'encoder.layers.11.self_attn.in_proj_weight', 'encoder.layers.11.self_attn.in_proj_bias', 'encoder.layers.11.self_attn.relative_position_keys', 'encoder.layers.11.self_attn.out_proj.weight', 'encoder.layers.11.self_attn.out_proj.bias', 'encoder.layers.11.fc1.weight', 'encoder.layers.11.fc1.bias', 'encoder.layers.11.fc2.weight', 'encoder.layers.11.fc2.bias', 'encoder.layers.11.layer_norms.0.weight', 'encoder.layers.11.layer_norms.0.bias', 'encoder.layers.11.layer_norms.1.weight', 'encoder.layers.11.layer_norms.1.bias', 'encoder.layers.12.self_attn.in_proj_weight', 'encoder.layers.12.self_attn.in_proj_bias', 'encoder.layers.12.self_attn.relative_position_keys', 'encoder.layers.12.self_attn.out_proj.weight', 'encoder.layers.12.self_attn.out_proj.bias', 'encoder.layers.12.fc1.weight', 'encoder.layers.12.fc1.bias', 'encoder.layers.12.fc2.weight', 'encoder.layers.12.fc2.bias', 'encoder.layers.12.layer_norms.0.weight', 'encoder.layers.12.layer_norms.0.bias', 'encoder.layers.12.layer_norms.1.weight', 'encoder.layers.12.layer_norms.1.bias', 'encoder.layers.13.self_attn.in_proj_weight', 'encoder.layers.13.self_attn.in_proj_bias', 'encoder.layers.13.self_attn.relative_position_keys', 'encoder.layers.13.self_attn.out_proj.weight', 'encoder.layers.13.self_attn.out_proj.bias', 'encoder.layers.13.fc1.weight', 'encoder.layers.13.fc1.bias', 'encoder.layers.13.fc2.weight', 'encoder.layers.13.fc2.bias', 'encoder.layers.13.layer_norms.0.weight', 'encoder.layers.13.layer_norms.0.bias', 'encoder.layers.13.layer_norms.1.weight', 'encoder.layers.13.layer_norms.1.bias', 'encoder.layers.14.self_attn.in_proj_weight', 'encoder.layers.14.self_attn.in_proj_bias', 'encoder.layers.14.self_attn.relative_position_keys', 'encoder.layers.14.self_attn.out_proj.weight', 'encoder.layers.14.self_attn.out_proj.bias', 'encoder.layers.14.fc1.weight', 'encoder.layers.14.fc1.bias', 'encoder.layers.14.fc2.weight', 'encoder.layers.14.fc2.bias', 'encoder.layers.14.layer_norms.0.weight', 'encoder.layers.14.layer_norms.0.bias', 'encoder.layers.14.layer_norms.1.weight', 'encoder.layers.14.layer_norms.1.bias', 'encoder.layers.15.self_attn.in_proj_weight', 'encoder.layers.15.self_attn.in_proj_bias', 'encoder.layers.15.self_attn.relative_position_keys', 'encoder.layers.15.self_attn.out_proj.weight', 'encoder.layers.15.self_attn.out_proj.bias', 'encoder.layers.15.fc1.weight', 'encoder.layers.15.fc1.bias', 'encoder.layers.15.fc2.weight', 'encoder.layers.15.fc2.bias', 'encoder.layers.15.layer_norms.0.weight', 'encoder.layers.15.layer_norms.0.bias', 'encoder.layers.15.layer_norms.1.weight', 'encoder.layers.15.layer_norms.1.bias', 'encoder.layers.16.self_attn.in_proj_weight', 'encoder.layers.16.self_attn.in_proj_bias', 'encoder.layers.16.self_attn.relative_position_keys', 'encoder.layers.16.self_attn.out_proj.weight', 'encoder.layers.16.self_attn.out_proj.bias', 'encoder.layers.16.fc1.weight', 'encoder.layers.16.fc1.bias', 'encoder.layers.16.fc2.weight', 'encoder.layers.16.fc2.bias', 'encoder.layers.16.layer_norms.0.weight', 'encoder.layers.16.layer_norms.0.bias', 'encoder.layers.16.layer_norms.1.weight', 'encoder.layers.16.layer_norms.1.bias', 'encoder.layers.17.self_attn.in_proj_weight', 'encoder.layers.17.self_attn.in_proj_bias', 'encoder.layers.17.self_attn.relative_position_keys', 'encoder.layers.17.self_attn.out_proj.weight', 'encoder.layers.17.self_attn.out_proj.bias', 'encoder.layers.17.fc1.weight', 'encoder.layers.17.fc1.bias', 'encoder.layers.17.fc2.weight', 'encoder.layers.17.fc2.bias', 'encoder.layers.17.layer_norms.0.weight', 'encoder.layers.17.layer_norms.0.bias', 'encoder.layers.17.layer_norms.1.weight', 'encoder.layers.17.layer_norms.1.bias', 'encoder.layers.18.self_attn.in_proj_weight', 'encoder.layers.18.self_attn.in_proj_bias', 'encoder.layers.18.self_attn.relative_position_keys', 'encoder.layers.18.self_attn.out_proj.weight', 'encoder.layers.18.self_attn.out_proj.bias', 'encoder.layers.18.fc1.weight', 'encoder.layers.18.fc1.bias', 'encoder.layers.18.fc2.weight', 'encoder.layers.18.fc2.bias', 'encoder.layers.18.layer_norms.0.weight', 'encoder.layers.18.layer_norms.0.bias', 'encoder.layers.18.layer_norms.1.weight', 'encoder.layers.18.layer_norms.1.bias', 'encoder.layers.19.self_attn.in_proj_weight', 'encoder.layers.19.self_attn.in_proj_bias', 'encoder.layers.19.self_attn.relative_position_keys', 'encoder.layers.19.self_attn.out_proj.weight', 'encoder.layers.19.self_attn.out_proj.bias', 'encoder.layers.19.fc1.weight', 'encoder.layers.19.fc1.bias', 'encoder.layers.19.fc2.weight', 'encoder.layers.19.fc2.bias', 'encoder.layers.19.layer_norms.0.weight', 'encoder.layers.19.layer_norms.0.bias', 'encoder.layers.19.layer_norms.1.weight', 'encoder.layers.19.layer_norms.1.bias', 'encoder.layer_norm.weight', 'encoder.layer_norm.bias', 'decoder.embed_out', 'decoder.version', 'decoder.embed_tokens.weight', 'decoder.embed_positions._float_tensor', 'decoder.layers.0.self_attn.in_proj_weight', 'decoder.layers.0.self_attn.in_proj_bias', 'decoder.layers.0.self_attn.relative_position_keys', 'decoder.layers.0.self_attn.out_proj.weight', 'decoder.layers.0.self_attn.out_proj.bias', 'decoder.layers.0.self_attn_layer_norm.weight', 'decoder.layers.0.self_attn_layer_norm.bias', 'decoder.layers.0.encoder_attn.in_proj_weight', 'decoder.layers.0.encoder_attn.in_proj_bias', 'decoder.layers.0.encoder_attn.out_proj.weight', 'decoder.layers.0.encoder_attn.out_proj.bias', 'decoder.layers.0.encoder_attn_layer_norm.weight', 'decoder.layers.0.encoder_attn_layer_norm.bias', 'decoder.layers.0.fc1.weight', 'decoder.layers.0.fc1.bias', 'decoder.layers.0.fc2.weight', 'decoder.layers.0.fc2.bias', 'decoder.layers.0.final_layer_norm.weight', 'decoder.layers.0.final_layer_norm.bias', 'decoder.layers.1.self_attn.in_proj_weight', 'decoder.layers.1.self_attn.in_proj_bias', 'decoder.layers.1.self_attn.relative_position_keys', 'decoder.layers.1.self_attn.out_proj.weight', 'decoder.layers.1.self_attn.out_proj.bias', 'decoder.layers.1.self_attn_layer_norm.weight', 'decoder.layers.1.self_attn_layer_norm.bias', 'decoder.layers.1.encoder_attn.in_proj_weight', 'decoder.layers.1.encoder_attn.in_proj_bias', 'decoder.layers.1.encoder_attn.out_proj.weight', 'decoder.layers.1.encoder_attn.out_proj.bias', 'decoder.layers.1.encoder_attn_layer_norm.weight', 'decoder.layers.1.encoder_attn_layer_norm.bias', 'decoder.layers.1.fc1.weight', 'decoder.layers.1.fc1.bias', 'decoder.layers.1.fc2.weight', 'decoder.layers.1.fc2.bias', 'decoder.layers.1.final_layer_norm.weight', 'decoder.layers.1.final_layer_norm.bias', 'decoder.layer_norm.weight', 'decoder.layer_norm.bias'])`


It has made some changes in the model structure.

**Comment by guillaumekln** [comment]
According to the README, the student model uses the architecture `transformer_t2t_wmt_en_de` which is supported by CTranslate2. However, it is unclear whether the model trained in this repository can be directly loaded by a recent and original version of Fairseq. I would guess yes, but you should probably try a quick training and test the conversion.

**Comment by guillaumekln** [comment]
I'm closing this issue, but feel free to reopen it if you can run the student model with the official Fairseq version (https://github.com/facebookresearch/fairseq/) but there is an error when converting it to CTranslate2.
