### ISSUE TITLE
Conversion and quantization of HF Transformer (MarianMT model) hardware dependant?

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [OpenNMT/CTranslate2#929]
Hi,

Thank you for this great repository!

My issue is more a query: Are conversion and quantization of a Hugging Face Transformer (MarianMT model) harware dependant?

I have converted and quantized this model type from this https://opennmt.net/CTranslate2/guides/transformers.html#marianmt with my RTX 3090 on local machine. But if the target is a GPU AWS T4 instance, do I need to redo the conversion and quantization on this instance or could I use those I have created on my local machine?

**Comment by guillaumekln** [comment]
Hi,

The converted model is **not** hardware dependent, even with quantization. You can convert it once and load it anywhere.

There is a small section about this in the documentation: https://opennmt.net/CTranslate2/conversion.html#portability

**Comment by Matthieu-Tinycoaching** [comment]
Thanks for the quick feedback. I didn't noticed this section.
