### ISSUE TITLE
How to speed-up real-time inference of MarianMT transformer model ?

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [OpenNMT/CTranslate2#930]
Hi,

When using converted model of a MarianMT transformer model with or without quantization on RTX 3090 GPU, I didn't notice latency/throughput improvement of quantized models compared to default model (float) when using in real-time inference with `bacth_size=1`.

Despite the `beam_size` parameter and the possibility to run real-time bacth inference, are there ano other factors that could improve latency/throughput?

**Comment by guillaumekln** [comment]
Hi,

For GPU latency, there are no obvious ways to improve the speed further. The MarianMT models are quite small, so with `batch_size=1` the GPU receives very little work and quantization does not have a big effect, especially on powerful cards like the 3090.

For GPU throughput, you should definitely use batch inference.

If you always run with `batch_size=1`, you might also consider running the quantized model on CPU. It is cheaper and you can configure the translator to run multiple translation requests [in parallel](https://opennmt.net/CTranslate2/parallel.html).

**Comment by guillaumekln** [comment]
> Is it really cheaper to use CPU with parallelization ? Since, on the benchmark, I see slower performances than GPU (https://github.com/OpenNMT/CTranslate2) with a [c5.metal](https://aws.amazon.com/ec2/instance-types/c5/) instance which is not cheap. How many CPUs are needed to have improvement with parallelization regarding GPU with batch_size=1?

The benchmark is measuring throughput (tokens/s) but it seems you are more interested in latency with `batch_size=1`. Latency for a single request will always be lower on GPU, but if there are multiple concurrent requests with `batch_size=1`, you can obtain better average latency on CPU with multiple workers.

<details>
  <summary>Example</summary>
  I tested on a V100 instance with the En-De MarianMT model. It takes about 30 ms to translate a single sentence on GPU, and about 90 ms on CPU with 4 threads. You can compute that with 4 CPU workers (4*4=16 threads) and 8 concurrent requests, the average response time is the same on CPU and GPU.

* Average CPU response time = (90 * 4 + 180 * 4) / 8 = 135 ms
* Average GPU response time = (30 + 60 + 90 + 120 + 150 + 180 + 210 + 240) / 8 = 135 ms
</details>

Of course, if you expect a lot of concurrent requests you should batch sentences together and then GPU will take the lead again.

> Did you make benchmark on ARM64 processors and are there any guidelines in building docker image working in this architecture?

There is no benchmark for ARM64 and no guidelines specific to this architecture.
