### ISSUE TITLE
Containerization of CTranslate2 service into fastAPI for GPU inference

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [OpenNMT/CTranslate2#931]
Hi,

1 / This is more a question regarding containerization of the CTranslate2 service with fastAPI. For GPU inference, is it needed to start from an nvidia-cuda docker image in dockerfile, in order to perform GPU inference on target machine with CUDA and cuDNN installed?

2 / Do you know an API service that would enable containerization of a CTranslate2 service for real-time batch GPU inference?

**Comment by guillaumekln** [comment]
Hi,

1. Yes, CUDA must be installed in the Docker image for GPU inference. More specifically, CTranslate2 requires the cuBLAS library. You can start from a runtime NVIDIA image like `nvidia/cuda:11.2.2-runtime-ubuntu20.04` or start from a base image and install cuBLAS manually, as we do in [our Docker image](https://github.com/OpenNMT/CTranslate2/blob/v2.23.0/docker/Dockerfile#L71-L82).
2. No, I don't have a specific recommendation for that.
