### ISSUE TITLE
TypeError: cannot pickle 'ctranslate2.translator.Translator' object

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [OpenNMT/CTranslate2#932]
I have used the CTranslate2 inference within bentoML (https://github.com/OpenNMT/CTranslate2) with custom runner.

But, when trying to save the model with cloudpickle, it results in the following error: 

> converting 'CT2_default_opus_mt_fr_en' to lowercase: 'ct2_default_opus_mt_fr_en'
> Traceback (most recent call last):
> File "/home/matthieu/Code/Python/CTranslate2/MarianMT.py", line 125, in
> saved_model = bentoml.picklable_model.save_model(
> File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/bentoml/_internal/frameworks/picklable.py", line 145, in save_model
> cloudpickle.dump(model, f)
> File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
> CloudPickler(
> File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
> return Pickler.dump(self, obj)
> TypeError: cannot pickle 'ctranslate2.translator.Translator' object

To reproduce: please follow the following issue https://github.com/bentoml/BentoML/issues/3061

**Comment by guillaumekln** [comment]
Pickling the `Translator` instance is currently not supported.

Do you really need to pickle the translator itself? The instance can be recreated from the model directory on disk.

**Comment by Matthieu-Tinycoaching** [comment]
For serving with bentoML and adaptive-batching, I need to save the model and specify signatures of it during this saving: https://docs.bentoml.org/en/latest/concepts/model.html#batching

as CTranslated is not a valid framework in bentoML, I tried to `save_model` and specify `batchable=True` with `cloudpickle`: https://github.com/bentoml/BentoML/blob/main/examples/custom_python_model/simple_pickable_model/model.py

**Comment by Matthieu-Tinycoaching** [comment]
I close this issue, since it appears that adaptive-batching is permitted without saving the model on a defined framework.

**Comment by kvasilopoulos** [comment]
Hi @Matthieu-Tinycoaching how did you achieve using the model artifact? Did you use the [custom model artifact](https://docs.bentoml.org/en/0.13-lts/guides/custom_artifact.html)? Can you share the example please?

**Comment by kolserdav** [comment]
Hi @kvasilopoulos Maybe it's better to create a `Translator` on every request? Most likely it will take the same time as reading from disk.
