### ISSUE TITLE
onmt_release_model currently broken when installing from PyPI

### ISSUE THREAD

**Issue by PJ-Finlay** [OpenNMT/CTranslate2#975]
I trained a OpenNMT-py v3.0 model and installed CTranslate2 2.24 from PyPI and `onmt_release_model` is broken.

```
onmt_release_model --model run/openmt.model_step_34000.pt --format ctranslate2 --output run/model --quantization float16
```

I was able to convert to CTranslate2 successfully by installing CTranslate2 from source. I think the issue is that [this commit](https://github.com/OpenNMT/CTranslate2/commit/3193c1af02257468d870587c20c7d8900727a23e) isn't available on PyPI.

The old method using `ct2-opennmt-py-converter` is also broken for OpenNMT-py v3.

**Comment by vince62s** [comment]
it is now.
