### ISSUE TITLE
Possible to use custom decoder start token and prefix_bias_beta together?

### ISSUE THREAD

**Issue by shamilcm** [OpenNMT/CTranslate2#987]
Custom decoder start tokens for models like mbart 25  is set with the the "target_prefixes". However, if we use this along with prefix bias beta with prefix other prefix tokens, will the start token decoding also be biased?

Is there any work around to have both?

**Comment by guillaumekln** [comment]
> will the start token decoding also be biased?

No. The biased decoding only applies to the decoder output, but the start token is only used as input.
