### ISSUE TITLE
The lousy result on openai whisper model.

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/CTranslate2#995]
Hi, thanks for your great work!

I have converted the large whisper model by this command:
```
ct2-transformers-converter --model openai/whisper-large --output_dir converted_whisper
```
This is my test script
```py
import ctranslate2
import transformers
import librosa

audio, _ = librosa.load("audio.m4a", sr=16000, mono=True)

processor = transformers.WhisperProcessor.from_pretrained("openai/whisper-large")
inputs = processor(audio, return_tensors="np", sampling_rate=16000)
features = ctranslate2.StorageView.from_array(inputs.input_features)

model = ctranslate2.models.Whisper("converted_whisper/")
results = model.detect_language(features)

prompt = processor.tokenizer.convert_tokens_to_ids(
    [
        "<|startoftranscript|>",
        "<|en|>",
        "<|transcribe|>",
        "<|notimestamps|>",
    ]
)

results = model.generate(features, [prompt])
print(results[0].sequences_ids[0])
transcription = processor.decode(results[0].sequences_ids[0], skip_special_tokens=True)
print(transcription)
```
I got the lousy result
<img width="1250" alt="截屏2022-11-27 14 55 16" src="https://user-images.githubusercontent.com/25839309/204123195-ab82917d-87e3-400e-808c-7328f098a475.png">

But the result from the original whisper repository is pretty good.
<img width="1430" alt="截屏2022-11-27 14 54 03" src="https://user-images.githubusercontent.com/25839309/204123156-1fd0ec36-2f5f-4947-a026-f7c5eb497de0.png">

Is anything wrong with my script?

**Comment by guillaumekln** [comment]
Hi,

Can you share the input audio file if possible?

**Comment by BrightXiaoHan** [comment]
Sure.

**Comment by BrightXiaoHan** [comment]
I have sent you the audio file by email, can you receive it?

**Comment by guillaumekln** [comment]
Thanks. I downloaded the file from Google Drive.

For this file it seems you need to increase the beam size to get a better output. Try adding `beam_size=5` when calling the `generate` method.

I will update the default beam size to match the value used by OpenAI.

**Comment by BrightXiaoHan** [comment]
![image](https://user-images.githubusercontent.com/25839309/204254703-cb85d32b-07cd-4925-8996-b8aad305f1f3.png)
I changed the beam_size to 5 but the result is still not very good.

**Comment by guillaumekln** [comment]
Yes, sorry. I also removed `<|notimestamps|>` to generate the timestamps like in openai/whisper. The output is then like this:

>  This morning, all eyes are on the weather as millions of people are on the move or will be soon returning from the long holiday weekend. But it's not looking pretty in some spots. Joining us now is meteorologist Daniel Breezy from our affiliate WKRN in Nashville, Tennessee. Good morning to you, Danielle. And good morning, Janay. Yes, a lot of folks waking up to a soggy start on this Saturday. If you are doing some traveling, be aware it is going to be wet out there. Let's show you where the storm system is right now. As you look

However, generating without `<|notimestamps|>` will only be supported in the next CTranslate2 version (3.1). It should be released this week.

**Comment by guillaumekln** [comment]
Can you try with the latest version after removing `<|notimestamps|>`?

**Comment by BrightXiaoHan** [comment]
<img width="1202" alt="截屏2022-11-30 15 26 58" src="https://user-images.githubusercontent.com/25839309/204733621-7b14e3db-45fb-4ae8-b350-3096a9ae5745.png">

The results still don't seem to be good.

**Comment by BrightXiaoHan** [comment]
<img width="1202" alt="截屏2022-11-30 15 29 44" src="https://user-images.githubusercontent.com/25839309/204734036-559b2d26-de80-484c-a08d-88273ff4ad3d.png">
Pretty good. Thanks.
